### ISSUE TITLE
Huge WARN logs regarding "CheckpointTs is greater than ResolvedTs" seen when resume redo changefeed 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10071]
### What did you do?

1. Create CDC changefeed with redo log on
2. Pause changefeed and run workload for 2 hours
3. Resume changefeed

### What did you expect to see?

There should be not too much logs 

### What did you see instead?

Lots of WARN logs about "schedulerv3: resolved ts should not less than checkpoint ts" and "schedulerv3: CheckpointTs is greater than ResolvedTs"
![image](https://github.com/pingcap/tiflow/assets/7403864/df1f6dfe-805a-4a48-98ac-7d26b2b1518c)

![image](https://github.com/pingcap/tiflow/assets/7403864/fff72cc4-c722-4ed1-a96b-f53f7baf217f)

### Versions of the cluster

bash-5.1# /cdc version                                              
Release Version: v6.5.5-20231109-c8eed98                            
Git Commit Hash: c8eed98f03df1a9fa032018d14acacd697eda0bc           
Git Branch: heads/refs/tags/v6.5.5-20231109-c8eed98                 
UTC Build Time: 2023-11-09 09:24:38                                 
Go Version: go version go1.19.12 linux/amd64                        
Failpoint Build: false

**Comment by asddongmen** [comment]
Fixed by https://github.com/pingcap/tiflow/pull/10740
