### ISSUE TITLE
ticdc: after redo changefeed reported error and resumed  the changefeed , redolog writer is closed

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tiflow#10124]
### What did you do?

1. redo log changefeed reported error 
![image](https://github.com/pingcap/tiflow/assets/50363732/3ce496fb-4b5c-4872-b4d4-15d1e74fab2b)
2. change storage url and resume it

### What did you see instead?

redo log changefeed reported writer closed
![img_v3_025e_88520f08-5134-42c0-b472-226a62b0325g](https://github.com/pingcap/tiflow/assets/50363732/2c4724a2-8f34-4337-8f68-b6203c53e25b)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
sh-5.1# /cdc version
Release Version: v7.5.0
Git Commit Hash: 99c1f8fdffe72f2a9dbce6d0b58a52a162ce72b7
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-16 10:33:24
Go Version: go version go1.21.3 linux/amd64
Failpoint Build: false

```

**Comment by asddongmen** [comment]
@CharlesCheung96 Could please take a look at this issue? Thank you!

**Comment by CharlesCheung96** [comment]
The root cause of this problem is that redo returns meaningless errors. We will optimize this later and temporarily downgrade the problem to avoid affecting the release of the new version.
