### ISSUE TITLE
(Redo) TestGCAndCleanup may take several hundreds seconds

### ISSUE THREAD

**Issue by zhangjinpeng87** [pingcap/tiflow#10214]
### What did you do?

In the test case of `TestGCAndCleanup`, each CheckGC will sleep for 100 seconds here https://github.com/pingcap/tiflow/blob/master/cdc/redo/meta_manager_test.go#L255 , this will make this test very slow.

### What did you expect to see?

TestGCAndCleanup is very slow

### What did you see instead?

TestGCAndCleanup can be finished in few seconds

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
master
```

Upstream TiKV version (execute `tikv-server --version`):

```console
master
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by okJiang** [comment]
it has been replaced [here](https://github.com/pingcap/tiflow/blob/e0bdf8c3a5a0bec83533565a6a335c278c69fbd5/cdc/redo/main_test.go#L23-L30)? So it won't wait so long

**Comment by CharlesCheung96** [comment]
> it has been replaced [here](https://github.com/pingcap/tiflow/blob/e0bdf8c3a5a0bec83533565a6a335c278c69fbd5/cdc/redo/main_test.go#L23-L30)? So it won't wait so long

close this issue, since it has been addressed in `cdc/redo/main_test.go`.
