### ISSUE TITLE
DM supports MySQL 8.0 GA

### ISSUE THREAD

**Issue by lyzx2001** [pingcap/tiflow#10405]
## Enhancement
Currently descring of DM as below:
Database version requirements
MySQL version 5.5 ~ 5.7
MySQL version 8.0 (experimental features)
As EOL of Aurora2 (MySQL5.7) is approaching, customer is considering if there is any way to migrate from Aurora3 (MySQL8.0) to TiDB for the future.

**Comment by dveeden** [comment]
Looks like this might need to be updated: https://github.com/pingcap/tiflow/blob/36aed02d3e1416bff8a64829b3a05eecd89abf89/dm/pkg/checker/mysql_server.go#L37-L47
