### ISSUE TITLE
cdc can not parse kv event after truncate table partition

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#10460]
![image](https://github.com/pingcap/tiflow/assets/1779704/75b3be97-1bef-4703-8799-13cb732c85cc)

**Comment by CharlesCheung96** [comment]
Fixed in https://github.com/pingcap/tiflow/pull/10528

**Comment by flowbehappy** [comment]
Duplicate with https://github.com/pingcap/tiflow/issues/10522
