### ISSUE TITLE
start-ts is not verified when creating the changefeed

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#10499]
At the moment, if user specifies the `start-ts` when creating the changefeed, it's not checked whether it's valid.

A valid start-ts should be:
1. not smaller than the gc-safepoint
2. not larger than the current tso

If the `start-ts` is in the future, which may caused by mis-operations, the changefeed can be created but cannot make any progress, since the replication is not started yet, this makes users confused.

## How to solve it
There are 2 ways to solve the issue:
1. When creating the changefeed, verify the `start-ts`, make sure it's legal, otherwise report the error and failed to create the changefeed.
2. If the `start-ts` is smaller than the `gc-safepoint`, just report the error, since the changefeed cannot replicate data already gc. If the `start-ts` is in the future, warning the user and need user's confirmation to create the changefeed.

**Comment by flowbehappy** [comment]
@Benjamin2037 @zhangjinpeng87 Which approach do you prefer?

**Comment by zhangjinpeng87** [comment]
I personally prefer 1, since create a changefeed start from future is meaningless from applications perspective.

**Comment by benmeadowcroft** [comment]
@zhangjinpeng87 yes, that makes sense. I am not sure I can see a generally applicable use case where that behavior would be desirable

**Comment by flowbehappy** [comment]
I think we don't need to back port this enhancement.
