### ISSUE TITLE
changefeed cannot start if syncpoint enabled and using base64 encoded password on v6.5.x

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#10510]
### What did you do?

When creating the changefeed, enable sync point, and using base64 encoded password.

### What did you expect to see?

the changefeed start and running normally

### What did you see instead?

the changefeed cannot make progress, and report error

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
v6.5.0
```

**Comment by asddongmen** [comment]
duplicated with #10516
