### ISSUE TITLE
[CDC] Known incompatible setting issues after upgraded to new versions

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflow#10709]
- [x] `enable-old-value` got remove after v7.4.0. Source: https://asktug.com/t/topic/1022449. Issue: https://github.com/pingcap/tiflow/issues/10711
      * Addressed by this issue. We introduce two new configs with smaller granularity on specific protocols.
- [x] `partition = "index-value"` is not recognized after upgraded from v6.1.7 to v7.5.0. Source: https://asktug.com/t/topic/1019467 . Issue: https://github.com/pingcap/tiflow/issues/10707

**Comment by lidezhu** [comment]
enable-old-value related issue: https://github.com/pingcap/tiflow/issues/10711
