### ISSUE TITLE
[CDC] Create changefeed failed when config the parameter enable-old-value

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tiflow#10711]
### What did you do?

From https://asktug.com/t/topic/1022449

Create changefeed
tiup ctl:v7.5.1  cdc changefeed create  --server=http://1xxxxxx:8324   
--sink-uri="kafka://xxxxxx9092/tidb-supexxx?protocol=canal-json&kafka-version=2.4.1
&partition-num=6&max-message-bytes=10485760&compression=lz4&replication-factor=1"  
--config=/home/tidb/cdctoml/cdc-xxxxxx-kafka.toml  --changefeed-id="cdc-xxxx-kafka"    --sort-engine="unified"

### What did you expect to see?
Changfeed create successfully and log a warning that config `enable-old-value` is deprecated.

### What did you see instead?
It reports error: unknown configuration options: `enable-old-value`

### Versions of the cluster
```console
cdc v7.5.x
```

**Comment by flowbehappy** [comment]
We addressed it in this issue. Closing this one.
