### ISSUE TITLE
CDC lag too large during CDC rolling restart

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10789]
### What did you do?

1. Cluster with 27 TiKV, 5 cdc nodes, 3 kafka changefeed running: one for 4k tables (row width: 1.7K), one for 2 big tables (30TB+), one for a table with large rows (1MB+), workload throughput ~40MB/s
2. Rolling restart ticdc nodes

### What did you expect to see?

1, CDC lag should be less than 10s

### What did you see instead?

1. for the 4k table changefeed, cdc lag 1.4min, other 2 changefeed lag ~25s
![image](https://github.com/pingcap/tiflow/assets/7403864/fbd4527e-507b-4d4c-b22c-ba5bac61e7f2)
![image](https://github.com/pingcap/tiflow/assets/7403864/eec16f7a-03f7-4873-b145-9d676e9efbd2)

### Versions of the cluster

```
mysql> select type, version, git_hash from CLUSTER_INFO;
+-------+--------------------------+------------------------------------------+
| type  | version                  | git_hash                                 |
+-------+--------------------------+------------------------------------------+
| tidb  | 8.0.0-alpha-491-gb609fa6 | b609fa6d271b514dfc83530c5e14812dd043cd2e |
| pd    | 8.0.0-alpha-91-g7d22c4f  | 7d22c4f3950a49e7da702426c4fec6c98af6928f |
| tikv  | 8.0.0-alpha              | 4c121d72b842e5e4088f2741a4d2ed21cce0c59d |
| ticdc | 8.0.0-alpha-103-geb1e3bc | eb1e3bc95f028aa2a53622b4a694bb12bfbbdc4d |
```

**Comment by flowbehappy** [comment]
Addressed by this issue https://github.com/pingcap/tiflow/issues/10845.

**Comment by asddongmen** [comment]
Track by https://github.com/pingcap/tiflow/issues/10797
