### ISSUE TITLE
changefeed stucks when there are 100 changefeed and restarting PD 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10798]
### What did you do?

1. TiDB cluster deployed in GCP GKE env, with 24 TiKV (16c64g) and 9 CDC node (16c64g), cluster size ~40TB. 3 workload running, one workload with row width ~1mb, one 9kb, one 1.7kb.
2. 100 changefeed created, each changefeed cover 40 tables.
3. update PD configuration to trigger rolling restart

### What did you expect to see?

CDC lag should be less than 10s

### What did you see instead?

CDC changefeed stucks

![image](https://github.com/pingcap/tiflow/assets/7403864/c1f3ef5f-4255-4e0a-9cf1-88893abb29f6)
![image](https://github.com/pingcap/tiflow/assets/7403864/cf468f07-b82f-45f9-a222-f68362f2dabb)

### Versions of the cluster

cdc version:
Release Version: v8.0.0                                  
Git Commit Hash: 130403f3b9b8ad8a28ceada642277986e317ebc2
Git Branch: heads/refs/tags/v8.0.0                       
UTC Build Time: 2024-03-15 13:58:58                      
Go Version: go version go1.21.6 linux/amd64              
Failpoint Build: false

**Comment by sdojjy** [comment]
the test env is not stable, I retested this case with 50 changefeeds, the max changefeed LAG is less than 5s.

**Comment by fubinzh** [comment]
After PD rolling restart at 3/17 11:44, we can see that workload not balanced, cdc-8 has 4k tables, and CPU usage almost full, and disk size keep increasing and finally full.

![image](https://github.com/pingcap/tiflow/assets/7403864/c5ce2944-8fa8-4aea-a910-3b177c2617b8)
![image](https://github.com/pingcap/tiflow/assets/7403864/700b3376-ee13-4d7d-a877-65c0d0dc9b10)

**Comment by fubinzh** [comment]
PD side issue: https://github.com/tikv/pd/issues/7973

**Comment by fubinzh** [comment]
Close this issue, PD issue will be tracked seperately.
