### ISSUE TITLE
CDC CPU usage high and initial scan is slow

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10822]
### What did you do?

CDC usage high and initial scan slow is seen 
![image](https://github.com/pingcap/tiflow/assets/7403864/d1377efe-1601-4956-8f45-1ea38e954c80)

![image](https://github.com/pingcap/tiflow/assets/7403864/1fe77944-aacf-4605-8e55-62ecbcebd782)
![image](https://github.com/pingcap/tiflow/assets/7403864/4aa79192-a890-4c6a-ad6d-cf47ab4a5a69)

### What did you expect to see?

initial scan should fast 

### What did you see instead?

CPU usage high and initial scan is slow.

### Versions of the cluster

CDC version:
 [release-version=v8.0.0-alpha] [git-hash=0424aba6e4861365ace73162b49e7c6d5ccda6b2]

**Comment by hicqu** [comment]
I have tested with setting `kv-client.advance-interval-in-ms = 0`, but CPU usage still reaches 800%. 
![图片](https://github.com/pingcap/tiflow/assets/8407317/440a167d-0341-4950-a5b0-797586514c46)

**Comment by hicqu** [comment]
Seems it's caused by small upstream `min-ts-interval`.
