### ISSUE TITLE
TiCDC Puller Resolved Ts calculation uncorrectly when some region's incremental scan is stuck

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflow#10856]
### What did you do?

run a workload and some region stuck in incremental scan

### What did you expect to see?

cdc puller resolved ts is stuck

### What did you see instead?

cdc puller resolved ts increase normally

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by asddongmen** [comment]
It is a metrics issue.
