### ISSUE TITLE
cherry-pick simple protocol to release-7.5 branch

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#10874]
Cherry-pick simple protocol to release-7.5 to meet user requirement.

**Comment by asddongmen** [comment]
- [x] Cherrypick schemaStorage refactor
- [x] Cherrypick Simple Protocol encoder and decoder 
- [x] Cherrypick Simple Protocol related configuration
- [ ] Cherrypick Bootstrap Function logic 
- [ ] Cherrypick row checksum function changes
- [ ] Cherrypick simple protocol integration test cases

**Comment by asddongmen** [comment]
Finish by #10898
