### ISSUE TITLE
Changefeed checkpointTs lag reach 30s during TiDB/TiKV rolling upgrading.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#10880]
### What did you do?

1. Create a changefeed replicated 4000 tables with 50Mb/s throughput. 
2. Rolling restart upstream TiDB/ TiKV.

### What did you expect to see?

Changefeed checkpointTs lag is less than 15s. 

### What did you see instead?

As title.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
v8.0.0
```

**Comment by asddongmen** [comment]
During a rolling restart of TiDB and TiKV, stale locks from interrupted transactions may remain in TiKV. This can hinder the progression of resolvedTs, leading to changefeed delays.

This issue should ideally be addressed on the TiDB side to avoid the creation of stale locks in the first place.

Although TiCDC can make efforts to actively clear these stale locks and minimize delays, this approach isn't a complete solution to the problem.

**Comment by 3AceShowHand** [comment]
This PR is on release-8.1 branch
