### ISSUE TITLE
unstable big_txn test in kafka and pulsar pipeline

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#10912]
ref: 
- [cdc_integration_kafka_test](https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_kafka_test/activity)
- [cdc_integration_pulsar_test](https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_pulsar_test/activity)
![image](https://github.com/pingcap/tiflow/assets/61726649/a6e1b503-67e9-45a0-a814-734ec8ecbd5f)

**Comment by asddongmen** [comment]
fixed by https://github.com/pingcap/tiflow/pull/10951/files
