### ISSUE TITLE
changefeed of downstream status was always abnormal after kill all ticdc of upstream for BDR cluster

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#10925]
### What did you do?

1、deploy BDR cluster
ticdc-task1：tc -> cdc-downstream
ticdc-task2：cdc-downstream -> tc
2、run workload for tc and cdc-downstream
run workload for the db “sysbench_64_7000w ”of tc and db “test” of cdc-downstream
3、kill all ticdc of tc

### What did you expect to see?

all changefeed are normal

### What did you see instead?

ticdc-task2 of downstream was abnormal and always report warning
![img_v3_02a2_d8d4cf5c-faba-4791-b643-cc7b9be7c7ag](https://github.com/pingcap/tiflow/assets/84712107/3cba552b-2c7c-49f5-b258-c2d3cb5432f0)

from the log of downstream ticdc, the data of up-changefeed -> down-tidb is synchronized back to up-tidb by down-changefeed

downstream ticdc logs：
`[2024/04/18 05:23:08.780 +08:00] [WARN] [mysql.go:834] ["execute DMLs with error, retry later"] [error="[CDC:ErrMySQLTxnError]MySQL txn error: Error 1062 (23000): Duplicate entry '39779195' for key 'sbtest1.PRIMARY'"] [errorVerbose="[CDC:ErrMySQLTxnError]MySQL txn error: Error 1062 (23000): Duplicate entry '39779195' for key 'sbtest1.PRIMARY'\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:34\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql.(*mysqlBackend).execDMLWithMaxRetries.func1.3\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql/mysql.go:807\ngithub.com/pingcap/tiflow/cdc/sink/metrics.(*Statistics).RecordBatchExecution\n\tgithub.com/pingcap/tiflow/cdc/sink/metrics/statistics.go:80\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql.(*mysqlBackend).execDMLWithMaxRetries.func1\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql/mysql.go:761\ngithub.com/pingcap/tiflow/pkg/retry.run\n\tgithub.com/pingcap/tiflow/pkg/retry/retry_with_opt.go:57\ngithub.com/pingcap/tiflow/pkg/retry.Do\n\tgithub.com/pingcap/tiflow/pkg/retry/retry_with_opt.go:34\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql.(*mysqlBackend).execDMLWithMaxRetries\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql/mysql.go:750\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql.(*mysqlBackend).Flush\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql/mysql.go:234\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn.(*worker).doFlush\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/worker.go:187\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn.(*worker).run\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/worker.go:142\ngithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn.newSink.func1\n\tgithub.com/pingcap/tiflow/cdc/sink/dmlsink/txn/txn_dml_sink.go:113\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.7.0/errgroup/errgroup.go:78\nruntime.goexit\n\truntime/asm_amd64.s:1650"] [duration=1m9.540244976s] [query=COMMIT] [count=93] [startTs="[449154624144539651,449154624144539656,449154624065896462,449154624065896543,449154624131432532,449154624144539756,449154624157384782,449154624065896487,449154624065896491,449154624131432538,449154624131432566,449154624157384711,449154624131432508,449154624065896543,449154624157384714,449154624065896488,449154624131432498,449154624157384719,449154624065896536,449154624131432494,449154624144539706,449154624157384718,449154624131432508,449154624065896449,449154624144539743,449154624144539750,449154624118325251,449154624065896546,449154624131432537,449154624052789367,449154624144539649,449154624131432500,449154624118325251,449154624131432483,449154624092110859,449154624131432496,449154624131432574,449154624065896542,449154624157384795,449154624157384748,449154624131432538,449154624131432562,449154624144539726,449154624131432586,449154624131432496]"] [changefeed=default.ticdc-task2]
[2024/04/18 05:23:12.292 +08:00] [WARN] [mysql.go:834] ["execute DMLs with error, retry later"] [error="[CDC:ErrMySQLTxnError]MySQL txn error: Error 1062 (23000): Duplicate entry '35182119' for key 'sbtest23.PRIMARY'"] [errorVerbose="[CDC:ErrMySQLTxnError]MySQL txn error: Error 1062 (23000): Duplicate entry '35182119' for key 'sbtest23.PRIMARY'\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.`

### Versions of the cluster

sh-5.1# ./cdc version
Release Version: v8.1.0-alpha
Git Commit Hash: c8ed99f6396968d53642d19de22e54f1c8d1d285
Git Branch: heads/refs/tags/v8.1.0-alpha
UTC Build Time: 2024-04-17 11:36:47
Go Version: go version go1.21.6 linux/amd64
Failpoint Build: false

**Comment by asddongmen** [comment]
The issue could possibly be caused by a data race during processor initialization.
```log
WARNING: DATA RACE
Read at 0x00c0035d8d58 by goroutine 567:
  github.com/pingcap/tiflow/cdc/processor.(*processor).lazyInitImpl()
      /home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/processor/processor.go:628 +0xb18
  github.com/pingcap/tiflow/cdc/processor.(*processor).lazyInitImpl-fm()
      <autogenerated>:1 +0x47
  github.com/pingcap/tiflow/cdc/async.(*Initializer).TryInitialize.func1()
      /home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/async/async_initializer.go:68 +0x108
  github.com/pingcap/tiflow/pkg/workerpool.(*asyncWorker).run()
      /home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/pkg/workerpool/async_pool_impl.go:166 +0x9b
  github.com/pingcap/tiflow/pkg/workerpool.(*defaultAsyncPoolImpl).Run.func2()
      /home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/pkg/workerpool/async_pool_impl.go:114 +0x48
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x97
```

**Comment by asddongmen** [comment]
When data races occur, the `TiDBSourceID` may be set to `0`. This leads to the session value `tidb_cdc_write_source` being set to `0`, so the TiKV CDC component will not filter out the data written by TiCDC. (TiKV CDC only filters out data where `tidb_cdc_write_source` is larger than `0`.) This results in cyclic data replication.
