### ISSUE TITLE
DM CI failed because `Unsupported tidb_enable_dist_task setting. To utilize distributed task execution, please enable tidb_ddl_enable_fast_reorg first.`

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#10975]
### What did you do?

dm_ghpr_compatilbity_test

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by purelind** [comment]
Found frequent failures also occur on the master branch, is it also due to this reason?

https://prow.tidb.net/?repo=pingcap%2Ftiflow&type=presubmit&pull=10904&job=pingcap%2Ftiflow%2Fpull_dm_compatibility_test

**Comment by lance6716** [comment]
> Found frequent failures also occur on the master branch, is it also due to this reason?
> 
> https://prow.tidb.net/?repo=pingcap%2Ftiflow&type=presubmit&pull=10904&job=pingcap%2Ftiflow%2Fpull_dm_compatibility_test
> 
> ```shell
> [2024/04/24 22:35:20.365 +08:00] [INFO] [diff.go:193] ["not found checkpoint file, start from beginning"]
> [2024/04/24 22:35:20.370 +08:00] [ERROR] [utils.go:332] ["column num not equal"] ["upstream table"=t1] ["column num"=5] ["downstream table"=t1] ["column num"=4] [stack="github.com/pingcap/tidb-tools/sync_diff_inspector/utils.CompareStruct\n\t/home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/utils/utils.go:332\nmain.(*Diff).compareStruct\n\t/home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:318\nmain.(*Diff).StructEqual\n\t/home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/diff.go:302\nmain.checkSyncState\n\t/home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:125\nmain.main\n\t/home/jenkins/agent/workspace/d_tidb_tools_multi_branch_master/go/src/github.com/pingcap/tidb-tools/sync_diff_inspector/main.go:104\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]
> [2024/04/24 22:35:20.370 +08:00] [INFO] [diff.go:711] ["start writeSQLs goroutine"]
> [2024/04/24 22:35:20.370 +08:00] [INFO] [diff.go:375] ["start handleCheckpoint goroutine"]
> ```

yes, i checked one of pull_dm_compatibility_test
