### ISSUE TITLE
cdc发送大消息到外部存储问题

### ISSUE THREAD

**Issue by lee1988well** [pingcap/tiflow#10988]
### What did you do?

版本是v7.5.1
测试ticdc消息超过设置的最大值能不能成功发送消息到s3
两个测试场景：
* 场景一：
   * kafka中topic的参数max.message.bytes为12M
   * cdc任务sink-uri中的max-message-bytes=10
* 场景二：
  * kafka中topic的参数max.message.bytes为1kb
  * cdc任务sink-uri中的max-message-bytes=1024
  
配置文件如下：
```
case-sensitive = false
changefeed-error-stuck-duration = "30m"

[mounter]
worker-num = 16

[filter]
rules = [ "lee.*",]
[[filter.event-filters]]
matcher = [ "*.*",]
ignore-event = [ "all ddl",]

[scheduler]
enable-table-across-nodes = true
write-key-threshold = 300

[sink]
protocol = "canal-json"
delete-only-output-handle-key-columns = false
encoder-concurrency = 32
only-output-updated-columns = false
[[sink.dispatchers]]
matcher = [ "lee.*",]
topic = ""
partition = "table"

[integrity]
integrity-check-level = "none"
corruption-handle-level = "warn"

[sink.kafka-config.large-message-handle]
large-message-handle-option = "claim-check"
claim-check-storage-uri = "s3://devops-db-qa-bj-1322237698/tmp/ticdc/qa/?access-key=AKIDhHfqpZ6xxxx&secret-access-key=yoVxxxx"
```
创建任务命令如下：
```
tiup cdc:v7.5.1 cli changefeed create \
    --server=http://10.1.0.1:8300 \
    --sink-uri="kafka://10.14.4.1:9092/cdc.lee.test1?kafka-version=2.8.1&partition-num=1&max-message-bytes=1024&replication-factor=3&max-batch-size=1&enable-tidb-extension=true" \
    --changefeed-id="test-task" \
    --config './test.toml'
```

### What did you expect to see?

两个测试场景，遇到大的消息体都能够正常发送到s3，cdc任务正常

### What did you see instead?

场景一：
* cdc任务异常
* s3中不断的在反复创建这一条记录，不能停止
* kafka中的这个topic没有收到任何消息
cdc任务状态：
```
{
  "upstream_id": 7347985492377217198,
  "namespace": "default",
  "id": "test-task",
  "state": "warning",
  "checkpoint_tso": 449343822818181126,
  "checkpoint_time": "2024-04-26 13:50:52.230",
  "error": {
    "time": "2024-04-26T13:54:05.688402412+08:00",
    "addr": "10.194.8.5:8300",
    "code": "CDC:ErrMessageTooLarge",
    "message": "[CDC:ErrMessageTooLarge]message is too large%!(EXTRA int=396)"
  }
}
```

场景二：
* cdc任务正常
* s3中只会收到一行记录，正常
* kafka中不断收到WATERMARK Event消息，并且正确收到大消息如下：
```
{"id":0,"database":"lee","table":"test1","pkNames":["id"],"isDdl":false,"type":"INSERT","es":1714115532330,"ts":1714115533284,"sql":"","sqlType":{"id":4},"mysqlType":{"id":"int"},"old":null,"data":[{"id":"4"}],"_tidb":{"commitTs":449345102107115534,"claimCheckLocation":"s3://devops-db-qa-bj-1322237698/tmp/ticdc/qa/ec24e3c1-2965-41b7-9ea6-7e42476fb6d5.json"}}
```

问题：
* 场景一肯定是不正常的，是不是消息超过了cdc任务设置的值，但是没有超过kafka设置的值会触发
* 场景二能不能关闭WATERMARK Event

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment]
In the case 1, the `max-message-bytes` is too small, only 10.

* s3 always receives the large message, this the changefeed failed and restart.
* the claim check message will be delivered to the kafka, which has the link to the large message in the S3, but the claim check message size is large than 10, cannot be delivered, then cause error and make the changefeed restart.


This is not a bug, the `max-message-bytes` should at least make sure the claim check message can be successfully delivered.

**Comment by 3AceShowHand** [comment]
In the case 2, the watermark will be delivered periodically, it's the normal behavior.

**Comment by lee1988well** [comment]
Thank you very much, I understand now.
