### ISSUE TITLE
update of changefeed configiration changefeed-error-stuck-duration not working

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10998]
### What did you do?

1. creaet an kafka changefeed with default configuration (changefeed-error-stuck-duration default 30m)
2. pause and update changefeed, set changefeed-error-stuck-duration to 90m
3. resume changefed
4. Inject network partition between cdc and kafka for 60m

### What did you expect to see?

CDC should be able to tolerate network partition between cdc and kafka for 90m, before that CDC changefeed should not be in failed state.

### What did you see instead?

CDC changefeed in failed state after 30m.
![image](https://github.com/pingcap/tiflow/assets/7403864/e0abd641-2cdb-4d39-99d6-811707df92a8)
![img_v3_02a9_30a1b0ad-2ddb-4312-a945-f6d39177706g](https://github.com/pingcap/tiflow/assets/7403864/96a2725a-20b3-40b1-874f-07d5b1bcc481)

### Versions of the cluster

master

**Comment by asddongmen** [comment]
The root cause of the issue is that the feedStateManager.changefeedErrorStuckDuration is set at the time of a changefeed's creation and remains unchanged when the changefeed is updated.

**Comment by wk989898** [comment]
Get
