### ISSUE TITLE
cdc print unexpected logs

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#11022]
### What did you do?

1、create bdr cluster
2、create changefeed
3、restart downstream

### What did you see instead?

the up stream print log which was not unexpected
`[2024/05/02 09:57:33.821 +08:00] [ERROR] [config.go:210] ["The TiDB source ID should never be set to 0. Please report it as a bug. The default value will be used: 1."] [default=0]`

### Versions of the cluster

./cdc version
 Release Version: v8.1.0
Git Commit Hash: 38eb040812f817df410abe870952629df60fd01f
Git Branch: HEAD
UTC Build Time: 2024-04-30 06:27:14
Go Version: go version go1.21.4 linux/amd64
Failpoint Build: false
2024-05-02T07:06:00.351+0800

**Comment by asddongmen** [comment]
This issue will not cause any actual error; it's just an annoying log.
