### ISSUE TITLE
CDC resolved ts and checkpoint lag unstable and up to 2min

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#11060]
### What did you do?

1. Deploy TiDB cluster with 2 CDC nodes (16c32g)
2. Create kafka simple protocol changefeed
3. Run workload for 4k tables (row width: 1.8k, cdc throughtput ~12k

### What did you expect to see?

CDC lag should be stable 

### What did you see instead?

CDC resolve ts and checkpoint lag are very unstable, up to 2min sometimes.
![image](https://github.com/pingcap/tiflow/assets/7403864/5c0a9bee-a710-4db5-bfcc-6320e8643b89)

### Versions of the cluster

Release Version: v7.5.2-pr11031
Git Commit Hash: dd48f9e5bbd997a3885638315d5068bb194e2c80
Git Branch: heads/refs/tags/v7.5.2-pr11031
UTC Build Time: 2024-05-07 04:49:30
Go Version: go version go1.21.6 linux/amd64
Failpoint Build: false

**Comment by asddongmen** [comment]
Duplicated with #11078
