### ISSUE TITLE
CDC consumes too much cpu, and lag goes up from 2s to 4s every few hours

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#11078]
### What did you do?

1. TiDB cluster with 2 CDC nodes (24c32g)
cdc config:
```
 config: |
      log-file = "/var/lib/ticdc/log/ticdc.log"

      [debug]
        [debug.kv-client]
          frontier-concurrent = 32
```
TiKV cdc.min-ts-interval = "50ms"
2. CDC simiple protocol changefeed create to sync 4k tables (throughput <20k, rowwidth<10k)

### What did you expect to see?

CDC lag should be stable

### What did you see instead?

CDC lag goes up from 2s to 4s every few hours

![image](https://github.com/pingcap/tiflow/assets/7403864/8794f297-44cd-4a34-a6a5-bd68b2b32f52)
![image](https://github.com/pingcap/tiflow/assets/7403864/01aeac5e-ae8a-4327-b84a-e735d6219287)
![image](https://github.com/pingcap/tiflow/assets/7403864/e77837f0-614d-4c01-b628-336c070b82f6)
![image](https://github.com/pingcap/tiflow/assets/7403864/efac0b6f-74cf-46a7-984c-8fb67a7f2cd7)

### Versions of the cluster

Upstream TiKV version (execute `tikv-server --version`):

```console
[root@upstream-tikv-0 /]# /tikv-server -V
TiKV
Release Version:   8.1.0
Edition:           Community
Git Commit Hash:   6ebf7ef3a1627a59062ddfbe32b33006df881950

```

TiCDC version (execute `cdc version`):

```console
[root@upstream-ticdc-0 /]# /cdc version
Release Version: v8.1.0-lock-test
Git Commit Hash: 3afce276e3a79788be4e294bd4f322d844cffea7
Git Branch: heads/refs/tags/v8.1.0-lock-test
UTC Build Time: 2024-05-10 03:24:05
Go Version: go version go1.21.6 linux/amd64
Failpoint Build: false
```

**Comment by hicqu** [comment]
![图片](https://github.com/pingcap/tiflow/assets/8407317/5908ba55-509b-466e-9d17-6d9a483e0bee)

lag increasings always keep about 20 minutes, and intervals are always about 6h. I think there are some period changes.

**Comment by hicqu** [comment]
I find some doubts:
![图片](https://github.com/pingcap/tiflow/assets/8407317/ee6327d9-9245-4a63-9fae-e4aec92f00fb)
![图片](https://github.com/pingcap/tiflow/assets/8407317/fd7b6d26-cd8d-49a9-998f-fc25f2a2b7c1)
![图片](https://github.com/pingcap/tiflow/assets/8407317/9af7b4a9-2531-4980-a728-e9607e4fadfb)

Maybe we can adjust some parameters to fix it.
