### ISSUE TITLE
changefeed resolvedTS can not go on  after kill one of tidb

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#11341]
### What did you do?

1、create bdr 
2、run sysbench
3、kill one of tidb

### What did you expect to see?

changefeed lag can be less than 3s after fault recover

### What did you see instead?

changefeed resolvedTS can not go on and changefeed lag more and more after kill one of tidb
![image](https://github.com/pingcap/tiflow/assets/84712107/989ca314-6b08-4249-8180-a2080a0b9edc)

### Versions of the cluster

./cdc version
 Release Version: v8.2.0-alpha
Git Commit Hash: c001638fcf8cbe1790ca5d005a9a9464cfa53f84
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-21 11:36:49
Go Version: go version go1.21.10 linux/amd64
Failpoint Build: false
2024-06-24T11:57:43.248+0800

**Comment by hicqu** [comment]
Duplicated with https://github.com/tikv/tikv/issues/17211.
