### ISSUE TITLE
The creation time of the tidb_cdc.syncpoint_v1 table of the secondary cluster does not meet expectations

### ISSUE THREAD

**Issue by apollodafoni** [pingcap/tiflow#11375]
### What did you do?

1. Set the syncpoint interval to 5 minutes, and complete the creation of changefeeds for three clusters at 12:32:30
2. Primary cluster: tidb_cdc.syncpoint_v1 was created at 04:35:00
3. Secondary cluster: created at 2024-07-02 04:45:22, and it takes 13 minutes from create changefeed to tidb_cdc.syncpoint_v1
**This delay is greater than 2 syncpoint intervals**
4. The ticdc config is as follows
bdr-mode = true
force-replicate = true
enable-sync-point = true
sync-point-interval = "5m"

### What did you expect to see?

The creation time of the tidb_cdc.syncpoint_v1 table of the secondary cluster within 1~2 syncpoint intervals

### What did you see instead?

- more than 2 syncpoint intervals
- the changefeed status is warning
- the changefeed lag is very large

### Versions of the cluster

ticdc git_hash `2db092244d18c043f7f8ecc85a598680b33cc324`
tidb git_hash `585c631742acb338c9bd0913a89efc3efb5b884a`

**Comment by CharlesCheung96** [comment]
```log
[2024/07/02 04:40:08.276 +00:00] [ERROR] [changefeed.go:325] ["an error occurred in Owner"] [namespace=default] [changefeed=cluster-a-cluster-b] [error="[CDC:ErrMySQLTxnError]MySQL txn error: failed to create syncpoint table;: Error 8263 (HY000): The operation is not allowed while the bdr role of this cluster is set to secondary."]
```

The root cause is that ticdc did not set write source when creating syncpoint table.
