### ISSUE TITLE
mysql sink lag reached 206s when inject network partition between cdc and kafka

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#11449]
### What did you do?

1、create changefeed for mysql sink and kafka sink separately with the same upstream
2、run sysbench
3、inject network partition between cdc and kafka

### What did you expect to see?

will not effect mysql sink lag when inject network partition between cdc and kafka

### What did you see instead?

mysql sink lag reached 206s when inject network partition between cdc and kafka
![img_v3_02d9_93dba96b-9f5f-4404-b4cd-4fb96337f8cg](https://github.com/user-attachments/assets/c612d609-4f61-4182-afdd-475d24059ca6)

### Versions of the cluster

./cdc version
 Release Version: v8.2.0
Git Commit Hash: 498e3d3fd1cda4817e70ea50d27dcb157956349d
Git Branch: HEAD
UTC Build Time: 2024-07-03 02:52:36
Go Version: go version go1.21.10 linux/amd64
Failpoint Build: false
2024-07-30T10:59:11.930+0800

**Comment by asddongmen** [comment]
duplicate with: https://github.com/pingcap/tiflow/issues/11340
