### ISSUE TITLE
Support query argument redaction in DM logging

### ISSUE THREAD

**Issue by michaelmdeng** [pingcap/tiflow#11489]
### Is your feature request related to a problem?

When DM logs queries, either with debug logging for all queries, or when encountering errors with warning/error logging, it logs the entire text of the query with arguments. This risks logging sensitive data.

For example, many of the log lines in https://github.com/pingcap/tiflow/blob/master/dm/pkg/conn/baseconn.go will log (truncated) full queries and arguments

### Describe the feature you'd like

Configuration, similar to [tidb log redaction](https://docs.pingcap.com/tidb/stable/log-redaction), that will redact sensitive arguments from queries when DM logs them.

### Describe alternatives you've considered

Since they are logged at all possible log levels, no alternative but turning off logging entirely.

### Teachability, Documentation, Adoption, Migration Strategy

N/A

**Comment by db-will** [comment]
Hey @michaelmdeng , I want to follow up on this issue. Should we redact the SQL query, or is redacting the query arguments sufficient?

**Comment by lance6716** [comment]
There are still some places that forget to proactively use redact function.

**Comment by lance6716** [comment]
like https://github.com/pingcap/tiflow/blob/8e3b63acecbf9556c004c46ca3ab315953b096a4/dm/syncer/dbconn/db.go#L249

**Comment by db-will** [comment]
@lance6716 tried to find similar pattern as you presented, didn't find any other similar lines that print out query arguments. i create a update pr.
