### ISSUE TITLE
kafka consumer needs to correctly check partition and old message

### ISSUE THREAD

**Issue by wk989898** [pingcap/tiflow#11482]
### What did you do?

run kafka consumer

### What did you see instead?

simple protocol doesn't check partition and old message

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment]
This is not a bug, can be tagged as `enhancement`.
