### ISSUE TITLE
create table ddl executed too slow when using tidb as the downstream sink

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#11521]
### What did you do?

run `create table` ddl on the upstream TiDB.

### What did you expect to see?

TiCDC receive and execute ddl should be very quick

### What did you see instead?

![img_v3_02e1_71b504c8-8e37-4040-a340-2ac72edaa77g](https://github.com/user-attachments/assets/1f884ff5-a8d2-49ad-8d6f-233d7852f79c)

The second log is printed around 23 seconds later after the first one printed.

The root cause is that following query too slow, it may takes more than 20 seconds.

```
SELECT JOB_ID, JOB_TYPE, SCHEMA_STATE, SCHEMA_ID, TABLE_ID, STATE, QUERY
FROM information_schema.ddl_jobs
WHERE DB_NAME = "%s" 
    AND TABLE_NAME = "%s"
    AND JOB_TYPE LIKE "add index%%"
    AND (STATE = "running" OR STATE = "queueing")
LIMIT 1;
```

```
[2024/08/23 18:19:31.924 +08:00] [INFO] [async_ddl.go:165] ["async ddl query success"] [table=test.spmi_transfer_bill206] [duration=23.31010039s]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment]
This is introduced by #11476

**Comment by lance6716** [comment]
The root cause is https://github.com/pingcap/tidb/issues/52905
