### ISSUE TITLE
Upgrade go to 1.23

### ISSUE THREAD

**Issue by Benjamin2037** [pingcap/tiflow#11606]
### Is your feature request related to a problem?

No

### Describe the feature you'd like

Upgrade golang to version 1.23

**Comment by purelind** [comment]
Go 1.23 is released! Release notes https://go.dev/doc/go1.23.

In order to be able to use some new features introduced in go1.23 and  obtain subsequent security vulnerability fixes. We plan to upgrade go version to 1.23.1 on master branch( from version v8.4.0 use the go1.23).
