### ISSUE TITLE
eventFilter incorrectly affects update events

### ISSUE THREAD

**Issue by wk989898** [pingcap/tiflow#11636]
### What did you do?

1. create a changefeed with config
```
[filter]
rules = ['test.*']
[[filter.event-filters]]
matcher = ['test.t'] 
ignore-event = ["delete"] # filter out delete event of table `test.t` 
```
2. run sql
```
create table t (a int primary key);
insert into t values (1),(2);
update t set a = 3 where a = 1;
```

### What did you expect to see?

data should be equivalent

### What did you see instead?

```
The following tables contains inconsistent data

+------------+---------+--------------------+----------------+---------+-----------+
|   TABLE    | RESULT  | STRUCTURE EQUALITY | DATA DIFF ROWS | UPCOUNT | DOWNCOUNT |
+------------+---------+--------------------+----------------+---------+-----------+
| `test`.`t` | succeed | true               | +0/-1          |       2 |         3 |
+------------+---------+--------------------+----------------+---------+-----------+
```
fix sql:
```
DELETE FROM `test`.`t` WHERE `a` = 1 LIMIT 1;
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by wk989898** [comment]
The reason is that update event will be splited into delete event and insert event, and delete event will be ignored.

**Comment by asddongmen** [comment]
This behavior is mentioned in the official doc: https://arc.net/l/quote/vmuihkck 
cc @wk989898 @fubinzh

**Comment by wk989898** [comment]
close with https://github.com/pingcap/docs-cn/pull/18865
