### ISSUE TITLE
metadata error with MariaDB 11.4

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiflow#11735]
### What did you do?

Setup DM with MariaDB 11.4

### What did you expect to see?

"Message": "parse mydumper metadata error: [code=11123:class=functional:scope=upstream:level=low], Message: didn't found binlog location in dumped metadata file metadata, Workaround: Please check log of dump unit, there maybe errors when read upstream binlog status, metadata: Started dump at: 2024-11-08 16:30:53\nSHOW BINARY LOG STATUS:\n\tLog: mysqld-bin.000002\n\tPos: 329\n\tGTID:\n\nFinished dump at: 2024-11-08 16:30:54\n",

### Versions of the cluster

master @ 64decf62203ff818af81756368e3f302af36f946

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
caused by https://github.com/pingcap/tiflow/blob/64decf62203ff818af81756368e3f302af36f946/dm/pkg/dumpling/utils.go#L125-L146

we didn't handle `SHOW BINARY LOG STATUS`

**Comment by joccau** [comment]
> ### What did you do?
> Setup DM with MariaDB 11.4
> 
> ### What did you expect to see?
> "Message": "parse mydumper metadata error: [code=11123:class=functional:scope=upstream:level=low], Message: didn't found binlog location in dumped metadata file metadata, Workaround: Please check log of dump unit, there maybe errors when read upstream binlog status, metadata: Started dump at: 2024-11-08 16:30:53\nSHOW BINARY LOG STATUS:\n\tLog: mysqld-bin.000002\n\tPos: 329\n\tGTID:\n\nFinished dump at: 2024-11-08 16:30:54\n",
> 
> ### What did you see instead?
> _No response_
> 
> ### Versions of the cluster
> master @ [64decf6](https://github.com/pingcap/tiflow/commit/64decf62203ff818af81756368e3f302af36f946)
> 
> ### current status of DM cluster (execute `query-status <task-name>` in dmctl)
> ```
> (paste current status of DM cluster here)
> ```

Is the answers to question reversed for `What did you expect to see?` and `What did you see instead?` ?

**Comment by dveeden** [comment]
@joccau yes indeed. When setting up DM with MariaDB 11.4 I would expect it to work, but what I see instead is this error that mentions `SHOW BINARY LOG STATUS`.

I'm not sure it should mention `SHOW BINARY LOG STATUS` as that's for recent versions of MySQL and with MariaDB I would expect `SHOW MASTER STATUS`.
