### ISSUE TITLE
[Lightning:DB:ErrInitErrManager]init error manager error: create conflict view failed: Error 1146 (42S02): table doesn't exist

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#11811]
### What did you do?

dm upstream switch job failed, see https://github.com/pingcap/tiflow/actions/runs/12035450530

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
It's not caused by https://github.com/pingcap/tidb/pull/57480 . Please attach TiDB log in GitHub actions artifacts to know what's happened

**Comment by GMHDBJD** [comment]
close via #11904
