### ISSUE TITLE
CDC print lots of "etcd client outCh blocking too long, the etcdWorker may be stuck" and checkpoint lag metric abnormal

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#11884]
### What did you do?

1. create cdc changefeed
2. run workload (use lighting tidb backend to import 10+ tables )

### What did you expect to see?

CDC should be normal.

### What did you see instead?

CDC print lots of WARN : 
{"container":"ticdc","namespace":"cdc-testbed-tps-7653796-1-407","pod":"upstream-ticdc-0","log":"[client.go:272] [\"etcd client outCh blocking too long, the etcdWorker may be stuck\"] [duration=5m32.997091037s] [role=owner]","level":"WARN"}

CDC checkpoint lag abnormal:
![Image](https://github.com/user-attachments/assets/6f87d6bd-0490-4f98-894a-3db16c8334f0)

### Versions of the cluster

cdc version: master, git-hash: 45388394a9b50411b1e15c91e65e476d8aafa928

**Comment by flowbehappy** [comment]
Introduces by https://github.com/pingcap/tiflow/pull/11830
