### ISSUE TITLE
sarama produces messages in out-of-order when retries happen

### ISSUE THREAD

**Issue by wk989898** [pingcap/tiflow#11935]
we found sarama sends out-of-order messages when retries happen, and we think the issue causes this:  
- https://github.com/IBM/sarama/issues/2619

This could be reproduced by hacking codes. https://github.com/wk989898/sarama/commit/d06ee56ae5986f77f5bc88b8a63290e068a9c16c

**Comment by 3AceShowHand** [comment]
This affect release after v6.4.0
