### ISSUE TITLE
How can I filter if Kafka sink sends messages repeatedly?

### ISSUE THREAD

**Issue by masonone** [pingcap/tiflow#1263]
```
Replication order
For all DDL or DML statements, TiCDC outputs them at least once.

When the TiKV or TiCDC cluster encounters failure, TiCDC might send the same DDL/DML statement repeatedly. For duplicated DDL/DML statements:

MySQL sink can execute DDL statements repeatedly. For DDL statements that can be executed repeatedly in the downstream, such as truncate table, the statement is executed successfully. For those that cannot be executed repeatedly, such as create table, the execution fails, and TiCDC ignores the error and continues the replication.
Kafka sink sends messages repeatedly, but the duplicate messages do not affect the constraints of Resolved Ts. Users can filter the duplicated messages from Kafka consumers.
```

How can I filter if Kafka sink sends messages repeatedly? I use the canal-json format, which is consumed by flink.

**Comment by liuzix** [comment]
Since the current version of TiCDC does not support exactly once delivery, maybe you can try deduplicating using Flink's stateful computation? If you need any help implementing this, we can get in touch.

**Comment by masonone** [comment]
> Since the current version of TiCDC does not support exactly once delivery, maybe you can try deduplicating using Flink's stateful computation? If you need any help implementing this, we can get in touch.

Ok i try this.

**Comment by hi-rustin** [comment]
If you have any other questions please feel free to comment and I will close the issue.
