### ISSUE TITLE
Server log rotation configuration

### ISSUE THREAD

**Issue by LINKIWI** [pingcap/tiflow#1384]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiCDC server currently inherits log rotation configuration defaults when output to a log file is enabled.

**Describe the feature you'd like:**

The ability to configure log rotation parameters on the command line alongside `--log-file` and `--log-level`.

Currently, the log configuration struct is only partially populated: call trace:

https://github.com/pingcap/ticdc/blob/8ba8df75bd4a1fa9a0ffa847eabb2136fffe658f/cmd/server.go#L92

https://github.com/pingcap/ticdc/blob/8ba8df75bd4a1fa9a0ffa847eabb2136fffe658f/cmd/util.go#L83

https://github.com/pingcap/ticdc/blob/8ba8df75bd4a1fa9a0ffa847eabb2136fffe658f/pkg/logutil/log.go#L88

https://github.com/pingcap/log/blob/8f1e84a3abc8f75ae33a8bee86d561f21057393e/log.go#L41

https://github.com/pingcap/log/blob/8f1e84a3abc8f75ae33a8bee86d561f21057393e/log.go#L86

I'm proposing the addition of new server CLI flags `--log-max-size`, `--log-max-days` and `--log-max-backups` and propagating these values to the underlying logger per the stack trace above.

If this is something the team would be interested in I'm happy to submit a patch.

**Describe alternatives you've considered:**

N/A, feature is not critically needed.

**Teachability, Documentation, Adoption, Migration Strategy:**

If the proposal is accepted I can file some follow up documentation PRs as well as needed.

**Comment by amyangfei** [comment]
@LINKIWI  Thanks for your proposal. TiCDC does lack the configuration for log rotation.

In [TiDB](https://github.com/pingcap/tidb), there exist [three configuration items](https://github.com/pingcap/tidb/blob/109ad453031aa69124230cea4a5e0bb565d7783a/config/config.toml.example#L174-L181 ) corresponding to log rotation

```toml
# Max log file size in MB (upper limit to 4096MB).
max-size = 300

# Max log file keep days. No clean up by default.
max-days = 0

# Maximum number of old log files to retain. No clean up by default.
max-backups = 0
```

We would like to provide the same configuration in TiCDC.

However TiCDC server doesn't accept a config file now, the requirement is described in https://github.com/pingcap/ticdc/issues/1257. In my opinion, if we want to add the above mentioned configuration, we'd better add a config file to TiCDC first. It is very welcome to contribute this feature.

**Comment by LINKIWI** [comment]
I agree that the better path to supporting this would be a TiCDC config file in the same way as TiDB. I'll track #1257, I might be able to give its implementation a try if I have the time.

**Comment by SuperSupeng** [comment]
@LINKIWI I will add the configuration items to the config file recently.
