### ISSUE TITLE
When cdc owner is killed and all PD is restarting, all other CDC server exit with error 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1570]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Start 3x CDC server
- Kill the CDC owner
- Restart all PD: $tiup cluster restart -R pd

2. What did you expect to see?

- New CDC owner will be selected from the rest CDC server

3. What did you see instead?

- Both the rest 2x CDC servers are exit with error:
  Error: run server: new etcd client: [CDC:ErrNewCaptureFailed]context deadline exceeded

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       Release Version: v5.0.0
       Edition: Community
       Git Commit Hash: b18eae98087148ad967d7fcbf6586ed7b9607c4b
       Git Branch: heads/refs/tags/v5.0.0
        UTC Build Time: 2021-03-24 15:31:59

        ```

    - TiCDC version (execute `cdc version`):

        ```
       Release Version: v5.0.0-nightly-15-g8968aae
       Git Commit Hash: 8968aae98bc9832afb0c484a9e01bb8e0c665ba7
       Git Branch: HEAD
       UTC Build Time: 2021-03-29 08:31:59
        ```

**Comment by overvenus** [comment]
Can not reproduce the issue locally with the latest release, change to severity/moderate
