### ISSUE TITLE
Execute cdc command failed but not return any error 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1624]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
$ tiup cdc:nightly cli changefeed pause -c replication-task-1 --pd=http://172.31.10.94:2379
This command failed to execute but no any error message returned.

2. What did you expect to see?
Tell user the command failed to execute and the reason.

3. What did you see instead?
![image](https://user-images.githubusercontent.com/78345569/114129531-4bdaa680-9931-11eb-855e-49696baf196c.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       v5.0.0
        ```

    - TiCDC version (execute `cdc version`):

        ```
      release-5.0    Git Commit Hash: 39c1bd9ba9c3ab0e704d03a58df0360501e9f3bd
        ```

**Comment by JinLingChristopher** [comment]
I'm trying to  reproduce the issue, this is the following step:
`tiup playgound`
`./bin/cdc cli changefeed create --pd=http://127.0.0.1:2379 --sink-uri="mysql://root:123456@127.0.0.1:3306/" --changefeed-id=replication-task-1`
but I meet that `failed to open MySQL connection issue`

![Screen Shot 2021-04-13 at 00 15 53](https://user-images.githubusercontent.com/7138436/114427220-748ec480-9bed-11eb-8c5a-b6c139f6ec87.png)

Is there anything wrong?

**Comment by JinLingChristopher** [comment]
@Tammyxia can you provide the full commands，I'm new to ticdc，this can help me to solve the issue.

**Comment by JinLingChristopher** [comment]
`tiup playground`
`tiup cdc:nightly server --pd=http://127.0.0.1:2379`
`tiup cdc:nightly cli changefeed create --pd=http://127.0.0.1:2379 --sink-uri="mysql://root:123456@127.0.0.1:3306/" --changefeed-id="replication-task-1"`
`tiup cdc:nightly cli changefeed pause -c replication-task-1 --pd=http://127.0.0.1:2379 `
![Screen Shot 2021-04-13 at 3 46 12 PM](https://user-images.githubusercontent.com/7138436/114515882-6b463c00-9c6f-11eb-8bee-44191990d888.png)

I cannot reproduce the issue, it works fine on my machine.
@Tammyxia, can you provide the full commands that cause the problem?

**Comment by Tammyxia** [comment]
The command already is included in issue description.
If you have a changfeed that is in failed status , executing " tiup cdc:nightly cli changefeed pause -c replication-task-1 --pd=xxx"  still cannot pause it, but the command has not any error output like "Failed to pause this changfeed since it has been in failed status."

**Comment by asddongmen** [comment]
Close it since its stale.
