### ISSUE TITLE
CDC scan incremental data size(1.8TB+) is much larger than upstream the real incremental data size(327GB)

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1642]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Use lightning import 327GB data size to upstream TiDB.
- Resume changfeed,  sync the above 1 table with 327GB data size.

2. What did you expect to see?

3. What did you see instead?
![image](https://user-images.githubusercontent.com/78345569/114379992-1eedf400-9bbc-11eb-821f-dc694964c63b.png)
![image](https://user-images.githubusercontent.com/78345569/114380116-447afd80-9bbc-11eb-8e02-99cfeabe22cd.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
     Release Version: v5.0.0
     Edition: Community
     Git Commit Hash: bdac0885cd11bdf571aad9353bfc24e13554b91c
     Git Branch: heads/refs/tags/v5.0.0
     UTC Build Time: 2021-04-06 16:36:29

        ```

    - TiCDC version (execute `cdc version`):

        ```
      Release Version: v5.0.0
      Git Commit Hash: 39c1bd9ba9c3ab0e704d03a58df0360501e9f3bd
      Git Branch: release-5.0
      UTC Build Time: 2021-04-07 06:11:14
       Go Version: go version go1.13 linux/amd64

        ```

**Comment by amyangfei** [comment]
The same reason as #1843

**Comment by overvenus** [comment]
As of 2021/12, TiCDC is not fully compatiable with TiDB-Lightning import and BR restore, we will add it the TiCDC roadmap, also change the issue to severity/moderate.

**Comment by sdojjy** [comment]
see https://github.com/pingcap/tiflow/issues/1843
