### ISSUE TITLE
PD is down if CDC enabled during restoration.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tiflow#1676]
## Bug Report
see https://github.com/pingcap/br/issues/891

1. What did you do? If possible, provide a recipe for reproducing the error.
Restore some data to the cluster that enables CDC.
2. What did you expect to see?
Cluster is normal whether BR restore failed or not.
3. What did you see instead?
PD restarts and then TiKV restarts.

4. Versions of the cluster

    master

**Comment by lonng** [comment]
I will change the severity from critical to major because this scenario is not a common case.

**Comment by overvenus** [comment]
It's a known issue for TiCDC, that TiCDC may write lots of metadata to PD when there are freqent DDLs, and we have mitigated this issue, see https://github.com/pingcap/ticdc/issues/993 .
