### ISSUE TITLE
CDC Synchronize big transaction is too slow

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1683]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Pause changfeed.
- Start transaction operation  which has 5GB data in TiDB,  this process duration time is about half an hour. 
- Resume changfeed, observe the big transaction sync status.

2. What did you expect to see?

3. What did you see instead?
sync duration time is more than 5 hours， 
![image](https://user-images.githubusercontent.com/78345569/115491903-6565e180-a293-11eb-9700-30c43f7246a1.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v5.0.1
   

>  Edition: Community
> Git Commit Hash: 4141f837ad4655a567119db743b7b752a95f5aa2
> Git Branch: heads/refs/tags/v5.0.1
> UTC Build Time: 2021-04-17 04:28:49

        ```

    - TiCDC version (execute `cdc version`):

        ```
> Release Version: v5.0.0-master
> Git Commit Hash: 6363c4810edf2e25f63df28ace9b6f0a2939c6b9
> Git Branch: heads/refs/tags/v5.0.1
> UTC Build Time: 2021-04-17 04:40:20

        ```

**Comment by Tammyxia** [comment]
The workload in upstream is "start transaction; update more then 10 million rows; commit".

**Comment by overvenus** [comment]
It's more like a feature request, we will add it to TiCDC roadmap, thanks!
