### ISSUE TITLE
cdc cli changefeed list displays improper error messages

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#1696]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Error messages are wrongly formatted `"message": "[CDC:ErrMetaListDatabases][tikv:9001]PD server timeout%!(EXTRA string=start timestamp may fall behind safe point)"`.

```
➜ tiup cdc:v5.0.0-nightly cli changefeed list
Starting component `cdc`: /home/stn/.tiup/components/cdc/v5.0.0-nightly/cdc cli --pd=http://172.16.5.33:47902 changefeed list
[
  {
    "id": "bl1",
    "summary": {
      "state": "normal",
      "tso": 424522438189777299,
      "checkpoint": "2021-04-26 16:09:44.159",
      "error": {
        "addr": "172.16.5.33:47912",
        "code": "CDC-owner-1001",
        "message": "[CDC:ErrMetaListDatabases][tikv:9001]PD server timeout%!(EXTRA string=start timestamp may fall behind safe point)"
      }
    }
  }
]
```

2. What did you expect to see?

No '%!(EXTRA' in the error message.

3. What did you see instead?

4. Versions of the cluster

TiCDC: 3e215b07

**Comment by amyangfei** [comment]
https://github.com/pingcap/tidb/blob/d9e2bd3da49ec3e9a062831fb6e4ab1219a8d158/store/tikv/kv.go#L99

https://github.com/pingcap/tidb/blob/d9e2bd3da49ec3e9a062831fb6e4ab1219a8d158/errno/errname.go#L1047

**Comment by asddongmen** [comment]
Close it since it is stale.
