### ISSUE TITLE
When query  changfeed that has never been created, the error info is misled

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1703]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Query changfeed that has never been created:
![image](https://user-images.githubusercontent.com/78345569/116197977-f9d6b500-a767-11eb-9d46-0bef9dcbcf2b.png)

2. What did you expect to see?

- Distinguish changfeed that has been deleted in 24hours or has not existed yet.

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
         5.0.0-nightly
        ```

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
