### ISSUE TITLE
Create changfeed Succefully  with invalid sink-uri

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1704]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changfeed with invalid sink-uri 
- 
![image](https://user-images.githubusercontent.com/78345569/116198607-bd578900-a768-11eb-97a3-b987e87ab8e4.png)

2. What did you expect to see?
Failed to create changfeed 
3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.0-nightly      
       ```

    - TiCDC version (execute `cdc version`):

        ```
         5.0.0-nightly
        ```

**Comment by amyangfei** [comment]
sink uri verification for `--sink-uri="mysql::://root:@172.16.4.142:3306/"` is not correct

**Comment by amyangfei** [comment]
IMHO this bug is dangerous, because once user creates a changefeed with invalid sink-uri, the invalid changefeed could block the execution of DDL and cause replication interruption

**Comment by amyangfei** [comment]
@Tammyxia Can you confirm the invalid changefeed can affect the normal changefeed?
In my test environment it doesn't

**Comment by Tammyxia** [comment]
@amyangfei Yes. First pause the normal changefeed, while the invalid one status looks normal. After about 15 minutes, resume the normal changefeed, you can see it will be stuck.

**Comment by hi-rustin** [comment]
Sorry, I linked the issue by mistake.

**Comment by asddongmen** [comment]
Close it since it is stale. 
It has been fixed in > v6.1.0.
