### ISSUE TITLE
Create changfeed command failed to identify special characters 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1705]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changfeed, the downstream DB has password with !@#
![image](https://user-images.githubusercontent.com/78345569/116204969-db74b780-a76f-11eb-870b-a764a9df8970.png)

2. What did you expect to see?

- Create changfeed successfully.

3. What did you see instead?
![image](https://user-images.githubusercontent.com/78345569/116204990-e29bc580-a76f-11eb-8402-27469d0033be.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.0-nightly
        ```

**Comment by Tammyxia** [comment]
Replace --sink-uri='mysql://root:Pingcap!%40%231@172.16.4.142:3306/?time-zone=SYSTEM' succefully to create changfeed, this means apostrophe '' works but Double quotes "" not works.
shelll version:
# echo $SHELL
/bin/bash
# /bin/bash --version
GNU bash， 版本 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.

# tiup --version
'1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea

**Comment by hi-rustin** [comment]
This is essentially an escape character problem for URLs.

Try it in: https://go.dev/play/p/judO62rvWOG

**Comment by hi-rustin** [comment]
URLs are required to be escaped, so this is not a bug.
