### ISSUE TITLE
worker-count should has limit to set value

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1716]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed --sink-uri='xxx/worker-count=0' 
![image](https://user-images.githubusercontent.com/78345569/116341821-2d6f1900-a814-11eb-8f2b-24f30da227a6.png)

- Create changefeed --sink-uri='xxx/worker-count=1000000000000000'
![image](https://user-images.githubusercontent.com/78345569/116342034-82129400-a814-11eb-9740-72b2ba7a9b52.png)

2. What did you expect to see?

- worker-count=0 is not allowed to set
- What is the max value for  worker-count? worker-count=1000000000000000 seems too large to allowed be to set.

3. What did you see instead?
Successfully to create changefeed with worker-count=0 or worker-count=1000000000000000
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.0-nightly
        ```

**Comment by Tammyxia** [comment]
![image](https://user-images.githubusercontent.com/78345569/116346666-45976600-a81d-11eb-9a42-d33dc1dcbeb6.png)
too large worker-count makes  runtim oom.

**Comment by hi-rustin** [comment]
> /worker-count=-1 also allowed to create.

It will use the default value.
