### ISSUE TITLE
Update filter table don't works in some of capture

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1723]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Config: 3x CDC server, 1xchangefeed, at first there's 20 table count.
- Update changefeed, filter 2x table:  tiup ctl:v5.0.0-nightly-20210429 cdc changefeed update --config change.toml --pd=http://172.16.6.53:2379 -c=abcde
- 
![image](https://user-images.githubusercontent.com/78345569/116508452-fec86f80-a8f3-11eb-9f90-5e540ff6968c.png)

2. What did you expect to see?
Only 2x table from metrics

3. What did you see instead?

- One capture still listen 6x table

![image](https://user-images.githubusercontent.com/78345569/116508617-523abd80-a8f4-11eb-9ce3-f77a4d32066a.png)

- Compare cdc log between cdc server, one has incorrect filter info
53:
![image](https://user-images.githubusercontent.com/78345569/116508741-9201a500-a8f4-11eb-8a2e-425a530b3510.png)
54:
![image](https://user-images.githubusercontent.com/78345569/116508770-a34ab180-a8f4-11eb-9030-6cefc10d0a78.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.0-nightly
        ```

**Comment by asddongmen** [comment]
I can not reproduce this issue in both `v5.0.0-nightly` and the manster branch.
If you find the problem again, please feel free to reopen this issue.
