### ISSUE TITLE
When upstream has not workload and downstream mysql is shutted down,  changefeed still seems like normal

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1781]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- When upstream has not any workload,  downstream is MySQL and the server is shutted down
- Check changefeed status

2. What did you expect to see?
Changefeed status is stopped automatically since downstream server has shut down, it can quick debug the execption.
3. What did you see instead?
Changefeed status is normal and checkpoint has the latest time.
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.1
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.1
        ```

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
