### ISSUE TITLE
The changefeed checkpoint delay alerts persist after removing replication task 

### ISSUE THREAD

**Issue by pcqz** [pingcap/tiflow#1796]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

When TiCDC changefeed hang sometimes, we have to remove and re-create replication task in order to avoid impact of delay and possible OOM. After removing task, there are still a lot of noisy checkpoint delay alerts till we restart ticdc cluster.

2. What did you expect to see?

The related prometheus metrics are unregistered and no alerts arise.

3. What did you see instead?

These changefeed metric data like ticdc_processor_checkpoint_ts_lag are still fetched from monitor.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       TiDB 4.0.8
        ```

    - TiCDC version (execute `cdc version`):

        ```
        TiCDC 4.0.12
        ```

**Comment by asddongmen** [comment]
Close it since it is stale. 
If it happens again, please file an new issue and contact me.
