### ISSUE TITLE
TiCDC should respect cgroup limits

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#1798]
## Bug Report

1. What did you do? If possible, provide a recipe for reproducing the error.

TiCDC should respects cgroup limits on Linux:

- [CPU Quota](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#:~:text=CPUQuota)
- [MemoryMax/MemoryLimit](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#MemoryMax=bytes)

Otherwise, TiCDC may be misconfigured and cause OOM or other issues, 

- [x] https://github.com/pingcap/ticdc/pull/3436 unified sorter adjust memory usage according to system memory.
- [ ] Full support of recognizing cgroups, including cgroups set by systemd and manually.

2. What did you expect to see?

N/A

3. What did you see instead?

N/A

4. Versions of the cluster

master, v4.0.12 and v5.0.1

**Comment by overvenus** [comment]
For the second task, we can port TiKV cgroup detection https://github.com/tikv/tikv/blob/7b677d60ab3b60b3ef4750da09718ba8114060ed/components/tikv_util/src/sys/cgroup.rs

**Comment by amyangfei** [comment]
Task-2 is closed by https://github.com/pingcap/tiflow/pull/8589
