### ISSUE TITLE
Monitor for table resolved ts has invalid datatime

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1833]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Check table resolved ts in cdc monitor
- 
![image](https://user-images.githubusercontent.com/78345569/119428317-371a6c80-bd3f-11eb-9239-187c2da291cb.png)

2. What did you expect to see?

- 05-24 18:49:09.778

3. What did you see instead?

- 01-01 08:00:00.000

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
        [release-version=v5.0.0-master] [git-hash=1c0706e4d2ee2ad3e115bda9a95698f7aca1cee9] [git-branch=master] [utc-build-time="2021-05-21 07:53:31"] [go-version="go version go1.13 linux/amd64"]
        ```

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
