### ISSUE TITLE
cdc scan data size is much more larger than the incremental data size

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1843]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Pause changefeed, then lightning load data to upstream tidb, backend=tidb.
- When load 200GB data size, resume changefeed.
- Waiting for changefeed sync completing. 

2. What did you expect to see?

3. What did you see instead?
1. The time from changefeed resume to sync completed takes 14 hours.
 2. kv scan 1.6TB while the real incremental data size is only 200GB, and unified sorter disk usage is also 1.6TB.
 
![image](https://user-images.githubusercontent.com/78345569/119619452-97d8a080-be36-11eb-98c4-d3212494afa7.png)
![image](https://user-images.githubusercontent.com/78345569/119619510-a7f08000-be36-11eb-96ac-7a1af702be8c.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0-nightly 05-24-2021
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.0-nightly 05-24-2021
        ```

**Comment by amyangfei** [comment]
The version `5.0.0-nightly 05-24-2021` could reconnect when a region is in incremental scan state, which causes large amount of duplicated scan data.
We have refined the reconnect strategy in #1949, could you please confirm this issue has been solved @Tammyxia ?

**Comment by overvenus** [comment]
Both table rebalance and TiKV leader transfer will cause TiKV scan data more than we wrote. As long as TiCDC/TiKV are in stable state, it won't be a problem. Change to severity/moderate

**Comment by nongfushanquan** [comment]
could you please  check this issue has been solved  in the recent version?

**Comment by sdojjy** [comment]
it's not a bug, we will improve this case in feature.
