### ISSUE TITLE
After removing changefeed, the removed changefeed is still visible in list command for several seconds

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1975]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Remove changefeed, then immediately list changefeed, it is still visible.
![image](https://user-images.githubusercontent.com/78345569/120975714-2092fd00-c7a4-11eb-8372-abd45d1954b1.png)

- After 3 second, list changefeed again, it finally disapeared.

2. What did you expect to see?

- After removing changefeed command completed,  the changefeed will not disapear in list command.

3. What did you see instead?

- The removed changefeed is still visible for about 3 seconds after removing command returned.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.2
        ```

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
