### ISSUE TITLE
Since --sort-dir is unsupported but error message is incorrect

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2079]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 
![75ySxZ9jT1](https://user-images.githubusercontent.com/78345569/122341845-8470af00-cf76-11eb-9348-f7cfb17593c1.png)

2. What did you expect to see?

- Refer to other unsupported paramter 
![9qZYQ6OqdW](https://user-images.githubusercontent.com/78345569/122342029-b4b84d80-cf76-11eb-89dd-bda50edfc67d.png)

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v5.1.0-20210615
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v5.1.0-20210615
        ```

**Comment by amyangfei** [comment]
will be fixed by https://github.com/pingcap/ticdc/pull/1921

**Comment by overvenus** [comment]
`sort-dir` has been deprecated.
