### ISSUE TITLE
After changefeed syncing for 5-10 minutes, it failed "checkpoint-ts xxx is earlier than GC safepoint at xxx", gc-ttl is 10days

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2112]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed with --start-ts"tiup cdc cli changefeed create --pd=http://172.16.6.195:2379 --sink-uri='mysql://tester:PingCAP!1@172.16.6.223:3306'   --changefeed-id="ddl-dml-cf3"  --start-ts=425699977987621864" successfully:
![MEXaIBHT7G](https://user-images.githubusercontent.com/78345569/122710253-7da5ad00-d292-11eb-989d-4c81dbdf9815.png)

- gc-ttl is 10 days:

![vg3S6E9tff](https://user-images.githubusercontent.com/78345569/122710286-8d24f600-d292-11eb-9481-44b3651f3596.png)

- After 9 minutes, this changefeed become failed with error  "checkpoint-ts xxx is earlier than GC safepoint at xxx":
![TTMrZnvyim](https://user-images.githubusercontent.com/78345569/122710386-b8a7e080-d292-11eb-92e5-f13de9206c78.png)

2. What did you expect to see?

- No error about  "checkpoint-ts xxx is earlier than GC safepoint at xxx" since gc-ttl is 10days.

3. What did you see instead?
 "checkpoint-ts xxx is earlier than GC safepoint at xxx"

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.1.0
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.1.0
        ```

**Comment by amyangfei** [comment]
![image](https://user-images.githubusercontent.com/1527315/122723879-037f2380-d2a6-11eb-835f-329e7fa94663.png)
- A stopped changefeed exists
- cdc owner meets the error `update gc safe point failed, the gc safe point is larger than checkpointTs` continuously  when updating service GC safepoint (`[2021/06/17 16:59:01.332 +08:00] [WARN] [gc_manager.go:100] ["update gc safe point failed, the gc safe point is larger than checkpointTs"] [actual=425700764419358720] [checkpoint
Ts=425499687368523788]`)

**Comment by asddongmen** [comment]
This bug can't be repreduced again now. 
I will try to fix it in the future.

**Comment by Tammyxia** [comment]
Change to major severity because it happened in low rate.

**Comment by LiPL2017** [comment]
Similar error occured
![image](https://user-images.githubusercontent.com/33644226/143825778-4576c0ac-5251-4b23-9d29-550b8babafba.png)

CDC log

> [2021/11/29 05:42:23.571 +08:00] [WARN] [gc_manager.go:103] ["update gc safe point failed, the gc safe point is larger than checkpointTs"] [actual=429427244870926336] [checkpointTs=429368326827016194]

**Comment by asddongmen** [comment]
> Similar error occured ![image](https://user-images.githubusercontent.com/33644226/143825778-4576c0ac-5251-4b23-9d29-550b8babafba.png)
> 
> CDC log
> 
> > [2021/11/29 05:42:23.571 +08:00] [WARN] [gc_manager.go:103] ["update gc safe point failed, the gc safe point is larger than checkpointTs"] [actual=429427244870926336] [checkpointTs=429368326827016194]

@LiPL2017 Could you plase provide more information like cdc version and cdc log to help us locate this problem? Thanks~!

**Comment by LiPL2017** [comment]
@asddongmen 
CDC Version: 5.2.2 and I am using v5.3.0 now. I found another bug:
1. start a mock kafka server
2. create a changefeed with kafka sink
3. restart mock server then cdc would block and checkpoint didn't update unless restart cdc

**Comment by overvenus** [comment]
> @asddongmen CDC Version: 5.2.2 and I am using v5.3.0 now. I found another bug:
> 
> 1. start a mock kafka server
> 2. create a changefeed with kafka sink
> 3. restart mock server then cdc would block and checkpoint didn't update unless restart cdc

@LiPL2017 Could you elaborate the mock kafka server? (A link to mock kafka server source code is better.) Maybe it's the issue that can be fixed by #3598 .

**Comment by overvenus** [comment]
After https://github.com/pingcap/tiflow/pull/2512, this issue have been mitigated. Feel free to reopen if it happens again.
