### ISSUE TITLE
"A table is being replicated by at least two processors xxx, Please report a bug", changefeed close

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2116]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Delete changefeed named pk-cf3.
- Create changefeed also named pk-cf3, DDL writing in upstream.

2. What did you expect to see?

- Sync completed without error.

3. What did you see instead?

- Error in cdc.log:
![Uploading image.png…]()

- sync can be completed.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.1.0 6-17
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.1.0 6-17
        ```

**Comment by asddongmen** [comment]
It never occurs again. 
If you meet this bug again, please reopen this issue and @ me, thanks!
