### ISSUE TITLE
Tracking issue for replace github.com/pingcap/check with github.com/stretchr/testify

### ISSUE THREAD

**Issue by ben1009** [pingcap/tiflow#2164]
## Background

as described in the thread https://internals.tidb.io/t/topic/141/6

```
I did ever use testify in pingcap/errors [[1]](https://github.com/pingcap/errors/pull/36) and it works well with richer matchers and default parallelism support.

I think the modification from gocheck to pingcap/check mainly focuses on parallelism. It is possibly we switch to testify to live with a stronger community instead of a lack of maintenance version of a smaller community.

* [testify ](https://github.com/stretchr/testify) has 188 contributors and latest updated at Apr. 27
* [go-check](https://github.com/go-check/check) has 13 contributors and latest updated at last year.

If you think this direction is good to go, maybe we can draft a pre-RFC to collect wider input.
```

This is somewhat a subtask of https://github.com/pingcap/tidb/issues/26022 that we make a decision that deprecating [pingcap/check](https://github.com/pingcap/check) and adopting [testify](https://github.com/stretchr/testify). Take a look at the tidb issue for more information.

After an offline discussion with @overvenus we think it is fine we make the same change on this repo and here is the tracking issue for the effort.

If you have any further concern, please comment below and reply will be in days.

We first write down a task list and since I have no time to continue the actual work, let's kick off when there is a contributor ask for starting the subtasks.

## Join Forces

If you want to participant the movement, you can comment under this issue to acquire pkg or files to migrate. For example,

```
Hi, I'd like to migrate tests under `errno` pkg. Please create a subtask and assign to me.
```

React will be in time and do the favor for you.

Also you can directly comment under any open issues below without assignee to require assignment.

You can take a look at https://github.com/pingcap/tidb/pull/26375 as an example to do the migration.

## Note
* new unit-test

    - New uts should use testify and goleak directly. Ref to the [Pr 2833](https://github.com/pingcap/ticdc/pull/2833)
    - Pkg github.com/pingcap/tidb/util/testkit should be replaced by github.com/pingcap/tidb/testkit

* parallel

    - Keep test cases as parallel as possible.
    - Don't use t.Parallel() if pkg has failpoint control. Need review Carefully.
    - When some test cases should be run in serial, take use of go testing subtests (t.Run(name string, f func(t *T))) and parallel the parent test only. In this way, test cases in the same subtests set run in serial.
    - Avoid using suite of testify as discussed errno: [migrate test-infra to testify #26082 (comment)](https://github.com/pingcap/tidb/pull/26082#issuecomment-877230972)

* migrate kits

    - [Migrate Script](https://github.com/maxshuang/ticdc_script) or [Migrate Tool](https://github.com/w169q169/migrate-tools)  can do some replace work quickly, try and make pr.

## Progress

Considering test-infra migration is a long-term process，we need to divide the whole process into several phases. After that, 
each pkgs will be classified into specific phase.

- Phase0: small pkgs, no kits dependent,  [migrate script](https://github.com/maxshuang/ticdc_script)/[migrate tool](https://github.com/w169q169/migrate-tools) can do most work.
- Phase1: small pkgs dependent on kits, need to deal after we migrate kits
- Phase2: medium pkgs,  need to modify suite logic manually
- Phase3: large pkgs,  need to modify suite logic manually

## Subtasks

- Phase0:
* [x] #2919
* [x] #2890
* [x] #2928
* [x] #2927
* [x] #2925
* [x] #2923
* [x] #2921
* [x] #2859
* [x] #2869
* [x] #2870
* [x] #2871
* [x] #2936
* [x] #2935
* [x] #2934
* [x] #2933
* [x] #2930
* [x] #2825
* [x] #2954

- Kits
* [x] #2874
* [x] #2879

- Phase1:
* [x] #2932
* [x] #2878
* [x] #4200
* [x] #4878

- Phase2:
* [x] #2912
* [x] #4879
* [x] #2826
* [x] #2902
* [x] #2903

- Phase3:
* [x] #2899
* [x] #2900
* [x] #2901
* [x] #2904
* [x] #2905
* [x] #2906
* [x] #2907
* [x] #2908
* [x] #2909
* [x] #2910
* [x] #2911

**Comment by hi-rustin** [comment]
I have a question:

Why we need a test framework? Can we just use the golang's built-in test framework?

**Comment by ben1009** [comment]
> I have a question:
> 
> Why we need a test framework? Can we just use the golang's built-in test framework?

more functionality support i guess, ref https://github.com/stretchr/testify, also could discuss the option in https://internals.tidb.io/t/topic/141/6 with community, i think

**Comment by hi-rustin** [comment]
Off-line discussion:

I support the use of testify, but the migration costs may be higher. Because there are a lot of tests.

From @overvenus , we can use testify, because pingcap/check requires writing redundant templates. But we need to make sure that leak test is supported.

**Comment by tisonkun** [comment]
> But we need to make sure that leak test is supported.

Unnecessary. As done in pingcap/tidb and tikv/client-go, we can migrate testleak to goleak also, which requires less setups and is able to control (ignore) options per test (package). testleak is a toolkit build on pingcap/check and we don't have to maintain it if find a better replacement.

**Comment by tisonkun** [comment]
Also I don't think this is a feature request.

**Comment by tisonkun** [comment]
@ben1009 the next time you can comment this effort on the post or the issue of tidb so that we're aware of its happening.

**Comment by tisonkun** [comment]
> I support the use of testify, but the migration costs may be higher. Because there are a lot of tests.

Agree. I think there are several potential contributors to work on this topic. Let's postpone this issue util there is actually someone want to work on it. We should avoid throwing ourselves into a situation that maintain two kinds of test cases for a long time.

**Comment by sunxiaoguang** [comment]
Looks like I can't convert task into issue. I assume contributor can create task and reply to this issue to create link, am I right?

**Comment by tisonkun** [comment]
> Looks like I can't convert task into issue. I assume contributor can create task and reply to this issue to create link, am I right?

Yes. See also https://github.com/pingcap/tidb/issues/27618#issuecomment-907790848 .

**Comment by maxshuang** [comment]
@tisonkun hello, tisonkun,  i am new to the ticdc group. We made offline discussion recently , and wanted to make the migration to testify and goleak step by step.  What should we pay attention to the migration?  Did you met something bad in the progress?

**Comment by tisonkun** [comment]
@maxshuang I don't remember with an offline discussion though. What I can say it just go ahead to do it. Maybe start from some utility package like `pkg/version`.

If you'd like to do it, I'll create a subtask and you can assign yourself by `/assign`.

**Comment by tisonkun** [comment]
@maxshuang you can take a look at https://github.com/pingcap/tidb/pull/26082 for best practices collected and previous discussions.

**Comment by hi-rustin** [comment]
Thank you all for your excellent work!
