### ISSUE TITLE
CREATE INDEX and cancelling the DDL job causes replication to be interrupted

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#2261]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
- Two changefeeds, with `tidb` and `kafka(canal)` sinks respectively.
- Run `ALTER table tbl0 ADD COLUMN aaa varchar(48) DEFAULT NULL COMMENT 'blahblah';`
- Run `ALTER table tbl0 ADD UNIQUE INDEX unq_aaa_bbb(`aaa`, `bbb`);`
- Wait for about one hour, before the ADD INDEX could finish, pause the TiCDC changefeeds, cancel the DDL job in upstream TiDB, and resume the TiCDC changefeeds.

2. What did you expect to see?
- That everything goes smoothly, and TiKV should not experience performance issues.

3. What did you see instead?
- TiCDC changefeeds could not proceed, with TiKV consuming too much CPU due to reading old value from RocksDB.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.12
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.12
        ```

**Comment by overvenus** [comment]
Here are some metrics and TiKV flamegraph.

![image](https://user-images.githubusercontent.com/2150711/125089734-311af800-e101-11eb-8f04-38b365c41e03.png)

TiKV flamegraph: https://gist.github.com/overvenus/389739d09a155938d3d5016b2f55a3f7

**Comment by liuzix** [comment]
Upon reviewing the user's log, the time at which TiKV CPU consumption starts increasing coincides with the `start-ts` of the DDL job. 

`
  "id": 3014,
  "type": 7,
  "schema_id": 1382,
  "table_id": 1588,
  "schema_name": xxx_xxx",
  "state": 3,
  "err": {
   "class": 2,
   "code": 8214,
   "message": "Cancelled DDL job",
   "rfccode": "ddl:8214"
  },
  "err_count": 1,
  "row_count": 35560104,
  "raw_args": [
   9
  ],
  "schema_state": 0,
  "snapshot_ver": 426194794047866320,
  "start_ts": 426194793943010848,
  "dependency_id": 0,
  "query": "ALTER table tbl0 ADD UNIQUE INDEX unq_aaa_bbb(`aaa`, `bbb`)",
  "binlog": {
   "SchemaVersion": 2879,
   "DBInfo": null,
   "TableInfo": {
    "id": 1588,
    "name": {
     "O": "xxx",
     "L": "xxx"
    },
    "charset": "utf8mb4",
    "collate": "utf8mb4_bin",
    "cols": [
     {
      "id": 1,
      "name": {
       "O": "id",
       "L": "id"
      },
      "offset": 0,
      "origin_default": null,
      "default": null,
      "default_bit": null,
      "default_is_expr": false,
      "generated_expr_string": "",
      "generated_stored": false,
      "dependences": null,
      "type": {
       "Tp": 8,
       "Flag": 547,
       "Flen": 20,
       "Decimal": 0,
       "Charset": "binary",
       "Collate": "binary",
       "Elems": null
      },
      "state": 5,
      "comment": "",
      "hidden": false,
      "version": 2
     },
    .......
   "FinishedTS": 426195157707129427
  },
  "version": 1,
  "reorg_meta": null,
  "priority": 1
 },


`

**Comment by nongfushanquan** [comment]
since the ticdc part in the tikv node has refactored  many times , so close it .  
/close
