### ISSUE TITLE
CDC owner exited persistently which causing CDC always need to re-scan region and sync task don't work

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2350]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Workload is "insert...on duplicate key" and "add/remove partition".
- 2x changefeed, one sink-uri is tidb, the other sink-uri is kafka, each changefeed has about 200 tables need to be synced.
 
2. What did you expect to see?

- CDC works normally.

3. What did you see instead?

- CDC owner exited persistently which causing CDC always need to re-scan region and sync task don't work。
- CDC log：
cdc-2021-07-21T17-05-58.565.log:[2021/07/21 16:50:46.645 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=4b8ef87a-fc88-4797-9bd3-c2809ff776bc]
cdc-2021-07-21T19-19-03.894.log:[2021/07/21 18:20:44.015 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=87f6f560-9510-4067-ad5e-e6c8b50d8d18]
cdc-2021-07-21T20-27-50.012.log:[2021/07/21 20:14:23.824 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=2dfcc2ad-1e6a-400e-b25f-4d911f820d59]
cdc-2021-07-21T22-50-34.145.log:[2021/07/21 22:05:16.927 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=c81a9c2c-5bb2-4f4c-9743-2b77581200f1]
cdc-2021-07-22T01-00-23.471.log:[2021/07/21 22:56:54.361 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=e911f872-d6bf-4f82-9fc9-3b1d55c7fbec]
cdc-2021-07-22T01-00-23.471.log:[2021/07/21 23:59:52.543 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=b9a3574c-76b3-4e31-bc48-e9ca8c202d0b]
cdc-2021-07-22T03-25-10.501.log:[2021/07/22 01:38:41.276 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=0f0de77a-70a4-4445-8ee0-7d0cdf58386e]
cdc-2021-07-22T03-25-10.501.log:[2021/07/22 02:32:43.556 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=d3092740-5479-4828-9d22-dd0ddc86854b]
cdc-2021-07-22T03-25-10.501.log:[2021/07/22 02:33:41.659 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=5fec895c-3c71-4c29-b945-55c97cbd6dbb]
cdc-2021-07-22T05-46-56.083.log:[2021/07/22 03:30:18.783 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=c23b62ec-626f-4489-afa3-a242578e540c]
cdc-2021-07-22T05-46-56.083.log:[2021/07/22 04:31:18.472 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=c6a02a4e-6732-4797-91e7-e5e43bbb5c72]
cdc-2021-07-22T05-46-56.083.log:[2021/07/22 05:19:08.406 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=ad6c0901-a0fc-418a-827b-73f4ea7b2f1c]
cdc-2021-07-22T07-36-28.686.log:[2021/07/22 06:19:40.045 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=43dbe1e8-b731-4c5b-99b6-a0236b82c2ce]
cdc-2021-07-22T07-36-28.686.log:[2021/07/22 06:20:11.422 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=ff96b6fe-e074-403c-a56e-f0d076243372]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 07:37:40.746 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=62f7ca5c-e1fe-4b23-b22c-9cc6b2cbfcb2]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 07:38:37.271 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=3dbf50b7-4648-4307-bef9-241e36152e71]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 08:40:28.398 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=4950e8a6-7493-4943-9caa-177e7da5772f]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 08:42:11.964 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=c56f1788-3a23-40ae-ac9f-e9cc0f5504f0]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 09:27:41.216 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=11dd555e-f128-4a8b-aa23-bd7d0112470f]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 09:28:10.330 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=77a1953b-f336-4913-812e-4ead4b729ea4]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 09:28:45.370 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=b6f18575-10b4-4ef0-bf51-946c1b5fa09a]
cdc.log:[2021/07/22 10:40:06.113 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=ad70e1b5-e76b-4d54-a272-e6e8c144e898]
cdc.log:[2021/07/22 10:40:25.143 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=56842b24-9f50-43cb-83c7-ed9a10790e26]
cdc.log:[2021/07/22 10:41:20.835 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=e0acbb2f-7d4e-46e8-aa07-78c7cb31dbbc]
cdc.log:[2021/07/22 10:41:52.177 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=109da0ec-fbb2-4021-acf7-c72858f2c10c]

- grep "owner exited" cdc*
  cdc-2021-07-21T17-05-58.565.log:[2021/07/21 16:50:51.534 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=4b8ef87a-fc88-4797-9bd3-c2809ff776bc]
cdc-2021-07-21T19-19-03.894.log:[2021/07/21 18:20:48.908 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=87f6f560-9510-4067-ad5e-e6c8b50d8d18]
cdc-2021-07-21T20-27-50.012.log:[2021/07/21 20:15:12.319 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=2dfcc2ad-1e6a-400e-b25f-4d911f820d59]
cdc-2021-07-21T22-50-34.145.log:[2021/07/21 22:05:21.781 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=c81a9c2c-5bb2-4f4c-9743-2b77581200f1]
cdc-2021-07-22T01-00-23.471.log:[2021/07/21 22:56:58.565 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=e911f872-d6bf-4f82-9fc9-3b1d55c7fbec]
cdc-2021-07-22T01-00-23.471.log:[2021/07/21 23:59:57.081 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=b9a3574c-76b3-4e31-bc48-e9ca8c202d0b]
cdc-2021-07-22T03-25-10.501.log:[2021/07/22 01:38:46.693 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=0f0de77a-70a4-4445-8ee0-7d0cdf58386e]
cdc-2021-07-22T03-25-10.501.log:[2021/07/22 02:32:48.511 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=d3092740-5479-4828-9d22-dd0ddc86854b]
cdc-2021-07-22T05-46-56.083.log:[2021/07/22 03:30:22.789 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=c23b62ec-626f-4489-afa3-a242578e540c]
cdc-2021-07-22T05-46-56.083.log:[2021/07/22 04:31:23.042 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=c6a02a4e-6732-4797-91e7-e5e43bbb5c72]
cdc-2021-07-22T05-46-56.083.log:[2021/07/22 05:19:12.917 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=ad6c0901-a0fc-418a-827b-73f4ea7b2f1c]
cdc-2021-07-22T07-36-28.686.log:[2021/07/22 06:19:44.287 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=43dbe1e8-b731-4c5b-99b6-a0236b82c2ce]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 07:37:45.330 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=62f7ca5c-e1fe-4b23-b22c-9cc6b2cbfcb2]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 08:40:33.819 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=4950e8a6-7493-4943-9caa-177e7da5772f]
cdc-2021-07-22T10-20-34.426.log:[2021/07/22 09:27:45.857 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=11dd555e-f128-4a8b-aa23-bd7d0112470f]
cdc.log:[2021/07/22 10:40:11.318 +08:00] [INFO] [server.go:235] ["owner exited"] [capture-id=ad70e1b5-e76b-4d54-a272-e6e8c144e898]

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
         Release Version: v4.0.14
Edition: Community
Git Commit Hash: a3baab49f93ba33915fd7ab6b19d8bc12e6542ce
Git Branch: heads/refs/tags/v4.0.14
UTC Build Time: 2021-07-15 06:54:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v4.0.14
       Git Commit Hash: 5a7851967f686da896b45acd3f3e968bfe53d6bd
       Git Branch: heads/refs/tags/v4.0.14
       UTC Build Time: 2021-07-15 05:48:23
        Go Version: go version go1.13 linux/amd64
        Failpoint Build: false

        ```

**Comment by Tammyxia** [comment]
![image](https://user-images.githubusercontent.com/78345569/126587834-5e610ba5-348f-4ca9-92eb-dd3b5b19df2d.png)
![image](https://user-images.githubusercontent.com/78345569/126587787-d6471e04-16d1-406e-a9ec-005333c5632d.png)

**Comment by Tammyxia** [comment]
1x changefeed sort-engine=memory, the other changefeed sort-engine=memory.

**Comment by Tammyxia** [comment]
cdc cli unsafe reset && tiup cluster restart 360UP -R cdc
tiup cdc:v4.0.14 cli changefeed create --pd=http://xxx:2379 --sink-uri='mysql://root:@xxx:4000/'   --changefeed-id="replication-task-12" || tiup cdc:v4.0.14 cli changefeed create --pd=http://xxx:2379 --sink-uri='kafka://xxx:9092/cdc2-events?'   --changefeed-id="kafka-task-11"
Still CDC has owner exited: 
[2021/07/22 21:58:58.023 +08:00] [INFO] [capture.go:202] ["capture session done, capture suicide itself"] [capture-id=de604ef2-ff22-4c2b-b039-c4f000447fe7]

**Comment by overvenus** [comment]
Seems it also relates to low GC MMU, like https://github.com/pingcap/ticdc/issues/2375.
