### ISSUE TITLE
Enable integration tests for release branches

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#2442]
Enable integration tests for release branches. (Specifically for github action tests)

/assign

**Comment by hi-rustin** [comment]
It seems difficult to specify the version of tikv based on the branch number, because our image does not have a tag like v5 v4, only the x.x.x version number. Do you have any suggestions?

/cc @liuzix @amyangfei

**Comment by amyangfei** [comment]
What about using specific version of TiKV, such as `5.0-nightly` in release-5.0 branch,

**Comment by hi-rustin** [comment]
Because of the problem of incomplete docker images and our lack of reliance on these tests, close it for now.
