### ISSUE TITLE
CDC cloud: CDC OOM when upstream has historical data and has 60K tables

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2553]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- There are 8 CDC servers, each has vcpu36c mem72g , 1 changefeed, 6w tables.
- Stop changefeed, add workload in upstream tidb, data size less then 40GB.
- Resume changefeed. Meanwhile, workload IO in upstream is still running...

2. What did you expect to see?

- No any error.

3. What did you see instead?

- CDC OOM persistently...

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
Release Version: v4.0.14-42-gc24e30f
Git Commit Hash: c24e30f1a26b3de97443254b6c178acb613c2263
Git Branch: HEAD
UTC Build Time: 2021-08-11 06:03:32
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false
        ```

**Comment by overvenus** [comment]
We have confirmed this issue is fixed in release-5.4.
