### ISSUE TITLE
changefeed restriction

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#267]
when user creates a new chagnefeed, TiCDC should have some pre verification for the changefeed config, including
- [x] The changefeed `StartTs` must be larger than `tikv_gc_safe_point`
- [ ] The must be unique, which means TiCDC can't have more than one changefeed to replicate to .
   - Here we should make a definition for unique data flow, maybe (schema, table, target sink)?
   - We also need to have a boundary for each definition, such as
     - What if there exist three downstream TiDB addresses and they share the same TiKV store, then how can TiCDC recognize it.
     - The table-filter in changefeed config may be various, is it possible to check table confliction accurately
   - What should TiCDC do when it detects data flow confliction

**Comment by IANTHEREAL** [comment]
Currently, TiCDC does not provide a consumption that is lower than the table/partition data range. In the user concept, the flow combination [`source table/partition` -> `sink table/partition`] needs to be unique, that is, no more than one flow is the from `source table./partition` to `sink table/partition`

**Comment by overvenus** [comment]
The above tasks has been added.
