### ISSUE TITLE
CDC cloud: unified sorter IO error: too many open files

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2698]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- scale-in 4 tikv, workload is go-ycsb, 1 changefeed, 6w tables.
- owner switch, then all pd restart
- check changefeed status.

2. What did you expect to see?

3. What did you see instead?

- $ /cdc cli --ca=/var/lib/ticdc-tls/ca.crt --cert=/var/lib/ticdc-tls/tls.crt --key=/var/lib/ticdc-tls/tls.key changefeed list --pd=https://db-pd:2379

[
  {
    "id": "replication-task-60063",
    "summary": {
      "state": "normal",
      "tso": 427405617999380761,
      "checkpoint": "2021-08-31 15:17:22.295",
      "error": {
        "addr": "db-ticdc-2.db-ticdc-peer.tidb60105.svc:8301",
        "code": "CDC:ErrUnifiedSorterIOError",
        "message": "[CDC:ErrUnifiedSorterIOError]unified sorter IO error. Make sure your sort-dir is configured correctly by passing a valid argument or toml file to `cdc server`, or if you use TiUP, review the settings in `tiup cluster edit-config`. Details: open /var/lib/ticdc/tmp/sorter/sort-1-3187215.tmp: too many open files"
      }
    }
  }
]
cdc log:
![image](https://user-images.githubusercontent.com/78345569/131608437-5b8fbdd4-097f-4b6e-bea9-9150a9a0a8f5.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.14
        ```

**Comment by overvenus** [comment]
It relates to https://github.com/pingcap/ticdc/issues/2793

**Comment by liuzix** [comment]
This problem has been solved by dbsorter, which is enabled by default from 6.0 onward. It is also available on 5.4.1, which satisfies the needs of the cloud. So I'm closing this issue.
