### ISSUE TITLE
some captures exited: error="etcdserver: request timed out

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2708]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 8 captures, 1 changefeed, 6w+ tables.

2. What did you expect to see?

3. What did you see instead?

-  3 captures exited with this error(UTC):

![image](https://user-images.githubusercontent.com/78345569/131628064-a1b30b97-9e3d-45be-9e3d-cb9b839784ee.png)
![image](https://user-images.githubusercontent.com/78345569/131628211-4c101aeb-37f6-4211-8aa0-6c48eecb2f3f.png)

-  None-owner capture exiting makes changefeed sync task interrupt 15 minutes.
- 
![image](https://user-images.githubusercontent.com/78345569/131628849-6844706a-0c19-4b76-b27f-00c05c9dc65b.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.14 cloud
        ```

**Comment by liuzix** [comment]
Could you provide PD metrics?

**Comment by overvenus** [comment]
We have confirmed this issue is fixed in release-5.4.
