### ISSUE TITLE
First time resume failed : [CDC:ErrKafkaFlushUnfinished]

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2917]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 1 changefeeed --sink-uri="kafka://172.16.6.2:9092/cdc-events?kafka-version=2.4.1&partition-num=3&max-message-bytes=12582912&replication-factor=3"
- pause changefeed
- update changefeed:
   
![image](https://user-images.githubusercontent.com/78345569/134795097-7d9023dd-8cb2-4586-a4e7-0de5829e51c2.png)

- Resume changefeed.

2. What did you expect to see?

- Resume changefeed successful.

3. What did you see instead?

- The first time to resume changefeed don't work, error: flush not finished before producer close.
   [root@idc-4-30 ~]# tiup ctl:v5.0.4 cdc changefeed  --pd=http://172.16.4.30:2379 list
Starting component `ctl`: /root/.tiup/components/ctl/v5.0.4/ctl cdc changefeed --pd=http://172.16.4.30:2379 list
[
  {
    "id": "kafka-1",
    "summary": {
      "state": "stopped",
      "tso": 427985261576063156,
      "checkpoint": "2021-09-26 13:30:07.062",
      "error": null
    }
  }
]
[root@idc-4-30 ~]# tiup ctl:v5.0.4 cdc changefeed  --pd=http://172.16.4.30:2379 resume -c kafka-1
Starting component `ctl`: /root/.tiup/components/ctl/v5.0.4/ctl cdc changefeed --pd=http://172.16.4.30:2379 resume -c kafka-1
[root@idc-4-30 ~]# tiup ctl:v5.0.4 cdc changefeed  --pd=http://172.16.4.30:2379 list
Starting component `ctl`: /root/.tiup/components/ctl/v5.0.4/ctl cdc changefeed --pd=http://172.16.4.30:2379 list
[
  {
    "id": "kafka-1",
    "summary": {
      "state": "stopped",
      "tso": 427985261576063156,
      "checkpoint": "2021-09-26 13:30:07.062",
      "error": {
        "addr": "172.16.6.5:8300",
        "code": "CDC:ErrProcessorUnknown",
        "message": "[CDC:ErrKafkaFlushUnfinished]flush not finished before producer close"
      }
    }
  }
]

- Resume this changefeed again successfully.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.4
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.4
        ```

**Comment by Tammyxia** [comment]
Reproduced this issue agin, when new changefeed is just created, this error occurred and the changefeed is stopped.
![image](https://user-images.githubusercontent.com/78345569/135432753-a67c28a2-9617-4fec-a351-6d0413ea2c23.png)

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
According to the steps, it cannot be reproduced either with or without workload.
This error only occurs if the kakfa producer shuts down early before the data has been flushed. The normal producer should not exit when the changfeed has just been created.

**Comment by hi-rustin** [comment]
The problem cannot be reproduced even with three brokers and identical commands.

**Comment by hi-rustin** [comment]
It didn't resurface it again for a long time. So close it for now. If you encounter problems again, feel free to reopen this issue.
