### ISSUE TITLE
Outlier point in tikv resolved ts lag metrics

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#3031]
### What did you do?

Run ticdc replication, with a large number of regions.

### What did you see instead?

![screenshot-20211013-170229](https://user-images.githubusercontent.com/1527315/137102323-273ce215-b370-4663-9912-4e442f75eb4c.png)

- The replication works normally, without any large lag

![screenshot-20211013-170202](https://user-images.githubusercontent.com/1527315/137266739-4aa1a624-8466-4bc7-8d45-ab28f044d224.png)

- But the resolved ts lag duration percentile in TiKV metrics has outlier point, with `2.3 hour` lag in resovled ts

I checked the `CDC_RESOLVED_TS_GAP_HISTOGRAM` metric in TiKV, it is `exponential_buckets(0.001, 2.0, 24)`

and 0.001 * 2^(24-1) = 8388.608s = 2.33h, suspect a zero `resolved_ts` is counted when calculating resolved ts gap

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

TiCDC version (execute `cdc version`):

```console
in v4.1.14 and v5.2.1 both
```

**Comment by overvenus** [comment]
Maybe we can try `quantile_over_time`? 

See https://grafana.com/blog/2020/10/20/quick-tip-how-prometheus-can-make-visualizing-noisy-data-easier/

**Comment by Tammyxia** [comment]
Reproduced this issue in v5.3.0

**Comment by Tammyxia** [comment]
![GGOy6YYmtU](https://user-images.githubusercontent.com/78345569/141279742-01441e11-1869-45a4-9659-1a9c65c3c6ca.png)
Test case is network loss in all tikv from test-infra.

**Comment by asddongmen** [comment]
Close it since it's stale.
