### ISSUE TITLE
Downgrading TiCDC cluster failed

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#3036]
### What did you do?

Downgrading from v5.1.2 to v5.1.1, by TiUP.

### What did you expect to see?

That everything goes smoothly.

### What did you see instead?

`CDC:ErrInvalidEtcdKey` report unknown key `/meta/ticdc-delete-etcd-key-count`

### Versions of the cluster

v5.1.2 -> v5.1.1

**Comment by overvenus** [comment]
Downgrade is not recommended and uncommon, change to severity/moderate.
