### ISSUE TITLE
TiCDC may resolve lock, then cause TiKV errored

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#3057]
### What did you do?

Run the `truncate_table_sync` case, which run sysbench `oltp_write_only`, tableCount = 200, tableSize = 5, then delete the table one per 2s.

### What did you expect to see?

sink to downstream successfully

### What did you see instead?

sysbench report error
```
(tikv aborts txn: Error(Txn(Error(Mvcc(Error(PessimisticLockNotFound { start_ts: TimeStamp(428381553275699258), key: [116, 128, 0, 0, 0, 0, 0, 0, 79, 95, 114, 128, 0, 0, 0, 0, 0, 0, 3] })))))) for query 'COMMIT'\nFATAL
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
nightly
```

TiCDC version (execute `cdc version`):

```console
nightly
```
[issue-log.zip](https://github.com/pingcap/ticdc/files/7344825/issue-log.zip)

**Comment by overvenus** [comment]
After https://github.com/tikv/tikv/pull/11991, this issue is mitigated, lower the severity to moderate.

**Comment by sdojjy** [comment]
can not reproduce it, reopen it if reproduced again
