### ISSUE TITLE
Remove ErrGCTTLExceeded changefeed panic

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#3128]
### What did you do?

```
tiup playground v.5.1.1

update mysql.tidb set VARIABLE_VALUE="10s" where VARIABLE_NAME="tikv_gc_run_interval";

./bin/cdc server --pd=http://127.0.0.1:2379 --gc-ttl=120

./bin/cdc cli changefeed create --pd=http://127.0.0.1:2379 --sink-uri="mysql://root:123456@127.0.0.1:3306/" --changefeed-id="gcttl-test"

./bin/cdc cli changefeed pause --pd=http://127.0.0.1:2379 --changefeed-id="gcttl-test"

wait for a few minutes, changefeed's status become error, then:

./bin/cdc cli changefeed remove --pd=http://127.0.0.1:2379 --changefeed-id="gcttl-test"
```

### What did you expect to see?

changefeed removed successfully.

### What did you see instead?

![20211025-164148](https://user-images.githubusercontent.com/7138436/138663685-445bab8a-505d-4186-a2c6-744a9575d93b.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.1.1
```

TiCDC version (execute `cdc version`):

```console
v5.1.1
```

[ticdc.log](https://github.com/pingcap/ticdc/files/7408570/ticdc.log)

**Comment by zhaoxinyu** [comment]
This bug cannot be reproduced on v5.3.0. The immediate cause for this bug is passing a nil value to `s.Func` in:
https://github.com/pingcap/tiflow/blob/v5.1.1/pkg/orchestrator/interfaces.go#L55

**Comment by 3AceShowHand** [comment]
it's fine to close the issue.

**Comment by zhaoxinyu** [comment]
> it's fine to close the issue.

The nil pointer still needs to be checked. I will submit a PR later.
