### ISSUE TITLE
DM: Track `handle-error skip` ddl

### ISSUE THREAD

**Issue by okJiang** [pingcap/tiflow#3160]
reopen https://github.com/pingcap/dm/issues/1717#issuecomment-952652199

**Comment by lance6716** [comment]
And also it's better that we unify the skip logic. Currently our syncer.go is totally a mess, I have considered [refine the main loop of syncer](https://github.com/pingcap/dm/issues/1117) by a state machine or something, but no good design yet 😂

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/tiflow/pull/4178
