### ISSUE TITLE
coding mistake in file_backend.go

### ISSUE THREAD

**Issue by nchuxyz** [pingcap/tiflow#3206]
### What did you do?

no need to reproduce

### What did you expect to see?

writtenCount() should return events written and dataSize() should return bytes written

### What did you see instead?

func (w *fileBackEndWriter) writtenCount() int {
	return int(w.bytesWritten)
}

func (w *fileBackEndWriter) dataSize() uint64 {
	return uint64(w.eventsWritten)
}

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
4.x, 5.x
```

TiCDC version (execute `cdc version`):

```console
4.x, 5.x
```

**Comment by overvenus** [comment]
Thanks for your feedback! PTAL @liuzix
