### ISSUE TITLE
Should TiCDC continue replicating data during rolling update

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#3261]
### Is your feature request related to a problem?

For example if we deploy a TiDB cluster across three AZs to achieve high availability, and also deploy one TiCDC server in each AZ to replicate data from TiDB to downstream.

We we want to upgrade the TiDB cluster, we could perform a rolling upgrade for servers one by one, in the order of AZ.

Since the rolling upgrade of TiKV could be very slow (as long as hours), there will exist different versions of TiCDC in the whole cluster for quite a long time. During that time, TiCDC refuses to replicate data because of **strict version check**, ref: 

https://github.com/pingcap/ticdc/blob/6655bf0835c8bbd31d949b7c8da79bf09e6f5a3c/cdc/owner/owner.go#L271-L280

### Describe the feature you'd like

**Loosen the version check strategy**, such as when upgrading TiCDC from `v5.2.2` to `v5.2.3`, TiCDC can continue replicate during rolling upgrade.

**Comment by ben1009** [comment]
FYI https://github.com/pingcap/ticdc/issues/2364

**Comment by amyangfei** [comment]
Solved by https://github.com/pingcap/tiflow/issues/4757
