### ISSUE TITLE
support extend colum with lightning-loader

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow#3339]
### Is your feature request related to a problem?

https://github.com/pingcap/dm/issues/2111

### Describe the feature you'd like

as https://github.com/pingcap/ticdc/pull/3262 add extend column for syncer and loader, lightning-loader should also support this feature

### Describe alternatives you've considered

always use loader instead of `lightning-loader` when user config extend column

**Comment by lance6716** [comment]
I'll transfer the issue here
