### ISSUE TITLE
Distinguish data source when merge shared tables with no shared key

### ISSUE THREAD

**Issue by yufan022** [pingcap/tiflow#3340]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Hi, 
  we are trying to use DM to merge the shared tables of AWS Aurora into the tidb cluster managed by tidb operator.

But our scene is a little special, our shared tables doesn't have shared key, we use table name to splite the table.

So if we merged source table `order_btcusdt; order_ethusdt;...` to target table `order_collect`, We can't tell which orders are from btcusdt, and which are from ethusdt. Because there doesn't have shared column.

Can DM extract the table name as an extended column of target table? Or is there a better solution?

thanks.

**Describe the feature you'd like:**

Merge shared tables without partition keys, extract the table name to the target table column

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lichunzhu** [comment]
closed by https://github.com/pingcap/tiflow/pull/3262
