### ISSUE TITLE
Test upstream-database-switch is not stable

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#3353]
### Which jobs are flaking?

upstream-database-switch

### Which test(s) are flaking?

upstream-database-switch

### Jenkins logs or GitHub Actions link

In this test we killed upstream MySQL, so sometimes we will meet errors like 

- MySQL server has gone away

https://github.com/pingcap/ticdc/runs/4151520050?check_suite_focus=true

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by GMHDBJD** [comment]
https://stackoverflow.com/questions/7942154/mysql-error-2006-mysql-server-has-gone-away

**Comment by okJiang** [comment]
upstream-database-switch has been failing for months https://github.com/pingcap/tiflow/actions/workflows/dm_upstream_switch.yaml
