### ISSUE TITLE
`cdc processor query` returns a CDC:ErrTaskStatusNotExists error

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#3375]
### What did you do?

- create a new TiCDC change feed.
- execute command `cdc processor query`, get `CDC:ErrTaskStatusNotExists` error.
- write some data to TiDB using sysbench.
- execute command `cdc processor query` again, get normal processor info.

### What did you expect to see?

The `cdc processor query` command should return reasonable output even if it is associated with a newly created change feed.

### What did you see instead?

![image](https://user-images.githubusercontent.com/4409014/141084375-b531dbc6-7e7c-4d38-bad5-c8fbcd795b7d.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.2.2
```

TiCDC version (execute `cdc version`):

```console
v5.2.2
```

**Comment by liuzix** [comment]
`TaskPosition` keys are expected to be created after there is at least one table assigned to the processor. The `cli` command should have considered the situation where there is no table running on the specified capture.

The HTTP API implementation seems to have a similar flaw.

TODO
- [ ] Fix cli
- [ ] Fix HTTP API
