### ISSUE TITLE
Encounter table data loss and CDC:ErrProcessorUnknown error for a sysbench test

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#3410]
### What did you do?

1. bootstrap a new TiDB cluster.
```
tiup playground  --host 172.16.6.124 --db 3 --kv 3 --pd 3 --ticdc 3
```
2. create a TiCDC change feed, and use MySQL as TiCDC's sink target.
```
tiup ctl:v5.2.2 cdc changefeed create --pd=http://172.16.6.124:2379 --sink-uri="mysql://root:xxxxxx@127.0.0.1:3306" --changefeed-id="simple-replication-task2" --sort-engine="unified"
```
3. create a database `sbtest` in TiDB and create one table for `sbtest`.
```
sysbench /usr/local/share/sysbench/oltp_write_only.lua --db-driver=mysql --table_size=1000 --mysql-host=172.16.6.124 --mysql-port=4000 --mysql-db=sbtest --mysql-user=root --mysql-password= --tables=1 --threads=8 --time=3600 --report-interval=5 prepare
```
![image](https://user-images.githubusercontent.com/4409014/141259626-95b4197e-22b1-4d1c-b9e2-aa4ef58b77bb.png)
Now we can see table `sbtest.sbtest1` is replicated to the downstream MySQL as expected.
![image](https://user-images.githubusercontent.com/4409014/141260222-24bd048e-12e5-4abd-be78-b374084d0065.png)
4. execute the `sysbench cleanup` subcommand to remove the `sbtest.sbtest1` table.
![image](https://user-images.githubusercontent.com/4409014/141260485-8aaf2da7-e529-4cb6-a999-133439a1a564.png)
Now we can see table `sbtest.sbtest1` is removed from the downstream MySQL as expected.
![image](https://user-images.githubusercontent.com/4409014/141260814-0852b38d-6abf-4272-a0f1-e00944382d88.png)
5. create 10 tables for `sbtest`.
![image](https://user-images.githubusercontent.com/4409014/141261219-59f0c904-d1a9-45e8-b85e-33bc681e610e.png)
6. only one empty table is created on the downstream MySQL side.
![image](https://user-images.githubusercontent.com/4409014/141261781-dd1b75ac-aabe-4367-9d18-5fe90d26670a.png)
7. `cdc changefeed query` returns CDC:ErrProcessorUnknown error
![image](https://user-images.githubusercontent.com/4409014/141262046-4b367099-275f-4c47-9970-1d80c78bca35.png)

### What did you expect to see?

After executing the second `sysbench prepare` command (see reproducing step 5), the whole 10 tables are supposed to be replicated to MySQL.

### What did you see instead?

Only one table is created on the downstream MySQL side.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.2.2
```

TiCDC version (execute `cdc version`):

```console
v5.2.2
```

**Comment by asddongmen** [comment]
Close it since it is stale.
