### ISSUE TITLE
cdc: cli have different behaviour when query, pause, resume no exist changefeed

### ISSUE THREAD

**Issue by ben1009** [pingcap/tiflow#3456]
### What did you do?

cd cli query, pause, resume a not exist changefeed

### What did you expect to see?

should have the same result when deal with not exist changefeed 

### What did you see instead?

if cf not exist, should report `[CDC:ErrChangeFeedNotExists]changefeed not exists` like `query` returned
but when resume `Replicate lag (454712h5m40.041s) is larger than 1 days, large data may cause OOM, confirm to continue at your own risk [Y/N]`
`pause` have no result when the changefeed not exist

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.2
```

TiCDC version (execute `cdc version`):

```console
5.3
```

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
