### ISSUE TITLE
TiCDC prints lots of error log 

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tiflow#3524]
### What did you do?

when replicated lots of tables(1w+) and pd schedule region frequency(don't know why). TiCDC prints lots of error log, such as
`[ERROR] [client.go:452] ["check tikv version failed"] [error="[CDC:ErrGetAllStoresFailed]rpc error: code = Canceled desc = context canceled"]`
which create 300M log file every 5 minute.
<img width="941" alt="截屏2021-11-18 下午4 53 21" src="https://user-images.githubusercontent.com/5906259/142388165-1214d964-d3a4-4dd3-b31f-576da74f5c04.png">

### What did you expect to see?

a clear error log.
reduce the times of check tikv version, maybe we can cache the store's version. when new stream created. only first check is enough.

### What did you see instead?

too many errors `[ERROR] [client.go:452] ["check tikv version failed"] [error="[CDC:ErrGetAllStoresFailed]rpc error: code = Canceled desc = context canceled"]`

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
N/A
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by zhaoxinyu** [comment]
This issue does not appear for a long time. Reopen it if the same issue appear again.
