### ISSUE TITLE
The owner should have filtered DDL events before sending them to Sink

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#3537]
### What did you do?

Executes a DDL on a database that is filtered out for a changefeed.

### What did you expect to see?

The implementer of `Sink` should not have been notified of this DDL event.

### What did you see instead?

The `Sink` was notified of this event. This seems to be a sub-optimal design.
In current implementations, the sink needs to filter out DDL events by itself. 
https://github.com/pingcap/ticdc/blob/c91af794e65f54222b46094b287042cdadaf3bcb/cdc/sink/mysql.go#L280

This design is not friendly for third party contributors.

### Versions of the cluster

Introduced since https://github.com/pingcap/ticdc/pull/325

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
