### ISSUE TITLE
Verify kafka producer configuration works in a reasonable way.

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#3538]
### Is your feature request related to a problem?

As mentioned in #3352, when creating the changefeed with Kafka sink, the main loop of the CDC would be blocked, since we create the sink in a synchronous way.

One reason for the problem mentioned above is that our Kafka producer initialization takes too long in an unstable network environment, and this is controlled by producer configurations. So that we have to verify the configuration parameters works as expected, we have to test it.

### Describe the feature you'd like

* verify the meaning of each parameter, and test the correctness.

**Comment by hi-rustin** [comment]
Discuss in the https://docs.google.com/document/d/1xaVPxrSLABTijZPZIqRDMYu-FymGn4R1hNRs6LcCbnI/edit#.

**Comment by hi-rustin** [comment]
Fixed by https://github.com/pingcap/tiflow/pull/4359
