### ISSUE TITLE
Avro: missing tests for column types

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiflow#3644]
### What did you do?

https://github.com/pingcap/ticdc/issues/3624 showed issues with the JSON column type and https://github.com/pingcap/ticdc/issues/2648 showed issues with `unsigned tinyint`. Looking at the tests there seem to be more column types that don't seem to get sufficient testing.

```
$ grep 'case mysql.Type' avro.go | awk '{ print substr($2,0,length($2)-1) }' | sort -u
mysql.TypeBit
mysql.TypeDate
mysql.TypeDouble
mysql.TypeDuration
mysql.TypeEnum
mysql.TypeFloat
mysql.TypeJSON
mysql.TypeLong
mysql.TypeLonglong
mysql.TypeNewDecimal
mysql.TypeNull
mysql.TypeSet
mysql.TypeTiny
mysql.TypeTinyBlob
mysql.TypeVarchar
mysql.TypeYear
```

```
$ grep 'Type: mysql.Type' avro_test.go | sed -E 's/^.*(mysql.Type[a-zA-Z]*).*$/\1 /g' | sort -u
mysql.TypeBlob 
mysql.TypeFloat 
mysql.TypeLong 
mysql.TypeTimestamp 
mysql.TypeTiny 
mysql.TypeVarchar 
```

**Comment by zhangyangyu** [comment]
In #5339, I have a UT for every type. But UTs are not very helpful in such situations. I think more IT should be taken into account in future.
