### ISSUE TITLE
calculate secondsBehindMaster when dm sync block

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#3695]
### Is your feature request related to a problem?

when DM block in the sync stage(e.g. waiting for DDL), the `secondsBehindMaster` will not be updated.

### Describe the feature you'd like

update the `secondsBehindMaster` even DM block. Don't need to be too precise, just make it bigger and bigger

**Comment by lance6716** [comment]
seems an old issue of secondsBehindMaster but I didn't find it in DM's repo. 
cc @glorv

**Comment by lance6716** [comment]
replaced by https://github.com/pingcap/tiflow/issues/4471 (it has a root cause analysis so I prefer to leave that one open)

**Comment by Ehco1996** [comment]
another request is updating the secondsBehindMaster even DM block. Don't need to be too precise, just make it bigger and bigger
