### ISSUE TITLE
can't start a GTID-based incremental task when upstream GTID is empty

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#3731]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

upstream gtid is empty, and binlog-gtid in meta field in task file is also empty

2. What did you expect to see?

start successfully

3. What did you see instead?

query-status shows "invalid position (mysql-bin.000001, 4) or GTID not enabled in upstream"

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.5
        ```

**Comment by lance6716** [comment]
it's very annoying because many of out internal logic can't tell empty GTID set from GTID not enabled. Like https://github.com/pingcap/tiflow/blob/cdc9fa5524731d9dce557faa784f5c45ddb598db/dm/syncer/syncer.go#L3695

/cc @niubell

**Comment by lance6716** [comment]
During a little refactor, I think we can use nil gtid to represent "gtid not enabled", and empty string to represent empty gtid. Do you have some suggrestions @D3Hunter

**Comment by D3Hunter** [comment]
so hacky, why not check `s.cfg.EnableGTID` directly
