### ISSUE TITLE
multiple worker write for same upstream

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#3737]
### What did you do?

chaos test: pod kill dm

### What did you expect to see?

no error log in dm-worker.log

### What did you see instead?

write conflict: insert xxxx

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
The log shows that after chaos kill worker1, worker1 still wait for all jobs flushed, while worker2 bound to source1 imediately and then write same data from source1, then cause write conflict.

**Comment by GMHDBJD** [comment]
May be the same as the root cause of #3698

**Comment by lance6716** [comment]
seems a correct exit logic is very complex...

**Comment by lance6716** [comment]
/assign @Ehco1996 

also please take a look at `context.WithDelayedCancel(ctx, delayTime, immediateCancelCh)`
