### ISSUE TITLE
Flaking Test：TestWriterRedoGC

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#3850]
### Which jobs are flaking?

https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/4602/tests/

### Which test(s) are flaking?

TestWriterRedoGC – github.com/pingcap/ticdc/cdc/redo/writer

### Jenkins logs or GitHub Actions link

```log
=== RUN   TestWriterRedoGC
    writer_test.go:732: 
        	Error Trace:	writer_test.go:732
        	Error:      	Should have called with given arguments
        	Test:       	TestWriterRedoGC
        	Messages:   	Expected "GC" to have been called with:
        	            	[mock.Anything]
        	            	but actual calls were:
        	            	        []
        	            	[]
        	            	[]
        	            	[]
--- FAIL: TestWriterRedoGC (0.01s)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by ben1009** [comment]
duplicated with https://github.com/pingcap/tiflow/issues/4320, close
