### ISSUE TITLE
why there're two WithBackoffMaxDelay?

### ISSUE THREAD

**Issue by Eric-star-ball** [pingcap/tiflow#3912]
https://github.com/pingcap/ticdc/blob/71e2a4818e91b8b7fc4ffe90a936f0772c36f2b9/cdc/processor/processor.go#L882

**Comment by asddongmen** [comment]
It seems a little bug.

**Comment by asddongmen** [comment]
@Eric-star-ball Are you interested in pull a request to fix this bug?

**Comment by overvenus** [comment]
Fixed by #3992
