### ISSUE TITLE
[CC scenario] panic: commit ts < resolved ts

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#3969]
### What did you do?

- Testbed: 8 captures deployed in 4 physical servers; 1 changefeed; upstream TiDB cluster: 6 TiKV 2 TiDB, 3 PD; downstream cluster: 3 TiKV, 1 TiDB, 1 PD; CDC & TiKV numa_node binded; each physical server has: CPU 40-48C, 188GB memory, 2 NVME 3.6TB; 10GB/s NIC
- upstream and downstream cluster already have 5.6TB data size before the changefeed creating.

### What did you expect to see?

panic: commit ts < resolved ts

goroutine 8590 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc091a1e000, 0xc041ce00c0, 0x3, 0x3)
	go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x532
go.uber.org/zap.(*Logger).Panic(0xc076a73740, 0x379c91e, 0x17, 0xc041ce00c0, 0x3, 0x3)
	go.uber.org/zap@v1.19.1/logger.go:230 +0x85
github.com/pingcap/log.Panic(0x379c91e, 0x17, 0xc041ce00c0, 0x3, 0x3)
	github.com/pingcap/log@v0.0.0-20211207084639-71a2e5860834/global.go:54 +0x10b
github.com/pingcap/ticdc/cdc/sorter/leveldb.(*Sorter).wait.func1(0xc0426e2030)
	github.com/pingcap/ticdc/cdc/sorter/leveldb/table_sorter.go:147 +0x315
github.com/pingcap/ticdc/cdc/sorter/leveldb.(*Sorter).wait(0xc039ba74d0, 0x3e3e708, 0xc03ad3b800, 0x222c65736c616600, 0xc03bd86600, 0x20, 0x20, 0x383a227054227b3a, 0x3a2267616c46222c, 0x6e656c46222c3134,
...)
	github.com/pingcap/ticdc/cdc/sorter/leveldb/table_sorter.go:187 +0x3f3
github.com/pingcap/ticdc/cdc/sorter/leveldb.(*Sorter).poll(0xc039ba74d0, 0x3e3e708, 0xc03ad3b800, 0xc04209feb0, 0x5f656c646e61685f, 0x226e6f6973726576)
	github.com/pingcap/ticdc/cdc/sorter/leveldb/table_sorter.go:459 +0x97
github.com/pingcap/ticdc/cdc/sorter/leveldb.(*Sorter).Run(0xc039ba74d0, 0x3e3e708, 0xc03ad3b800, 0xc03c3041d8, 0xc03bba77c8)
	github.com/pingcap/ticdc/cdc/sorter/leveldb/table_sorter.go:617 +0x18f
github.com/pingcap/ticdc/cdc/processor/pipeline.(*sorterNode).Init.func2(0x3e3eeb0, 0xc03acfaa40)
	github.com/pingcap/ticdc/cdc/processor/pipeline/sorter.go:127 +0x57
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc08cba24a8, 0xc03ad3b840)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
panic: commit ts < resolved ts

- all cdc node is always restart:
![Uploading vUKaG2VpK8.png…]()

### What did you see instead?

no panic

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
v5.4.0-nightly-20211213
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
cdc-cloud-cdc-b82eb4f05-2021-12-16-15-59.tar.gz
```

**Comment by overvenus** [comment]
I don't think it's a critical bug, it's dead code unless we turn on the leveldb sorter experimental feature.
