### ISSUE TITLE
[CC scenario] one of capture has not any table to sync

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#3970]
### What did you do?

- Testbed: 8 captures deployed in 4 physical servers; 1 changefeed; upstream TiDB cluster: 6 TiKV 2 TiDB, 3 PD; downstream cluster: 3 TiKV, 1 TiDB, 1 PD; CDC & TiKV numa_node binded; each physical server has: CPU 40-48C, 188GB memory, 2 NVME 3.6TB; 10GB/s NIC

- Upstream and downstream cluster already have 5.6TB data size before the changefeed creating.
- Run workload run phase: ./bin/go-ycsb run mysql -P workloads/betting -p operationcount=5000000000 -p mysql.host=172.16.6.35 -p mysql.port=4000 --threads 200 -p dbnameprefix=betting_ -p databaseproportions=1.0 -p unitnameprefix=unit1_ -p unitscount=10 -p tablecount=20
- Because there's not storage.tikv.cache setting (two TiKV deployed in one server), there's two TiKV  OOM which is expected.

### What did you expect to see?

cdc works fine.

### What did you see instead?

- one of capture has not work for any table, and lasted for 10 hours after I reboot cluster.
![YTsRO752nN](https://user-images.githubusercontent.com/78345569/146704509-7b7bc44d-1f9d-49d7-a67c-6ab14c111562.png)
![EVQ2NC0rFu](https://user-images.githubusercontent.com/78345569/146704525-13286933-c85b-4546-a36f-aee68450494a.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.4.0-nightly-20211213
```

TiCDC version (execute `cdc version`):

```console
cdc-cloud-cdc-b82eb4f05-2021-12-16-15-59.tar.gz
```

**Comment by liuzix** [comment]
Fixed by https://github.com/pingcap/tiflow/pull/3916
