### ISSUE TITLE
when cdc is hanging, the changefeed status in monitor is sometime normal, sometime error

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tiflow#3987]
### What did you do?

1. Create a database a in upstream tidb before creating a changefeed
2. Creating a changefeed
3. Create a table in database a in the upstream tidb

### What did you expect to see?

1. the cdc will be hanging, and the status of the changefeed is always error Unless the changefeed is really become normal.

### What did you see instead?

1.when cdc is hanging, the changefeed status in monitor is sometime normal, sometime error
![hQGUMRbBx2](https://user-images.githubusercontent.com/81375082/146730350-112dbd60-0d55-4947-9628-16502d837937.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```
tidb 5.3.0
TiCDC version (execute `cdc version`):
v5.3.0
```console
(paste TiCDC version here)
```

**Comment by overvenus** [comment]
We will adjust changefeed retry backoff mechanism as described in https://github.com/pingcap/tiflow/issues/3329#issuecomment-966980048
