### ISSUE TITLE
Chengefeed is not automatically restored

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tiflow#3988]
### What did you do?

1. Create a database a in the upstream tidb before creating a changefeed
2. Creating a changefeed
3. Create a table aa in database a and  insert data into table aa in the upstream tidb
4. When the changefeed is hanging,  create database a in the downstream tidb

### What did you expect to see?

1. When I create database a in the downstream tidb, the chengefeed will be automatically restored

### What did you see instead?

1. The chengefeed is still hanging.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```
5.3.0
TiCDC version (execute `cdc version`):
5.3.0
```console
(paste TiCDC version here)
```

**Comment by overvenus** [comment]
Could you elaborate your `cdc cli changefeed create` command? Also what's your downstream?

**Comment by hanfei1991** [comment]
We should prove that the schema should be consistant before sync job starts. This shouldn't be a bug
