### ISSUE TITLE
Create changefeed with api without checking old value against protocol

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#4003]
### What did you do?

When I create a changefeed using the api, it does not check the relationship between the protocol and the old value. For canal and canal-json maxwell protocols, it should automatically turn on old value.

### What did you expect to see?

Automatically opens old value.

### What did you see instead?

It does not open automatically.

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
https://github.com/pingcap/tiflow/commit/9ef831fdbb92e7795d20445c50a12238b4e15291
```

**Comment by hi-rustin** [comment]
https://github.com/pingcap/tiflow/blob/9ef831fdbb92e7795d20445c50a12238b4e15291/pkg/cmd/cli/cli_changefeed_create.go#L208

**Comment by asddongmen** [comment]
I think we coudl close this issue as a result that we enable old value when using OpenAPI to create a changefeed.
What do you think about it? @hi-rustin

**Comment by hi-rustin** [comment]
/close

Make sense.
