### ISSUE TITLE
TiCDC exec DDL too slow

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#4050]
the upstream tidb cluster has 220k regions and 10 tables,  start a changefeed,  ticdc sync 10 tables to the downstream tidb after about 22 minutes.

upstream: 3 tikv, 3tidb 2pd,  5.2.3 , 16c 32G
upstream 3 tikv, 3tidb 2pd,  5.2.3, 16c 32G
5 ticdc  16c 32G
version：v5.2.2-29-g0c853a68

**Comment by maxshuang** [comment]
Could u add more information about your case? like grafana monitor, DDL sql, etc

**Comment by sdojjy** [comment]
> Could u add more information about your case? like grafana monitor, DDL sql, etc
10 tables are the same 
``sql
 CREATE TABLE if not exists sbtest%d (
  id bigint NOT NULL,
   k bigint NOT NULL DEFAULT '0',
   c char(30) NOT NULL DEFAULT '',
   pad char(20) NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    KEY k_1 (k)
)
     ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

**Comment by maxshuang** [comment]
@sdojjy Can we close this issue? It needs more infomation to define DDL slow. Now, we can expect a DDL need about 1s~3s to exec.
