### ISSUE TITLE
A scenario that TiCDC could have more than one owner

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#4051]
### What did you do?

1. Create two ticdc servers
2. Delete the owner key of the ticdc owner in etcd. `/tidb/cdc/owner/<lease-id>`
3. Observe another ticdc server will become owner, and the old owner is still running.

### What did you expect to see?

The old owner could detect this behavior.

### What did you see instead?

Two owner exist.

**NOTE: this is an unexpected user operation, if we don't think it is a bug, we must forbid it.**

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):

master@aa6f3c6e5ccf1dd5578de35a4a946712e9ef4ef9

**Comment by lance6716** [comment]
why the old owner can't know the leadership has been changed though watch?

**Comment by asddongmen** [comment]
I will do a investigation on this issue.

**Comment by asddongmen** [comment]
This issue is fixed in >= v6.3.0, and we do not cherrypick it to the older version since we consider it's an malicious behavior and we should have no guarantee in such scenario.
