### ISSUE TITLE
CDC continuous OOM  for truncate 500 table

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4068]
### What did you do?

- Run test-infra case: cdc_truncate_table_sync
- Run sysbench to create 500 tables, then truncate these tables one by one, interval 2s.

### What did you see instead?

- CDC OOM repeatedly:  
    
![image](https://user-images.githubusercontent.com/78345569/147352199-3ec45f36-2d0a-4308-ab36-91f29af71ae3.png)
![image](https://user-images.githubusercontent.com/78345569/147352214-01dc5e45-c42a-4765-b74d-e748691d8afc.png)
![image](https://user-images.githubusercontent.com/78345569/147352405-6f49f033-17e4-478f-9fcc-39092673a629.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.0.6
```

TiCDC version (execute `cdc version`):

```console
5.0.6
```

**Comment by overvenus** [comment]
Dup with https://github.com/pingcap/tiflow/issues/1386
