### ISSUE TITLE
[Kafka sink] upgrade from 4.0.15 to 5.0.6: kafka server: Message was too large, with canal protocol

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4069]
### What did you do?

- Cluster v4.0.16, broker topics: bin/kafka-topics.sh --create --topic cdc-events --config max.message.bytes=1073741824 replica.fetch.max.bytes=1073741824 fetch.message.max.bytes=1073741824 --bootstrap-server 172.16.4.51:9092
- Workload is sysbench
- Create changefeed: tiup ctl:v4.0.15 cdc changefeed create --pd=http://172.16.4.158:2379 --sink-uri="kafka://172.16.4.51:9092/cdc-events?kafka-version=2.4.0&partition-num=1&protocol=canal&replication-factor=1" --changefeed-id="kafka-task-4"
- Upgrade cluster to v5.0.6

### What did you see instead?

 "id": "kafka-task-4",
    "summary": {
      "state": "error",
      "tso": 430009182164353024,
      "checkpoint": "2021-12-24 22:07:31.396",
      "error": {
        "addr": "172.16.4.158:8300",
        "code": "CDC:ErrProcessorUnknown",
        "message": "[CDC:ErrKafkaAsyncSendMessage]kafka: Failed to produce message to topic cdc-events: kafka server: Message was too large, server rejected it to avoid allocation error."
      }

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment]
we have to fix `canal` protocol.

**Comment by overvenus** [comment]
We has tested open-protocol and canal-json protocol, they works fine. As canal is still in experimental stage, change to severity/minor.

**Comment by asddongmen** [comment]
Close it since it is stale.
