### ISSUE TITLE
cdc encoder `max-message-bytes` is not set correctly.

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#4089]
### What did you do?

create a changefeed with kafka sink, no parameter set in the `sink-uri`, then run workload to insert data.

### What did you expect to see?

changefeed works normal

### What did you see instead?

changefeed meet `Message Too Large` 

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by overvenus** [comment]
Has the issue been fixed? @3AceShowHand

**Comment by 3AceShowHand** [comment]
> Has the issue been fixed? @3AceShowHand

yes，open this issue for tracking purposd
