### ISSUE TITLE
some changefeeds become [CDC:ErrSnapshotLostByGC] when upgrade from 5.1.0 to 5.1.1-hotfix

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4115]
### What did you do?

- k8s, create tidb cluster v5.1.0, 3 changefeeds: 
    1. "sink-uri": "mysql://root:@downstream1.testbed-tammy-586vr:3306",
    2. "sink-uri": "kafka://downstream2-kafka.testbed-tammy-586vr:9092/cdc-test1?max-message-bytes=1048576\u0026protocol=canal-json",
    3. "sink-uri": "kafka://downstream2-kafka.testbed-tammy-586vr:9092/cdc-test2?max-message-bytes=1048576",
     all changefeed gc-ttl using default value: "gc-ttl\":86400

- run workload: tpcc 50 warehouse, prepare and run

-  upgrade cdc only for cdc hotfix version 5.1.1-xxx, meanwhile, tpcc is running.

### What did you see instead?

- 2 of 3 changefeeds has became failed: "CDC:ErrSnapshotLostByGC" after upgrade successful
- / # /cdc cli changefeed list --pd=http://upstream-pd:2379
[
  {
    "id": "kafka-canal-json-before",
    "summary": {
      "state": "failed",
      "tso": 430093979858763792,
      "checkpoint": "2021-12-28 07:58:48.929",
      "error": {
        "addr": "upstream-ticdc-0.upstream-ticdc-peer.testbed-tammy-586vr.svc:8301",
        "code": "CDC:ErrSnapshotLostByGC",
        "message": "[CDC:ErrSnapshotLostByGC]fail to create or maintain changefeed due to snapshot loss caused by GC. checkpoint-ts 430093979858763792 is earlier than or equal to GC safepoint at 430093979858763792"
      }
    }
  },
  {
    "id": "kafka-default-before",
    "summary": {
      "state": "failed",
      "tso": 430093979858763792,
      "checkpoint": "2021-12-28 07:58:48.929",
      "error": {
        "addr": "upstream-ticdc-0.upstream-ticdc-peer.testbed-tammy-586vr.svc:8301",
        "code": "CDC:ErrSnapshotLostByGC",
        "message": "[CDC:ErrSnapshotLostByGC]fail to create or maintain changefeed due to snapshot loss caused by GC. checkpoint-ts 430093979858763792 is earlier than or equal to GC safepoint at 430093979858763792"
      }
    }
  },
  {
    "id": "mysql-before",
    "summary": {
      "state": "normal",
      "tso": 430095990280159233,
      "checkpoint": "2021-12-28 10:06:38.078",
      "error": null
    }
  }
]
- 

- 

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.1.0
```

TiCDC version (execute `cdc version`):

```console
5.1.0 to v5.1.1-20211227
```

**Comment by 3AceShowHand** [comment]
this is known, and reasonable, so close it.
