### ISSUE TITLE
panic: close of closed channel in cdc/kv

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#4135]
### Which jobs are flaking?

CDC-UT

### Which test(s) are flaking?

unit test github.com/pingcap/tiflow/cdc/kv

### Jenkins logs or GitHub Actions link

```log
panic: close of closed channel
goroutine 3486 [running]:
github.com/pingcap/tiflow/cdc/kv.(*clientSuite).TestRegionWorkerExitWhenIsIdle.func1.1(0xc001684240, 0xc0007641a0, 0xc002326120)
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:3348 +0x39
github.com/pingcap/tiflow/cdc/kv.(*clientSuite).TestRegionWorkerExitWhenIsIdle.func1(0x6b20130, 0xc00089aa50)
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:3359 +0x26e
github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed.func1(0xc001e14370, 0x6b20130, 0xc00089aa50)
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:255 +0x62
created by github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:254 +0x38f
```

https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/7559/tests/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by lance6716** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/16978/pipeline

**Comment by ben1009** [comment]
@maxshuang https://github.com/pingcap/tiflow/issues/2747 same issue again

**Comment by asddongmen** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/17251/pipeline

**Comment by asddongmen** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/8278/tests/

**Comment by lance6716** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_test/detail/cdc_ghpr_test/14583/pipeline
