### ISSUE TITLE
cdc/kv timed out

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#4139]
### Which jobs are flaking?

github.com/pingcap/tiflow/cdc/kv

### Which test(s) are flaking?

CDC-UT

### Jenkins logs or GitHub Actions link

https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/7605/tests/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by hi-rustin** [comment]
It seems like it hasn't happened again for a long time, so close it.
