### ISSUE TITLE
Unclear ErrNewSemVersion

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiflow#4170]
### What did you do?

Run

```
dlv debug ./cmd/cdc -- server
./bin/cdc cli changefeed create ...
```

### What did you expect to see?

When running the server as `dlv exec bin/cdc -- server` things work fine. Same for running outside of delve.

### What did you see instead?

```
Error: [CDC:ErrNewSemVersion]create sem version: None is not in dotted-tri format
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
sql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:32:39
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.0008 sec)

```

TiCDC version (execute `cdc version`):

```console
$ ./bin/cdc version
Release Version: v5.4.0-master
Git Commit Hash: 7d9dd2f1d220084e8480f793be160e3a49bb8887
Git Branch: master
UTC Build Time: 2021-12-30 16:04:38
Go Version: go version go1.16.12 linux/amd64
Failpoint Build: false

```

The problem with this is that it is unclear which of the following has the wrong version: PD, TiKV or the CDC server.

Would be good if the error would indicate which component has the wrong version.

It would be great if this would work when using Delve, but that's not as important as a more informative error.

**Comment by dveeden** [comment]
Running Delve like this makes it more diffcult to debug as Delve might not have the right path for the source files and the build may be optimized etc.

**Comment by amyangfei** [comment]
We can pass build flags to dlv too via `build-flags`: `dlv debug --build-flags="-ldflags='-X github.com/pingcap/tiflow/pkg/version.ReleaseVersion=v5.4.0-master'" ./cmd/cdc -- server`

- maybe we need a script to get build flags, such as 

```bash
$ dlv debug --build-flags="$(./get_build_flags.sh)" ./cmd/cdc -- server
```

```bash
➜  cat get_build_flags.sh
#!/bin/bash

echo "-ldflags='-X github.com/pingcap/tiflow/pkg/version.ReleaseVersion=v5.4.0-master'"
```

**Comment by amyangfei** [comment]
Would you please take a look @CharlesCheung96

**Comment by dveeden** [comment]
@amyangfei maybe we should put that in the README?

And maybe something like this:
```
echo "-ldflags='-X github.com/pingcap/tiflow/pkg/version.ReleaseVersion=$(git describe --tags)"
```
to not hardcode the version.

**Comment by amyangfei** [comment]
> @amyangfei maybe we should put that in the README?
> 
> And maybe something like this:
> 
> ```
> echo "-ldflags='-X github.com/pingcap/tiflow/pkg/version.ReleaseVersion=$(git describe --tags)"
> ```
> 
> to not hardcode the version.

yes, the build flags should be generated dynamically, like what `Makefile` does, this is just a demo to show how it works.
