### ISSUE TITLE
sql-skip无法执行

### ISSUE THREAD

**Issue by yity** [pingcap/tiflow#4185]
File: [/release-1.0/zh/skip-or-replace-abnormal-sql-statements.md](https://docs.pingcap.com/zh/tidb-data-migration/v1.0/skip-or-replace-abnormal-sql-statements)
sql-skip无法执行，报错为：
 bin/dmctl --master-addr 127.0.0.1:8261
» » sql-skip --worker=127.0.0.1:8262 --binlog-pos=mysql_bin.000020:526741 test
fail to run: [» sql-skip --worker=127.0.0.1:8262 --binlog-pos=mysql_bin.000020:526741 test]
Error: unknown command "»" for "dmctl"
Run 'dmctl --help' for usage.
» 
»

**Comment by lance6716** [comment]
hi, which version of DM do you use? `sql-skip` is a command of v1.0

**Comment by D3Hunter** [comment]
> » » sql-skip --worker=127.0.0.1:8262 --binlog-pos=mysql_bin.000020:526741 test
> ...
> Error: unknown command "»" for "dmctl"

seems there's an extra `»` as the error message shows.
