### ISSUE TITLE
ticdc openapi new parameter support

### ISSUE THREAD

**Issue by Galaxy-Explorer** [pingcap/tiflow#4186]
### Is your feature request related to a problem?

ticdc openapi kafka  new parameter support 
"enable-old-value": 
"opts": 

### Describe the feature you'd like

in operation ticdc openapi， support opts enable-old-value modify
curl -X POST -H "'Content-type':'application/json'" http://127.0.0.1:8301/api/v1/changefeeds -d '{"changefeed_id":"test","sink_uri":"blackhole://","enable-old-value":"false", "opts":"tidb-domain=test-tidb.svc.local"}'

**Comment by zhaoxinyu** [comment]
The enable-old-value param is set to true by default and we suggest not changing it.

**Comment by Galaxy-Explorer** [comment]
Can another parameter   eg : "opts":"tidb-domain=test-tidb.svc.local" be supported?
