### ISSUE TITLE
No processor running or created

### ISSUE THREAD

**Issue by truong-hua** [pingcap/tiflow#4191]
### What did you do?

I created a simple changefeed and try to query processor but seem like there is no processor and nothing is running.

cdc cli changefeed create --sink-uri=local://testdir

cdc cli processor query -c cc62858d-3abb-4018-b14a-af09a675cb8c -p 26833d6e-43cb-4bcd-a101-938897f658bb

The output of `processor query` is:
```[CDC:ErrTaskPositionNotExists]task position not exists, key: /tidb/cdc/task/position/26833d6e-43cb-4bcd-a101-938897f658bb/cc62858d-3abb-4018-b14a-af09a675cb8c```

I tried to check in PD and there is no any keys under `/tidb/cdc/task/position/`

### What did you expect to see?

Changefeed is running and tso property is updated realtime.

### What did you see instead?

`changefeed list` respond a stable tso property and replication lag time is keep increasing until it's over gc-ttl value.

### Versions of the cluster

TiDB version: 5.2.1
TiCDC version: 5.2.1

**Comment by zhaoxinyu** [comment]
This bug is fixed in PR https://github.com/pingcap/tiflow/pull/4052

**Comment by zhaoxinyu** [comment]
@truong-hua , Is the `changefeed list` abnormality related to this bug as well?

**Comment by truong-hua** [comment]
thank @zhaoxinyu , I found out that the issue is related to high workload of our nodes so that seem ike TiCDC take a longer time to create a new processor. After the workload is reduced, TiCDC is working well as new processor is running.
