### ISSUE TITLE
kafak changefeed seems works normally when zookeeper down, broker running 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4240]
### What did you do?

- 1cdc ,3 kafka changefeed, 1 broker, tidb cluster v5.4.0
- stop zookeeper

### What did you see instead?

3 changefeeds seems work normally since checkpoint always keeps the latest time, I'm not sure if this behavior is expected since zookeeper has down but broker is running.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.4.0
```

TiCDC version (execute `cdc version`):

```console
v5.4.0
```

**Comment by hi-rustin** [comment]
This is expected because the producer will not use zk in production.
