### ISSUE TITLE
revert asynchronously create sink

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#4245]
In #3598, we initialize the `asyncSink` in an asynchronous way.

This would introduce some known problems and have some issues that need to be resolved.

The commit is already in the release-5.4, revert it now.

**Comment by asddongmen** [comment]
Could you specify the issues that cause by #3598? 
I want to know more what are this issue really means.
 @3AceShowHand

**Comment by amyangfei** [comment]
> This would introduce some known problems and have some issues that need to be resolved.

What are these known problems? Why master branch doesn't revert these changes.

**Comment by 3AceShowHand** [comment]
Actually, I would prefer to make asynchronous sink initialization and close merged at the same time. I think it's a part work.

**Comment by 3AceShowHand** [comment]
#4249 after the PR merged, test the functionality together.
