### ISSUE TITLE
TestBalancerFindTargetTied is unstable

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#4307]
### Which jobs are flaking?

unit test

### Which test(s) are flaking?

TestBalancerFindTargetTied

### Jenkins logs or GitHub Actions link

```log
=== RUN   TestBalancerFindTargetTied
    balancer_test.go:238: 
        	Error Trace:	balancer_test.go:238
        	Error:      	Should be false
        	Test:       	TestBalancerFindTargetTied
--- FAIL: TestBalancerFindTargetTied (0.00s)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by asddongmen** [comment]
another case:https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/17993/pipeline
