### ISSUE TITLE
panic when executeBatchJobs meet error

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow#4317]
### What did you do?

make a slow downstrem and decrease sycner's maxDMLConnectionTimeout
so every execSQL will meet a timeout error

---
```
[2022/01/13 14:33:19.604 +08:00] [ERROR] [db.go:221] ["execute statements failed after retry"] [task=test] [unit="binlog replication"] [queries="[DELETE FROM `sspanel`.`sspanel_user` WHERE `id` = ? LIMIT 1 REPLACE INTO `sspanel`.`sspanel_user` (`id`,`password`,`last_login`,`is_superuser`,`username`,`first_name`,`last_name`,`email`,`is_staff`,`is_active`,`date_joined`,`inviter_id`,`balance`,`invitecode_num`,`level`,`level_expire_time`,`theme`,`vmess_uuid`,`download_traffic`,`last_use_time`,`ss_password`,`ss_port`,`total_traffic`,`upload_traffic`,`uid`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]"] [arguments="[[7] [7 ehco1 <nil> 1 1 1 1 1 1 1 2022-01-11 09:56:23.000000 1 <nil> 1 1 2022-01-11 09:56:38.000000 d 1 0 <nil> 1 1 1 1 <nil>]]"] [error="[code=10006:class=database:scope=not-set:level=high], Message: execute statement failed: REPLACE INTO `sspanel`.`sspanel_user` (`id`,`password`,`last_login`,`is_superuser`,`username`,`first_name`,`last_name`,`email`,`is_staff`,`is_active`,`date_joined`,`inviter_id`,`balance`,`invitecode_num`,`level`,`level_expire_time`,`theme`,`vmess_uuid`,`download_traffic`,`last_use_time`,`ss_password`,`ss_port`,`total_traffic`,`upload_traffic`,`uid`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), RawCause: invalid connection"]
panic: runtime error: index out of range [1] with length 1

goroutine 750 [running]:
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeBatchJobs.func1(0x14005947e98, 0x14005dbebb0, 0x0, 0x14005947ea8, {0x14004c79710, 0x1, 0x1}, 0x14005947e40)
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:209 +0xb4
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeBatchJobs(0x14005dbebb0, 0x0, {0x14004c79710, 0x1, 0x1})
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:248 +0x3dc
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeJobs(0x14005dbebb0, 0x0, 0x14005e39f80)
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:180 +0x330
created by github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).run
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:102 +0xac
```

## RootCause

https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/syncer/dml_worker.go#L209

use wrong job index `affect` 
should use `affect-1` and check `jobs` length beacuse `affect` always equal  to job count in one batch
https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/pkg/conn/baseconn.go#L154

### What did you expect to see?

task paused but worker still alive

### What did you see instead?

worker panic

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
this is a old bug introduced in https://github.com/pingcap/dm/pull/850

Since for a long time users don't meet it, we can lower its severity.

**Comment by dsdashun** [comment]
I noticed those clues: 

If we just look at the abnormal return codes of `ExecuteSQLWithIgnoreError` method for `BaseConn`: 
https://github.com/pingcap/tiflow/blob/25b134de89ca2d8afb5b9a9dec3711b796583d88/dm/pkg/conn/baseconn.go#L116
https://github.com/pingcap/tiflow/blob/25b134de89ca2d8afb5b9a9dec3711b796583d88/dm/pkg/conn/baseconn.go#L199
https://github.com/pingcap/tiflow/blob/25b134de89ca2d8afb5b9a9dec3711b796583d88/dm/pkg/conn/baseconn.go#L205
For all the error places, it will not return the query length.  

But back to `executeBatchJobs` method.  It will return the query length as well as a non-nil error.  So the issue means `ExecuteSQLWithIgnoreError` executes OK, and there are some error generated in the calling chain other than `ExecuteSQLWithIgnoreError` ?

**Comment by Ehco1996** [comment]
> For all the error places, it will not return the query length.

this one is  return the error with len(query)
https://github.com/pingcap/tiflow/blob/25b134de89ca2d8afb5b9a9dec3711b796583d88/dm/pkg/conn/baseconn.go#L199

we just need to handle index out of range panic

**Comment by Ehco1996** [comment]
closed due to can not repruduced on master, it may something wrong on on my local code

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/syncer/dml_worker.go#L233 genSQLs may generate multiple DMLs per job(update job in safemode will generate delelete and replace), if later one meet a error, jobs[affect] may panic.

**Comment by Ehco1996** [comment]
> https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/syncer/dml_worker.go#L233
> 
> genSQLs may generate multiple DMLs per job(update job in safemode will generate delelete and replace), if later one meet a error, jobs[affect] may panic.

seems this is the root cause, could you please fix this? @dsdashun

**Comment by dsdashun** [comment]
> > https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/syncer/dml_worker.go#L233
> > 
> > genSQLs may generate multiple DMLs per job(update job in safemode will generate delelete and replace), if later one meet a error, jobs[affect] may panic.
> 
> seems this is the root cause, could you please fix this? @dsdashun

OK, I'll do that
