### ISSUE TITLE
Add metrics about batch size in a transaction

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#4327]
### Is your feature request related to a problem?

When we find the COMMIT costs too much time, we can't know the TiDB is slow or DM generates a big transaction

### Describe the feature you'd like

as title

### Describe alternatives you've considered

I can find the number of statement in a transaction in TiDB's metrics

**Comment by lance6716** [comment]
@Ehco1996 do you remember you have implement it?

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/tiflow/blob/master/dm/syncer/syncer.go#L1390-L1391
