### ISSUE TITLE
*(dm): db not closed when init failed

### ISSUE THREAD

**Issue by okJiang** [pingcap/tiflow#4353]
### description

I found the same problem in more places same as https://github.com/pingcap/tiflow/issues/4142

https://github.com/pingcap/tiflow/blob/4a06fe3104fc5ee37b4328e8f6a8c2cbfdd40199/dm/loader/checkpoint.go#L103-L126

https://github.com/pingcap/tiflow/blob/4a06fe3104fc5ee37b4328e8f6a8c2cbfdd40199/dm/syncer/checkpoint.go#L413-L425

https://github.com/pingcap/tiflow/blob/4a06fe3104fc5ee37b4328e8f6a8c2cbfdd40199/dm/syncer/sharding_group.go#L429-L441

didn't close db once err return

**Comment by lance6716** [comment]
`dbconn.CreateConns` will close `db` internally when it has error

**Comment by okJiang** [comment]
> `dbconn.CreateConns` will close `db` internally when it has error

I mean `prepare()` returns error.
