### ISSUE TITLE
Dmctl can't start relay after upgrade from 2.0.1(enable-relay:  true)-> 5.4.0 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tiflow#4370]
### What did you do?

config source1 as enable-relay: false
upgrade dm cluster from 2.0.1 -> v5.4.0
try to start-relay for source1

### What did you expect to see?

start-relay for source1 success

### What did you see instead?

fail to start-relay,  
use:
 tiup dmctl --master-addr=ip:8261 start-relay  -s mysql-replica-2-002 dm-worker-8101
report :
               "result": {
                    "isCanceled": false,
                    "errors": [
                        {
                            "ErrCode": 30008,
                            "ErrClass": "relay-unit",
                            "ErrScope": "internal",
                            "ErrLevel": "high",
                            "Message": "initial relay unit: dirpath is empty",
                            "RawCause": "",
                            "Workaround": "Please check the `relay-dir` config in source config file."
                        }
                    ],
use _operate-source show_ to check, report:
           "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:30008 ErrClass:\"relay-unit\" ErrScope:\"internal\" ErrLevel:\"high\" Message:\"initial relay unit: dirpath is empty\" Workaround:\"Please check the `relay-dir` config in source config file.\" , Workaround: Please execute `query-status` to check status.",
            "source": "mysql-replica-2-002",
            "worker": "dm-worker-8101"
        }
    ]

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.4.0
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
caused by in v2.0.1, we only adjust `relay-dir` for `enable-relay: true` sources.

we changed to always adjust `relay-dir` in https://github.com/pingcap/dm/pull/1515

**Comment by niubell** [comment]
I will add a flag `--relay-dir` to command `dmctl start-relay`.When receiving `start-relay` command, The dm-master will check if empty the `relay-dir` in source config, if so, "relay-dir is empty" error will be responded and we offer "dmctl start-relay --relay-dir" as a workaround to solve this problem.How about this solution ? @lance6716 @sunzhaoyang @Ehco1996

**Comment by lance6716** [comment]
currently `relay-dir` in DM-worker config file has highest priority. And after introduce `start-relay --relay-dir`, I think the command line argument should have highest priority. If the implementation is that use `start-relay --relay-dir` to fillback `relay-dir` in source config file, the source config will still be overwritten by `relay-dir` in DM-worker config file. Please take note of it. @niubell

**Comment by niubell** [comment]
> currently `relay-dir` in DM-worker config file has highest priority. And after introduce `start-relay --relay-dir`, I think the command line argument should have highest priority. If the implementation is that use `start-relay --relay-dir` to fillback `relay-dir` in source config file, the source config will still be overwritten by `relay-dir` in DM-worker config file. Please take note of it. @niubell

Thanks for reminding me. The priority of `relay-dir` in open-api is lower than `relay-dir` in dm-worker config file.Shall we keep this consistent with each other? By the way, the `relay-dir` in dm-worker config file goes to effect in observation of Etcd path, it's hard to change this mechanism.

**Comment by niubell** [comment]
Just optimize workaround message in `30008`. The message will be `Please check the relay-dir config in source config file or dm-worker config file`
