### ISSUE TITLE
TiCDC openapi GET /api/v1/changefeeds showing error status changefeeds

### ISSUE THREAD

**Issue by Galaxy-Explorer** [pingcap/tiflow#4492]
### What did you do?

tidb 5.3.0

/ # ./cdc cli changefeed query -s --pd=http://127.0.0.1:2379 --changefeed-id=test
{
 "state": "error",
 "tso": 430771177965223938,
 "checkpoint": "2022-01-27 05:33:54.694",
 "error": {
  "addr": "127.0.0.1:8301",
  "code": "CDC:ErrProcessorUnknown",
  "message": "[CDC:ErrMySQLTxnError]Error 1146: Table 'test.t' doesn't exist: Error 1146: Table 'test.t' doesn't exist"
 }

/ # curl -X GET http://127.0.0.1:8301/api/v1/changefeeds/test
{"id":"test","sink_uri":"mysql://test:123456@10.10.10.10:4000","create_time":"2022-01-27 04:38:28.036","start_ts":430770305785921537,"target_ts":0,"checkpoint_tso":430771267185934338,"checkpoint_time":"2022-01-27 05:39:35.044","sort_engine":"unified","state":"error","error":null,"error_history":null,"creator_version":"","task_status":[]}

but
/ # curl -X GET http://127.0.0.1:8301/api/v1/changefeeds
get [] list

### What did you expect to see?

/ # curl -X GET http://127.0.0.1:8301/api/v1/changefeeds
[
    {
        "id": "test",
        "state": "error",
        "checkpoint_tso": 430771648199393281,
        "checkpoint_time": "2022-01-27 06:03:48.495",
        "error": {
  "addr": "127.0.0.1:8301",
  "code": "CDC:ErrProcessorUnknown",
  "message": "[CDC:ErrMySQLTxnError]Error 1146: Table 'test.t' doesn't exist: Error 1146: Table 'test.t' doesn't exist"
 }
    }
]

### What did you see instead?

/ # curl -X GET http://127.0.0.1:8301/api/v1/changefeeds
[]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
tidb_version(): Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:32:39
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

TiCDC version (execute `cdc version`):

```console
Release Version: v5.3.0-dirty
Git Commit Hash: 20626babf21fc381d4364646c40dd84598533d66
Git Branch: HEAD
UTC Build Time: 2022-01-13 05:31:40
Go Version: go version go1.16.5 linux/amd64
Failpoint Build: true
```

**Comment by ben1009** [comment]
it is kind of by design, according to https://docs.pingcap.com/tidb/stable/ticdc-open-api/#query-the-replication-task-list
```
The value options for state are all, normal, stopped, error, failed, and finished.

If this parameter is not specified, the basic information of replication tasks whose state is normal, stopped, or failed is returned by default.
```

**Comment by overvenus** [comment]
Try `curl  http://127.0.0.1:8301/api/v1/changefeeds\?state\=all`.
