### ISSUE TITLE
make operate-schema --sync default value to true

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#4547]
### Is your feature request related to a problem?

when user manually set schema for a table using `operate-schema`, they usually don't know that --sync needs to be set to true, which may cause DDL conflict later.

### Describe the feature you'd like

make operate-schema --sync default value to true

**Comment by lance6716** [comment]
also we should provide a easy way to get the TableInfo in etcd, like get --sync

**Comment by zhenjiaogao** [comment]
@lance6716 A similar feature request has been submitted before: https://github.com/pingcap/tiflow/issues/3238
