### ISSUE TITLE
TiKV OOM when sysbench write_only and cdc changefeed exists

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4589]
### What did you do?

- During v5.1.4 test infra cdc case run, sysbench write_only +  cdc always make tikv oom.
- 
![image](https://user-images.githubusercontent.com/78345569/153842954-f7a76f5a-387b-497c-bfd0-60095e7efd20.png)

   
![70V7Ww25r2](https://user-images.githubusercontent.com/78345569/153842371-4542a19a-652d-47f6-923c-5cbc536c5ff2.png)

- While in main version with the same test case, no tikv oom. 
![image](https://user-images.githubusercontent.com/78345569/153843142-8d2adf07-5a47-4d25-aef6-35e1cb7320e5.png)

- Each tikv pod's memory is 16GB, block cache size is 7GB.

### What did you expect to see?

No TiKV OOM

### What did you see instead?

TiKV OOM

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.1.4
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.1.4
```

TiCDC version (execute `cdc version`):

```console
v5.1.4
```

**Comment by hicqu** [comment]
It can't be reproduced for a long time. Let's close it.
