### ISSUE TITLE
canal-json return a list with null instead of a directly null

### ISSUE THREAD

**Issue by usxiaojunyang** [pingcap/tiflow#4597]
### What did you do?

I'm using canal-json protocal in ticdc version v5.1.1.After sink to kafka,the consumer received something like this:
"old":[null]
The downstream flink platform will get a list but NULL in it,which cause some NPE exceptions like this:
![image](https://user-images.githubusercontent.com/44763540/154019626-edfd17f2-1916-44d0-9fec-a9dd3b6661d4.png)

And after that we check the code(https://github.com/pingcap/tiflow/blob/v5.1.1/cdc/sink/codec/canal_flat.go#L110) and found when sqltype is insert,"oldData" would not be initialized.It will return null to struct canalFlatMessage.We made some change

    //insert or update 
	if len(rowData.AfterColumns) > 0 {
		//insert 
		if len(rowData.BeforeColumns) == 0 {
		    oldData = map[string]interface{}{}
	    }
                //update
		data = make(map[string]interface{}, len(rowData.AfterColumns))
		for i := range rowData.AfterColumns {
			if !rowData.AfterColumns[i].GetIsNull() {
				data[rowData.AfterColumns[i].Name] = rowData.AfterColumns[i].Value
			} else {
				data[rowData.AfterColumns[i].Name] = nil
			}
		}
	}

And we finally received new result like this:
![image](https://user-images.githubusercontent.com/44763540/154020835-c4099cf7-b3a1-4563-ae37-139eee21ab74.png)

In master tag we notice new function getOld().Could you please check whether you can change it also
https://github.com/pingcap/tiflow/blob/14db59be99371a0ef996708fa2867e73b2d7b8af/cdc/sink/codec/canal_flat.go#L135
func (c *canalFlatMessage) getOld() map[string]interface{} {
	if c.Old == nil {
		return map[string]interface{}{}
	}
	return c.Old[0]
}

### What did you expect to see?

Expect to c:
"old":null
or 
"old":[]

### What did you see instead?

"old":[null]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.1.1
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.1.1
```

TiCDC version (execute `cdc version`):

```console
v5.1.1
```

**Comment by 3AceShowHand** [comment]
This is a known bug, fixed by https://github.com/pingcap/tiflow/pull/3677.

**Comment by 3AceShowHand** [comment]
<img width="650" alt="Screen Shot 2022-02-16 at 1 50 54 PM" src="https://user-images.githubusercontent.com/7138436/154204476-560fcc63-d38a-4136-bba6-4f6aa1de6489.png">

**Comment by 3AceShowHand** [comment]
`"old": null` is identical to the official implementation.

**Comment by usxiaojunyang** [comment]
Thanks for replying,we'll upgrade cdc when we upgrade tidb version in the future.For now we've built an independent binary to work around.

**Comment by 3AceShowHand** [comment]
> Thanks for replying,we'll upgrade cdc when we upgrade tidb version in the future.For now we've built an independent binary to work around.

you can manaully cherry pick #3677, it should work as described as https://docs.pingcap.com/zh/tidb/stable/ticdc-canal-json
