### ISSUE TITLE
replication is slow and many “checkpoint has no change, skip sync flush checkpoint” in DM log

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#4619]
### What did you do?

This issue may be triggered when DM uses GTID replication and with one of below scenarios:
- upstream has a big DML event which contains millions of row changes. **normally this would not happen**, for [default max size of any ROWS_EVENT is 8192](https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#option_mysqld_binlog-row-event-max-size)
- an extra large transaction totally has millions of row changes

or DM uses position-based replication and with:
- upstream has a big DML event which contains millions of row changes, **normally this would not happen**

https://asktug.com/t/topic/573236

### What did you see instead?

The bug phenomenon is that DM replicates data very slow and there are many “checkpoint has no change, skip sync flush checkpoint” in DM log

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.4.0
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
### Root cause

When DM meets row changes of a big transaction in upstream and the locations of row changes are same (same GTID or belonging to one big event), the checkpoint can not be updated thus can not be flushed to downstream.

Since v5.4.0, after the checkpoint flush interval (30s by default), DM will try to check the checkpoint status and print a log in https://github.com/pingcap/tiflow/blob/14db59be99371a0ef996708fa2867e73b2d7b8af/dm/syncer/syncer.go#L1114
 which involves a disk IO . Disk IO is slow thus will cause the replication becomes slower.

**Comment by D3Hunter** [comment]
possible solution after discuss with @lance6716 
- change this log's level to `debug`
- on dml events, if there's no check point change after flush interval, mark a flag we entered into a large transaction, and disable checking when this flag is on, reset this flag when we met `XID` event, to avoid checking checkpoint change repeatedly.

**Comment by GMHDBJD** [comment]
> change this log's level to debug

to `WARN` ?

**Comment by Ehco1996** [comment]
> > change this log's level to debug
> 
> to `WARN` ?

warn level is higher than info

**Comment by GMHDBJD** [comment]
Oh, I misunderstood it as saying the user's workaround

**Comment by lance6716** [comment]
@glorv has reminded us that write disk may not be such slow, so extra time costs may come from checking if any table checkpoint is outdated. Also considering the GTID set of user's scenario is complex, the GTID set comparing may contribute an innegligible factor to time cost.

**Comment by lance6716** [comment]
if the task has a few tables to replicate, the speed does not drop even if a lots of log is printed.

reproduced with 4 tables in task, a transaction delete 2M rows, checkpoint-flush-interval is 5 seconds.

**Comment by lance6716** [comment]
if the task has 500 tables and a simple GTID set, DELETE QPS will drop from 16.8k to 15.0k (~10%). This is the effects of checking table checkpoints

**Comment by lance6716** [comment]
if the task has 500 tables and a complex GTID set (10 uuid parts), DELETE QPS will drop from 16.8k to 3.7k (drop ~78%).

**Comment by XuJianxu** [comment]
reappear this issue in upgrade testing.

- two upstream open relay log with dm 2.0.1 with  3 masters 3 workers
- execute create index to upstream1, continue to load data to upstream 2
- upgrade to v5.4.0
- execute same ddl to upstream2
-  continue to load data to upstream 1&2
- this issue happened
