### ISSUE TITLE
data(table index) inconsistency after detaching upstream in dbaas v5.4.0

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4688]
### What did you do?

-  dbaas cluster, sysbench workload in upstream
- stop workload:
   
![origin_img_v2_ec46c5ff-604a-454b-9395-cd62cbdedaeg](https://user-images.githubusercontent.com/78345569/155486886-a1f52fbb-72de-4de4-aa45-d5151522df76.png)

- detach upstream cluster
- check if data consistency between two cluster.

### What did you expect to see?

- data consistent between two cluster as spec.

### What did you see instead?

[2022/02/23 10:08:37.619 +00:00] [INFO] [report.go:80] ["check result summary"] ["check passed num"=29] ["check failed num"=3]
[2022/02/23 10:08:37.619 +00:00] [INFO] [report.go:87] ["table check result"] [schema=test] [table=sbtest32] ["struct equal"=false] ["data equal"=false]
[2022/02/23 10:08:37.619 +00:00] [INFO] [report.go:87] ["table check result"] [schema=test] [table=sbtest31] ["struct equal"=false] ["data equal"=false]
[2022/02/23 10:08:37.619 +00:00] [INFO] [report.go:87] ["table check result"] [schema=test] [table=sbtest20] ["struct equal"=false] ["data equal"=false]

- upstream cluster table sbtest32 has index "KEY", but downstream cluster has not.

![middle_img_v2_0df63d73-989b-44f1-b5d9-61dd78a3186g](https://user-images.githubusercontent.com/78345569/155483282-3e1f15b0-44ac-421d-bd65-b6afcb157506.png)
![middle_img_v2_3c905b07-5788-4627-98ad-6ca71cbeea1g](https://user-images.githubusercontent.com/78345569/155486334-fc27acec-a334-42e9-a783-88448c63c3da.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.4.0 GA
```

TiCDC version (execute `cdc version`):

```console
v5.4.0 GA
```

**Comment by lance6716** [comment]
does downstream have a running DDL of creating index?

**Comment by overvenus** [comment]
Most likely it is caused DDL execution timeout. It can be workaround by setting a large `readTimeout` and `writeTimeout` in sink URI.

**Comment by overvenus** [comment]
Duplicate of #4782

**Comment by Tammyxia** [comment]
Reproduced in DBaaS v6.0.0.

**Comment by Tammyxia** [comment]
- Stop sysbench command, after 3s, planned detach cross region cluster.
- Check "show create table xxx"  between primary tidb and secondary tidb:

**Comment by nongfushanquan** [comment]
The plan detach function is  removed from the cross region situation
