### ISSUE TITLE
[CC scenario] checkpoint don't move event sink write is normal

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4698]
### What did you do?

- 8 cdc node, upstream 18TB data size, downstream 11TB data size, so cdc has 7TB to sync.
- sink write is normal, but checkpoint don't move.
-   /cdc cli changefeed list --pd=https://db-pd-peer.tidb1373933076657975300:2379 --ca ca.crt --cert tls.crt --key tls.key

[
  {
    "id": "362e4d46-8380-4f45-b103-5a6f040adfdb",
    "summary": {
      "state": "normal",
      "tso": 431381392152854535,
      "checkpoint": "2022-02-23 04:10:17.087",
      "error": null
    }
  }
]
bash-5.1# date
Fri Feb 25 05:10:23 UTC 2022

### What did you see instead?

- There is a risk that checkout execeed gc-ttl.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.4.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.4.0
```

TiCDC version (execute `cdc version`):

```console
v5.4.0
```

**Comment by liuzix** [comment]
TiCDC will not advance the checkpoint unless all tables' checkpoints have moved. Can you provide more details?

**Comment by asddongmen** [comment]
Close it since it is stale.
