### ISSUE TITLE
[CC scenario] table count is imbalance

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4700]
### What did you do?

- When cdc sink write, check table count.
   
![HxT5LJoxoi](https://user-images.githubusercontent.com/78345569/155661426-4959b3af-c776-4af7-b069-2da90ae63958.png)
Sometimes it's like this:
![HQqdLz9fes](https://user-images.githubusercontent.com/78345569/155661316-f5547dfe-dbcd-4c44-bee3-0a2e2436b5ca.png)

- Restart all cdc pod, when cdc sink write, check table count.

![image](https://user-images.githubusercontent.com/78345569/155661201-d8835215-6dc0-45c7-a4d5-088954409e44.png)

### What did you see instead?

As above

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.4.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.4.0
```

TiCDC version (execute `cdc version`):

```console
v5.4.0
```

**Comment by liuzix** [comment]
TiCDC does not try to rebalance tables when there are tables that have pending operations on it, such as when it is being added to a capture. To ensure safety, we do not consider an adding table operation as complete, unless its table-level resolved-ts is larger than or equal to the global resolved-ts. But the global resolved-ts can be considerably larger than the global checkpoint-ts, especially after a capture fail-over. This means that, if there is a table whose delta scan is not yet finished, sometimes the owner will consider the adding table operation as ongoing, until the delta scan has finished. During this period, the owner consider the table's replication as "uninterruptable", which prevents an attempt to rebalance the workload.

**Comment by asddongmen** [comment]
Close it since it is stale. It has been fix in > v6.1.0.
