### ISSUE TITLE
integration test-clustered_index fail 

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#4727]
### Which jobs are flaking?

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/9308/pipeline

### Which test(s) are flaking?

integration test-clustered_index

### Jenkins logs or GitHub Actions link

```log
(paste logs here)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by hi-rustin** [comment]
Duplicate of https://github.com/pingcap/tiflow/issues/3421
