### ISSUE TITLE
Support column and data mismatch in cyclic replication

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#475]
## Description

**Is your feature request related to a problem? Please describe:**

This is part of #471

Considering the following scenario:

cluster A <-> cluster B

- drop column of table t at cluster A
- DMLs from B->A before the `drop column` DDL in A will have one more column.

**Describe the feature you'd like:**

Allow MySQL sink to process this scenario

### Value Score
> Optional value: 1~5

* 4

### Workload Estimation
> 1 Point for 1 Person/Work Day

* 10 Points

**Comment by overvenus** [comment]
![image](https://user-images.githubusercontent.com/2150711/80068391-1e56ea80-8572-11ea-9e54-d4ccdff28256.png)

Discussed offline, as the figure above, the mismatch column is only possible between C -> A.
* If A has more columns, we could just relax sql_mode and add null to these columns.
* If A has few columns, CDC reports an error but **not** interrupts changefeeds, though A and B may lose some data.

**Comment by overvenus** [comment]
#509 resolves 'i' in the https://github.com/pingcap/ticdc/issues/475#issuecomment-618218560.

**Comment by hi-rustin** [comment]
close it, as we no longer continue to support that feature.
