### ISSUE TITLE
Querying status via openapi may be blocked when pd fails

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#4778]
### What did you do?
When network isolation occurs between pd nodes and cdc nodes, run `curl -X GET http://127.0.0.1:8300/status`, and the terminal is stuck.

### What did you expect to see?

```shell
> curl -X GET http://127.0.0.1:8300/status                                                                          
{
 "version": "v5.4.0",
 "git_hash": "14db59be99371a0ef996708fa2867e73b2d7b8af",
 "id": "12f02f4c-59c2-4e73-8f9c-9db516fad91c",
 "pid": 8156,
 "is_owner": true
}
```

### What did you see instead?

There is no return message from the terminal

### Versions of the cluster

TiCDC version (execute `cdc version`):
```console
v5.4.0
14db59be99371a0ef996708fa2867e73b2d7b8af
```

**Comment by amyangfei** [comment]
Please confirm the affected versions @CharlesCheung96
