### ISSUE TITLE
v5.3.1 relay log may turn off after master reboot

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#4803]
### What did you do?

prerequisite: all conditions below must be satisfied
- v5.3.1
- user use `start-relay -s source01 worker01` to start relay log for `source01` on worker01
- source configuration file of `source01` has `enable-relay: true` (in v5.3.1, this field does not take effect, `start-relay` command is the only way to start relay)
- master reboot or leader switch

### What did you expect to see?

relay is still turned on for `source01` on worker01

### What did you see instead?

relay is turned off

### Versions of the cluster

v5.3.1

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
(waiting to be reproduced)

## Root cause

during cherry-pick and resolve conflict for https://github.com/pingcap/tiflow/pull/4430 , we wrongly included the logic of v5.4 into v5.3, this logic is about cleaning etcd relay KV which causes the issue.

## Walkaround (to be confirmed)

If user need relay log feature, he/she must not have `enable-relay: true` in source configuration file

**Comment by niubell** [comment]
`enable-relay` is depreacted from v2.0.2, so we don't need to fix this issue, right ?

**Comment by lance6716** [comment]
depreacted means it doesn't take effects, but https://github.com/pingcap/tiflow/blob/641df5d54c37721a94697d06a8373674a50ae877/dm/dm/master/scheduler/scheduler.go#L1515 it can cause relay KV deleted.

User may upgrade from v2.0.1 and not turn off `enable-relay`

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/tiflow/pull/4877
