### ISSUE TITLE
ticdc suddenly hang，there is no owner node？

### ISSUE THREAD

**Issue by lddlww** [pingcap/tiflow#4841]
### What did you do?

**ticdc version：**
```
5.3.0
```
**grafana monitor：**
![image](https://user-images.githubusercontent.com/27006237/157628900-cbad5128-9f0b-4c7f-92d0-824328284f5e.png)
![image](https://user-images.githubusercontent.com/27006237/157626797-8aa2a435-9b2a-40b9-9a82-dfcef9bd9394.png)
![image](https://user-images.githubusercontent.com/27006237/157626843-d3553efc-ec41-4559-8dd8-627ddda7abe2.png)

**pingcap metrictool ticdc monitor：**
[ticdc.zip](https://github.com/pingcap/tiflow/files/8221822/ticdc.zip)

**ticdc log：**
[ticdc_log.zip](https://github.com/pingcap/tiflow/files/8221931/ticdc_log.zip)

**question：**
there was no business in tidb cluster，grafana monitor shows ticdc suddenly miss owner node, what's wrong with it?

### What did you expect to see?

ticdc not hang

### What did you see instead?

ticdc miss owner node

### Versions of the cluster

5.3.0

**Comment by overvenus** [comment]
Could you provide TiCDC goroutine when it happens again?

```
curl http://${CDC_ADDR}/debug/pprof/goroutine\?debug\=2 -o goroutine.log
```

Also, you can try TiCDC v5.3.1, we have fixed several similar issues.

**Comment by lddlww** [comment]
sorry，i can not reproduce it

however i will try upgrade ticdc from 5.3.0 to 5.3.1 ，thanks

**Comment by overvenus** [comment]
I'm going to close the issue, please feel free to reopen if it sill exists in v5.3.1. And thank you for your feedback!

**Comment by lddlww** [comment]
@overvenus last night，we suffer ```ticdc``` owner node hung again，follow file contains owner node and worker node ```goroutine``` info at the time：
[goroutine.zip](https://github.com/pingcap/tiflow/files/8460515/goroutine.zip)

**Comment by overvenus** [comment]
> @overvenus last night，we suffer `ticdc` owner node hung again，follow file contains owner node and worker node `goroutine` info at the time： [goroutine.zip](https://github.com/pingcap/tiflow/files/8460515/goroutine.zip)

What's your TiCDC version?

**Comment by lddlww** [comment]
5.3.0

**Comment by lddlww** [comment]
@overvenus could you find something wrong in ```ticdc owner```

**Comment by lddlww** [comment]
@overvenus i only want to upgrade ticdc to ```5.3.1```， not all tidb cluster which current version is ```5.3.0```, if it's ok?
