### ISSUE TITLE
ticdc_processor_checkpoint_ts metric bugs?

### ISSUE THREAD

**Issue by lddlww** [pingcap/tiflow#4859]
### What did you do?

**prometheus monitor data:**
![image](https://user-images.githubusercontent.com/27006237/157834707-adba7a73-529c-4f51-adb7-9de766294354.png)

**problem:**
when changefeed task switch to other capture node，but processort checkpoint of old capture node couldn't change，this result in prometheus fire alert to alertmanager  when use (time() - ticdc_processor_checkpoint_ts / 1000) > 600 to compute checkpoint lag

### What did you expect to see?

old capture processor checkpoint can be clear

### What did you see instead?

old capture processor checkpoint can't change

### Versions of the cluster

5.3.0

**Comment by overvenus** [comment]
Try updating TiCDC alert rules, https://github.com/pingcap/tiflow/blob/master/metrics/alertmanager/ticdc.rules.yml

There are some false alarms in old rules, as you mentioned. We have improved in the recent releases. Replacing `(time() - ticdc_processor_checkpoint_ts / 1000) > 600 ` with `ticdc_processor_checkpoint_ts_lag > 600`

**Comment by lddlww** [comment]
thanks for your solution，and i'm closing this issue now
