### ISSUE TITLE
Relay hanged while migrate data(Grafana display error info of replication lag)

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tiflow#4860]
### What did you do?

- add workeload to 9 upstreams(11K QPS/each, for 1h) , use dm to migrate date to downstream tidb
- after workload for upstream completed, check the grafana

### What did you expect to see?

relication lag will display as expect 

### What did you see instead?

relay hanged and migrate stoped.
after stop relay, migrate process resume.
grafana display as below:
![image](https://user-images.githubusercontent.com/23207893/157842015-7b10cdc9-a96f-4771-90e4-9f83f4fc98fe.png)

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
nightly
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by Ehco1996** [comment]
this may caused by not called clear jobTS when exec SQL timeout 

and this was introduced in https://github.com/pingcap/tiflow/pull/4496

**Comment by lance6716** [comment]
My expected implementation is:

For each DML and DDL queue, when a batch of job is finished and ready to execute next batch, set the queue's "processing ts" to the minimum job ts of next batch or 0 when the queue is empty. When query the lag, filter out the 0 and get minimum "processing ts" among queues, and calculate the lag based on current timestamp.

**Comment by Ehco1996** [comment]
> My expected implementation is:
> 
> For each DML and DDL queue,
> 
> * when a batch of job is finished and ready to execute next batch, set the queue's "processing ts" to the minimum job ts of next batch or 0 when the queue is empty.
> * when a job is added to queue and "processing ts" is 0, update "processing ts" to the timestamp of the job.
> * when query the lag, filter out the 0 and get minimum "processing ts" among queues, and calculate the lag based on current timestamp.

> you mean set processing ts to 0 only when queue is empty ?

btw, this is basically hot it is implemented now , see https://github.com/pingcap/tiflow/pull/4496#issuecomment-1040995004

but semms i forget to reset TS to 0 in some corner case

**Comment by lance6716** [comment]
replaced by https://github.com/pingcap/tiflow/issues/5063
