### ISSUE TITLE
DM can not start task with mariadb 10.1.2 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tiflow#4959]
### What did you do?

- prepare dm cluster with version nightly 
- create source for mariadb 10.1.2
- try to start task

### What did you expect to see?

start-task success

### What did you see instead?

Below error output:
"errors": [
                                        {
                                                "severity": "warn",
                                                "short_error": "Migrating from MariaDB is experimentally supported. If you must use DM to migrate data from MariaDB, we suggest make your MariaDB \u003e= 10.1.2"
                                        }
                                ],
                                "extra": "address of db instance - [upstream1.dm](http://upstream1.dm/)-migrate-mariadb-basic-testbed-tps-721316-1-926:3306"
                        }
                ],
                "summary": {
                        "passed": false,
                        "total": 10,
                        "successful": 8,
                        "failed": 1,
                        "warning": 1
                }
        }"

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
nightly
```
Upstream MySQL/MariaDB server version:
```console
10.1.2-MariaDB-1~wheezy-wsrep-log
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
this is a warning, not error. Task should have been started. I'll lower the priority to moderate

**Comment by Ehco1996** [comment]
actully the check err from dmctl is , so the reason of why this task can not start  is `mysql_binlog_row_image`

```
❯ dmctl start-task tasks/task-from-mariadb.yaml
{
    "result": false,
    "msg": "",
    "sources": [
    ],
    "checkResult": "[code=26005:class=dm-master:scope=internal:level=medium], Message: fail to check synchronization configuration with type: check was failed, please see detail
    	detail: {
		"results": [
			{
				"id": 0,
				"name": "mysql_version",
				"desc": "check whether mysql version is satisfied",
				"state": "warn",
				"errors": [
					{
						"severity": "warn",
						"short_error": "Migrating from MariaDB is experimentally supported. If you must use DM to migrate data from MariaDB, we suggest make your MariaDB \u003e= 10.1.2"
					}
				],
				"extra": "address of db instance - 42.192.194.142:3308"
			},
			{
				"id": 5,
				"name": "mysql_binlog_row_image",
				"desc": "check whether mysql binlog_row_image is FULL",
				"state": "fail",
				"errors": [
					{
						"severity": "fail",
						"short_error": "sql: no rows in result set"
					}
				],
				"extra": "address of db instance - xxxxxxx:3308"
			}
		],
		"summary": {
			"passed": false,
			"total": 10,
			"successful": 8,
			"failed": 1,
			"warning": 1
		}
	}"
}
```
