### ISSUE TITLE
KV client don't  receive any event during changefeed sync data

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4967]
### What did you do?

1. BR restore to both upstream and downstream TiDB cluster, with the same source data.
2. Create a changefeed.
3. Run workload: go-ycsb load and run.

### What did you expect to see?

changefeed sync data normally

### What did you see instead?

1.  After sink write works for 23 min, then unexpectedly there's not any row to sink write.
2. KV client don't receive any event, and tikv-3 min-resolved is 1hour, while other tikv min-resolved is 12.2s
![tiMiJqxyqW](https://user-images.githubusercontent.com/78345569/159233391-2352be33-8d8b-47bb-80f2-1ec04a673349.png)
![wIgrfQGEXG](https://user-images.githubusercontent.com/78345569/159233419-8a03c06e-ad62-4a95-927d-8a7f34cacf12.png)
3. ticdc log: 
      [2022/03/21 07:40:09.411 +00:00] [WARN] [region_worker.go:355] ["region not receiving resolved event from tikv or resolved ts is not pushing for too long time, try to resolve lock"] [changefeed=cc-mysql-t
ask] [addr=upstream-tikv-3.upstream-tikv-peer.cdc-testbed-tps-662589-1-708.svc:20160] [regionID=1267152] [span="[748000000000009aff4b5f720000000000fa, 748000000000009aff4b5f730000000000fa)"] [duration=56m
40.799s] [lastEvent=160.387851ms] [resolvedTs=431972681911369730]
4. Manually pause & resume changefeed, changefeed  can be recovered.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
TiKV
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   9a43faf4da20389a4e2c262ee8ab8b369a3bfec4
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:    2022-03-19 11:16:46
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
/cdc version
Release Version: v5.4.0-master
Git Commit Hash: 43ca1cdb1cc02f1635796e119d235a08f5fc3191
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-03-18 11:13:20
Go Version: go version go1.18 linux/amd64
Failpoint Build: false
```

**Comment by hicqu** [comment]
[1267152.zip](https://github.com/pingcap/tiflow/files/8322832/1267152.zip)

Here is the log of region 1267152 which has the smallest resovled ts on the store tikv-3.
From the log we can know it's caused by https://github.com/tikv/tikv/issues/12160.
