### ISSUE TITLE
DM(syncer): syncer may lost dml under special sharding ddls

### ISSUE THREAD

**Issue by WizardXiao** [pingcap/tiflow#5002]
### What did you do?

1. open gtid
2. pessimistic shard mode
3. two sub-table in one source
4. sql like this:
    tb1 --> ddl1
    tb1 --> dml (lost)
    tb1 --> ddl2
    tb2 --> ddl1
    tb2 --> ddl2

### What did you expect to see?

Don't lost tb1's dml.

### What did you see instead?

lost tb1's dml

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.3 --> master
```
Upstream MySQL/MariaDB server version:
```console
5.7.22-log
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
5.7.25-TiDB-v5.3.0
```
How did you deploy DM: tiup or manually?
```console
manually
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
![middle_img_v2_2a630eea-6a5b-45f7-86f7-4d62a59ec86g](https://user-images.githubusercontent.com/35025882/159673954-7fe87815-dbb8-4d4b-b802-5aacb66a0e81.png)
ping @lance6716

**Comment by lance6716** [comment]
If this bug need not to be cherry-pick to earlier version, I guess it's earier to fix when use https://github.com/pingcap/tiflow/blob/c48f208177e825fc52c905fed70a7bbaea263ba9/dm/syncer/binlog_locations.go#L30-L45

😂 not likely that we don't cherry-pick

**Comment by GMHDBJD** [comment]
> 😂 not likely that we don't cherry-pick

/(ㄒoㄒ)/~~

**Comment by WizardXiao** [comment]
After `tb1-ddl1` and `tb2-ddl1` has been resolved, `tb1-dml` will be synced, and we will check wether `tb1-dml` < `tb1-ddl2` (active ddl), but caculate `tb1-ddl2`'s position use last_position‘s gtid which is the same as `tb1-dml`, when use gtid, we will filter  `tb1-dml`
