### ISSUE TITLE
DM report confusing error message after "too many connection" error

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#5005]
### What did you do?

downstream limit max-server-connections to 50
start a task with two source

### What did you expect to see?

task fail with `downstream too many connection error`

### What did you see instead?

One source succeed, one source failed with error bad connection
```
{
            "result": false,
            "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:10002 ErrClass:\"database\" ErrScope:\"downstream\" ErrLevel:\"high\" Message:\"fail to initial unit Sync of subtask test : database driver\" RawCause:\"driver: bad connection\" Workaround:\"Please check the database connection, then use `pause-task` to pause the task and then use `resume-task` to resume the task.\" , Workaround: Please execute `query-status` to check status.",
            "source": "source2",
            "worker": "dm-127.0.0.1-8272"
        }
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.4.0
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
It is important to note that TiDB Cloud "dev tier" sets max-server-connections=50. DM default loader pool size is 16, default sync worker-count is 16, so a all mode task will create more than 32 connection when init task, which means if user create a sharding merge task, the task will always failed and report such a bad connection error.

**Comment by lance6716** [comment]
can we get "downstream too many connection error" in the code?

**Comment by D3Hunter** [comment]
> DM default loader pool size is 16, default sync worker-count is 16, so a all mode task will create more than 32 connection when init task

also, subtask.initUnits init all units first, then close them one by one if that unit is done already, may fail even we don't use those conns.

**Comment by buchuitoudegou** [comment]
I think it's necessary to add a clear workaround first (e.g. recommending users to configure their loader's and syncer's worker count)

**Comment by lance6716** [comment]
> I think it's necessary to add a clear workaround first (e.g. recommending users to configure their loader's and syncer's worker count)

we can query the connection limit of downstream and calculate the total need when precheck, and also give that total need in walkaround
