### ISSUE TITLE
DM may meet `Error 8004: Transaction is too large, size: xxx` when update checkpoint

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#5010]
### What did you do?

https://asktug.com/t/topic/603512

seems when there're many tables and big TableInfo, DM will meet this problem. And don't know why v5.4 is more error-prone then earlier versions.

This problem may auto-resume but in some very bad cases I guess auto-resume will not help. In that case, user can split task to many smaller tasks that contain part of tables to be replicated.

### Versions of the cluster

v5.4.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
I have checked v5.4.0, v5.3.1, v5.3.0 will JSON dump same bytes of a TableInfo

**Comment by GMHDBJD** [comment]
Has the checkpoint flush logic changed in v5.4.0 due to the async flush? Seems no.

**Comment by D3Hunter** [comment]
we can skip insert tableinfo(that's the main cause of large tx) if it's not changed
