### ISSUE TITLE
DM monitoring does not work for TiDB Operator

### ISSUE THREAD

**Issue by KanShiori** [pingcap/tiflow#5056]
### What did you do?

Customers want to deploy dm monitoring by TiDB Operator but failed.

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by Ehco1996** [comment]
will support  this in  https://github.com/pingcap/monitoring like tidb and cdc

**Comment by Ehco1996** [comment]
closed due to  https://github.com/pingcap/monitoring/pull/188 is merged
