### ISSUE TITLE
Nondeterministic DDLs may cause more data inconsistency

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tiflow#5066]
### What did you do?

Use DM-master to replicate DDL `alter table add column x datetime default current_timestamp` to downstream. The downstream/upstream table already has some data in tables.

### What did you expect to see?

The upstream/downstream data can be consistent.

### What did you see instead?

DM upstream/downstream tables x column diff.

### Versions of the cluster

v6.0.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lichunzhu** [comment]
# Root Cause
Some kind of ddls will rewrite data in tables with uncertainty:
`add column default current_timestamp`
# Fix
We can use either way to fix this problem:
1. alert an error immediately and notify users to fix data after this kind of ddl. Like we did for add not fully dropped columns now.
2. fix the data automatically for users.

**Comment by lance6716** [comment]
For MySQL 5.7, AFAIK the undetermistic DDL is DEFAULT CURRENT_TIMESTAMP. MySQL 8.0.13 will have more cases.

https://stackoverflow.com/questions/46134550/mysql-set-default-id-uuid

So we can check if the CURRENT_TIMESTAMP in binlog header is the same as the time of DDL

**Comment by lance6716** [comment]
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_timestamp

> Set the time for this client. This is used to get the original timestamp if you use the binary log to restore rows.

**Comment by D3Hunter** [comment]
> For MySQL 5.7, AFAIK the only undetermistic DDL is DEFAULT CURRENT_TIMESTAMP. MySQL 8.0.13 will have more cases.
> 
> https://stackoverflow.com/questions/46134550/mysql-set-default-id-uuid
> 
> So we can check if the CURRENT_TIMESTAMP in binlog header is the same as the time of DDL

seems header timestamp is the ddl execute time https://dev.mysql.com/doc/internals/en/unsafe-statements.html

https://github.com/mysql/mysql-server/blob/8d8c986e5716e38cb776b627a8eee9e92241b4ce/sql/item_timefunc.cc#L1997

> CURDATE, CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, CURTIME, LOCALTIME, LOCALTIMESTAMP, NOW, UNIX_TIMESTAMP, UTC_DATE, UTC_TIME, UTC_TIMESTAMP (Query_log_event contain timezone and the time when the statement was executed)

we can split `alter table` into 2 ddl, one with explicit timestamp, another with `current_timestamp` to fix the data automatically, but this not work for sharding tables
