### ISSUE TITLE
sink(cdc): cdc panic when use maxwell protocol

### ISSUE THREAD

**Issue by ben1009** [pingcap/tiflow#5069]
### What did you do?

deploy cdc with kafka as sink maxwell protocol 

https://asktug.com/t/topic/603599

### What did you expect to see?

work as expected no panic

### What did you see instead?

![image](https://user-images.githubusercontent.com/1741864/160770378-c41e95c4-4b38-463e-8dbe-8b858ac7d68c.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.4.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.4.0
```

TiCDC version (execute `cdc version`):

```console
v5.4.0
```

**Comment by 3AceShowHand** [comment]
The issue cannot be reproduced.
