### ISSUE TITLE
data inconsistency for json generate column from json_gcol(tidb-mysql-test)

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#5075]
### What did you do?

1. Setup upstream and downstream cluster
2. run follow sql
```SQL
CREATE TABLE t(id INT, j JSON,
               gc INT GENERATED ALWAYS AS (JSON_EXTRACT(j, '$[0]')));
INSERT INTO t(id, j) VALUES (0, '"5"'), (1, '[]'), (2, '[1,2]'), (3, '5');
--error ER_INVALID_JSON_VALUE_FOR_CAST
INSERT INTO t(j) VALUES ('{}');
--error ER_INVALID_JSON_VALUE_FOR_CAST
INSERT INTO t(j) VALUES ('{"a":1}');
--error ER_INVALID_JSON_VALUE_FOR_CAST
INSERT INTO t(j) VALUES ('"abc"');
--error ER_INVALID_JSON_TEXT
INSERT INTO t(j) VALUES ('');
--error ER_INVALID_JSON_TEXT
INSERT INTO t(j) VALUES ('[');
SELECT * FROM t ORDER BY id;
UPDATE t SET j = '[123]';
SELECT * FROM t ORDER BY id;
--error ER_INVALID_JSON_TEXT
UPDATE t SET j = '[';
rename table t to t_3;
```
3. check data consistency

### What did you expect to see?

data consistency

### What did you see instead?

data inconsistency

upstream:
mysql> select * from t_3;
+------+-------+------+
| id   | j     | gc   |
+------+-------+------+
|    0 | [123] |  123 |
|    1 | [123] |  123 |
|    2 | [123] |  123 |
|    3 | [123] |  123 |
+------+-------+------+

downstream:
mysql> select * from t_3;
+------+--------+------+
| id   | j      | gc   |
+------+--------+------+
|    0 | "5"    |    5 |
|    1 | []     | NULL |
|    2 | [1, 2] |    1 |
|    3 | 5      |    5 |
|    0 | [123]  |  123 |
|    1 | [123]  |  123 |
|    2 | [123]  |  123 |
|    3 | [123]  |  123 |
+------+--------+------+

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v6.1.0-alpha-77-gcd0d6b85a
Edition: Community
Git Commit Hash: cd0d6b85a92ad2ee5da735563603b1588c1d1463
Git Branch: master
UTC Build Time: 2022-03-28 11:12:19
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

Upstream TiKV version (execute `tikv-server --version`):

```console
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   4f3e720e1ec2e4e2f8d1ce2c0151a0879b01b885
Git Commit Branch: master
UTC Build Time:    2022-03-28 11:09:04
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
Release Version: v6.0.0-master-dirty
Git Commit Hash: c5333f294240a5195d71ccd4f64802bba292660a
Git Branch: migrate-tidb-mysql-test2
UTC Build Time: 2022-03-30 07:06:11
Go Version: go version go1.18 linux/amd64
Failpoint Build: false
```

**Comment by xiongjiwei** [comment]
it is caused by no primary key, if we specify a primary key, the issue is solved. see https://docs.pingcap.com/tidb/dev/manage-ticdc#replicate-tables-without-a-valid-index
