### ISSUE TITLE
dm checker init too slow when there are a lot of sources

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow#5098]
### Is your feature request related to a problem?

The current DM init checker will be started sequentially according to the number of sources, so the time taken will increase linearly with the number of sources， see [here](https://github.com/pingcap/tiflow/blob/master/dm/checker/checker.go#L129)

In addition, there will be external IO in [here](https://github.com/pingcap/tiflow/blob/69485890b08b25405cd50e8085f271d532e674dd/dm/checker/checker.go#L140) and [here](https://github.com/pingcap/tiflow/blob/69485890b08b25405cd50e8085f271d532e674dd/dm/checker/checker.go#L181), so when there are a lot of sources, init will be unacceptably slow

### Describe the feature you'd like

speed up the init

**Comment by buchuitoudegou** [comment]
just FYI: https://asktug.com/t/topic/663172/3

Is it related to this issue?

**Comment by Ehco1996** [comment]
> just FYI: https://asktug.com/t/topic/663172/3
> 
> Is it related to this issue?

it's from a incall, but i think [this](https://asktug.com/t/topic/663172/3)  is related to this problem
