### ISSUE TITLE
DM: query-status returns empty information when task-mode is full and has no privilege about 'show master status'

### ISSUE THREAD

**Issue by WizardXiao** [pingcap/tiflow#5121]
### What did you do?

1. Task configration like this:
task-mode: full
ignore-checking-items: ["binlog_enable"]
2. There has no privilege about 'show master status'  to upstream mysql
3. Use query-status check the status of task

### What did you expect to see?

query-status can return normal.

### What did you see instead?

query-status returns empty information.

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
5.4.0
```
Upstream MySQL/MariaDB server version:
```console
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
```
How did you deploy DM: tiup or manually?
```console
```
Other interesting information (system version, hardware config, etc):
```console
```

**Comment by WizardXiao** [comment]
`querystatus` will call [updateSourceStatus](https://github.com/pingcap/tiflow/blob/master/dm/dm/worker/source_worker.go#L668) and will query `show master status`，it should not return empty infomation when there has no privilege and only full mode.

**Comment by lance6716** [comment]
introduced in https://github.com/pingcap/tiflow/pull/4049

**Comment by buchuitoudegou** [comment]
Should this [warning](https://github.com/okJiang/ticdc/blob/ea9bfc72bd93ca5302d7a329e82f371e213c06bf/dm/dm/worker/source_worker.go#L646) be returned?

**Comment by lance6716** [comment]
> Should this [warning](https://github.com/okJiang/ticdc/blob/ea9bfc72bd93ca5302d7a329e82f371e213c06bf/dm/dm/worker/source_worker.go#L646) be returned?

I think we don't need it.
