### ISSUE TITLE
changefeed status don't become error when broker unavaible

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#5131]
### What did you do?

- Creating a changefeed with kafka sink
- Run workload for 1 hour
- Stop broker and zookeeper

### What did you expect to see?

Changefeed status becomes to error and report error msg.

### What did you see instead?

After 10+ hours, changefeed status is still normal, only cdc.log has error msg.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
5.3.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
5.3.0
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
5.3.0
```

**Comment by CharlesCheung96** [comment]
This issue has been fixed by this [pr](
https://github.com/pingcap/tiflow/pull/4359/files#diff-19b009ba5782f7c73c79ef7f1daa069c1ab254b7837bbc6be44d04bfa6621d93R228).

**Comment by Tammyxia** [comment]
Yes, it can be closed.
