### ISSUE TITLE
starting validator makes dmworker panic

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tiflow#5184]
### What did you do?

1. start task with validator on
2. `dmctl query-status`

### What did you expect to see?

print the status of the worker

### What did you see instead?

worker panicked and exited

### Versions of the cluster

commit: bca4b480792536d2548fc3a02c41ebd93f86e25f

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by buchuitoudegou** [comment]
root cause: before starting validator, validator's checkpoint would try persisting the status of all the workers while all the workers are still `nil`.

I'll fix it in https://github.com/pingcap/tiflow/pull/5181

**Comment by D3Hunter** [comment]
validator feature is not GA and it's hidden, change to moderate
