### ISSUE TITLE
after filtered some DDL event and manually fix downstream, tracker can't track table structure

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#5272]
### What did you do?

task

```
...
block-allow-list:        # 上游数据库实例匹配的表的 block-allow-list 过滤规则集，如果 DM 版本 <= v2.0.0-beta.2 则使用 black-white-list
  bw-rule-1:             # 黑白名单配置的名称
    do-dbs: ["test"] # 迁移哪些库
...
filters:
  filter-rule-1:
    schema-pattern: "test"
    table-pattern: "test1"
    events: ["all ddl"]
    action: Ignore
```

1. create `test.test1` in upstream
2. start-task --remove-meta
3. `alter table test1 add column c4 int;` in upstream
4. `create table test2 (c int primary key);` in upstream or wait 30s, to flush checkpoints
5. `insert into test1`. Now task will report error because downstream doesn't have column `c4`
6. `alter table test1 add column c4 int;` in downstream
7. resume-task

### What did you expect to see?

task goes on

### What did you see instead?

gen insert sqls failed, sourceTable: `test`.`test1`, targetTable: `test`.`test1`: Column count doesn't match value count: 3 (columns) vs 4 (values)",

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

at least v5.4.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
root cause:

when a DDL is filtered by binlog event filter, we forget to save checkpoint for the table

**Comment by D3Hunter** [comment]
cannot reproduce in current master, and there is another bug: after auto-resume on first error, the dml is skipped too, and global point is larger than table point:
```
+------------+-----------+----------+------------------+------------+
| id         | cp_schema | cp_table | binlog_name      | binlog_pos |
+------------+-----------+----------+------------------+------------+
| mysql-3306 |           |          | mysql-bin.000001 |        766 |
| mysql-3306 | test      | test2    | mysql-bin.000001 |        505 |
| mysql-3306 | test      | test1    | mysql-bin.000001 |        735 |
+------------+-----------+----------+------------------+------------+
```

**Comment by D3Hunter** [comment]
5.3 doesn't has this issue, can auto recover

**Comment by lance6716** [comment]
fixed by https://github.com/pingcap/tiflow/pull/5273
