### ISSUE TITLE
after print "rollback checkpoint" in log, unistore folder size grows

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#5344]
### What did you do?

https://github.com/pingcap/tiflow/blob/630896740566eb0f7a81062506e92177e755f404/dm/syncer/checkpoint.go#L715-L727

mock the logic of rollback checkpoint

```
	for i := 0; i < 10000; i++ {
		err = tracker.DropTable(tbl)
		c.Assert(err, IsNil)

		err = tracker.CreateSchemaIfNotExists("test")
		c.Assert(err, IsNil)
		err = tracker.CreateTableIfNotExists(tbl, oriTi)
		c.Assert(err, IsNil)
	}
```

during the test

```
# lance @ LAPTOP-AK9BOS6J in ~/go/src/github.com/pingcap/tiflow on git:630896740
 x [19:38:27]
$ du -h /tmp/tidb-unistore-temp944770732
16M     /tmp/tidb-unistore-temp944770732/kv
16M     /tmp/tidb-unistore-temp944770732

# lance @ LAPTOP-AK9BOS6J in ~/go/src/github.com/pingcap/tiflow on git:630896740
 x [19:38:42]
$ du -h /tmp/tidb-unistore-temp944770732
104M    /tmp/tidb-unistore-temp944770732/kv
104M    /tmp/tidb-unistore-temp944770732

# lance @ LAPTOP-AK9BOS6J in ~/go/src/github.com/pingcap/tiflow on git:630896740
 x [19:40:22]
$ du -h /tmp/tidb-unistore-temp944770732
195M    /tmp/tidb-unistore-temp944770732/kv
195M    /tmp/tidb-unistore-temp944770732
```

So if the task is resumed for many times (which means the task has a resumable error), the size of unistore folder will grow.

### What did you expect to see?

the size of `/tmp/tidb-unistore-temp944770732` has an upper-bound

### Versions of the cluster

v5.3.1

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
after some discussion, this space may be occupied by DDL history job and we have no way to clean it. Maybe the fix that we close schema tracker and remove the unistore folder after the task is paused.

Or we think about #5334

**Comment by GMHDBJD** [comment]
> Maybe the fix is that we close schema tracker

looks good to me

**Comment by lance6716** [comment]
> after some discussion, this space may be occupied by DDL history job and we have no way to clean it. Maybe the fix is that we close schema tracker and remove the unistore folder after the task is paused.
> 
> Or we think about #5334

just created 500 tables in a task (ADMIN SHOW DDL JOBS has 535 rows), the disk usage is 257M...

**Comment by lance6716** [comment]
> > Maybe the fix is that we close schema tracker
> 
> looks good to me

Just found that operate-schema should let DM-master directly modify the table checkpoint after this 😂
