### ISSUE TITLE
Failed to create changefeed with pulsar sink "[CDC:ErrMQSinkUnknownProtocol]unknown '' protocol for Message Queue sink"

### ISSUE THREAD

**Issue by hashbone** [pingcap/tiflow#5371]
### What did you do?

Try to create changefeed with Pulsar sink ( (apache pulsar v2.10.0)) by the following command:

`tiup cdc cli changefeed create --pd="http://192.168.255.203:2379" --sink-uri="pulsar://192.168.255.204:6650/public/default/cdc?connectionTimeout=2s"`

### What did you expect to see?

changefeed with pulsar sink that should be successfully created and work without problem.

### What did you see instead?

error message below after executed the above command

`[CDC:ErrKafkaInvalidConfig]kafka config invalid: [CDC:ErrMQSinkUnknownProtocol]unknown '' protocol for Message Queue sink`

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:33:28
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

Upstream TiKV version (execute `tikv-server --version`):

```console
TiKV
Release Version:   6.0.0
Edition:           Community
Git Commit Hash:   2b4f7d57af9ca3e21bc07b91a9cfc466ed87734f
Git Commit Branch: heads/refs/tags/v6.0.0
UTC Build Time:    2022-04-01 06:54:28
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
Release Version: v6.0.0
Git Commit Hash: 2f363f653a49fc557ebaab1afa7a47f900fbfc8f
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:05:34
Go Version: go version go1.18 linux/amd64
Failpoint Build: false
```

**Comment by hi-rustin** [comment]
> tiup cdc cli changefeed create --pd="http://192.168.255.203:2379" --sink-uri="pulsar://192.168.255.204:6650/public/default/cdc?connectionTimeout=2s

try: tiup cdc cli changefeed create --pd="http://192.168.255.203:2379" --sink-uri="pulsar://192.168.255.204:6650/public/default/cdc?connectionTimeout=2s&protocol=open-protocol

**Comment by hashbone** [comment]
> > tiup cdc cli changefeed create --pd="http://192.168.255.203:2379" --sink-uri="pulsar://192.168.255.204:6650/public/default/cdc?connectionTimeout=2s
> 
> try: tiup cdc cli changefeed create --pd="http://192.168.255.203:2379" --sink-uri="pulsar://192.168.255.204:6650/public/default/cdc?connectionTimeout=2s&protocol=open-protocol

It worked. Thanks.
And according to the official document of ticdc , it seems that the parameter of "protocol" is optional and only mentioned at kafka sink section. Wonder if there is a "default" option without the "protocol" setting.
