### ISSUE TITLE
DM-worker will skip MariaDB events by table checkpoint when gtid is enabled

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tiflow#5394]
### What did you do?

1. Use DM-worker to replicate some MariaDB data. GTID is enabled.
2. Restart DM-worker.

### What did you expect to see?

DM-worker can replicate data completely and correctly(at least once).

### What did you see instead?

DM-worker skips some row events data after a restart.

### Versions of the cluster

only in the master version, not included in any released versions.
https://github.com/pingcap/tiflow/commit/858613b7c26823d26d195840ec2c34833a75119f

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lichunzhu** [comment]
## Root cause
This problem is introduced by https://github.com/pingcap/tiflow/pull/5198. 

||Before|After|
|:--:|:--:|:--:|
|When do we save table point| Every time we receive a rows event | Position-based: Every time we receive a rows event<br> GTID-based: Cache tables in this transaction and save table point when we met an XID event |
|When do we skip table event by table point| Position-based: currentLoc <= tablePoint<br> GTID-based: currentLoc < tablePoint| currentLoc <= tablePoint |

### MySQL
For MySQL, there is a BEGIN query event before every DML transaction. For example:
```sql
| mysql-bin.000001 |  343 | Gtid           |    123421 |         420 | SET @@SESSION.GTID_NEXT= '1c82f414-c3a9-11ec-ae6f-0242ac110003:2' |
| mysql-bin.000001 |  420 | Query          |    123421 |         544 | use `gtid`; create table t1 (id int PRIMARY KEY) /* xid=38014 */  |
| mysql-bin.000001 |  544 | Gtid           |    123421 |         623 | SET @@SESSION.GTID_NEXT= '1c82f414-c3a9-11ec-ae6f-0242ac110003:3' |
| mysql-bin.000001 |  623 | Query          |    123421 |         698 | BEGIN                                                             |
| mysql-bin.000001 |  698 | Table_map      |    123421 |         746 | table_id: 1337 (gtid.t1)                                          |
| mysql-bin.000001 |  746 | Write_rows     |    123421 |         786 | table_id: 1337 flags: STMT_END_F                                  |
```
We will make `ec.lastestLocation` contain the current transaction's GTID set at https://github.com/pingcap/tiflow/blob/858613b7c26823d26d195840ec2c34833a75119f/dm/syncer/syncer.go#L2646
when we met this `BEGIN` query event.
When we handle the rows event, `ec.currentLocation` will be "newer" than table point.
https://github.com/pingcap/tiflow/blob/858613b7c26823d26d195840ec2c34833a75119f/dm/syncer/syncer.go#L2414-L2419

### MariaDB
For MariaDB, there is **NO** BEGIN query event before every DML transaction.
```sql
| mysql-bin.000002 | 457 | Gtid              |         1 |         499 | GTID 0-1-2                                                         |
| mysql-bin.000002 | 499 | Query             |         1 |         608 | use `test`; create table t(a int primary key)                      |
| mysql-bin.000002 | 608 | Gtid              |         1 |         650 | BEGIN GTID 0-1-3                                                   |
| mysql-bin.000002 | 650 | Annotate_rows     |         1 |         705 | insert into t values (1),(2),(3)                                   |
| mysql-bin.000002 | 705 | Table_map         |         1 |         749 | table_id: 18 (test.t)                                              |
| mysql-bin.000002 | 749 | Write_rows_v1     |         1 |         797 | table_id: 18 flags: STMT_END_F                                     |
| mysql-bin.000002 | 797 | Xid               |         1 |         828 | COMMIT /* xid=15 */                                                |
```
So `ec.lastestLocation` won't update when we receive a new DML transaction.  When we replicate transaction `0-1-3`, then we will have `ec.lastestLocation=ec.currentLocation=0-1-2`. If we didn't replicate this transaction before and quited after `0-1-2`, tablePoint would be `0-1-2`. So this transaction will be considered as obsolete and won't be replicated.

**Comment by lance6716** [comment]
> | mysql-bin.000002 | 608 | Gtid              |         1 |         650 | BEGIN GTID 0-1-3                                                   |

is this the output of `mysqlbinlog`? very readable output.

I also write a similar logic in https://github.com/pingcap/tiflow/blob/858613b7c26823d26d195840ec2c34833a75119f/dm/syncer/binlog_locations.go#L196 , if our logic has some unknown problem please ping me
