### ISSUE TITLE
Unreasonable of the Sink interface

### ISSUE THREAD

**Issue by lonng** [pingcap/tiflow#5425]
### What did you do?

I think the `Sink` interface is unreasonable and the definition of the methods is inconsistent.

```go
type Sink interface {
	// Init initializes the sink resource
	// when the sink is added, this function will be called
	// init resource or clean up the old values in this function
	Init(tableID model.TableID) error

	// EmitRowChangedEvents sends Row Changed Event to Sink
	// EmitRowChangedEvents may write rows to downstream directly;
	//
	// EmitRowChangedEvents is thread-safety.
	// FIXME: some sink implementation is not thread-safety, but they should be.
	EmitRowChangedEvents(ctx context.Context, rows ...*model.RowChangedEvent) error

	// TryEmitRowChangedEvents is thread-safety and non-blocking.
	TryEmitRowChangedEvents(ctx context.Context, rows ...*model.RowChangedEvent) (bool, error)

	// EmitDDLEvent sends DDL Event to Sink
	// EmitDDLEvent should execute DDL to downstream synchronously
	//
	// EmitDDLEvent is thread-safety.
	// FIXME: some sink implementation is not thread-safety, but they should be.
	EmitDDLEvent(ctx context.Context, ddl *model.DDLEvent) error

	// FlushRowChangedEvents flushes each row which of commitTs less than or
	// equal to `resolvedTs` into downstream.
	// TiCDC guarantees that all the Events whose commitTs is less than or
	// equal to `resolvedTs` are sent to Sink through `EmitRowChangedEvents`
	//
	// FlushRowChangedEvents is thread-safety.
	// FIXME: some sink implementation is not thread-safety, but they should be.
	FlushRowChangedEvents(ctx context.Context, tableID model.TableID, resolvedTs uint64) (uint64, error)

	// EmitCheckpointTs sends CheckpointTs to Sink.
	// TiCDC guarantees that all Events **in the cluster** which of commitTs
	// less than or equal `checkpointTs` are sent to downstream successfully.
	//
	// EmitCheckpointTs is thread-safety.
	// FIXME: some sink implementation is not thread-safety, but they should be.
	EmitCheckpointTs(ctx context.Context, ts uint64, tables []model.TableName) error

	// Close closes the Sink.
	//
	// Close is thread-safe and idempotent.
	Close(ctx context.Context) error

	// Barrier is a synchronous function to wait all events to be flushed
	// in underlying sink.
	// Note once Barrier is called, the resolved ts won't be pushed until
	// the Barrier call returns.
	//
	// Barrier is thread-safe.
	Barrier(ctx context.Context, tableID model.TableID) error
}
```

1. The `Init` method makes me confuse, I checked the source code and I think `AddTable` is more reasonable because the `Init` is not used to initialize the `Sink` resource.
2. All the others methods use `model.TableID` but the `EmitCheckpointTs` method uses `model.TableName`.

### What did you see instead?

See above code.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by hi-rustin** [comment]
> 1. The `Init` method makes me confuse, I checked the source code and I think `AddTable` is more reasonable because the `Init` is not used to initialize the `Sink` resource.

Makes sense to me. I'll land it next week.


> 2\. All the others methods use `model.TableID` but the `EmitCheckpointTs` method uses `model.TableName`.

This is because when we broadcast checkpoint ts for a table, we need to find the corresponding topic based on the table name, and when the renaming of a table occurs, the table id may not be enough to handle the situation, or the sink needs to look up the corresponding name separately. Now it is mainly called by ddlSink in Owner, using the name may be a simpler and more intuitive approach.

**Comment by lonng** [comment]
@hi-rustin thanks for your reply, and it's better to add some comments for that method if it's signature inconsistent with others.
