### ISSUE TITLE
Revert prometheus client_golang from  from v1.12.2 to v1.11.0

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#5494]
### What did you do?

When merge engine to tiflow repo, client_golang(v1.12.2) will introduce some incompatible change to the go collector and some metric name.

**Detail**
ref : https://github.com/prometheus/client_golang/releases
[CHANGE] ⚠️ Change in collectors.NewGoCollector metrics: Reverting addition of new ~80 runtime metrics by default. You can enable this back with GoRuntimeMetricsCollection option or GoRuntimeMemStatsCollection | GoRuntimeMetricsCollection for smooth transition.
[BUGFIX] Fixed the bug that causes generated histogram metric names to end with _total. ⚠️ This changes 3 metric names in the new Go collector that was reverted from default in this release.
go_gc_heap_allocs_by_size_bytes_total -> go_gc_heap_allocs_by_size_bytes,
go_gc_heap_frees_by_size_bytes_total -> go_gc_heap_allocs_by_size_bytes
go_gc_pauses_seconds_total -> go_gc_pauses_seconds.

### What did you see instead?

some go collector metric lost

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by Ehco1996** [comment]
reopen because https://github.com/pingcap/tiflow/pull/5393 upgrade promtheus_client again
