### ISSUE TITLE
seems grpc name has collision

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#5555]
### What did you do?

2022/05/24 03:25:35 proto: duplicate proto type registered: pb.WorkerInfo

https://github.com/pingcap/tiflow/runs/6566411247?check_suite_focus=true

### What did you expect to see?

no error

### What did you see instead?

2022/05/24 03:25:35 proto: duplicate proto type registered: pb.WorkerInfo

### Versions of the cluster

master

**Comment by amyangfei** [comment]
Yep,
https://github.com/pingcap/tiflow/blob/12317f4139996245d238fcaff7c15d18308607da/dm/dm/proto/dmmaster.proto#L349
https://github.com/pingcap/tiflow/blob/12317f4139996245d238fcaff7c15d18308607da/engine/proto/master.proto#L92

`WorkerInfo` defined in dataflow engine should be renamed.
