### ISSUE TITLE
TiKV OOM continually  at intervals of 30-40 min, upstream has 1TB historical data

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#5560]
### What did you do?

- Testbed: 3 TiKV, 8C 16GB, 1GB region size (dynamic region); 3 TiCDC, 8C 16GB, 1 changefeed mysql sink SSD
- Stop changefeed, start workload: sysbench oltp_insert prepare --tables=256 --table-size=5000000000 --threads=256
- When PD current storage size =1TB, resume changefeed, meanwhile, sysbench prepare is still alive.

### What did you see instead?

After changefeed resumed for about 5 hours, TiKV start to OOM, and continually at intervals of 30-40 min till changefeed stopped. When changefeed stopped (observed for 3 hours), TiKV never OOM again.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
6.1.0-nightly 2022-05-20 
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   1fb8980ccab9ff40c1adc206df52952dab8e8ad8
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:    2022-05-20 06:14:46
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
6.1.0-nightly 2022-05-20 
```

**Comment by Tammyxia** [comment]
This issue occurred in x86 and arm testbed with the same resource config (Memory size of TiKV and TiCDC both are 16GB), what's more, arm testbed has CDC OOM...

**Comment by Tammyxia** [comment]
Verified with this different config: all 3 TiKV have 32GB

**Comment by overvenus** [comment]
> Verified with this different config, and got PASS result:
> 
> 1. all 3 TiKV have 32GB
> 2. When changefeed resumed for 1 hour, stop workload.
>    PD current storage size = 2.4TB, cdc takes 29 hours from starting resume to completing sync.

Checked metrics offline, for the good case, I find TiKV memory usage is almost the same with or without TiCDC.

TiCDC was started around 00:50
![image](https://user-images.githubusercontent.com/2150711/170463226-d5ece459-468f-48ad-b983-e001fc6dece7.png)

**Comment by nongfushanquan** [comment]
the workload out of the range of the cdc
