### ISSUE TITLE
cdc goroutines become crazy when initializing a capture with lots of regions and tikv.cdc.min-ts-interval = 200ms

### ISSUE THREAD

**Issue by hicqu** [pingcap/tiflow#5610]
### What did you do?

Create a capture on 16 MySQL tables, 131K regions totally with
* tikv.cdc.min-ts-interval = 200ms
* tikv.cdc.min-ts-interval = 1s

### What did you expect to see?

Both 2 operations can be finished quickly. With `tikv.cdc.min-ts-interval = 1s` it's expected:
<img width="326" alt="图片" src="https://user-images.githubusercontent.com/8407317/170626613-5d801bbc-a31f-469d-8cc2-c3f25ee17c91.png">

### What did you see instead?

However with `tikv.cdc.min-ts-interval = 200ms` the capture creating can never finished, and cpu usage is *very high*:
<img width="331" alt="图片" src="https://user-images.githubusercontent.com/8407317/170626862-266c381b-7442-4b1a-be51-bb74c5038d2c.png">
<img width="659" alt="图片" src="https://user-images.githubusercontent.com/8407317/170626933-3845c067-c626-444e-9552-35498868e6e6.png">

And here is a 30s CPU profile:
<img width="1316" alt="图片" src="https://user-images.githubusercontent.com/8407317/170627006-3a1ac684-0c0d-4dbf-80b0-25d38e2ef036.png">

We can see the CPU time is about 480s, which means all 16C are very busy on `runtime.selectgo`.

### Versions of the cluster

All components are nightly.
Go version is 1.18.1.

**Comment by MimeLyc** [comment]
update
