### ISSUE TITLE
An enhancement of MySQL sink to turn off safe-mode automatically

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#5611]
### Is your feature request related to a problem?

By default, TiCDC translates upstream `INSERT/UPDATE` into `REPLACE` (the safe-mode) which is slow and may cause deadlock in MySQL.

  

### Describe the feature you'd like

When TiCDC replicates a table, it can turn off safe-mode automatically when there is no duplicated events that has been replicated before.

TiCDC may output duplicated events when a table is scheduled to another node. The table have to replicate start from the global checkpoint (a checkpoint of the slowest tables) which it may has already replicated.

So turn off safe-mode, it has to know a ts that it has **not** replicated before. The trick is simple, it takes the latest ts from PD after it starts replicating, so any txn that is greater than the tso, it must have never replicated before. after the table see such txn, it can safely turn off safe-mode.

**Comment by lance6716** [comment]
BTW, please take a look at this library https://github.com/pingcap/tiflow/blob/d957fe87d6cca06605a6dcfec8905b8202d242d4/pkg/sqlmodel/row_change.go#L347-L361

Hope we can let DM and CDC use same implementation
