### ISSUE TITLE
when the hotspot region is splitting constantly, data cannot be synchronized to downstream

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tiflow#5612]
### What did you do?

1. create a cluster on dbaas
2. create a changefeed on this cluster(cdc to mysql/kafka function)
3. Load data to the cluster(use go-tpc load tool)
4. Observation data synchronization

### What did you expect to see?

Data is synchronized to downstream normally

### What did you see instead?

data cannot be synchronized to downstream，the lag increases constantly
![LcxSYEnpIH](https://user-images.githubusercontent.com/81375082/170646639-34b1c893-0f44-4baf-a279-03d4598a5429.jpg)
![Ucp67uOssj](https://user-images.githubusercontent.com/81375082/170646706-43f982d6-7b85-48c3-b3a3-abde06bbf13b.jpg)

### Versions of the cluster

tidb: 5.4.1
ticdc:5.4.1

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by asddongmen** [comment]
Close it since it's stale.
