### ISSUE TITLE
command gc-ttl does not work as expected

### ISSUE THREAD

**Issue by truong-hua** [pingcap/tiflow#5647]
### What did you do?

Set gc-ttl via command like --gc-ttl to 259200 (3 days). But after changefeed interuption for some hours, the changefeed can not resume due to `CDC:ErrSnapshotLostByGC`

### What did you expect to see?

Changefeed should be able to resume or any error different from ErrSnapshotLostByGC and gc-ttl is working properly

### What did you see instead?

Changefeed is interupted and can not be resumed
![image](https://user-images.githubusercontent.com/2027923/170953520-8d34ab0f-b7ad-4349-be5d-4d486c76f366.png)

According to the picture above, the last safe point is `433559400984084480` which equivalents to `system:  2022-05-30 08:04:21.42 +0000 UTC` and the changefeed is interrupted at `433555730731892746` (system:  2022-05-30 04:11:00.519 +0000 UTC). And now is `Mon May 30 08:46:11 UTC 2022`.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v5.3.1
Edition: Community
Git Commit Hash: 459917c6f83df155edcc03f6ebde24942ff73b0e
Git Branch: heads/refs/tags/v5.3.1
UTC Build Time: 2022-03-02 08:35:22
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

Upstream TiKV version (execute `tikv-server --version`):

```console
TiKV Control (tikv-ctl) 
Release Version:   5.3.1
Edition:           Community
Git Commit Hash:   ecc2549ed63fc21f1f6e11f1b85f19c2465234a5
Git Commit Branch: heads/refs/tags/v5.3.1
UTC Build Time:    2022-03-03 10:10:50
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
Release Version: v5.3.1
Git Commit Hash: 630896740566eb0f7a81062506e92177e755f404
Git Branch: heads/refs/tags/v5.3.1
UTC Build Time: 2022-03-02 02:05:42
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false
```

**Comment by truong-hua** [comment]
Even the default gc-ttl which is 24h should not raise that exception :(

**Comment by asddongmen** [comment]
> Even the default gc-ttl which is 24h should not raise that exception :(

Could you give more infomation about what casue this changefeed interruption? And the what is the **state** of this changefeed?

**Comment by truong-hua** [comment]
> > Even the default gc-ttl which is 24h should not raise that exception :(
> 
> Could you give more infomation about what casue this changefeed interruption? And the what is the **state** of this changefeed?

It's on the screenshot above. The state is `failed` and error message is `CDC:ErrSnapshotLostByGC`.

Is it possible to check the gc-ttl config or update it directly via pd-ctrl?

**Comment by asddongmen** [comment]
> > > Even the default gc-ttl which is 24h should not raise that exception :(
> > 
> > 
> > Could you give more infomation about what casue this changefeed interruption? And the what is the **state** of this changefeed?
> 
> It's on the screenshot above. The state is `failed` and error message is `CDC:ErrSnapshotLostByGC`.
> 
> Is it possible to check the gc-ttl config or update it directly via pd-ctrl?

1. If a changefeed is interrupted by a `CDC:ErrSnapshotLostByGC` error and become `failed`, it is expected that it can't resume again.  refer to: [What is the complete behavior of TiCDC garbage collection (GC) safepoint?](https://docs.pingcap.com/tidb/stable/troubleshoot-ticdc#:~:text=If%20the%20replication%20task%20is%20suspended%20longer%20than%20the%20time%20specified%20by%20gc%2Dttl%2C%20the%20replication%20task%20enters%20the%20failed%20status%20and%20cannot%20be%20resumed.%20The%20PD%20corresponding%20service%20GC%20safepoint%20will%20continue.)  and [State transfer of replication tasks](https://docs.pingcap.com/tidb/stable/manage-ticdc#:~:text=tasks%20(changefeed)-,State%20transfer%20of%20replication%20tasks,-The%20state%20of)
2. You can use `pd-ctl service-gc-safepoint` to show all `gc safepoint` but can not update cdc `gc-ttl`, `gc-ttl` can only be config through tiup or command line when you start a cdc server . Refer to: [Modify TiCDC configuration using TiUP](https://docs.pingcap.com/tidb/v5.3/manage-ticdc#modify-ticdc-configuration-using-tiup) and [Description of TiCDC cdc server command-line parameters
](https://docs.pingcap.com/tidb/v5.3/deploy-ticdc#description-of-ticdc-cdc-server-command-line-parameters)

**Comment by asddongmen** [comment]
> > > Even the default gc-ttl which is 24h should not raise that exception :(
> > 
> > 
> > Could you give more infomation about what casue this changefeed interruption? And the what is the **state** of this changefeed?
> 
> It's on the screenshot above. The state is `failed` and error message is `CDC:ErrSnapshotLostByGC`.
> 
> Is it possible to check the gc-ttl config or update it directly via pd-ctrl?

Sorry, I asked a wrong question, the information I wanna know is the state of this changefeed before it beome `failed`. Is there was any error occur before it failed?

**Comment by asddongmen** [comment]
I have checked the code logic and did some tests but have not found any problem yet, I will do more investigation in next couple of days.

**Comment by asddongmen** [comment]
This problem may casue by:
 1. This changefeed encoutered a error, and cdc automatically try to resume it.
 2. If after `defaultBackoffMaxElapsedTime` it still can not  be resumed, cdc will set this changefeed state to `failed`.
 3. We would skip a changefeed in `gcSafepoint` calculation, so this changefeed will encouter a `CDC:ErrSnapshotLostByGC` after a while.

**Comment by asddongmen** [comment]
It can be fix in https://github.com/pingcap/tiflow/pull/6020

**Comment by zhaoxinyu** [comment]
This is fixed by #6020. And i will cherry-pick it back to lower versions.

**Comment by truong-hua** [comment]
No no no, sorry for late @asddongmen, the problem here is that you see in my starting CDC cli? I have a --gc-ttl=259200.

But according to

```
According to the picture above, the last safe point is 433559400984084480 which equivalents to system: 2022-05-30 08:04:21.42 +0000 UTC and the changefeed is interrupted at 433555730731892746 (system: 2022-05-30 04:11:00.519 +0000 UTC). And now is Mon May 30 08:46:11 UTC 2022
```
The last safe point is just 40 mins ago from that current system time, which is not true with --gc-ttl=259200

**Comment by truong-hua** [comment]
And to be more clear, I'm ok to pause and resume the changefeed if it goes into the `failed` state. But I can not resume it because the GC checkpoint has been wrongly passed (does not respect --gc-ttl). My expectation is that I can pause and resume the changefeed and GC checkpoint has to respect the configuration in --gc-ttl=259200 (7 days)

**Comment by truong-hua** [comment]
Thank @zhaoxinyu @asddongmen , it looks promising to my problem. Willing to test it when it's cherry-picked back to 5.3 (we are using 5.3.1) and will let you know the result later.
