### ISSUE TITLE
When the upstream cluster has only databases but no data, an error will be reported when the CDC synchronizes data in this database to the secondary cluster

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tiflow#5665]
### What did you do?

1. create primary cluster on dbaas
2. create a database zm2 in primary cluster, do not create table and insert data
3. create a secondary cluster on dbass
4. create tables in the database zm2 of the primary cluster

### What did you expect to see?

The synchronization between the primary and secondary clusters is normal

### What did you see instead?

an error will be reported when the CDC synchronizes data in this database to the secondary cluster
![origin_img_v2_4e7d582d-d79c-4e4a-8823-91a23c90d13g](https://user-images.githubusercontent.com/81375082/171076150-bade01e8-a681-40b6-a222-2268aa13f2e2.jpg)

### Versions of the cluster

ticdc v 5.4.1

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by asddongmen** [comment]
close it since its stale
