### ISSUE TITLE
Support configurable BackoffMaxElapsedTime

### ISSUE THREAD

**Issue by pcqz** [pingcap/tiflow#5684]
### Is your feature request related to a problem?

TiCDC replication task enters failed status when kafka has been down more than MaxElapsedTime (90min). The failed status cannot be resumed, and cannot continue to affect the progress of the GC safepoint. Although gc-ttl is in the valid period, the data after checkpoint may be cleaned when tidb_gc_life_time variable remains default.

### Describe the feature you'd like

Make BackoffMaxElapsedTime a TICDC server configuration.

### Describe alternatives you've considered

Increase gc_litime_time temporarily when kafka is unavailable.

**Comment by leoppro** [comment]
MaxElapsedTime is not necessary. We should let ticdc keep waiting and retrying

**Comment by jansu-dev** [comment]
> 

mysql PR is to fix this issue --> https://github.com/pingcap/tiflow/pull/6009. Could you help me to pass or close the PR,although it is not necessary.

**Comment by zhaoxinyu** [comment]
> mysql PR is to fix this issue --> #6009. Could you help me to pass or close the PR,although it is not necessary.

I will fix the issue in PR https://github.com/pingcap/tiflow/pull/6020, the `defaultMaxElapsedTime` is removed.
