### ISSUE TITLE
ListTopic may cause performance degradation when creating large amount of topics

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#5694]
### What did you do?

1. prepare 10K tables using sysbench prepare
2. create a changefeed and use a topic expression to dispatch each table to its corresponding topic.
3. execute sysbench run, 10K topics will be created.

### What did you expect to see?

- The topic metadata fetching process should be as fast as possible. 
- Only produce MQ messages to the topics which can be safely written to.

### What did you see instead?

The topic list operation is extremely slow when the topic number increases. As as result, messages cannot be timely sinked to downstream Kafka. And sometimes the following error occurs:
```
kafka server: Request was for a topic or partition that does not exist on this broker.
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
v6.1
```

**Comment by zhaoxinyu** [comment]
/affects-6.1

**Comment by 3AceShowHand** [comment]
I think this is not a bug, since it does not affect the correctness.

This should be a performance issue in a rare sceneario (a huge number of topics).
