### ISSUE TITLE
[engine] Refactor and adjust APIs in engine/framework

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#5853]
- [x] Rename `lib` to `framework` @liuzix  #5826 
- [ ] Rename `BaseMaster`, `BaseWorker` and `BaseJobMaster` to appropriate names. @gozssky P1
- [ ] Investigate a solution for splitting the bases into `MasterDriver`, `WorkerDriver`, etc., and `MasterAPIs`, `WorkerAPIs`, etc. @liuzix P1
- [x] #5926 @maxshuang P0
- [ ] #5927 @maxshuang P0
- [x] #5925 @gozssky P0
- [x] Refactor `ExitController` to support exiting after `Init` fails. @liuzix P0

**Comment by maxshuang** [comment]
@liuzix  name after the item means owner? Right?

**Comment by liuzix** [comment]
> @liuzix name after the item means owner? Right?

Yes
