### ISSUE TITLE
sysbench 1TB historical data, replication performance is pretty slow 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#5915]
### What did you do?

- Create a changefeed, sink=mysql, pause it.
- Workload: "sysbench --db-driver=mysql --mysql-host=xxx  --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=128 --table-size=30000000 --time=18000 --debug=true --threads=128  oltp_insert prepare"
-  Resume changefeed
- Workload: "sysbench --db-driver=mysql --mysql-host=xxx  --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=128 --table-size=30000000 --time=18000 --debug=true --threads=128  oltp_insert run"

### What did you see instead?

- Changefeed cli resume  happened  in 6-16 20:28, during the next 14 hours, replication performance is really too slow:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/78345569/174269973-6a409719-a9c9-4819-be62-5f0d02559526.png">

- 
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/78345569/174271036-062e991c-4115-4013-9f8e-15cd19280925.png">

- Log: https://tcms.pingcap.net/dashboard/executions/plan/845391

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
TiKV
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   11b5d4c3d6ca740cc0bf272691fd15ec94345cd9
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:    2022-06-15 11:04:15
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
# /cdc version
Release Version: v6.1.0-nightly
Git Commit Hash: 7d755affaff9347eda15949155cb83bcdb3d6429
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-06-15 11:04:58
Go Version: go version go1.18.2 linux/amd64
Failpoint Build: false
```

**Comment by hicqu** [comment]
![图片](https://user-images.githubusercontent.com/8407317/174273690-37abe358-7dc0-470c-af46-3e6bd4f7f0f0.png)

Puller writes PebbleDB too slow so that upstream incremental scans can't be finished on time. After incremental scans are finally finished, resolved timestamp can be updated and then cdc flushes lots of rows to the downstream sink.
