### ISSUE TITLE
Add `StopImpl` as a callback

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#5925]
The original requirement is from DM, when a DM job is paused, the business logic doesn't know when to delete business metadata(such as DM checkpoint). The business requires a `StopImpl` callback, which can be triggered when a job master is stopped(the same as paused).

Besides the current implementation of job pause has a drawback, it relies on the availability of p2p message channel. Supposing the job master runs into an abnormal status, which means it can't handle `OnJobManagerMessage` properly or it always exits before `OnJobManagerMessage` finishes, the job master can't be paused.

**Comment by maxshuang** [comment]
close by pr https://github.com/pingcap/tiflow/pull/6852
