### ISSUE TITLE
DM-worker should not retry on long time ddls directly

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tiflow#5962]
### What did you do?

Use DM-worker to replicate some long time costing ddls to downstream TiDB. For example, adding index ddls.

### What did you expect to see?

DM-worker can replicate ddls successfully.

### What did you see instead?

DM-worker fails because of i/o timeout and keeps retrying to replicate these ddls again.

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lichunzhu** [comment]
## Root Cause
When DM executes some time-costing ddls, especially for adding index, dm-worker may fail to get result because it won't return any result until it succeeds. If this time cost is larger than syncer's `read-timeout`, dm-worker will fail and try to execute ddl again. This will make the situation even worse.
## Workaround
For these long time costing ddls, we can use a special connection to execute them and keep watching the result asynchronously through `show ddl jobs`.

**Comment by lance6716** [comment]
duplicated with https://github.com/pingcap/tiflow/issues/4689
