### ISSUE TITLE
executor manager stop hangs the whole server master

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#6013]
### What did you do?

chaos test failure case: https://github.com/pingcap/tiflow/runs/7013417892?check_suite_focus=true

detail logs:
[chaos-base-logs.network-emulation-dataflow.zip](https://github.com/pingcap/tiflow/files/8966604/chaos-base-logs.network-emulation-dataflow.zip)
 

### What did you see instead?

- Job is submitted, but job master is not created.
- executor manager hangs

It seems `errctx.Err()` doesn't return a nil error

```go
goroutine 1168 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0xc00045fc00?)
        runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x4436a0?)
        sync/waitgroup.go:136 +0x52
github.com/pingcap/tiflow/engine/servermaster.(*ExecutorManagerImpl).Stop(0x281e5ea?)
        github.com/pingcap/tiflow/engine/servermaster/executor_manager.go:278 +0x1f
github.com/pingcap/tiflow/engine/servermaster.(*Server).runLeaderService.func12.1()
        github.com/pingcap/tiflow/engine/servermaster/server.go:763 +0x2c
github.com/pingcap/tiflow/engine/servermaster.(*Server).runLeaderService.func12()
        github.com/pingcap/tiflow/engine/servermaster/server.go:767 +0x8a
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:71 +0xa5
```

Besides we can find a lot of `github.com/pingcap/tiflow/engine/pkg/errctx.(*errCtx).Done.func1.1()` goroutines

```bash
$ grep "errctx/ctx.go.41" server-master-0_goroutines.log |wc -l
856
```

### Versions of the cluster

Dataflow Engine version (run `df-master -V` or `df-executor -V`):

master@49960d68d8b795758c0a1322219eea76b81a32d0

**Comment by gozssky** [comment]
It is unnecessary to create a goroutine for each `errctx`. I will optimize it first.

**Comment by gozssky** [comment]
https://github.com/pingcap/tiflow/issues/6388 will do some refinements for the servermaster's `Run` function. It may be hard to reproduce the previous scenario. So I close this issue.  If  the unstable test occurs later, a new issue will be created.
