### ISSUE TITLE
Manage TiCDC with TiDB SQL command

### ISSUE THREAD

**Issue by leoppro** [pingcap/tiflow#602]
## Description

**Is your feature request related to a problem? Please describe:**

TiCDC as a member of the TiDB ecosystem, should managed by SQL interface.

**Describe the feature you'd like:**

Hope the user can want to operate TiCDC like this:

```
# create changefeed
CREATE CHANGEFEED xxx
# query changefeed
SHOW CHANGEFEED 
```
- [ ] implement `ticdc-lib` library
- [ ] implement changefeed management
- [ ] implement capture management
- [ ] import meta data management

**Describe alternatives you've considered:**

### Value description 

This will provide a unified usage experience as a TiDB component.

### Value score 

* (TBD) / 5

### Workload estimation 

* (TBD) person-day

### Time

GanttStart: 2020-09-01
GanttDue: 2020-10-31

**Comment by overvenus** [comment]
Closed, as it's no longer in our roadmap (within 1 year)
