### ISSUE TITLE
Some test suites have not been migrated to testify

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#6094]
### Is your feature request related to a problem?

ref: https://github.com/pingcap/tiflow/issues/2164

```go
cdc/model/owner_test.go
19:     "github.com/pingcap/check"

pkg/util/testleak/leaktest.go
29:     "github.com/pingcap/check"

pkg/util/testleak/fake.go
21:     "github.com/pingcap/check"

pkg/txnutil/gc/gc_manager_test.go
21:     "github.com/pingcap/check"

pkg/txnutil/gc/gc_service_test.go
20:     "github.com/pingcap/check"
```

### Describe the feature you'd like

- [x] All tests in cdc packages use `github.com/stretchr/testify` instead of `github.com/pingcap/check`
- [ ] Add a script to verify that `goleak` is enabled for each package.
- [ ] Remove `leak_test` entry from Makefile after it is removed from CI. ref: https://github.com/ti-community-infra/configs/pull/644

**Comment by hi-rustin** [comment]
@amyangfei Can we disable the leak test now?

**Comment by amyangfei** [comment]
Leak tests have been removed after `release-5.4`

**Comment by hi-rustin** [comment]
Thanks for working on this!
