### ISSUE TITLE
Adding cdc changefeed, password with "#" failed to add

### ISSUE THREAD

**Issue by zhangyan0328** [pingcap/tiflow#6100]
### What did you do?

- 版本 v5.4.1
- 现象：添加cdc changefeed,密码中有“#”号，添加失败
![image](https://user-images.githubusercontent.com/69559746/176107838-1a43da2b-f21f-4034-a6e3-3924bf0d263f.png)

看了下 https://github.com/pingcap/tiflow/blob/master/cdc/model/changefeed.go#L153，这里的 Parse 是以#分割的。所以密码中不能写#号了吗

### What did you expect to see?

1

### What did you see instead?

1

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by hi-rustin** [comment]
It needs to be escaped. For example: https://go.dev/play/p/judO62rvWOG

**Comment by hi-rustin** [comment]
/assign

If you have any other questions, please feel free to @me.

**Comment by zhangyan0328** [comment]
I think It should be in the docs. 
https://docs.pingcap.com/zh/tidb/v5.4/manage-ticdc#%E5%88%9B%E5%BB%BA%E5%90%8C%E6%AD%A5%E4%BB%BB%E5%8A%A1

**Comment by hi-rustin** [comment]
Indeed, we need to improve it.

![image](https://user-images.githubusercontent.com/29879298/176584344-2c5f9a1a-f66f-4f5c-ba1b-707fe526af7a.png)

**Comment by zhangyan0328** [comment]
> Indeed, we need to improve it.
> 
> ![image](https://user-images.githubusercontent.com/29879298/176584344-2c5f9a1a-f66f-4f5c-ba1b-707fe526af7a.png)

ok,thanks

**Comment by hi-rustin** [comment]
I'll draft a pull request to improve it. Thanks for your feedback! 💚 💙 💜 💛 ❤️

**Comment by amyangfei** [comment]
“URL 编码” means url encode, which is not quite clear. 😅
changed history ref: https://github.com/pingcap/tiflow/issues/1145

**Comment by hi-rustin** [comment]
I'll update it today.
