### ISSUE TITLE
cdc  cli  changefeed  remove： Error: [CDC:ErrPDEtcdAPIError]etcd api call error: context deadline exceeded

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6122]
### What did you do?

- Create 300 changefeed with kafka sink
- Remove  all changefeeds one by one

### What did you see instead?

- When removing changefeed 6, cli failed: Error: [CDC:ErrPDEtcdAPIError]etcd api call error: context deadline exceeded

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
v5.4.2
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v5.4.2
```

**Comment by sdojjy** [comment]
need more log to do investigation

**Comment by Tammyxia** [comment]
Not able to reproduced in the test case, close it now. Reopen it If test can reproduce one day.
