### ISSUE TITLE
TiCDC metrics -> MySQL sink has not any data with the default express

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6125]
### What did you do?

- Metrics: Lag Analyze ->  sink write rows/s: 
![gL8JoFrDfr](https://user-images.githubusercontent.com/78345569/176592705-a2b6b942-b881-4db6-aee0-0f9bd8bab1cb.jpg)

- But metrics: MySQL Sink has not any data
![fYdDvfSNe2](https://user-images.githubusercontent.com/78345569/176592841-6dd67a81-6f80-442d-a3f0-b37e24b48fa3.jpg)

- Compare the default express between them:

> sum (rate(ticdc_sink_txn_batch_size_sum{k8s_cluster="$k8s_cluster", tidb_cluster=~"$tidb_cluster.*", changefeed=~"$changefeed", instance=~"$ticdc_instance"}[1m])) by (changefeed) --> Works fine.

>  sum(rate(ticdc_sink_txn_batch_size_sum{k8s_cluster="$k8s_cluster", tidb_cluster=~"$tidb_cluster.*", changefeed=~"$changefeed",instance=~"$ticdc_instance", type="DB"}[1m])) by (instance, changefeed) --> Don't work.

### What did you see instead?

As above.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
5.4.2
```

**Comment by Tammyxia** [comment]
The metrics is captured by clinic, so probably it's clinic's issue.

**Comment by hi-rustin** [comment]
I think the cause is clinic uses the latest template, but actually, we do not have this panel in v5.4.0. So there is no `type` label for this metric.
