### ISSUE TITLE
Changefeed error should be cleared when it is restarted from error state

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#6155]
### What did you do?

1. Create a changefeed
2. Kill the downstream process (MySQL/Kafka)
3. Wait several minutes
4. Restart the downstream process

### What did you expect to see?

When the downstream process is recovered, the changefeed error should be cleared.

### What did you see instead?

The changefeed error is not cleared, which may cause confusions for users.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.1.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v6.1.0
```

TiCDC version (execute `cdc version`):

```console
v6.1.0
```

**Comment by asddongmen** [comment]
Close it since it's stale.
