### ISSUE TITLE
[TiCDC] Feature Request: support schema-registry for OpenAPI V1

### ISSUE THREAD

**Issue by leoppro** [pingcap/tiflow#6158]
### Is your feature request related to a problem?

Can not create a changefeed sink to kafka with AVRO format by OpenAPI V1.

### Describe the feature you'd like

add a parameter named schema_registry to `POST /api/v1/changefeeds`

**Comment by leoppro** [comment]
I hope we can support schema-registry for OpenAPI V1 at v6.1.1

**Comment by sdojjy** [comment]
we  accept the ETCD model in open API v1 directly,  so we already support the schema-registry

https://github.com/pingcap/tiflow/blob/41ab14ce9fd31c185719a29cdd028f219240c616/cdc/api/open.go#L263-L267

https://github.com/pingcap/tiflow/blob/41ab14ce9fd31c185719a29cdd028f219240c616/pkg/config/sink.go#L35-L41

For example

```
curl -X POST -H "'Content-type':'application/json'" http://127.0.0.1:8300/api/v1/changefeeds -d '{"changefeed_id":"test5","sink_uri":"blackhole://" , "sink_config": {"schema-registry":  "your-schema-registry"}}'
```
