### ISSUE TITLE
TiCDC panicked when handling update events with `enable-old-value=false`

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#6198]
### What did you do?

1. set `enable-old-value = false` in  changefeed configuration file.
2. create a table with generated columns
3. execute update DMLs in upstream TiDB

### What did you expect to see?

TiCDC can properly handle this case and panic does not happen.

### What did you see instead?

TiCDC panicked

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.4.1
```

Upstream TiKV version (execute `tikv-server --version`):

```console
5.4.1
```

TiCDC version (execute `cdc version`):

```console
5.4.1
```

**Comment by hi-rustin** [comment]
You can reproduction with these steps:
1. start tidb and ticdc cluser
2. create a changefeed and disable the old value
3. create table
```sql
CREATE TABLE person2 (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    address_info JSON,
    city VARCHAR(64) AS (JSON_UNQUOTE(JSON_EXTRACT(address_info, '$.city'))),
    KEY (city)
);
```
4. insert data
```sql
INSERT INTO person2 (name, address_info) VALUES ('Morgan', JSON_OBJECT('city', 'Canada'));
```
5. Continuously updated data
```sh
#!/bin/bash

for ((i = 1; i <= 1000000000000; i++)); do
	mysql --comments --host 127.0.0.1 --port 4000 -u root --password="" <update.sql
done
```
```sql
use test;
UPDATE person2 set name='Morgan' where name='test';
UPDATE person2 set name='test' where name='Morgan';
```
6. Continuously DDL 
```sh
#!/bin/bash

for ((i = 1; i <= 1000000000000; i++)); do
	mysql --comments --host 127.0.0.1 --port 4000 -u root --password="" <add.sql
done
```
```
use test;
ALTER TABLE person2 ADD c1 int;
ALTER TABLE person2 DROP COLUMN c1;
```
7. TiCDC Panic

**Comment by hi-rustin** [comment]
The reason is:
https://github.com/pingcap/tiflow/blob/97f659262a708617a09a006dd5c94e3367ff4dc0/cdc/entry/mounter.go#L287

When we execute  the `add column` DDL, the data not exist and fillWithDefaultValue is false.

**Comment by nongfushanquan** [comment]
https://github.com/pingcap/tiflow/pull/6403
