### ISSUE TITLE
TiCDC OOM in the network loss frequently scenario

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#6221]
### What did you do?

Deploy 3 TiCDC, 8 CPU / 16Gi.

1 changefeed with MySQL Sink, replicating 100 tables, each 500000 rows, sysbench `oltp_update_non_index` 

tableCount: 100
tableSize: 500000
testName: "oltp_update_non_index"
threads: 100
duration: "2h"

### What did you expect to see?

TiCDC should works normally, shouldn't out of memory.

### What did you see instead?

TiCDC instance crashed since out of memory and meet `CrashLoopBackOff`

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
master
```

Upstream TiKV version (execute `tikv-server --version`):

```console
master
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by asddongmen** [comment]
I also meet this problem.
![image](https://user-images.githubusercontent.com/20351731/177909301-10ffc577-62fb-4750-9b43-4ca64aca15b5.png)
![image](https://user-images.githubusercontent.com/20351731/177909353-8039f84b-ecf4-4f76-a2ff-45218f659b70.png)
![image](https://user-images.githubusercontent.com/20351731/177909382-992268a2-f571-4738-8ab3-78d1e48cdb14.png)

[pprof.cdc.samples.cpu.001.pb.gz](https://github.com/pingcap/tiflow/files/9068655/pprof.cdc.samples.cpu.001.pb.gz)
[pprof.cdc.alloc_objects.alloc_space.inuse_objects.inuse_space.006.pb.gz](https://github.com/pingcap/tiflow/files/9068660/pprof.cdc.alloc_objects.alloc_space.inuse_objects.inuse_space.006.pb.gz)
[pprof.cdc.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz](https://github.com/pingcap/tiflow/files/9068661/pprof.cdc.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz)
