### ISSUE TITLE
TiCDC OOM Caused by TiDB with Massive Tables

### ISSUE THREAD

**Issue by nkorange** [pingcap/tiflow#6226]
### What did you do?

1. Prepare a TiDB cluster with 300,000+ tables.
2. Deploy TiCDC 5.1.4.
3. Create 150+ changefeeds targeting to the TiDB cluster, but the tables matching the changefeeds are only about 20,000.

### What did you expect to see?

Changfeeds are running normally.

### What did you see instead?

TiCDC OOM.

Monitoring:
<img width="1702" alt="image" src="https://user-images.githubusercontent.com/4593375/177908134-1100073c-3f66-473c-a37d-407fee375532.png">

Memory Detail:
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/4593375/177908248-21d8f25a-c190-4568-93c9-efb3d62ffd4e.png">

Seems for every changefeed, the whole table schema of the cluster would be loaded again, which results in the huge memory of ListTables function.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.1.2
```

Upstream TiKV version (execute `tikv-server --version`):

```console
5.1.2
```

TiCDC version (execute `cdc version`):

```console
5.1.4
```

**Comment by nkorange** [comment]
Seems related to https://github.com/pingcap/tiflow/issues/1386 but not the same.

**Comment by overvenus** [comment]
Try upgrade TiCDC to v6.1.0, with 8 TiCDC nodes, it can replicate about 60k tables in our tests.

**Comment by nkorange** [comment]
@overvenus Can TiCDC v6.1.0 work properly with TiDB v5.1.2? We were suggested that TiCDC version should keep consistent (major and minor).

**Comment by overvenus** [comment]
No, need to upgrade TiDB to v6.1 first.

**Comment by nkorange** [comment]
It's quite difficult for us to upgrade TiDB to v6.1, can the performance improvement patch be applied to TiCDC v5.1.x?

**Comment by nongfushanquan** [comment]
the patch can't be applied to 5.1.x。

**Comment by nkorange** [comment]
It seems quite a waste to store schema of all tables of TiDB when the changefeed only consumes a few of them.

I experimented filtering out the unwanted tables and their DDLs in schema_storage.go, looks like the changefeed works normally with much less memory allocated.

May I know if this solution is feasible?

**Comment by nkorange** [comment]
It seems quite a waste to store schema of all tables of TiDB when the changefeed only consumes a few of them.

I experimented filtering out the unwanted tables and their DDLs in schema_storage.go, looks like the changefeed works normally with much less memory allocated.

May I know if this solution is feasible? Is there a reason that TiCDC caches all tables?

**Comment by overvenus** [comment]
> May I know if this solution is feasible? Is there a reason that TiCDC caches all tables?

AFAIK, there may be some issues about RENAME TABLE, eg, a changefeed that captures `tableA[0-9]*`, and we rename `tableB1` to `tableA1`.

**Comment by nkorange** [comment]
> > May I know if this solution is feasible? Is there a reason that TiCDC caches all tables?
> 
> AFAIK, there may be some issues about RENAME TABLE, eg, a changefeed that captures `tableA[0-9]*`, and we rename `tableB1` to `tableA1`.

Yes, indeed. Could you help find the performance improvement related PRs in v6.1.0? I can then read and may copy them to v5.1.4.

**Comment by asddongmen** [comment]
Close it since it's stale. This is fixed > v6.5.3.
