### ISSUE TITLE
redo log: redo_apply_cdc_scale_sync data checksum mismatch

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6240]
### What did you do?

Case in test-infra: 
[redo_apply_cdc_scale_sync](510194)
[redo_enable_cdc_allnode_restart_sync](480260)
Both failed caused by data checksum mismatch

### What did you see instead?

Minio log: seach testbed name
testbed: cdc-testbed-tps-871607-1-840

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
main
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
[release-version=v6.2.0-alpha] [git-hash=1de2fb12b2b3633d4e816e7f92cf841350d8a4b5] [git-branch=heads/refs/tags/v6.2.0-alpha] [utc-build-time="2022-07-08 22:27:19"] [go-version="go version go1.18.2 linux/amd64"] [failpoint-build=false]
```

**Comment by Tammyxia** [comment]
Re-run this case, failed with Error: startTs, endTs (434500641670299699, 0] should match the boundary: (434500641670299699, 0]\nstartTs, endTs (434500641670299699, 0] should match the boundary: (434500641670299699, 0], ExitCode: 1"]

**Comment by hicqu** [comment]
/remove-label may-affects-4.0 may-affects-5.0 may-affects-5.1 may-affects-5.2 may-affects-5.3 may-affects-5.4
