### ISSUE TITLE
CDC should add a unique prefix to keys to distinguish new data from old data 

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#6282]
TiCDC cli reports `[CDC:ErrMultipleCDCClustersExist]multiple TiCDC clusters exist while using --pd`, after create a changefeed using an old cli. Currently, to fix solve the error, we need to use etcdctl to detele the new changefeed key. 

I propose adding a unique prefix to new keys (eg, `/tidb/cdc/_v1/<NAMESPACE>/<CHANGEFEED>/...`), so that TiCDC can distinguish the new data from the old data, and migrate old data automatically.  Note the prefix should be a string that can not be used as a changefeed name.

**Comment by asddongmen** [comment]
IMO, it is better to prohibit using old cli(version <= 6.1) to create a changefeed to a new version cluster (>= 6.2), so we should not migrate old data automatically after we upgrated TiCDC cluster.
