### ISSUE TITLE
redo_disable_enable_basic_real_time_sync: table crc32 mismatch

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6309]
### What did you do?

Redo log test case: redo_disable_enable_basic_real_time_sync, failed because data inconsistency between upstream and downtream.

### What did you see instead?

testbed: cdc-testbed-tps-990476-1-755
sysbench 10 tables crc32 mismatch

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
Release Version: v6.2.0-alpha
Git Commit Hash: 10af6ed799a2a96f96431fb37a097e1417aac16d
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-07-14 11:02:28
Go Version: go version go1.18.2 linux/amd64
Failpoint Build: false
```

**Comment by nongfushanquan** [comment]
https://github.com/pingcap/tiflow/pull/6313
