### ISSUE TITLE
update changefeed will report the previous error

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6330]
### What did you do?

- There's a error changefeed, pause it
- update changefeed with new config

### What did you expect to see?

Since update changefeed can solve this error, this error has been out of data after updating and should not display.

### What did you see instead?

- The output of update changefeed has previous error.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/78345569/179490787-42d8cbf8-a4ab-44a0-9b87-1be5adc9e5bf.png">

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
6.1.0
```

**Comment by asddongmen** [comment]
Close it since it's stale.
