### ISSUE TITLE
v6.2.0: changefeed list don't display changefeed that is error status 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6334]
### What did you do?

- Make kafka-canal-json become error status.
- /cdc cli changefeed list --pd=http://xxx:2579 -> display all changefeed except the error changefeed
- /ctl cdc --pd=http://172.16.6.5:2579 changefeed query -c kafka-canal-json -> can display this error changefeed
- Make kafka-canal-json become normal status. -> changefeed list can display this changefeed again.

### What did you see instead?

As above

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
Release Version: v6.2.0-alpha
Git Commit Hash: abc120caaf6bae9c64e9ed345618ecf303950409
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-07-17 14:25:40
Go Version: go version go1.18.2 linux/amd64
Failpoint Build: false
```

**Comment by asddongmen** [comment]
cdc cli changefeed list does not output `failed` state changefeed, which is inincompatible with TiCDC <= v6.1.0
