### ISSUE TITLE
changefeed update topicRule failed

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6336]
### What did you do?

- Pause changefeed, then update config with new dispatchers.topic:

Diff of changefeed config:
{Type:update Path:[Config Sink DispatchRules 0 TopicRule] From:{schema}_{table} To:{schema}2{table}}
Could you agree to apply changes above to changefeed [Y/N]
y
Error: invalid character 'p' after top-level value

### What did you see instead?

As above

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v6.2.0 nightly
```

**Comment by Tammyxia** [comment]
dispatchers.matcher also cannot be updated, dispatchers.dispatcher update will be ignored.

**Comment by sdojjy** [comment]
please check the add the cdc owner server log
