### ISSUE TITLE
can't not use config file to specify a sink protocol 

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#6360]
### What did you do?

as title.

### What did you see instead?

as title.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by lonng** [comment]
Is that a feature or a bug?

**Comment by asddongmen** [comment]
It is a bug introduce by this PR: https://github.com/pingcap/tiflow/pull/6038 
Before this PR above, we can specify sink protocol by config file when create a changefeed.
