### ISSUE TITLE
Redo log apply failed: Error: [CDC:ErrRedoFileOp]redo file operation: msgp: attempted to decode type \"int\" with method for \"map\"\n

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6367]
### What did you do?

Test case: redo_disable_enable_basic_real_time_sync

### What did you see instead?

2022-07-19T16:27:49.523Z        INFO    host/ticdc.go:236       Execute command on ticdc        {"command": "/cdc  redo  apply \"--s
ink-uri=mysql://root:@downstream.cdc-testbed-tps-1020793-1-643:3306\" \"--storage=s3://nfs/test-infra-redolog/redo-disable-enable-ba
sic-real-time-sync?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http://minio.pingcap.net:9000&force-path-style=true\"
 \"--tmp-dir=/tmp/nfs/redo-disable-enable-basic-real-time-sync\"", "timeout": "1m0s", "ticdc peer": 0}
2022-07-19T16:27:49.523Z        INFO    k8s/client.go:131       it should be noted that a long-running command will not be interrupt
ed even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
2022-07-19T16:27:49.855Z        ERROR   k8s/tidbcluster.go:173  Exec error{error 26 0  command terminated with exit code 1}
[2022/07/19 16:27:49.855 +00:00] [ERROR] [ticdc.go:104] ["run redo operation failed"] [output="{stdout: [2022/07/19 16:27:49.724 +00
:00] [INFO] [helper.go:52] [\"init log\"] [file=] [level=info]\nUsage:\n  cdc redo apply [flags]\n\nFlags:\n  -h, --help
  help for apply\n      --sink-uri string   target database sink-uri\n\nGlobal Flags:\n      --log-level string   log level (etc: de
bug|info|warn|error) (default \"info\")\n      --storage string     storage of redo log, specify the url where backup redo logs will
 store, eg, \"s3://bucket/path/prefix\"\n      --tmp-dir string     temporary path used to download redo log with S3 backend, stderr
: Error: [CDC:ErrRedoFileOp]redo file operation: msgp: attempted to decode type \"int\" with method for \"map\"\n[CDC:ErrRedoFileOp]
redo file operation: msgp: attempted to decode type \"int\" with method for \"map\", ExitCode: 1"] [stack="github.com/pingcap/test-i
nfra/caselib/pkg/host.(*TiCDCHost).Redo\n\tgithub.com/pingcap/test-infra/caselib/pkg/host/ticdc.go:104\ngithub.com/pingcap/test-infr
a/caselib/pkg/steps.(*redo).Execute\n\tgithub.com/pingcap/test-infra/caselib/pkg/steps/redo.go:28\ngithub.com/pingcap/test-infra/cas
elib/pkg/steps.(*Serial).Execute\n\tgithub.com/pingcap/test-infra/caselib/pkg/steps/step.go:31\nmain.main\n\t./main.go:48\nruntime.m
ain\n\truntime/proc.go:250"]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v6.1.0-20220719
```

**Comment by nongfushanquan** [comment]
dirty files left in s3 bucket will cause this problem. After cleaning the S3,  no such error happened when running cases in the test-infra.
