### ISSUE TITLE
DM: Support MySQL 8.0

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiflow#6381]
### Is your feature request related to a problem?

https://github.com/pingcap/tiflow/blob/77f8196f1b9a04a3f9cffd8bdaacffef64f5f566/dm/pkg/checker/mysql_server.go#L38-L48

When creating a task with a MySQL 8.0 source:
```json
			{
				"id": 0,
				"name": "mysql_version",
				"desc": "check whether mysql version is satisfied",
				"state": "warn",
				"errors": [
					{
						"severity": "warn",
						"short_error": "version suggested less than 8.0.0 but got 8.0.29"
					}
				],
				"extra": "address of db instance - 127.0.0.1:39135"
			}
```

### Describe the feature you'd like

Support MySQL 8.0

**Comment by lance6716** [comment]
There is a MySQL 8.0 features that will break the replication https://github.com/pingcap/tiflow/issues/5141 . And we have not fully utilized new features like https://dev.mysql.com/worklog/task/?id=4618 . A long way to go!

**Comment by dveeden** [comment]
> There is a MySQL 8.0 features that will break the replication #5141 . And we have not fully utilized new features like https://dev.mysql.com/worklog/task/?id=4618 . A long way to go!

Could we convert this check from a version based check to a feature based one? In this case to check if binlog compression is enabled instead of checking if the server is running MySQL 8.0.0 or newer?

Also, shouldn't this check be (also) done when defining the source instead of only when defining the task?
