### ISSUE TITLE
Remove changefeed must not return password in plaintext

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6429]
### What did you do?

- Now remove changefeed return with many infromation ,but it must not return cleartext passwords

### What did you see instead?

We can see password in plaintext, it's unreasonable.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v6.2.0 nightly
```

**Comment by asddongmen** [comment]
fixed by:https://github.com/pingcap/tiflow/pull/6374

**Comment by asddongmen** [comment]
I will manually https://github.com/pingcap/tiflow/pull/6374 to other release branch.

**Comment by asddongmen** [comment]
@Tammyxia can we close this issue now?
