### ISSUE TITLE
DML filter cannot handle "update" sql with clustered index, but it's a very common usage for DML filter

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6430]
### What did you do?

As title.

### What did you see instead?

As title

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v6.2.0 nightly 0721
```

**Comment by asddongmen** [comment]
I think it is not a bug but a feature.

**Comment by asddongmen** [comment]
We already this point in TiCDC user document: https://github.com/pingcap/docs-cn/pull/10557/files#diff-21c9182c9ba4dd92a3bf408beedea4a6d47faf8357bbe74989ee1d67eb8b858eR723
