### ISSUE TITLE
TiCDC cannot specify credentials for schema registry

### ISSUE THREAD

**Issue by leifan89** [pingcap/tiflow#6514]
### What did you do?

I attempted to connect TiCDC to Confluent Cloud. When specifying the URL for the `--schema-registry` option, I was unable to find anything in the [documentation](https://docs.pingcap.com/tidb/dev/manage-ticdc#integrate-ticdc-with-kafka-connect-confluent-platform) for specifying credentials for Schema Registry.

I then noticed that, in [schema_registry.go](https://github.com/pingcap/tiflow/blob/master/cdc/sink/mq/codec/schema_registry.go#L44), the credentials are always `nil`.

When attempting to connect to Confluent Cloud with just the URL for Schema Registry (and no credentials), I get an error:
```
Error: [CDC:ErrKafkaInvalidConfig]kafka config invalid: [CDC:ErrAvroSchemaAPIError]Unexpected response from Schema Registry
```

### What did you expect to see?

TiCDC should accept credentials for Schema Registry and work with Confluent Cloud

### What did you see instead?

TiCDC has no way to specify credentials for Schema Registry and does not connect to Confluent Cloud

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
| Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

Upstream TiKV version (execute `tikv-server --version`):

```console
TiKV
Release Version:   6.1.0
Edition:           Community
Git Commit Hash:   080d086832ae5ce2495352dccaf8df5d40f30687
Git Commit Branch: heads/refs/tags/v6.1.0
UTC Build Time:    2022-06-10 11:22:39
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
Release Version: v6.1.0
Git Commit Hash: 9f5e3cea2fae0a3dce6cc5ca79e3bcd654b8aa99
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-07 11:54:04
Go Version: go version go1.18.2 linux/amd64
Failpoint Build: false
```

**Comment by lance6716** [comment]
ptal @hi-rustin

**Comment by zhangyangyu** [comment]
Could you share how to configure your confluent cloud instance and the changefeed create statement? Although it's not possible to configure certs for schema registry. But seems schema registry urls of confluent cloud is signed under well-known CAs so not necessary to specify.

**Comment by leifan89** [comment]
Hi @zhangyangyu , thanks for the response. I was not trying to provide certificates - I had an API key + secret that are used for authentication, but there's no way to pass them in.

**Comment by zhangyangyu** [comment]
> Hi @zhangyangyu , thanks for the response. I was not trying to provide certificates - I had an API key + secret that are used for authentication, but there's no way to pass them in.

Ahh, get it. Then definitely you could. Check here: https://docs.pingcap.com/tidb/stable/ticdc-avro-protocol#use-avro
