### ISSUE TITLE
When a large upstream transaction causes the CDC OOM, the monitoring item "changefeed checkpoint lag" is not displayed correctly

### ISSUE THREAD

**Issue by jt20190617** [pingcap/tiflow#6551]
### What did you do?

1、Upstream TIDB emulates a large table with millions of data;
2、then performs a DELETE operation on the large table that causes CDC Server OOM

### What did you expect to see?

When large transactions are synchronized,the monitoring item "changefeed checkpoint lag" display is normal

### What did you see instead?

the monitoring item "changefeed checkpoint lag" display is abnormal,the latency value is still large and remains the same

### Versions of the cluster

tidb v5.1.4
ticdc v5.1.4

**Comment by asddongmen** [comment]
Close since it's stale.
Fixed > v6.1.0.
