### ISSUE TITLE
OpenAPI bad guide

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#6576]
### What did you do?

https://github.com/pingcap/tiflow/blob/cc8618143e268e61a1a88140d817a6738b58d6b1/engine/servermaster/openapi.go#L135

should be `job_type`. And better to display what's the received value.

### What did you see instead?

```
{
    "error": "job-type is not valid"
}
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
(paste Dataflow Engine version here)
```

**Comment by amyangfei** [comment]
The error message has been fixed by https://github.com/pingcap/tiflow/pull/6579
