### ISSUE TITLE
unstable e2e_dm_test

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#6580]
### Which jobs are flaking?

engine e2e test

### Which test(s) are flaking?

e2e_dm_test

### Jenkins logs or GitHub Actions link

```log
    e2e_dm_test.go:107: 
        	Error Trace:	e2e_dm_test.go:107
        	Error:      	Received unexpected error:
        	            	Get "http://127.0.0.1:11243/metrics": dial tcp 127.0.0.1:11243: connect: connection refused
        	Test:       	TestDMJob
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by GMHDBJD** [comment]
Any logs or links?

**Comment by GMHDBJD** [comment]
goroutine 300 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000b5e000, {0xc001a346c0, 0x1, 0x1})
	go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*Logger).Panic(0xc0007a5080?, {0x37a6523?, 0x1?}, {0xc001a346c0, 0x1, 0x1})
	go.uber.org/zap@v1.21.0/logger.go:230 +0x59
github.com/pingcap/log.Panic({0x37a6523, 0x22}, {0xc001a346c0, 0x1, 0x1})
	github.com/pingcap/log@v1.1.0/global.go:54 +0x10c
github.com/pingcap/tiflow/engine/framework.NewBaseMaster(0xc000ce9030, {0x3f65ac0?, 0xc0019eb7d0}, {0xc0008fe1b0, 0x24}, 0xb720?)
	github.com/pingcap/tiflow/engine/framework/master.go:237 +0x671
github.com/pingcap/tiflow/engine/framework.NewBaseJobMaster(0x36e49c0?, {0x7f806e73e3c8?, 0xc000246930}, {0xc00176a160, 0x1b}, {0xc0008fe1b0, 0x24}, 0xc3c0?)
	github.com/pingcap/tiflow/engine/framework/base_jobmaster.go:129 +0xcf
github.com/pingcap/tiflow/engine/framework/registry.(*registryImpl).CreateWorker(0x6c89938?, 0x3582940?, 0x8420?, {0xc0008fe1b0, 0x24}, {0xc00176a160, 0x1b}, {0xc000cc1000, 0xe80, 0x1000})
	github.com/pingcap/tiflow/engine/framework/registry/registry.go:115 +0x1ba
github.com/pingcap/tiflow/engine/executor.(*Server).makeTask(0xc000c17c70, {0x3f44b30?, 0xc000cad710}, 0xc000ca64a0, {0xc0008fe1b0, 0x24}, {0xc00176a160, 0x1b}, 0x4, {0xc000cc1000, ...})
	github.com/pingcap/tiflow/engine/executor/server.go:194 +0x48c
github.com/pingcap/tiflow/engine/executor.(*Server).PreDispatchTask(0xc000c17c70, {0x3f44b30, 0xc000cad710}, 0xc000cb8000)
	github.com/pingcap/tiflow/engine/executor/server.go:218 +0x131
github.com/pingcap/tiflow/engine/enginepb._Executor_PreDispatchTask_Handler({0x359e280?, 0xc000c17c70}, {0x3f44b30, 0xc000cad710}, 0xc000c9df80, 0x0)
	github.com/pingcap/tiflow/engine/enginepb/executor.pb.go:437 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001702000, {0x3f65dc0, 0xc00079bba0}, 0xc000ca5200, 0xc001704570, 0x6ba0e60, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc001702000, {0x3f65dc0, 0xc00079bba0}, 0xc000ca5200, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a

**Comment by amyangfei** [comment]
The same cause as https://github.com/pingcap/tiflow/issues/6581

**Comment by amyangfei** [comment]
closed by https://github.com/pingcap/tiflow/pull/6588
