### ISSUE TITLE
Invesetigate upgrade TiCDC from v5.4.2 to v6.1.0 cause metrics issue

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#6629]
Deploy a cluster in `v5.4.2`, run some workload, upgrade it to `v6.1.0.

* A lot of metrics in the TiCDC dashboard do not have any data (does not happen in v5.4.2)
* task-status which shows info at a unit level in changefeed query is empty. "task-status": [] (does not happen in v5.4.2)
* Usability of dashboard has degraded - such as old changefeeds are still shown in the dashboard (does not happen in v5.4.2)

**Comment by 3AceShowHand** [comment]
the problem was fixed by updating grafana JSON file.

**Comment by lonng** [comment]
@3AceShowHand The grafana JSON file will be updated automatically, why does 6.1 cause this problem?
