### ISSUE TITLE
ticdc exit graceful

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiflow#6651]
### What did you do?

1、 create changefeed
2、enter N

### What did you expect to see?

The changefeed create command should not reports a bug and should inform users that this changefeed creating procedure is aborted.

### What did you see instead?

![image](https://user-images.githubusercontent.com/20351731/184283261-69096d6c-3a16-49f2-8544-9d8bdde30915.png)

### Versions of the cluster

ctl and cluster version is v5.4.2

**Comment by asddongmen** [comment]
@glkappe Could please upload the image again?  I can't see it.

**Comment by asddongmen** [comment]
It is not a bug but a feature, I will handle it.
