### ISSUE TITLE
v4.0.9 upgrade to v6.2.0: upgrade successful but cdc is alway oom

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6653]
### What did you do?

- Install v4.0.9 cluster, 3 * ticdc 8c 16GB, create 3 changefeeds
- Case: cluster_upgrade_sync
- Workload: /go-tpc tpcc --db workload --warehouses 30 -T 30
- Upgrade cluster to v6.2.0
- Case log: 
[2022/08/08 07:07:08.566 +00:00] [INFO] [step.go:30] ["Upgrade TiDB All Component to version=v6.2.0-pre"]
W0808 07:07:08.566572       6 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
[2022/08/08 07:07:08.635 +00:00] [INFO] [tidb_cluster.go:294] ["Current TiDB Cluster version: v4.0.9"]
[2022/08/08 07:35:13.165 +00:00] [INFO] [tidb_cluster.go:308] ["upgrade tidb cluster success"] [option="Upgrade TiDB All Component to version=v6.2.0-pre"] [elapsed=28m4.5588713s]

### What did you see instead?

- TiCDC has oom in v4.0.9 this is expected.

- Upgrade to v6.2.0 successful, but all ticdc  pods are still always oom.
- 
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/78345569/183374210-21d9bec3-32c2-46ed-b823-9f0e120e04d1.png">

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
TiKV
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   fbf4c33f8e6cc037d2638f7237c8494172c93328
Git Commit Branch: heads/refs/tags/v6.2.0
UTC Build Time:    2022-08-05 09:07:12
Rust Version:      rustc 1.62.0-nightly (7c4b47696 2022-04-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
Release Version: v6.2.0
Git Commit Hash: bd21a6ea5ce58b86fe139eddca8dc4436320ca60
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-08-02 12:17:53
Go Version: go version go1.18.5 linux/amd64
Failpoint Build: false
```

**Comment by sdojjy** [comment]
it's hard to reproduce this issue, and v4.0.9 is a very old CDC version, better to upgrade the CDC sever to a higher version,(like v5.4) then upgrade to v6.2.
