### ISSUE TITLE
redo log: change stuck in case redo_apply_multiple_workload_node_restart_sync

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6695]
### What did you do?

- create changefeed1: enable redo log, filter sysbench table
- create changefeed2: enable redo log, filter go-ycsb table
- run sysbench prepare, meanwhile, all cdc node restart
- run truncate all sysbench table
- run sysbench run, meanwhile, all pd restart
- drop all sysbench tables
- run sysbench prepare again
- run go-ycsb workload
- sendfinishmark and waitforthisDDL

### What did you see instead?

![k0JvrUqnLJ](https://user-images.githubusercontent.com/78345569/183850342-ea78239f-a1bc-4e61-b0fe-c122d4c35a87.jpg)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
Release Version: v6.1.0-20220809
Git Commit Hash: 0c82c3405e49ac1da9f5e705d3862ec5a79c22bf
Git Branch: heads/refs/tags/v6.1.0-20220809
UTC Build Time: 2022-08-09 13:29:30
Go Version: go version go1.18.5 linux/amd64
Failpoint Build: false
```

**Comment by nongfushanquan** [comment]
https://github.com/pingcap/tiflow/pull/6671
