### ISSUE TITLE
metrics: TiKV min resolved ts  lag  is 52 years?

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6696]
### What did you do?

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/78345569/183872923-d77088f8-5a70-4f95-b251-c7739e432d6c.png">

### What did you see instead?

As above

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
/ # /cdc version
Release Version: v6.2.0-alpha
Git Commit Hash: fa41e47819b1038b808ce0e34ea386be3e95563b
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-08-09 13:08:24
Go Version: go version go1.18.5 linux/amd64
Failpoint Build: false
```

**Comment by 3AceShowHand** [comment]
The `min-ts-lag` metrics formula is:
```
scalar(max(pd_cluster_tso{k8s_cluster="$k8s_cluster", tidb_cluster="$tidb_cluster"}))/1000 - avg(tikv_cdc_min_resolved_ts{k8s_cluster="$k8s_cluster", tidb_cluster="$tidb_cluster", instance=~"$tikv_instance"}/1000) by (instance) > 0
```

It's hard to investigate the problem if we cannot get the value of the metric from Prometheus, so close it now.

You can open this if meet again.
