### ISSUE TITLE
feed state does not report to owner, changefeed state does not changed

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#6698]
### What did you do?

one changefeed, sync upstream tidb data to the downstream tidb, with differnet SQL mode.

### What did you expect to see?

changefeed should be come error state, and can be known by `changefeed list`.

### What did you see instead?

`feed state manager` can detect the error, but changefeed state does not changed, and `changefeed list` didn't show the error information.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
v5.3.1
```

**Comment by asddongmen** [comment]
This bug only exists in TiCDC <= v5.4.0, so it is reasonable to change its severity to moderate.
/severity Moderate

**Comment by asddongmen** [comment]
I will fix it in the next couple of days.
