### ISSUE TITLE
Redo log: test result is not meet the commitment "RTO<=10s"

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6699]
### What did you do?

- Create redo enabled changefeed
- Run workload: /go-ycsb load mysql -P xxx -p operationcount=5000 -p autocommit=1 -p databasename=workload -p tablecount=10 -p mysql.host=upstream-tidb.cdc-testbedbtnlx -p mysql.port=4000 --threads=20
- After workload finished, waiting for 10s to let cdc sync data
- Stop changefed, then apply redo log
- Check data between upstream and downstream

### What did you expect to see?

Since redo log commit RTO < 10s, so when upstream workload finished for 10s, then let upstream crash, the expected result is cdc can sync all data in upstream to downstream.

### What did you see instead?

Upstream has 10 tables, dowstream only has 2 tables.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
/ # /cdc version
Release Version: v6.2.0-alpha
Git Commit Hash: fa41e47819b1038b808ce0e34ea386be3e95563b
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-08-09 13:08:24
Go Version: go version go1.18.5 linux/amd64
Failpoint Build: false
```

**Comment by nongfushanquan** [comment]
redo log will cache the events for 2s which may invoke the flow controlling , so set per-table-memory-quota to a decent value if the QPS is high. And also make sure the performance of disk isn't  a bottleneck .
