### ISSUE TITLE
Drop interactive cmd support for cli

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#6728]
Just discussed with @leoppro  about removing one of cli's current interactive modes, https://github.com/pingcap/tiflow/blob/409c9525596e8ce2c8e1ec80244202427bfbee1c/pkg/cmd/cli/cli.go#L74.
Introduced two years ago in this PR: https://github.com/pingcap/tiflow/pull/351
This mode is rarely used by users and is not documented. Also, it is difficult to use it correctly, and our implementation is rather hacky. help hints are almost useless. So I'm going to just remove it.

**Comment by leoppro** [comment]
LGTM
