### ISSUE TITLE
[CDC:ErrTaskStatusNotExists]task status not exists in large scale changefeeds TiCDC

### ISSUE THREAD

**Issue by nkorange** [pingcap/tiflow#6753]
### What did you do?

Deployed 150+ changefeeds replicating 15000+ tables in total, and the source TiDB has over 300,000 tables in total.

### What did you expect to see?

No capture down.

### What did you see instead?

After some time the captures were down because of error CDC:ErrTaskStatusNotExists.

```[2022/08/15 07:41:12.325 +00:00] [ERROR] [server.go:137] ["run server"] [error="[CDC:ErrTaskStatusNotExists]task status not exists, key: %s\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/normalize.go:156\ngithub.com/pingcap/tiflow/cdc/processor.(*processor).handleTableOperation.func1.1\n\tgithub.com/pingcap/tiflow/cdc/processor/processor.go:345\ngithub.com/pingcap/tiflow/cdc/model.(*ChangefeedReactorState).PatchTaskStatus.func1\n\tgithub.com/pingcap/tiflow/cdc/model/reactor_state.go:345\ngithub.com/pingcap/tiflow/cdc/model.(*ChangefeedReactorState).patchAny.func1\n\tgithub.com/pingcap/tiflow/cdc/model/reactor_state.go:389\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*SingleDataPatch).Patch\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/interfaces.go:55\ngithub.com/pingcap/tiflow/pkg/orchestrator.getChangedState\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/batch.go:77\ngithub.com/pingcap/tiflow/pkg/orchestrator.getBatchChangedState\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/batch.go:41\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).applyPatchGroups\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:335\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:207\ngithub.com/pingcap/tiflow/cdc/capture.(*Capture).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:328\ngithub.com/pingcap/tiflow/cdc/capture.(*Capture).run.func3\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:232\nruntime.goexit\n\truntime/asm_amd64.s:1371\nprocessor exited with error"].  ```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.1.2
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.1.2
```

TiCDC version (execute `cdc version`):

```console
v5.1.4
```

**Comment by nkorange** [comment]
I think the etcd worker has concurrent issue such as:

``` ... -> processor.tick: mark table operation to finished -> capture etcd worker: apply patch -> owner etcd worker: receive event -> owner scheduler: cleanup finished operation so the table is deleted -> capture etcd worker: received event -> capture etcd worker: cache data in raw state -> processor.tick: mark table operation to finished again -> capture etcd worker: apply patch ```

In the last step it would find the table to mark is deleted in raw state, so the error occurs.

**Comment by nongfushanquan** [comment]
150+ changefeeds or 15000+ table is out of the version 5.1.2's range , please upgrade the cdc to 6.1

**Comment by nkorange** [comment]
@nongfushanquan It's not about the scale, I suspect there is a logic flaw in etcd worker. Is it fixed in 6.1?

**Comment by nongfushanquan** [comment]
in 6.1 , P2P message mode is adopted to schedule the table  between the owner and processors instead of by the etcd worker.

**Comment by nkorange** [comment]
It seems not applicable to us as we were told 6.1 is not compatible with 5.1.x. Is there a guide on how to gracefully upgrade 5.1.x to 6.1?

**Comment by Johnnyssc** [comment]
we met the same problem when use ticdc to create changefeed from two different tidb cluster, do we have any related progress in this issue?
tidb-version:5.1.0

**Comment by asddongmen** [comment]
Close since it's stale. 
Never happen again > v6.1.0.
