### ISSUE TITLE
v5.4.2 : Redo log & sync-point enabled changefeed, data loss

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6766]
### What did you do?

- Case: redo_enable_downstream_failure_sync
-  Workload: sysbench 10 tables
- After downstream tidb recovered from chaos, enable changefeed
- Check data consistency

### What did you see instead?

- Only table sbtest9 data loss
- 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/78345569/184838461-f7636187-141b-458d-ad15-6c12f1a368ed.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/78345569/184838262-b75f9800-4231-4181-8a88-6cdb81b693e7.png">

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
bash-5.1# /cdc version
Release Version: v5.4.2
Git Commit Hash: 4d7dc3dc4547ef8e4e2ff6ae4eaecd74d610c6d0
Git Branch: heads/refs/tags/v5.4.2
UTC Build Time: 2022-06-27 06:43:35
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false
```

**Comment by nongfushanquan** [comment]
there are some problems about redo log before 6.1.1 , don't use this feature  in 5.4.2 version.
