### ISSUE TITLE
remove error redo changefeed failed

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6767]
### What did you do?

![IPmsCrSwPi](https://user-images.githubusercontent.com/78345569/184847918-b540b4e0-4ac8-434e-8194-609390faff0e.jpg)

### What did you see instead?

As above.
After clean up redo nfs data, remove this changefeed successfully.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
Release Version: v6.1.0-20220812-2-g635906755
Git Commit Hash: 635906755320661ad9c1c5a834c5553f455d8a53
Git Branch: release-6.1-20220719
UTC Build Time: 2022-08-16 08:35:26
Go Version: go version go1.18.5 linux/amd64
Failpoint Build: false
```

**Comment by hicqu** [comment]
Closed by #6765 .
