### ISSUE TITLE
error(engine): Normalize error code for engine and business

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#6779]
### Is your feature request related to a problem?

https://github.com/pingcap/tiflow/issues/6745

When quering dm job status by `http://127.0.0.1:10245/api/v1/jobs/$job_id/status`, it returns :
![Pn3I8oWEZl](https://user-images.githubusercontent.com/17703670/185055651-97e09bba-0d6a-4347-9a8b-dbf393e9b046.jpg)

The reason for `code:0` is engine currently don't have normalize error code for engine and business, so dm use `0` directly.

### Describe the feature you'd like

Normalize error code for engine and business

**Comment by gozssky** [comment]
This issue will be fixed by https://github.com/pingcap/tiflow/pull/7607.
