### ISSUE TITLE
"Error 1059: Identifier name '10k_dm_jobs_1577b500-bdba-4fcd-b9c3-7a169426d865_lightning_checkpoint_list' is too long"

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#6785]
### Is your feature request related to a problem?

add a precheck about user inputs a long task name so DM internal table can't be created

### Describe the feature you'd like

see above

**Comment by maxshuang** [comment]
Looks like this issue is fixed. Close it.
