### ISSUE TITLE
redo log changefeed stuck after enable sync-point

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6827]
### What did you do?

- redo log changefeed works well.
- Make redo storage NFS umount for 10min, then recover NFS storage
- Check the changefeed can recover and checkpoint ts moving forward.
- Pause changefeed and update it to enable sync-point
- Resume changefeed, the checkpoint ts will not go on.

### What did you see instead?

- Changefeed  getstuck at 2022-08-20 6:45:45

<img width="719" alt="image" src="https://user-images.githubusercontent.com/78345569/185751481-5ae8f7b0-51a5-4941-99f4-8dbfc99620f9.png">

- [2022/08/20 06:52:37.293 +08:00] [ERROR] [pipeline.go:101] ["found error when running the node"] [name=sink] [error="[CDC:ErrRedoWriterStopped]redo manager is stopped"] [errorVerbose="[CDC:ErrRedoWriterStopped]redo manager is stopped\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:155\ngithub.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).withLock\n\tgithub.com/pingcap/tiflow/cdc/redo/manager.go:679\ngithub.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).EmitRowChangedEvents\n\tgithub.com/pingcap/tiflow/cdc/redo/manager.go:338\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).emitRowToSink.func2\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:237\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).emitRowToSink\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:276\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).HandleMessage\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:379\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).Receive\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:345\ngithub.com/pingcap/tiflow/pkg/pipeline.(*nodeRunner).run\n\tgithub.com/pingcap/tiflow/pkg/pipeline/runner.go:65\ngithub.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).driveRunner\n\tgithub.com/pingcap/tiflow/pkg/pipeline/pipeline.go:97\nruntime.goexit\n\truntime/asm_amd64.s:1571"]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
[release-version=v6.1.0-20220817] [git-hash=766289676ff0e5c883c00b79a8c4b21a93d1f454]
```

**Comment by hicqu** [comment]
![图片](https://user-images.githubusercontent.com/8407317/185830282-f51c64ac-e3ab-45b9-9085-71c7a25ec5b1.png)
![图片](https://user-images.githubusercontent.com/8407317/185830349-68c08055-8b51-407f-9e2d-db7447e86dad.png)
![图片](https://user-images.githubusercontent.com/8407317/185830407-ca98453d-5167-45d1-bb91-f12856a73096.png)
![图片](https://user-images.githubusercontent.com/8407317/185830696-f9c716e6-c728-4056-9e4b-ca5ece62d42b.png)

The above error `ErrRedoWriterStopped` is expected. The reason is redo writer exits on NFS accessing errors.

However the error shouldn't hang checkpoint in the last step. We can see that all processors and owner had rebuilt their RedoManager correctly.

**Comment by nongfushanquan** [comment]
in cdc ，sync-point feature will set barrier ts every fixed interval . when resuming from a changefeed which didn't enable sync-point feature, some tables' checkpoint or the global resolved ts may lager than the next barrierts produced by the sync-point.
