### ISSUE TITLE
executor panic after task resume

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#6851]
### What did you do?

[df.log](https://github.com/pingcap/tiflow/files/9399245/df.log)

### What did you see instead?

```
3m3e-server-executor-2               | panic: duplicate metrics collector registration attempted
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
(paste Dataflow Engine version here)
```

**Comment by maxshuang** [comment]
May be it's better to return an registration error instead of making executor panic.
I will fix it later.

**Comment by maxshuang** [comment]
BTW, business logic should protect its own goroutine to avoid taking down the executor.
