### ISSUE TITLE
A redo log changefeed has too many connections(>151) while worker-count using default value

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#6877]
### What did you do?

- Create a changefeed with redo log enabled, worker-count is by default, redo storage is nfs.
- Run tpcc prepare 10 warehouse
- Umount nfs storage for 5min, then mount nfs as before.

### What did you expect to see?

Changefeed works normally

### What did you see instead?

- Changefeed checkpoint ts don't move forward after umount nfs, cdc log has ERROR: Error 1040: Too many connections. Check downstream mysql connection: "show process list" display there's 152 rows which is reached the default max_connections=151. --> Why cdc has so many connections with mysql? the expected connection is equal to worker-count (16 by default).
- cli changefeed pause or remove get stuck, cli command will never return.
- 
![Uploading image.png…]()

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
6.1.0
```

**Comment by nongfushanquan** [comment]
https://github.com/pingcap/tiflow/pull/6882.
