### ISSUE TITLE
Version information log to wrong file

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#6946]
### What did you do?

start dm-master with tiup

### What did you expect to see?

see following log in dm-master.log
```
[2022/09/01 16:54:50.642 +08:00] [INFO] [version.go:47] ["Welcome to dm-master"] [release-version=v6.3.0-master]
```

### What did you see instead?

the log appear in dm-master_stdout.log rather than dm-master.log

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
nightly
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
introduced by https://github.com/pingcap/tiflow/issues/6819, cc @gozssky

**Comment by gozssky** [comment]
Does it affect `dm-master` only? It seems dm-master doesn't initialize the global logger `github.com/pingcap/log`.

**Comment by GMHDBJD** [comment]
and dm-worker.

**Comment by gozssky** [comment]
@GMHDBJD Do you have any suggestions about fixing this issue? Replace the global logger or add a new `LogVersionInfo` function for DM.

**Comment by GMHDBJD** [comment]
Seems we won't replace the global logger, but I forget the reason. @lance6716

**Comment by lance6716** [comment]
Also can't remember

**Comment by GMHDBJD** [comment]
Seems we embed the tidb ddl tracker, which use global logger, but we won't it log to dm-master.log

**Comment by lance6716** [comment]
> Seems we embed the tidb ddl tracker, which use global logger, but we won't it log to dm-master.log

Now new schema tracker should print less or none logs

**Comment by gozssky** [comment]
> > Seems we embed the tidb ddl tracker, which use global logger, but we won't it log to dm-master.log
> 
> Now new schema tracker should print less or none logs

@lance6716 If so, is it okay to replace the global logger with the dm logger now?

**Comment by GMHDBJD** [comment]
lgtm
