### ISSUE TITLE
Can't create ticdc job when the sink database is mariadb on Mac M1

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflow#6947]
### What did you do?

1. tiup playground nightly --ticdc 1
2. tiup cdc:nightly cli changefeed create --sink-uri="mysql://root@127.0.0.1:3306/"
3. mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p
4. tiup cdc:nightly cli changefeed create --sink-uri="mysql://root@127.0.0.1:3306/?time-zone=Asia"

### What did you expect to see?

create job successfully.

### What did you see instead?

# in step 2:

Starting component `cdc`: /Users/hongyunyan/.tiup/components/cdc/v6.3.0-alpha-nightly-20220901/cdc cli changefeed create --sink-uri=mysql://root@127.0.0.1:3306/
Error: [CDC:ErrMySQLConnectionError]fail to open MySQL connection: Error 1298: Unknown or incorrect time zone: 'UTC'

# in step 3:

Enter password: Warning: Unable to load '/usr/share/zoneinfo/+VERSION' as time zone. Skipping it.

ERROR 1064 (42000) at line 12: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Offset, Is_DST, Abbreviation) VALUES
 (@time_zone_id, 0, -968, 0, 'LMT')
,(@t...' at line 1

# in step 4:

Starting component `cdc`: /Users/hongyunyan/.tiup/components/cdc/v6.3.0-alpha-nightly-20220901/cdc cli changefeed create --sink-uri=mysql://root@127.0.0.1:3306/?time-zone=Asia
Error: [CDC:ErrMySQLInvalidConfig]MySQL config invalid: is a directory

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
nightly
```

Upstream TiKV version (execute `tikv-server --version`): 

```console
nightly
```

TiCDC version (execute `cdc version`): 

```console
nightly
```

**Comment by CharlesCheung96** [comment]
mysql_tzinfo_to_sql reads your system's time zone files and generates SQL statements from them. [mysql](https://dev.mysql.com/doc/refman/8.0/en/mysql.html) processes those statements to load the time zone tables:
```
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
```
Ref: https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html
