### ISSUE TITLE
About ticdc

### ISSUE THREAD

**Issue by mxd-321** [pingcap/tiflow#6954]
### Is your feature request related to a problem?

At present, ticdc sends multiple tables to one topic.

### Describe the feature you'd like

It is recommended that one table corresponds to one topic.

### Describe alternatives you've considered

At present, multiple ticdc tasks can be created. Each ticdc task subscribes to a table, so that one table corresponds to one topic.

**Comment by 3AceShowHand** [comment]
As far as I know, TiCDC support dispatch data to different topics by one changefeed.

@hi-rustin Can you provide more details about `multiple topics`?

**Comment by mxd-321** [comment]
Ok, thank you.

**Comment by mxd-321** [comment]
Ok, thank you. I can't find it in the official documentation, can you send me how to configure it?

**Comment by hi-rustin** [comment]
You can check out https://docs.pingcap.com/tidb/dev/manage-ticdc#topic-dispatchers.

**Comment by mxd-321** [comment]
Thank you, very perfect!

**Comment by hi-rustin** [comment]
You're welcome. I am going to close this issue, please feel free to comment if you have any other questions.
