### ISSUE TITLE
Unexpected schema registry naming on . (dot) in Kafka topic name pattern

### ISSUE THREAD

**Issue by mrmaddx2** [pingcap/tiflow#6984]
### What did you do?

We use Kafka as ticdc downstream buffer. 
Changefeed configuration looks like:
```
[sink]
dispatchers = [
    {matcher = ['*.*'], partition = "index-value", topic = "cdc_tidb_avro.cluster_name.{schema}.{table}"},
]
protocol = "flat-avro"
```

It does a great job and creates Kafka topics with expected names. However, in the schema registry it names entries replacing dots with underscores. Which is not expected and leads to downstream issues.
Using dots in naming patterns are desired in our case to support existing naming patterns with other sources.

### What did you expect to see?

The naming pattern is the same for Kafka topics and entries in the schema registry. 

### What did you see instead?

The naming pattern is NOT the same for Kafka topics and entries in the schema registry. 

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.1.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v6.1.0
```

TiCDC version (execute `cdc version`):

```console
Release Version: v6.1.0
Git Commit Hash: 9f5e3cea2fae0a3dce6cc5ca79e3bcd654b8aa99
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-07 12:07:43
Go Version: go version go1.18.2 linux/arm64
Failpoint Build: false
```

**Comment by nongfushanquan** [comment]
The purpose is to  keep the same behavior with  the jdbc source

**Comment by mrmaddx2** [comment]
First of all thanks for taking a look at it and for your replies.

To be honest i do not follow why something that we are not even using should affect our pipeline? :) 
I mean we do not use JDBC sink and the change feed was successfully created with no warnings.
We do use s3 sink with a variety of configurations and it works just fine with dots. 

I would vote to change the behavior in either way: 

1. Do not allow creating change feeds that produce inconsistent downstream flow (IMO silent changing user-defined naming pattern is not expected by anyone)
2. Allow use of whatever the user wants if it does not break the current layer

The latter is preferable because:

- An upstream component must not know anything about downstream
- we used to use Debezium and it allowed dot with no restrictions. So getting rid of the limitation would require no code changes from us to migrate :)

**Comment by zhangyangyu** [comment]
The avro functionality is designed to be compatible with JDBC sink. For your suggestions, cc @nongfushanquan @leoppro.
