### ISSUE TITLE
Increase the default table memory quota

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#7030]
Now, our default table memory quota is 10 MiB. I think it's come from the `txn-entry-size-limit` config of TiDB. But sometimes the user can change the `txn-entry-size-limit` to a bigger value. It will cause the TiCDC can not deal with the big single event. So @nongfushanquan and I propose to increase the default table memory quota. We think 64MiB is a reasonable value.

For example, if the user gets 300 tables, then it will spend 300 * 61 MiB bytes of memory. It is almost about 20G, we think it's acccepable.

**Comment by overvenus** [comment]
What is the "the big single event"? Does it mean one row in TiDB?

**Comment by hi-rustin** [comment]
> What is the "the big single event"? Does it mean one row in TiDB?

Yes.

**Comment by overvenus** [comment]
It's conflict to TiDB's row size limit.

> ## Limitation on a single column
> 
> Type | Upper limit
> -- | --
> Size | 6 MB

https://docs.pingcap.com/tidb/stable/tidb-limitations#limitation-on-a-single-row

**Comment by overvenus** [comment]
I think there may be a bug in TiCDC, which mis-calculates row size.

**Comment by hi-rustin** [comment]
> I think there may be a bug in TiCDC, which mis-calculates row size.

It can be config.
