### ISSUE TITLE
tikv disk full, event feed report the region not found, kv client meet EventFeed retry rate limited, resolved ts lag increased last for a long period

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#7046]
### What did you do?

1 changefeed, 310 tables. 2 cdc nodes。

### What did you expect to see?

the resolved ts make progress normally.

### What did you see instead?

The resolved ts lag increased dramatically.

<img width="2080" alt="image" src="https://user-images.githubusercontent.com/7138436/189803280-fd6ccb1e-656a-453a-9998-4fea13feed3e.png">

<img width="2930" alt="image" src="https://user-images.githubusercontent.com/7138436/189803375-13b9c01b-d533-4603-9ee6-78cd44f305d9.png">

<img width="2937" alt="image" src="https://user-images.githubusercontent.com/7138436/189803780-1fc0ee23-f162-4871-aa26-76f348826ba4.png">

From the log we found that, `EventFeed retry rate limited` for the table `481`.

<img width="2741" alt="image" src="https://user-images.githubusercontent.com/7138436/189803867-39191075-f867-43d9-a1a6-1329cd66e601.png">

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by 3AceShowHand** [comment]
we have found that 2 out of 3 tikv instances disk usage were fulled, this may cause the upstream service unavailable.

![NOF5VEIQzF](https://user-images.githubusercontent.com/7138436/189804875-827dddbe-f71c-4a21-9ecb-d0881c5ec965.jpg)

**Comment by 3AceShowHand** [comment]
This issue is resolved by clean up tikv disk space, so we change the severity from major to moderate temporarily.

**Comment by asddongmen** [comment]
Close it since it's stale.
