### ISSUE TITLE
Can not deserialize the binary/varbinary type data with canal-json format.

### ISSUE THREAD

**Issue by HZSHZSHZS** [pingcap/tiflow#7058]
### What did you do?

I used type binary(16) to store UUID and type varbinary(32) to store SHA256. The binary/varbinary data sent by Ticdc with canal-json format was packed by function string(bytes). And when the data was received by Flink using Kafka, the binary array was not correct and the data can not be deserialized any more.
 

### What did you see instead?

normal hash: 0xD7D3B07AAD307CF5FEA3194B09D36893C98FBDA74A7438055F928A9A03FD0074

sent by ticdc and deserialized by flink
"hash":"varbinary"
"hash":"\ufffdӰz\ufffd0|\ufffd\ufffd\ufffd\u0019K\t\ufffdh\ufffdɏ\ufffd\ufffdJt8\u0005_\ufffd\ufffd\ufffd\u0003\ufffd\u0000t"

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.3.1
```

Upstream TiKV version (execute `tikv-server --version`):

```console
TiKV 
Release Version:   5.3.1
Edition:           Community
Git Commit Hash:   ecc2549ed63fc21f1f6e11f1b85f19c2465234a5
Git Commit Branch: heads/refs/tags/v5.3.1
UTC Build Time:    2022-03-03 10:10:50
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

```

TiCDC version (execute `cdc version`):

```console
Release Version: v5.3.1
Git Commit Hash: 630896740566eb0f7a81062506e92177e755f404
Git Branch: heads/refs/tags/v5.3.1
UTC Build Time: 2022-03-02 02:05:42
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false
```

**Comment by 3AceShowHand** [comment]
We have update the canal-json detail since v5.4, you can take the document `https://docs.pingcap.com/tidb/v6.0/ticdc-canal-json` as the reference.

Can you also test it on the TiCDC at leasat v5.4.1, since we know other issue on v5.4.0.

**Comment by 3AceShowHand** [comment]
This is not a bug, `Canal-Json` GA since `v5.4.0`, this version is `v5.3.1`, not supported.
