### ISSUE TITLE
After created changefeed with start-ts older than 20 hours,  TiCDC was in oom

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tiflow#7084]
### What did you do?

1. ticdc create changefeed with start-ts ts1, and sink is tidb
2. ticdc 8c 32g , 3 nodes
3. create time is ts2, ts2 - ts1 = 20 hours
4. in the 20 hours, workload was writing data to changefeed upstream. workload covers 2000 tables, and qps is almost 4k/s

### What did you expect to see?

1. ticdc can work normally
2. tidb sink can get data

### What did you see instead?

1. ticdc was in oom
2. tidb sink was no data
here is some heap screenshot at oom time:
![image](https://user-images.githubusercontent.com/50363732/190543169-b629d9a6-b2dc-475b-b9f0-3bdb83ffa873.png)
and heap zip:
[cdc-heap.zip](https://github.com/pingcap/tiflow/files/9580113/cdc-heap.zip)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: c646842f2926b38c96bf05350033cce53fbce4ba
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-09-14 13:43:48
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

Upstream TiKV version (execute `tikv-server --version`):

```console
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   8c93b91fea7396b9261551297d1bfa037c82e605
Git Commit Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time:    2022-09-13 11:02:56
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
Release Version: v6.3.0-alpha
Git Commit Hash: b77140106a5f48c9a49d98fa0780648d7dd0d56f
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-09-15 10:50:49
Go Version: go version go1.19 linux/amd64
Failpoint Build: false
```

**Comment by overvenus** [comment]
This is likely related to https://github.com/pingcap/tiflow/issues/7561

**Comment by nongfushanquan** [comment]
duplicated https://github.com/pingcap/tiflow/issues/7553
