### ISSUE TITLE
Remove pulsar sink support

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#7087]
Pulsar is in an unmaintained state, with no unit tests, no integration tests, and no support for new features. So we decided to remove it.

StreamNative officially provides Kafka-on-Pulsar (https://github.com/streamnative/kop) to give Pulsar the ability to support the native Kafka protocol, so the TiCDC Kafka Sink can write data to Pulasr with the power of kop. .

**Comment by Jiangrb** [comment]
@hi-rustin  

After integrating the kop, the ticdc does not work, and the prompt the error blow : 
```
Error: [CDC:ErrKafkaNewSaramaProducer]new sarama producer: [CDC:ErrKafkaBrokerConfigNotFound]cannot find the `message.max.bytes` from the broker's configuration
```
I can not found anywhere to config the property of `message.max.bytes` in kop , so I tried to find the code that describing the config of kafka in kop ,then I found the method 'describeConfigsAsync' in this link  [kop AdminManager.java](https://github.com/streamnative/kop/blob/66efad61c853aa9044fd4b03e7bffc3823a36042/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java)
<img width="809" alt="image" src="https://user-images.githubusercontent.com/11899426/210195721-5d77921f-dd42-4fe4-8eaf-ca6db8dbbe38.png">

It seems that kop does not return the value of the attribute to `message.max.bytes`, but  Ti-CDC required it

**Comment by Jiangrb** [comment]
Finally , I modified the code and rebuilded kop in this  [AdminManager.java](https://github.com/streamnative/kop/blob/66efad61c853aa9044fd4b03e7bffc3823a36042/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java), then it works !  

that's what I added :

![image](https://user-images.githubusercontent.com/11899426/210356945-249e573b-cfa1-4267-aad2-2b3dba6dc204.png)

**Comment by Kevinzhuo** [comment]
> Finally , I modified the code in this [AdminManager.java](https://github.com/streamnative/kop/blob/66efad61c853aa9044fd4b03e7bffc3823a36042/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java) and rebuilded kop, then it works !
> 
> that's what I added :
> 
> ![changes](https://user-images.githubusercontent.com/11899426/210358010-8631c574-b388-4b32-9415-f4c8eee83dae.png)

@Jiangrb 
I added message.max.bytes, but ticdc still reports this error. Is there any other way to solve it?

**Comment by reAsOn2010** [comment]
I think Pulsar is actively maintained now？ https://github.com/apache/pulsar/actions

**Comment by hi-rustin** [comment]
> I think Pulsar is actively maintained now？ https://github.com/apache/pulsar/actions

I meant pulsar sink.
