### ISSUE TITLE
changefeed get stuck when replicating a 3 million rows transaction when using sinkv2.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#7090]
### What did you do?

1. prepare data, create 3 tables: `sbtest0, sutest1, sutest2` ,and insert 1 million rows into each table. (sysbench)
2. create changefeed called test1, with sinkv2 enable.
```
--sink-uri = "tidb://root:xxxx@10.2.6.77:4000/?worker-count=64&transaction-atomicity=none&time-zone="
```
4. excute a transaction.
```sql
begin;
update table sbtest0 set k=k+1;
update table sbtest1 set k=k+1;
update table sbtest2 set k=k+1;
commit;
```

### What did you expect to see?

changefeed take about 10 mins to replicate this transation as using sinkv1.

### What did you see instead?

changefeed took 2 hours to replicate this transaction.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master branch
```

**Comment by nongfushanquan** [comment]
https://github.com/pingcap/tiflow/pull/7133
https://github.com/pingcap/tiflow/pull/7106
