### ISSUE TITLE
unstable integration test dm/safemode

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#7099]
### Which jobs are flaking?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/9592/pipeline

### Which test(s) are flaking?

dm/integration/safemode

### Jenkins logs or GitHub Actions link

```log
(paste logs here)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by lance6716** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/9654/pipeline

**Comment by lance6716** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/9671/pipeline

**Comment by okJiang** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/52/pipeline/
