### ISSUE TITLE
Clean up dead code in the tiflow.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#7165]
### Is your feature request related to a problem?

There are some dead codes in tiflow repo which makes understanding the codebase more challenging.
So, it is an important things to make the codebase more concise.

Any PR that related to clean dead codes can refer to this issue to pass the merge check. 

### Describe the feature you'd like

as title.

**Comment by gozssky** [comment]
Maybe duplicate with https://github.com/pingcap/tiflow/issues/4954.

**Comment by asddongmen** [comment]
close by the reason commented above.
