### ISSUE TITLE
support routing rules mapping for source database/table and target database/table

### ISSUE THREAD

**Issue by gejibin** [pingcap/tiflow#7169]
### Is your feature request related to a problem?

no

### Describe the feature you'd like

Demands from customers:

1.support routing rules configuration for source database/table and target database/table
2.support conditional table data synchronization
3.support DML/DDL filter, such as delete statement, drop table

具体来说：

1.支持指定上游数据库名和下游数据库名的配置（数据库名变更），比如上游数据库db1（数据库名）的数据同步到下游数据库db2（数据库名）里；

2.支持指定上游数据库表名和下游数据库表名的配置（表名变更），比如上游数据库db1的表table_xx(表名)数据同步到下游数据库db1的表table_xx_tmp(表名)里；

3.支持配置数据库和表名变更，比如上游数据库db1的表table_xx(表名)数据同步到下游数据库db2的表table_xx_tmp(表名)里；

4.支持带条件的表数据同步， 比如上游数据库db1的表table_xx(表名)里的满足某个条件的数据（2021年6月份之后的数据）同步到下游数据库里面。

5.配置的时候支持通配符配置。

6.支持过滤DML/DDL语句，有些场景需要过滤某些操作，比如规档情况下过滤数据删除操作。

**Comment by lance6716** [comment]
All these features are already supported. Please check our document https://docs.pingcap.com/zh/tidb/stable/dm-overview

**Comment by kennytm** [comment]
This is a duplicate of #2504 which is referring to TiCDC rather than DM.
