### ISSUE TITLE
No sinkv2 related metrics in ti-operator clusters

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7205]
### What did you do?

1. Use ti-operator 1.3.8 to deploy TiDB cluster with CDC, configuring enable-new-sink = true (default)
2. Start CDC changefeed and check grafana for sinkv2 related metrics

### What did you expect to see?

There should be sinkv2 related metrics. Take tiup cluster as an example:
![image](https://user-images.githubusercontent.com/7403864/191917175-c6e3ece4-939d-4a8c-a1ed-b75e14481c77.png)

### What did you see instead?

No sink v2 related metrics.
![Uploading image.png…]()

### Versions of the cluster

v6.3.0

**Comment by hi-rustin** [comment]
Fixed. I am going to close this issue.
