### ISSUE TITLE
cdc 5.3.1  changefeed resolvedTs stuck

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#7217]
### What did you do?

From oncall case

monitor: https://clinic.pingcap.com.cn/portal/#/orgs/174/clusters/6951260769633055749

![image](https://user-images.githubusercontent.com/17703670/192208574-03383832-345b-4770-8eea-403e5fa5efd1.png)

The changfeed with the problem is `ote-to-rpt-cdctask`
After investigation, some phenomenent need to be noticed:
 1.  sorter input/output rate  has a gap  
 2.  fd in 147 had increased rapidly
 3. paramether "Processor Memory Consumption Per Capture" of changefeed  had not reach 10M table memory limit
 4. downstream  sink has little long duration
 5. upstream tikv cpu is normal，resolvedTs lag seems normal，but the log has too many abnormal kvclient fail `The resolvedTs is fallen back in kvclient`

### What did you see instead?

--

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
5.3.1
```

**Comment by buchuitoudegou** [comment]
BTW, ote-to-rpt-cdctask and ote-cdc-to-dw encountered big transaction and the latter one did not suffer from high latency while the former one did.

**Comment by maxshuang** [comment]
It's very likely that the table resolvedTs is stuck by the table flow control.
Since the grafana metric  "Processor Memory Consumption Per Capture" of ticdc  release 5.1 is inaccurate(fix by https://github.com/pingcap/tiflow/pull/5538 on master), 
we recommend to enlarge the cdc config  `per-table-memory-quota` to workaround this problem temporarily.
