### ISSUE TITLE
cdc OOM when running test cdc_owner_switch_sysbench

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7297]
### What did you do?

Run test case cdc_owner_switch_sysbench for v5.4.3

### What did you expect to see?

CDC should not OOM

### What did you see instead?

CDC OOM happens:

![image](https://user-images.githubusercontent.com/7403864/194743884-ad435b90-57fd-4929-a242-329a5fb27a73.png)

![img_v2_75c7af5b-afda-4303-a15f-96bc7007252g](https://user-images.githubusercontent.com/7403864/194743886-1c36e096-700f-49e8-b84e-443bf99080d0.jpg)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
/ # /tidb-server -V
Release Version: v5.4.3
Edition: Community
Git Commit Hash: f9b13b76505429b48cc479020e1b4b260a689175
Git Branch: heads/refs/tags/v5.4.3
UTC Build Time: 2022-09-28 09:21:22
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

```

Upstream TiKV version (execute `tikv-server --version`):

```console
/ # /tikv-server -V
TiKV
Release Version:   5.4.2
Edition:           Community
Git Commit Hash:   128bbc0d49d05ce3a9d8ec0a2790c30c67c67844
Git Commit Branch: heads/refs/tags/v5.4.3
UTC Build Time:    2022-09-28 09:17:26
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

```

TiCDC version (execute `cdc version`):

```console
bash-5.1# /cdc version
Release Version: v5.4.3
Git Commit Hash: ed9ffce29902707fdc52abd97197dc8270219331
Git Branch: heads/refs/tags/v5.4.3
UTC Build Time: 2022-09-28 09:15:34
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false

```

**Comment by 3AceShowHand** [comment]
v5.4.3 use scheduler V1， table pipeline, and unified sorter.

There are 100 tables, each with at least 500000 rows prepared, owner pod crash every 5 minutes and last for 20 seconds.

After the owner crashed, tables rescheduled to other captures, and cannot make progress for a while, then the owner crashed again, so it looks the whole changefeed cannot make progress and hoarding a large amount of incremental data, increasing the risk of memory overflow.

We can reduce the owner switch frequency to 30 minutes to make the owner can works properly and make progress.

**Comment by 3AceShowHand** [comment]
afte change the owner switch frequency to 30 minutes, the test passed, so we close the issue temporarily.
