### ISSUE TITLE
DM: more detailed query-status

### ISSUE THREAD

**Issue by okJiang** [pingcap/tiflow#7343]
### Is your feature request related to a problem?

no

### Describe the feature you'd like

add some status:
- duration(from unit start)
- instantaneous speed
	- for dump: bytes/s https://github.com/pingcap/tidb/pull/38456
	- for load: bytes/s https://github.com/pingcap/tiflow/pull/7212
	- ~~for sync: rows/s(now is tps)~~, in fact, tps is the rps(rows per sec), a naming problem
- progress
	- for dump: calculate by chunks https://github.com/pingcap/tidb/pull/38625
	- ~~for load: calculate by rows~~(bytes is accurate)
- completed phase's detail https://github.com/pingcap/tiflow/pull/7386

### Teachability, Documentation, Adoption, Migration Strategy

display in TiDB cloud

**Comment by lance6716** [comment]
Duration (start-time) should be kept across failover, for DM in engine scenario only the metaDB is survived across failover, so we might only add this field to the response of engine job's status.
