### ISSUE TITLE
Returned pos of function GetMasterStatus should be int64 instead of uint32

### ISSUE THREAD

**Issue by lyzx2001** [pingcap/tiflow#7483]
### What did you do?

https://github.com/pingcap/tiflow/blob/6ad967659ba98065994f8cb79415912a408abb28/dm/pkg/conn/utils.go#L101-L103

### What did you expect to see?

The second returned parameter `pos` should be `int64` instead of `uint32`, to conform to MySQL's behavior:
https://github.com/mysql/mysql-server/blob/a246bad76b9271cb4333634e954040a970222e0a/sql/rpl_source.cc#L1225-L1226

### What did you see instead?

The second returned parameter `pos` is `uint32`.

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v6.3.0-master-dirty
```

**Comment by lyzx2001** [comment]
@lance6716

**Comment by lance6716** [comment]
```
$ mysql -h127.0.0.1 -P3306 -uroot -p123456 --column-type-info

MySQL [(none)]> show master status;
...
Field   2:  `Position`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     20
Max_length: 4
Decimals:   0
Flags:      NOT_NULL UNSIGNED BINARY NUM
...
```

/cc @liumengya94
