### ISSUE TITLE
TiCDC support sync table with foreign key

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tiflow#7521]
### Is your feature request related to a problem?

Related TiDB Issue: [Support Foreign Key Dev Task#36982](https://github.com/pingcap/tidb/issues/36982)

### Describe the feature you'd like

N/A

### Describe alternatives you've considered

N/A

### Teachability, Documentation, Adoption, Migration Strategy

N/A

**Comment by lance6716** [comment]
same adjustment should be done for DM
