### ISSUE TITLE
ticdc create kafka sink changfeed and checkpoint lag is increasing and cdc in oom

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tiflow#7553]
### What did you do?

1. create kafka sink changefeed: 
`/cdc  cli  changefeed  create 
--pd 'http://xxxx-pd:2379' 
--sink-uri 'kafka://xxxxx:9092/xxxx-topic-01?protocol=canal-json&replication-factor=1' 
--changefeed-id 'xxxx-task-01'`

### What did you expect to see?

1. lag < 10s

### What did you see instead?

1. checkpoint lag is increasing
![image](https://user-images.githubusercontent.com/50363732/200528690-0b66be71-4022-4c46-a754-e8ad455d2679.png)
2. hours later , ticdc in oom and in crash
![image](https://user-images.githubusercontent.com/50363732/200727231-e915d862-ba15-48cb-880b-2b4c9aa07bbd.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
v6.4.0
```console
(paste TiDB cluster version here)
```
v6.4.0
Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```
v6.4.0
TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by overvenus** [comment]
See OOM details in https://github.com/pingcap/tiflow/issues/7561

**Comment by nongfushanquan** [comment]
duplicated https://github.com/pingcap/tiflow/issues/7553
