### ISSUE TITLE
data inconsistency after redo apply

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7554]
### What did you do?

1. Create changefeed with eventual consistency on,  save redo log to s3.
2. Run sysbench prepare and run
3. Stop sysbench workload
4. Stop changefeed
5. Run redo apply and redo meta
6. Check data consistency between upstream and downstream

### What did you expect to see?

Data should be consistent

### What did you see instead?

Data consistency check failed

### Versions of the cluster

v6.4.0

**Comment by nongfushanquan** [comment]
enabling redo log can't assure the consistency between the upstream and the downstream . But it will make sure the downstream in the consistent state .

**Comment by fubinzh** [comment]
This failure was due to a bug in test code of consistency check, close it.
