### ISSUE TITLE
TiCDC OOM due to lack of process level memory quota control

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#7561]
### What did you do?

Currently, there is no process-level memory quota control in TiCDC, memory usage is proportional to table count. TiCDC (cluster) may OOM when there are many tables being captured.

Also, it may cause an avalanche effect of TiCDC OOM, suppose there are 3 TiCDC nodes running at 80% memory consumption, if one node fails accidentally, then remains TiCDC nodes will OOM after taking over its tables because of exceeds their memory limit (120% > 100%).

In k8s, the situation is even worse, because of the randomness in CrashLoopBackOff, it is impossible to restart TiCDC pods simultaneously. TiCDC pods end in OOM continually.

### What did you expect to see?

TiCDC can downgrade services, but should not OOM.

### What did you see instead?

OOM.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

TiCDC version (execute `cdc version`):

```console
v6.4.0
```

**Comment by asddongmen** [comment]
After v6.5.0, TiCDC has already supported changefeed level memory control.

**Comment by overvenus** [comment]
The changefeed level memory control is not the process level memory control. A process means linux process, not the "processor" in TiCDC.
