### ISSUE TITLE
TiCDC stuck and OOM when replicating 100k tables.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#7593]
### What did you do?

1. start 4 cdc nodes (16c 64gb)
2. create a changefeed that replicate 100k tables
3. changefeed stuck, TiCDC OOM

### What did you expect to see?

TiCDC works normally.

### What did you see instead?

as title.
[100k_table_issue.zip](https://github.com/pingcap/tiflow/files/9999058/100k.zip)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
v6.1.1
```

**Comment by dbsid** [comment]
same issue when running with 800k table with 6 CDC.
two of 6 CDC is oom


![oD6ZXZHFJg](https://user-images.githubusercontent.com/2316425/202339890-e5af4333-2b67-4648-8e91-8dcbdc5be5f2.jpg)

**Comment by asddongmen** [comment]
It doesn't happen again in the 7.1.0 version.
