### ISSUE TITLE
no data for metrics ticdc_sinkv2_mq_worker_send_message_duration_bucket

### ISSUE THREAD

**Issue by dbsid** [pingcap/tiflow#7633]
### What did you do?

monitor cdc using latest master version

### What did you expect to see?

no data for ticdc_sinkv2_mq_worker_send_message_duration_bucket

### What did you see instead?

there is should be data
![9XwFYxhCix](https://user-images.githubusercontent.com/2316425/202427321-9fdf5ea7-f59b-411b-9bc0-7fce4bbae6db.jpg)
![Uploading HzTR3mojc0.jpg…]()

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console

```

TiCDC version (execute `cdc version`):

```console
master
[root@cdc-1-0 bin]# ./cdc version
Release Version: v6.5.0-alpha
Git Commit Hash: 482239d06b53241f589ab68053aa9d002822c9ac
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-15 14:25:21
Go Version: go version go1.19.2 linux/amd64
Failpoint Build: false
```

**Comment by 3AceShowHand** [comment]
what's your ticdc version? this is only supported by the master ticdc.

**Comment by dbsid** [comment]
on master 

```
[root@cdc-1-0 bin]# ./cdc version
Release Version: v6.5.0-alpha
Git Commit Hash: 482239d06b53241f589ab68053aa9d002822c9ac
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-15 14:25:21
Go Version: go version go1.19.2 linux/amd64
Failpoint Build: false```
