### ISSUE TITLE
Metrics in scheduler v3 leaks when pd cluster is down 

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#7660]
### What did you do?

Running TiDB cluster with single PD node. Metrics in scheduler v3 leaks when pd cluster is down.

### What did you expect to see?

No metrics leaks.

### What did you see instead?

Metrics leaks

| `by (changefeed)` | `by (changefeed, instance)`|
| - | - |
|  <img width="1507" alt="image" src="https://user-images.githubusercontent.com/2150711/203005082-6afc31ca-2c7f-436c-815f-f2499fcea19a.png"> | <img width="1494" alt="image" src="https://user-images.githubusercontent.com/2150711/203005060-b3fb74aa-8ac1-4893-a942-20f4e4547e14.png"> |

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

TiCDC version (execute `cdc version`):

```console
v6.{2,3,4}.0
```

**Comment by asddongmen** [comment]
Close it since it's stale.
