### ISSUE TITLE
CDC changefeed is slow recently

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7732]
### What did you do?

1. Run automation test case redo_apply_multiple_workload_node_restart_sync,

### What did you expect to see?

Case should pass

### What did you see instead?

Case failed since 11/25, and from cdc metrics, we can see the changefeed is much slower than that that of previous versions

== checkpoint lag metric 11/29== 
![8e5160f4-c4d7-43e1-8f52-ed3aeb38c857](https://user-images.githubusercontent.com/7403864/204237812-847cb683-d4e7-476e-87ae-d81fbd71a565.jpeg)

== checkpint lag metrics on 11/25
![01756de1-2072-44eb-bb9c-f212766c65d0](https://user-images.githubusercontent.com/7403864/204237871-0082841c-8d5e-47b9-88fc-93c4eb765b78.jpeg)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
master
```

Upstream TiKV version (execute `tikv-server --version`):

```console
master
```

TiCDC version (execute `cdc version`):

```console
[\"Welcome to Change Data Capture (CDC)\"] [release-version=v6.5.0-alpha] [git-hash=5dc3c5030992364db67d6e1ada9accc4409e9d35] [git-branch=heads/refs/tags/v6.5.0-alpha] [utc-build-time=\"2022-11-27 11:06:30\"] [go-version=\"go version go1.19.3 linux/amd64\"]
```

**Comment by fubinzh** [comment]
Run the case redo_apply_multiple_workload_node_restart_sync severral times when debug.enable-pull-based-sink = false.
The changefeed lag( 5min+) is better than that in original bug (~50min),  but it is still about 2 times of previous lag, which is less than 3 minutes.

bash-5.1# /cdc version
Release Version: v6.5.0-alpha
Git Commit Hash: 519c6f08dc5ca000d8c92101e2987daf071d716e
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-30 11:07:02
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false

![e0dcb268-f210-496c-b6e1-0601d0232e8a](https://user-images.githubusercontent.com/7403864/204956473-18c25ebd-4dad-4ef8-afd5-bcf902d7c335.jpeg)

**Comment by fubinzh** [comment]
Retest with latest CDC version
For case redo_apply_multiple_workload_node_restart_sync

- latest result
![image](https://user-images.githubusercontent.com/7403864/205579293-505e70f4-6ced-491a-b796-2eea72bfd57b.png)

- 11/25 result
![image](https://user-images.githubusercontent.com/7403864/205579662-d8283fca-8db2-4c06-ba0e-e23b68aab761.png)

```
bash-5.1# /cdc version
Release Version: v6.5.0-alpha
Git Commit Hash: 5b3158b1f13fea049be88004275f12cc0739d0ea
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-12-03 11:43:23
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false
```

**Comment by fubinzh** [comment]
verified and close it

**Comment by jebter** [comment]
https://github.com/pingcap/tiflow/issues/7780
