### ISSUE TITLE
CDC metric abnormal - checkpoint is invalid date "1970-01-01 08:00:00"

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7764]
### What did you do?

1. Start changefeed with storage sink, use minio as target storage 
2. minio has unavailabe at ~13:48

### What did you expect to see?

CDC storage sink checkpoint should not move forward when the target storage is unavailable

### What did you see instead?

From cli, we can see changefeed is stuck at 13:48
```
[root@tidb-node2 bin]# ./cdc cli changefeed list --server=[10.2.6.68:8300](http://10.2.6.68:8300/)
[
  {
    "id": "storage-test",
    "namespace": "default",
    "summary": {
      "state": "normal",
      "tso": 437747370671734937,
      "checkpoint": "2022-12-01 13:48:17.936",
      "error": null
    }
  }
]
```

From Grafana, the changefeed lag is still normally, though the changefeed checkpoint is not 1970-01-01 
![image](https://user-images.githubusercontent.com/7403864/204994834-43792b48-2c68-4e0b-9a1e-7c8b03068312.png)

### Versions of the cluster
master

**Comment by fubinzh** [comment]
In another testbed, one of the cdc lag is 52 years.

![image](https://user-images.githubusercontent.com/7403864/204995209-aa78ec74-53ed-4e37-bfce-7bc7d0d1a5ae.png)

**Comment by fubinzh** [comment]
changefeed in matric is normal, whicl changefeed is stuck actually during storage sink testing:
![47ed64c8-e9b7-4577-8ab9-25db01f607cd](https://user-images.githubusercontent.com/7403864/205049900-933e0127-e68e-40aa-b441-884887f05914.jpeg)
![5cdaa116-97ad-4e9f-b0b2-f809c6b3fb6d](https://user-images.githubusercontent.com/7403864/205049911-5e2fb48b-d2da-430b-9747-e4eeb336140b.jpeg)

**Comment by zhaoxinyu** [comment]
This issue cannot be reproduced. Reproduce steps:
-  mkdir /media/images/
- dd if=/dev/zero of=/media/images/data.img bs=1M count=200
- mkfs.ext4 /media/images/data.img
- mkdir /data
- mount -o loop /media/images/data.img /data
- minio server /data --console-address :9090

**Comment by zhaoxinyu** [comment]
> changefeed in matric is normal, whicl changefeed is stuck actually during storage sink testing: ![47ed64c8-e9b7-4577-8ab9-25db01f607cd](https://user-images.githubusercontent.com/7403864/205049900-933e0127-e68e-40aa-b441-884887f05914.jpeg) ![5cdaa116-97ad-4e9f-b0b2-f809c6b3fb6d](https://user-images.githubusercontent.com/7403864/205049911-5e2fb48b-d2da-430b-9747-e4eeb336140b.jpeg)

I think this behavior needs to be discussed. At present, when the changefeed is in `error` state, the `ticdc_owner_checkpoint_ts_lag` metric will not be reported anymore. So you will see there are no monitoring points after the changefeed is switched into `error` state.
