### ISSUE TITLE
storage sink uri doesn't support local:///

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7765]
### What did you do?

- create storage sink using NFS with sink-uri "local:///nfs/xxx"

### What did you expect to see?

create storage sink succeeded.

### What did you see instead?

```
- [root@centos76_vm topos]# /home/tidb-deploy/cdc-8300/bin/cdc cli changefeed create --pd=http://172.16.6.217:2379 --sink-uri="local:///nfs/storagesink_test" --changefeed-id=test1 --config=changefeed.toml
Error: [CDC:ErrSinkURIInvalid]sink uri invalid 'protocol csv is incompatible with local scheme'

```

### Versions of the cluster

master

**Comment by CharlesCheung96** [comment]
`local://` is not supported by ticdc. Use `file://` instead.
