### ISSUE TITLE
cdc sorter dir dose not release after removing task

### ISSUE THREAD

**Issue by 15767637775** [pingcap/tiflow#7817]
### What did you do?

tiup cdc cli changefeed remove --pd=http://IP:port --changefeed-id simple-replication-task

changefeed removes task, but cdc sorter dose not release.
![9e116fe28f35b5547b33075cdaec30c](https://user-images.githubusercontent.com/71695537/205842608-9a54641c-84e6-4e11-9456-377879417511.png)

![3cc215bd97a181235ed0ee3e98f6f0e](https://user-images.githubusercontent.com/71695537/205842633-ea8f423b-9e9f-4683-8e43-0e5d23f171f0.png)

### What did you expect to see?

changefeed removes task, the cdc's data will release.

### What did you see instead?

cdc sorter dir dose not release after removing task.

### Versions of the cluster

v6.4.0 arm

**Comment by nongfushanquan** [comment]
by the design
/close
