### ISSUE TITLE
TICDC OOM when upstream has large historical data

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#7850]
### What did you do?

1. create a blackhole changefeed and pause
2. using workload to insert 10000000 rows into 500 tables,  120 columns and 2k per row
3. resume changefeed.

pull based sink is disabled
```
[debug]
enable-pull-based-sink=false
```
### What did you expect to see?

NO OOM

### What did you see instead?

TICDC OOM

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
Release Version: v6.5.0-master-dirty
Git Commit Hash: 8ad66777c8fb21c61f11ca437909a79277653afc
Git Branch: master
UTC Build Time: 2022-12-07 06:07:33
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false
```

**Comment by nongfushanquan** [comment]
duplicated https://github.com/pingcap/tiflow/issues/7886
