### ISSUE TITLE
If tidb_enable_external_ts_read is set to on, Ticdc has no permission to synchronize data

### ISSUE THREAD

**Issue by nickzabc** [pingcap/tiflow#7854]
### What did you do?

set global tidb_enable_external_ts_read=on;

### What did you expect to see?

Succeeded in synchronizing data.

### What did you see instead?

"code": "CDC:ErrMySQLTxnError",
        "message": "[CDC:ErrMySQLTxnError]MySQL txn error: Error 1105: only support read-only statement during read-only staleness transactions"

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):
V6.4.0
```console
(paste TiCDC version here)
```

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/pull/7418#issuecomment-1289989369

The TiDB user should have a special privilege
