### ISSUE TITLE
CDC OOM when replicate 1000 tables

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#7886]
### What did you do?
1 cdc node, 16c 64g
1. create changefeed, pause changefeed
2. run sysbench oltp_insert 
3. resume changefeed

### What did you expect to see?

The old data synchronized successfully

### What did you see instead?

cdc OOM 
https://snapshots.raintank.io/dashboard/snapshot/N5a5fSz3brBZhbnVwmZyLUhI4f7nVKTG
![image](https://user-images.githubusercontent.com/61726649/207019201-86b9b74a-713a-4d6d-8a2b-81e2c66be9a7.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by fubinzh** [comment]
/affects-6.5
