### ISSUE TITLE
release-6.5 has large memory(object) allocation and deallocation

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#7898]
### What did you do?

run two cdc servers with release-6.5@https://github.com/pingcap/tiflow/commit/d520bc9915fe1c7d2ed45dea5519bbfb14eb928d, start a changefeed with 5000 tables. Observe the memory usage.

### What did you see instead?

Memory metrics

![image](https://user-images.githubusercontent.com/1527315/207283219-394a5851-9d2b-4e3f-9606-61660cbdda9d.png)

allocate_objects in heap profile

![image](https://user-images.githubusercontent.com/1527315/207283484-8fd01394-6b6b-4ddf-beea-a1209b192145.png)

heap profile raw file:
[heap.profile.with_table_stats_1.zip](https://github.com/pingcap/tiflow/files/10216562/heap.profile.with_table_stats_1.zip)

### Versions of the cluster

release-6.5@https://github.com/pingcap/tiflow/commit/d520bc9915fe1c7d2ed45dea5519bbfb14eb928d

**Comment by amyangfei** [comment]
- One memory allocate point is table.Stats
- The other one is sendResolvedTs in kv client

**Comment by MimeLyc** [comment]
refresh

**Comment by overvenus** [comment]
Will be fixed by #8015
