### ISSUE TITLE
TiCDC stuck on check tables if eligible to replicate

### ISSUE THREAD

**Issue by db-will** [pingcap/tiflow#7903]
### What did you do?

Start TiCDC within container with following command:

XXXX:~$ sudo docker run \
>     ...
>         cdc cli changefeed create  \
>     ...
Error: EOF
[WARN] some tables are not eligible to replicate, []model.TableName{model.TableName{Schema:"merchant_infra", Table:"xxxxxx", TableID:0, IsPartition:false}}
Could you agree to ignore those tables, and continue to replicate [Y/N]
EOF

### What did you expect to see?

can startup cdc successfully or providing useful info to continue

### What did you see instead?

Auto error out without meaningful instructions

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.1.0
```

Upstream TiKV version (execute `tikv-server --version`): v6.1.0

```console
v6.1.0
```

TiCDC version (execute `cdc version`): 

```console
v6.1.0
```

**Comment by CharlesCheung96** [comment]
Perhaps docker's interactive mode can solve the above problems, such as:
```bash
echo "Y"| docker run -i ...
```
