### ISSUE TITLE
CDC support TTL table

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tiflow#7997]
### Is your feature request related to a problem?

CDC should support TTL table

### Describe the feature you'd like

When a table is a TTL table in upstream, the downstream should turn off its `TTL_ENABLE` option to `OFF`

**Comment by nongfushanquan** [comment]
why should the downstream  turn off the ttl_enable option ?

**Comment by lcwangchao** [comment]
> why should the downstream turn off the ttl_enable option ?

It is a discussed conclusion with @SunRunAway . I think the main reason is the upstream will also sync delete operations to the downstream so we do not need to open TTL in the downstream. Another reason is that if `TTL_ENABLE` is on in the downstream cluster, there can be true that a row is deleted in the downstream but still exists in the upstream because of the downstream's TTL job. To avoid some confusing phenomenon, it's better to turn it off
