### ISSUE TITLE
CDC checkpoint not advance

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8001]
### What did you do?

1. Run cdc case:  redo_apply_multiple_workload_node_restart_sync

### What did you expect to see?

CDC checkpoint should advance normally

### What did you see instead?

CDC checkpoint not advance.

![d8c96b1e-8ca7-4f6f-b49a-426cc092f33d](https://user-images.githubusercontent.com/7403864/210049085-4ff69b5c-13b9-4a82-9bb2-fa59a731dc1c.jpeg)

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
[git-hash=d9c1cb5e4858455d872bf3a9503ce98835e6fc7b] [git-branch=heads/refs/tags/v6.6.0-alpha] [utc-build-time="2022-12-28 11:42:07"]
```

**Comment by fubinzh** [comment]
CDC log: [ticdc (18).log](https://github.com/pingcap/tiflow/files/10323604/ticdc.18.log)

**Comment by hicqu** [comment]
Close by https://github.com/pingcap/tiflow/pull/7996.
