### ISSUE TITLE
changefeed stuck when enabling pull based sink from v6.5.0

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#8007]
### What did you do?

1. Run a ticdc cluster in v6.5.0, with the `default` server config.
2. Create a changefeed with cdc ctl v6.5.0
3. Upgrade ticdc server config, setting `debug.enable-pull-based-sink` to true 
4. Observe replication status

### What did you expect to see?

Replication is normal

### What did you see instead?

Replication is stuck.

Event count in cdc keeps unchanged.
<img width="661" alt="Screenshot 2023-01-02 at 19 19 35" src="https://user-images.githubusercontent.com/1527315/210224453-d78e7765-4981-4a18-8e2c-ba5159764790.png">

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

TiCDC version (execute `cdc version`):

V6.5.0 -> master@https://github.com/pingcap/tiflow/commit/73bb333c8b8319ffcb402b676fefaf7bd51e1942

**Comment by hicqu** [comment]
We have some known issues of pull-based-sink in 6.5.0. There are some PRs not cherry-picked into 6.5 yet.
