### ISSUE TITLE
min_resolved_ts metric of a TiKV store will be frozen when it no longer has any captured regions

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiflow#8031]
### What did you do?

Suppose there are 2 neighboring regions R1, R2 each with different leaders T1, T2.

1. Create a CDC changefeed that observes a table X on R1
2. Merge R1 into R2, so that T2 becomes the new leader of R1 ∪ R2
3. Make sure the "TiCDC → TiKV → Captured region count" panel on Grafana is 0 for store T1
4. Check the "Min resolved ts" panel for store T1

### What did you expect to see?

There is no observable lag

### What did you see instead?

The min_resolved_ts of T1 is frozen and the min_resolved_lag is growing linearly.

![image](https://user-images.githubusercontent.com/103023/210969913-70d57302-945c-4107-be9d-778eb4562edc.png)

### Versions of the cluster

v6.1.1

**Comment by kennytm** [comment]
The issue here is that, when a TiKV's CDC endpoint has *no* `capture_regions`, its `min_resolved_ts` will forever be `TimeStamp::max()`

https://github.com/tikv/tikv/blob/cc9e69b925020e58b786bb811f1bcdba05a7c09f/components/cdc/src/endpoint.rs#L837-L872

This caused the metrics flusher to *never* update `tikv_cdc_min_resolved_ts` and `tikv_cdc_min_resolved_ts_region`, meaning they are frozen at the time when all of `capture_regions` are emptied.

https://github.com/tikv/tikv/blob/cc9e69b925020e58b786bb811f1bcdba05a7c09f/components/cdc/src/endpoint.rs#L1205-L1219

**Comment by kennytm** [comment]
This seems to affect the `tikv_cdc_region_resolve_status` gauge too, the value `self.resolved_region_count` is stuck at 1 because `on_min_ts` is simply not scheduled when capture_regions count drops to zero.

https://github.com/tikv/tikv/blob/v6.1.5/components/cdc/src/endpoint.rs#L868

https://github.com/tikv/tikv/blob/v6.1.5/components/cdc/src/endpoint.rs#L1050-L1051

**Comment by nongfushanquan** [comment]
This issue only affects one item of the metrics and will not affect the replication.

**Comment by hicqu** [comment]
It can be resolved by #9163 .
