### ISSUE TITLE
Performance optimization of GenUpdateSQL with multi updates

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#8057]
### Is your feature request related to a problem?

In a large update transaction scenario, we found high cpu usage with `github.com/pingcap/tiflow/pkg/sqlmodel.GenUpdateSQL (24.45%, 33.79s)`

![image](https://user-images.githubusercontent.com/1527315/211775373-f9888612-6c8d-433e-b658-a603fe2531a3.png)

cpu profile: [cdc.profile.zip](https://github.com/pingcap/tiflow/files/10391010/cdc.profile.zip)

### Describe the feature you'd like

Break down sub tasks
- [ ] Add more unit test cases to cover gen multi update scenario
- [ ] Add a GenUpdateSQLFast function to replace `GenUpdateSQL`, which remove the ast.Restore procedure, and generate SQL with template rendering.

**Comment by lance6716** [comment]
there's also other ways to avoid CPU consumption, like 
- don't need to generate for columns that are not changed
- cache the SQL per table, and invalidate it after DDL
- split into DELETE + INSERT
- use GenInsertSQL with DMLInsertOnDuplicateUpdate when PK/UK is not updated

**Comment by amyangfei** [comment]
This issue has been resolved.
