### ISSUE TITLE
CDC resolvedTs progress slowly when redo logging is enabled

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8074]
### What did you do?

- Create TiDB cluster in GCP
- Create changefeed with redo, storage is GCS 
```
[consistent]
level = "eventual"
storage = "gcs://qa-redo-log/redo-apply-multiple-cf0g92adj5hatumgaddg"` 
```
- Run tpcc workload （15:12 - ~16:30）
- Pause changefeed for about 1 hours, during with redo apply 2 time
- Workload stop (~16:30)
- Resume changefeed (~16:30)

### What did you expect to see?

Changefeed checkpoint should advance normally.

### What did you see instead?

- Changefeed doesn't advance for an hour after changefeed resume (puller is pulling)
- After that, sink starts to flush, but throughput is low (about 1024 rows/s)
![image](https://user-images.githubusercontent.com/7403864/212317595-2c72b0cc-3e44-464f-a73b-2a322bc8cc6a.png)

![image](https://user-images.githubusercontent.com/7403864/212317654-4b31b70f-16c6-4388-875b-584e13e497f5.png)

![image](https://user-images.githubusercontent.com/7403864/212317680-89eff553-9574-4a75-a6aa-95f015dc5d68.png)

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
bash-5.1# /cdc version
Release Version: v6.5.0-11-g3808d9732-dirty
Git Commit Hash: 3808d9732201b004147628abf4914fd2c5dd0711
Git Branch: release-6.5
UTC Build Time: 2023-01-10 06:19:02
Go Version: go version go1.19.1 linux/amd64
Failpoint Build: false
bash-5.1#
```

PD/TiDB/TiKV are v6.5.0

**Comment by fubinzh** [comment]
cdc log: [ticdc.log](https://github.com/pingcap/tiflow/files/10411483/ticdc.log)

**Comment by fubinzh** [comment]
After the error happens, I did another 2 testing:

1. Update changefeed to local, and resume changefeed => sink flush rows/s still about ~1024
![image](https://user-images.githubusercontent.com/7403864/212322008-cdfc00de-c781-4985-b6b8-1bbdc15fc961.png)

2. Enable pull based sink, resume changefeed from now,  run workload. => sink flush rows/s increases to ~2000
![image](https://user-images.githubusercontent.com/7403864/212320939-dda3a7ea-6a4f-42fa-83ab-2496cfb95feb.png)

3. Update changefeed  and close redo, resume changefeed. => sink flush rows/s increases to ~20K
![image](https://user-images.githubusercontent.com/7403864/212322291-90619e8f-1038-4bd0-9fcb-23e75b65965d.png)

**Comment by fubinzh** [comment]
CPU & Memory Usage:
![image](https://user-images.githubusercontent.com/7403864/212322677-87dbd3d0-7a03-4fc7-b145-158420d7d3d1.png)

**Comment by CharlesCheung96** [comment]
Monitor: https://snapshots.raintank.io/dashboard/snapshot/cYaeE8XKNO7tCvhF5Y5Px59yu0jRKe7d

**Comment by fubinzh** [comment]
Reproduced the issue as well, when CDC is configured to use SSD.

![image](https://user-images.githubusercontent.com/7403864/212465187-0dfd919f-0fac-4508-8127-427a71ae964e.png)

![image](https://user-images.githubusercontent.com/7403864/212465194-5828c095-a047-452f-8897-61faf738848f.png)

![image](https://user-images.githubusercontent.com/7403864/212465196-f4a44f43-3074-453e-8bd7-ac361a01532a.png)


[ticdc0.log](https://github.com/pingcap/tiflow/files/10417020/ticdc0.log)
[ticdc1.log](https://github.com/pingcap/tiflow/files/10417021/ticdc1.log)

monitor backup: https://snapshots.raintank.io/dashboard/snapshot/h74XS86BjNHyHTvu3u6FkYzO4dTN0ArJ
