### ISSUE TITLE
after restart all tikvs，pds，tidbs，one ticdc oom

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8091]
### What did you do?
 ticdc config：
"replica_config": {
"ignore_ineligible_table": true,
"memory_quota": 2147483648
}

1、run tpcc（qps：17k）
         warehouse: 1000
        threads: 64
2、restart all tikvs，pds，tidbs

### What did you expect to see?

ticdc are all normal

### What did you see instead?

one ticdc（ticdc1） oom
[2023/01/16 20:29:42.977 +08:00] [ERROR] [util.go:17] ["some components oom\n"] [error="Expected\n    <string>: tc-ticdc-1\nto equal\n    <string>: "] 
![image](https://user-images.githubusercontent.com/84712107/212850643-e5e53c6c-fef0-4ed9-a714-cda5e0d40493.png)

http://172.16.6.13:30690/d/YiGL8hBZ1/cluster-ticdc?orgId=1&from=1673871292802&to=1673873224531

### Versions of the cluster
/ # ./cdc version
Release Version: v6.6.0-alpha
Git Commit Hash: fb893519ef6ed6f20c5edf5e056d4472ba83f3e4
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-01-16 11:41:49
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false
/ # 

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by sdojjy** [comment]
can not reproduce this issue on the same env, reopen if happen again
