### ISSUE TITLE
CDC OOM when enable-pull-based-sink = true and memory-quota= 8GiB (CDC pod has 32GiB Memory) 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8103]
### What did you do?

1. Create TiDB cluster with 2 CDC (8C 32GiB), enable-new-sink true, enable-pull-based-sink true
2. Create redo log changefeed 
![a27c43af-6bf7-4a29-bdee-ab9a47fca1d8](https://user-images.githubusercontent.com/7403864/213074921-7dc6b570-9571-48fd-a063-c0999c83f409.jpeg)

3. Run tpcc workload to prepare 50 warehouse (/go-tpc tpcc --db workload --warehouses 200 -T 50 --host upstream-tidb.cdc-gcs-long-duration-tps-1353208-1-287 --port 4000 --parts 1 prepare)
4. Check CDC changefeed status

### What did you expect to see?

CDC should not OOM

### What did you see instead?

CDC OOMs

![97f3644d-842d-4f8e-a77a-e868533695e6](https://user-images.githubusercontent.com/7403864/213075092-36c38ec5-48d0-428f-86f9-5ae63e27dea0.jpeg)

### Versions of the cluster

/ # /cdc version                                         
Release Version: v6.5.0-master                           
Git Commit Hash: 313575909ff2ab93425acaab2adb3aedc0baf3d6
Git Branch: 6.5-8068-8075                                
UTC Build Time: 2023-01-17 09:14:54                      
Go Version: go version go1.19.3 linux/amd64              
Failpoint Build: false

**Comment by fubinzh** [comment]
monitor backup: https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters?query=cdc-gcs-long-duration-tps-1353208-1-287

**Comment by hicqu** [comment]
After fixed:
<img width="449" alt="图片" src="https://user-images.githubusercontent.com/8407317/217185290-e5160f92-a18a-4df9-be66-4f0852cd101d.png">
