### ISSUE TITLE
Replication manager in scheduler v3 logs too frequently

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tiflow#8166]
### What did you do?

1. create a changefeed with storage sink.
2. mock minio disk full space error.

### What did you expect to see?

replication manager logs in a reasonable manner.

### What did you see instead?

replication manager logs too frequently
![hmzGGZCjyS](https://user-images.githubusercontent.com/4409014/216300473-67842dc1-9b33-4fdc-a45f-2916fcdc64ec.jpg)

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
v6.6.0-alpha
```

**Comment by asddongmen** [comment]
fixed by #8674
