### ISSUE TITLE
Make cyclic replication stable and GA

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#817]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We have published the feature cyclic replication in 4.0.3, ref: https://github.com/pingcap/ticdc/issues/471
But this feature is not fully tested and refined. We will make an overall test on this feature, make it stable and reach the GA standard 

**Describe the feature you'd like:**

- [ ] Design test cases and pass the test
- [ ] Refine usage scenarios and restrictions

### Time

GanttStart: 2020-09-01
GanttDue: 2020-10-30
GanttProgress: 0%

## Workload estimation(person-day)

* Design: 5
* Develop & QA: 10
* Document: 3

**Comment by scsldb** [comment]
Reason for reprioritization: development complete, testing in progress, more important current development tasks.

**Comment by hi-rustin** [comment]
Turn it off, as we no longer continue to support that feature.
