### ISSUE TITLE
ticdc checkpoint lag is more and more when run tpcc due to conflict detect duration is big

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8244]
### What did you do?

one cluster：
1、br restore 1000 warehouse to upstream and tidb downstream
2、run tpcc with 32 threads
3、several hours later，create cdc changefeed with config
    			  "replica_config": {
				"ignore_ineligible_table": true,
				"memory_quota": 2147483648
			  }
4、checkpoint lag is less than 3s in hours
5、10 hours later，checkpoint lag became large and got bigger and bigger
![image](https://user-images.githubusercontent.com/84712107/218626838-d5d37b83-9884-4fa5-94aa-2bcc96c3e8ee.png)
![image](https://user-images.githubusercontent.com/84712107/218627329-4ef5b16a-0197-4610-8327-3b96867292a7.png)

another cluster
https://tcms.pingcap.net/dashboard/executions/plan/1620888
1、br restore 20000 warehouse to upstream and tidb downstream
2、create cdc changefeed with config
         			  "replica_config": {
				"ignore_ineligible_table": true,
				"memory_quota": 2147483648
			  }
3、run tpcc with 32 threads
4、checkpoint lag got bigger and bigger
![image](https://user-images.githubusercontent.com/84712107/218627237-f5701907-de11-44e3-adc7-f69c951c4f25.png)
![image](https://user-images.githubusercontent.com/84712107/218627406-8dec1e06-e32d-41ad-bb96-d344d7fdc95c.png)

### What did you expect to see?

checkpoint lag can not be too big

### What did you see instead?

ticdc checkpoint lag is more and more when run tpcc due to conflict detect duration is big

### Versions of the cluster

./tikv-server -V
 TiKV 
Release Version:   6.6.0
Edition:           Community
Git Commit Hash:   d7847d1be1a5176652dda0f182527615b5c22016
Git Commit Branch: heads/refs/tags/v6.6.0
UTC Build Time:    2023-02-12 08:08:03
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-02-13T18:09:35.786Z

sh-5.1# ./cdc version
Release Version: v6.6.0
Git Commit Hash: 30d4ca53fc52136b71d6f22c8248cf565af20832
Git Branch: heads/refs/tags/v6.6.0
UTC Build Time: 2023-02-11 12:11:03
Go Version: go version go1.19.5 linux/amd64
Failpoint Build: false

**Comment by sdojjy** [comment]
we did 2 tests
1. dryrun MySQL sink, the throughput is more than 100k
![0d9a0248-cb79-49a2-97eb-e71d89ee1357](https://user-images.githubusercontent.com/1779704/219266682-ddcedd6b-261a-4f89-9230-78545eb26e05.jpeg)
2. dryrun mysql sink with 20-400ms random latency, the throughput is about 10k
![a42176cf-8507-4b91-9f98-84638ac4fea9](https://user-images.githubusercontent.com/1779704/219266717-c1d61b4d-f443-4c39-94da-9fb0e7428637.jpeg)

from the above test results,  the downstream is the bottleneck.

**Comment by hi-rustin** [comment]
After testing, we found that this scenario exceeds the ability of the current TiCDC. So I am going to close this issue.
