### ISSUE TITLE
scale out from 2 to 3 CDC nodes doesn't improve pull speed 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8248]
### What did you do?

1. TiDB cluster with 1 CDC nodes, there is a big table with ~160K regions
2. Create a Kafka changefeed with region-per-span = 25000, check pull performance
3. Add one more CDC node, and re-create the changefeed with same configuration, and check pull performance
4. Add one more CDC node, and re-create the changefeed with same configuration, and check pull performance

### What did you expect to see?

Shen scale out from 2 CDC node to 3 CDC nodes, pull performance should increase

### What did you see instead?

Pull time changes as below when scale out CDC:
1 CDC: 15min
2 CDC: 8min
3 CDC: 7min

- 1 CDC
![image](https://user-images.githubusercontent.com/7403864/218657258-345c15b1-9115-42c9-8727-ad4fb6b3de64.png)

- 2 CDC
![image](https://user-images.githubusercontent.com/7403864/218657293-021303a0-68c0-4976-8a5a-3ac7f064d4f7.png)

- 3 CDC
![image](https://user-images.githubusercontent.com/7403864/218657323-ece7703b-d34e-4d50-8796-bd9cb6d27c67.png)

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
Release Version: 6.6.0-alpha
Git Commit Hash: 5444d2361c03bab714730456fb46768725ca7131
Git Branch: kafka-use-cached-topic-partition
UTC Build Time: 2023-02-13 04:41:15
Go Version: go version go1.19.1 linux/amd64
Failpoint Build: false
```

**Comment by overvenus** [comment]
From the metrics, we find TiKV ongoing scan tasks is full (by default 6), so the pull speed does not change.

![2d31d2dd-b833-4620-b74e-8fa8122b159a](https://user-images.githubusercontent.com/2150711/218693596-051eb38f-e4f4-4d6d-a79e-44e78e63d1a4.jpeg)

**Comment by overvenus** [comment]
Closed, see my previous comment.
