### ISSUE TITLE
ticdc oom when checkpoint lag is big

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8251]
### What did you do?

refer to https://github.com/pingcap/tiflow/issues/8244
after the case “ha-all-comp-restart” finish，some time later，ticdc oom
![iCCswLitti](https://user-images.githubusercontent.com/84712107/218702541-c3cb1e73-8959-4c82-a17b-ad311a047b35.jpg)

### What did you expect to see?

ticdc should not be oom

### What did you see instead?

ticdc oom when checkpoint lag is big

### Versions of the cluster

sh-5.1# ./cdc version
Release Version: v6.6.0
Git Commit Hash: https://github.com/pingcap/tiflow/commit/30d4ca53fc52136b71d6f22c8248cf565af20832
Git Branch: heads/refs/tags/v6.6.0
UTC Build Time: 2023-02-11 12:11:03
Go Version: go version go1.19.5 linux/amd64
Failpoint Build: false

**Comment by nongfushanquan** [comment]
please refer to 8244
/close
