### ISSUE TITLE
Check the message size of `canal-json` protocol

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#8274]
Now we do not check the message size of canal-json. So sometimes it would be too big and there would be no way to deliver it to the Kafka broker.

We should check its size with `max.message.bytes`. If it is too big, we need to report an error earlier.

We also need to give some tips for users on how to change their Kafka broker and topic configurations.

**Comment by zhaoxinyu** [comment]
BTW, the error message should also contain table information of which the encoded row size exceeds `max.message.bytes`

**Comment by kolbe** [comment]
We should also make it possible for a user to see the full contents of the oversized event.
