### ISSUE TITLE
ticdc mysql sink memory quota is always zero after inject pd leader networkpartition which will trigger pd leader change

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8293]
### What did you do?

https://tcms.pingcap.net/dashboard/executions/plan/1562736
1、br restore 20000 warehouse to upstream and tidb downstream
2、create cdc changefeed with config
"replica_config": {
"ignore_ineligible_table": true,
"memory_quota": 2147483648
}
3、run tpcc with 32 threads
4、checkpoint lag got bigger and bigger
5、run ha-pdleader-to-all-network-partition-last-for-10m（pd change leader）
     the time of pd leader changed : 2023-02-17 13:06
     and this time ticdc0 restart abnormally（issue：https://github.com/pingcap/tiflow/issues/8170）
     
![image](https://user-images.githubusercontent.com/84712107/219623083-c86a4d7a-48a3-4799-bc8d-9f7ad7b62e88.png)

### What did you expect to see?

ticdc mysql sink memory quota is normal as before 
![image](https://user-images.githubusercontent.com/84712107/219622305-59a7b83c-40e4-4954-b592-a19397cefa85.png)

### What did you see instead?

ticdc mysql sink memory quota is always zero after inject pd leader networkpartition which will trigger pd leader change

![image](https://user-images.githubusercontent.com/84712107/219621893-b5b43047-1ce7-4b41-aece-37cb603f0e77.png)

### Versions of the cluster

sh-5.1# ./cdc version
Release Version: v6.6.0
Git Commit Hash: feae75ed4c816da5df52e931cb936a97f619ae0e
Git Branch: heads/refs/tags/v6.6.0
UTC Build Time: 2023-02-15 15:38:00
Go Version: go version go1.19.5 linux/amd64
Failpoint Build: false

**Comment by asddongmen** [comment]
same as https://github.com/pingcap/tiflow/issues/8808
