### ISSUE TITLE
cdc server panic on send on closed channel

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#8313]
### What did you do?

exit the cdc instance by `ctrl + c`

### What did you expect to see?

nothing

### What did you see instead?

```
panic: send on closed channel

goroutine 3187 [running]:
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).Add(0x140028d9970, {0x54, {0x14002d82900, 0x12, 0x18}, {0x14002d82918, 0x12, 0x18}}, {0x14013986370, 0x1, ...})
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:164 +0x420
github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start.func3()
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:117 +0x27c
created by github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:106 +0x3cc
panic: send on closed channel

goroutine 3170 [running]:
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).Add(0x140028d9970, {0x52, {0x14002d828a0, 0x12, 0x18}, {0x14002d828b8, 0x12, 0x18}}, {0x140144061f0, 0x1, ...})
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:164 +0x420
github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start.func3()
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:117 +0x27c
created by github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:106 +0x3cc
panic: send on closed channel

goroutine 3153 [running]:
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).Add(0x140028d9970, {0x53, {0x14002d828d0, 0x12, 0x18}, {0x14002d828e8, 0x12, 0x18}}, {0x1400b6054d0, 0x1, ...})
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:164 +0x420
github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start.func3()
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:117 +0x27c
created by github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:106 +0x3cc
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by asddongmen** [comment]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52b29b6]

goroutine 616 [running]:
github.com/cockroachdb/pebble.Open.func1()
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/open.go:112 +0x21e
panic({0x74211a0, 0xe586390})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/cockroachdb/pebble/internal/manifest.(*L0Sublevels).InUseKeyRanges(0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/internal/manifest/l0_sublevels.go:887 +0x76
github.com/cockroachdb/pebble.calculateInuseKeyRanges(0xc000628500, 0x7c30630, 0x0, 0x6, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/compaction.go:664 +0xda
github.com/cockroachdb/pebble.(*compaction).setupInuseKeyRanges(0xc0001feb00)
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/compaction.go:648 +0x1c5
github.com/cockroachdb/pebble.newFlush(0xc000852240, 0xc000628500, 0x3f?, {0x0, 0x0, 0x0}, 0xc00276a910)
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/compaction.go:639 +0x1053
github.com/cockroachdb/pebble.(*DB).replayWAL(0xc00276a900, 0xc000889200?, 0xc002cebd50, {0x97a5720, 0xc000888320}, {0xc00282c840, 0x3f}, 0x2, 0x0)
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/open.go:680 +0x191d
github.com/cockroachdb/pebble.Open({0xc00282c000, 0x34}, 0xc000852000)
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/open.go:346 +0x5199
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.OpenPebble(0xca3a07c?, {0xc0006a5d10, 0x2f}, 0x1b7b8d7?, 0x96ecb2cc, {0xc002cec0f0, 0x1, 0xc002f00c00?})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/db.go:111 +0x634
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/factory.createPebbleDBs({0xc0006a5d10, 0x2f}, 0xc00021c850, 0x4b7659666)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/factory/pebble.go:60 +0x3d7
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/factory.(*SortEngineFactory).Create(0xc000773b00, {{0xc0026af6d2?, 0xc002f7e200?}, {0xc0026af6ea?, 0x2?}})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/factory/factory.go:83 +0x2b4
github.com/pingcap/tiflow/cdc/processor.(*processor).lazyInitImpl(0xc00084dce0, {0x9786e10, 0xc002864408})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/processor.go:681 +0xe05
github.com/pingcap/tiflow/cdc/processor.(*processor).tick(0xc00084dce0, {0x9786e10?, 0xc002864408})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/processor.go:557 +0x122
github.com/pingcap/tiflow/cdc/processor.(*processor).Tick(0xc00084dce0, {0x9786e10, 0xc002864408})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/processor.go:485 +0x4ec
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc0012ed310, {0x7fd4337f4518?, 0xc0026d4be0}, {0x974a050?, 0xc00081f440})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/manager.go:145 +0xac5
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc000e24790, {0x7fd4337f4518, 0xc0026d4be0}, 0xc001225d40, 0x2faf080, {0x7a66836, 0x9})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0x1627
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc000075680, {0x9786eb0?, 0xc0026d4be0}, {0x7fd3e88ea008, 0xc0012ed310}, {0x974a050, 0xc00081f440}, 0x2?, {0x7a66836, 0x9})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:500 +0x226
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:354 +0x356
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x87
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x12f

I found another panic.
