### ISSUE TITLE
`processor.Close` is blocked by `SourceManager.Close`

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#8329]
### What did you do?

Rolling upgrade TiDB and TiCDC cluster.

Changefeed lag is increasing and TiCDC OOM due to `processor.Close` is blocked between

https://github.com/pingcap/tiflow/blob/40ba4175a57a45d5facabe1e8f876368ca3a9b59/cdc/processor/processor.go#L958-L971

Because there is a log "Processor try to close source manager" but no "Processor closed source manager successfully" or "Failed to close source manager".

It also causes OOM on agent receiving message.

### What did you expect to see?

Lag is steady and no OOM.

### What did you see instead?

Changefeed lag is increasing and TiCDC OOM.

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
40ba4175a57a45d5facabe1e8f876368ca3a9b59
```

**Comment by amyangfei** [comment]
Could you please provide cdc logs @AkiraXie
