### ISSUE TITLE
ticdc start after 40min when this ticdc recover from network partition 

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8383]
### What did you do?
1、br restore data
2、create changefeed
3、run tpcc 
4、inject one ticdc network partition last for 10m and recover fault
fault start time：2023-02-27 08:22:43
fault recover time：2023-02-27 08:32:43

### What did you expect to see?

ticdc can run normally after network recover

### What did you see instead?

ticdc start after 40min when this ticdc recover from network partition 
![image](https://user-images.githubusercontent.com/84712107/221533735-bb787b3e-c041-4cbc-8ceb-e2815af68e05.png)

### Versions of the cluster

./cdc version
 Release Version: v6.7.0-alpha
Git Commit Hash: 00bfd0d0580d59977adf91ea9c1e237f787d0b6c
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-02-25 11:32:40
Go Version: go version go1.20.1 linux/amd64
Failpoint Build: false

**Comment by fubinzh** [comment]
not reproducible now.
/close

**Comment by Lily2025** [comment]
not reproducible now.
