### ISSUE TITLE
PD etcd storage full and out of service when CDC changefeed with error to connect to downstream mysql 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8425]
### What did you do?

1. Change downstream mysql setting: set global max_connections = 20000;
2. Create 50 kafka changefeeds, 50 MySQL changefeeds
3. Running workload
4. Kill downstream MySQL, and wait it is created by K8S, change dowstream mysql setting: : set global max_connections = 150;

### What did you expect to see?

Some mysql changefeed will run into error because of failing to connect to downstream mysql. PD should still be able to service.
```
  {
    "id": "cdc-large-number-changefeed-mysql7",
    "namespace": "default",
    "summary": {
      "state": "error",
      "tso": 439829624507596801,
      "checkpoint": "2023-03-03 04:14:25.950",
      "error": {
        "addr": "upstream-ticdc-0.upstream-ticdc-peer.cdc-testbed-tps-1653470-1-820.svc:8301",
        "code": "CDC:ErrMySQLConnectionError",
        "message": "[CDC:ErrMySQLConnectionError]fail to open MySQL connection: Error 1040: Too many connections"
      }
    }
  },

```

### What did you see instead?

PD etcs storage consumption increases rapidly and reach the limit of 8GB, and finally PD is out of service.

etcd storage usage metric when the issue happens:
![08b65de9-d9f6-476d-a4c1-4b8cd34ad42c](https://user-images.githubusercontent.com/7403864/222640870-5024118a-80f8-4c4e-bf3d-211ba753120c.jpeg)

etcd storage usage metric previously (when downstream MySQL max_connections doesn't decrease to 150)
![img_v2_06b0f81d-797d-4336-8430-d93b076fbb7g](https://user-images.githubusercontent.com/7403864/222641035-63c3c4c4-33b3-408d-94ae-91198b2fd571.jpg)

### Versions of the cluster

TiCDC version (execute `cdc version`):
latest master, and be able to reproduce with 03/21commit 4dcf1396ff8fc9e20bd424e069195bf06442182e
```console
4dcf1396ff8fc9e20bd424e069195bf06442182e
```

PD version:
```
Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: a99ff9f67bbf8eb83b9aec5a3f3e7aa81c8796ab
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:  2023-03-02 11:32:29

```

**Comment by overvenus** [comment]
This issue does not affect any release and only be triggered when there are lots of changefeeds in error state.
