### ISSUE TITLE
after inject pdleader network partition last for 10m，ticdc changefeed lag is more and more

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8479]
### What did you do?

https://tcms.pingcap.net/dashboard/executions/plan/1655438
run tpcc （1000 warehouse with 32 threads）
inject pdleader network partition last for 10m
[2023/03/08 15:24:23.579 +08:00] [INFO] [chaos.go:150] ["Run chaos"] [name=network_partition] [selectors="[endless-ha-test-tps-1655438-1-603/tc-pd-1]"] [SelectorsRetainPolicy(selectors)="[endless-ha-test-tps-1655438-1-603/tc-pd-1]"] 

### What did you expect to see?

ticdc changefeed lag less than 30s

### What did you see instead?

after inject pdleader network partition last for 10m，ticdc changefeed lag is more and more

clinic: https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7208067513104263723?from=1678259639&to=1678261493
logs: http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLWhhLXRlc3QtdHBzLTE2NTI3NTQtMS0yMjc=
![6fa13ad5-4571-4441-b9f6-aa61a28c1b85](https://user-images.githubusercontent.com/84712107/223970280-e3d6972a-9a34-4c9c-b09e-b391c0562976.jpeg)

### Versions of the cluster

./cdc version
 Release Version: v6.7.0-alpha
Git Commit Hash: f43dfb2cbc64a792d602b28398d5024c82e94ad7
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-03-07 11:34:11
Go Version: go version go1.20.1 linux/amd64
Failpoint Build: false

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by nongfushanquan** [comment]
duplicated with https://github.com/pingcap/tiflow/issues/8808 and fixed by https://github.com/pingcap/tiflow/pull/9118
