### ISSUE TITLE
TiCDC can't recover after TiDB of upstream OOM

### ISSUE THREAD

**Issue by WangLe1321** [pingcap/tiflow#8561]
### What did you do?

TiDB of upstream has too high qps and connections, causing TIDB OOM.
metrics of TiDB:
https://clinic.pingcap.com/grafana/d/000000013tidbcloudv6_1_x/tidb-runtime-cluster-clinic?orgId=1&var-tidb_cluster=1379661944640134080&var-instance=All&var-store=All&from=1678407999000&to=1678415199000&var-tidb_version=v6.1.x&var-org=1372813089196917631&refresh=15m&var-org_type=cloud
https://clinic.pingcap.com/grafana/d/2bbdcd7d4d88a2dtidbcloudv6_1_x/tidb-summary-cluster-clinic?orgId=1&var-tidb_cluster=1379661944640134080&var-instance=All&var-store=All&from=1678407999000&to=1678415199000&var-tidb_version=v6.1.x&var-org=1372813089196917631&refresh=15m&var-org_type=cloud
https://clinic.pingcap.com/portal/#/orgs/1372813089196917631/clusters/1379661944640134080/report/5/fed8c3b6-fe7a-48f7-80e1-100dacf18938 

after scale up TiDB nodes, TiDB recovered.

### What did you expect to see?

After TiDB recovered, cdc should reduce lag.

### What did you see instead?

cdc lag is still high.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

https://clinic.pingcap.com/portal/#/orgs/1372813089196917631/clusters/1379661944640134080

cluster version is v6.1.3

**Comment by fubinzh** [comment]
The issue can be work around per https://github.com/pingcap/tiflow/issues/4516#issuecomment-1049540773

**Comment by MimeLyc** [comment]
update
