### ISSUE TITLE
Panic occurs when table scheduling frequently in 100k table scenario.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#8663]
### What did you do?

as title.

### What did you expect to see?

no panic

### What did you see instead?

panic: Table sink not found when removing table

goroutine 1010301 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x3?, 0x3?, {0x0?, 0x0?, 0xc72769f800?})
	go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc532cc5860, {0xc6d5239b00, 0x3, 0x3})
	go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc00009ea00?, {0x3e735ae?, 0x414ca5?}, {0xc6d5239b00, 0x3, 0x3})
	go.uber.org/zap@v1.24.0/logger.go:258 +0x59
github.com/pingcap/log.Panic({0x3e735ae?, 0xc6d5239b80?}, {0xc6d5239b00?, 0x12?, 0x18?})
	github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x8b
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).AsyncStopTable.func1()
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:767 +0x5be
created by github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).AsyncStopTable
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:758 +0x105
[root@perf7 log]# grep "PANIC" cdc.log
[2023/03/23 19:59:52.209 +08:00] [PANIC] [manager.go:767] ["Table sink not found when removing table"] [namespace=default] [changefeed=test] [span={table_id:208816,start_key:748000000000032fffb05f720000000000fa,end_key:748000000000032fffb05f730000000000fa}] [stack="github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).AsyncStopTable.func1\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:767"]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
PR:https://github.com/pingcap/tiflow/pull/8633 
```

**Comment by asddongmen** [comment]
## Investigation

The root cause of this issue is that when a table needs to be moved or deleted, the owner continuously sends remove table tasks to the processor.

After receiving the remove table task, the processor calls `sinkManager.AsyncStopTable` to stop the table if the state of the table has not entered the `tablepb.TableStateStopping` or `tablepb.TableStateStopped` state.

This function uses a goroutine to stop the table, which may be stopped by the go scheduler in some cases, causing the table's state to remain unchanged after multiple rounds of processor ticks into the `tablepb.TableStateStopping` or `tablepb.TableStateStopped` state.

At this point, if the owner sends multiple remove table tasks continuously, the `AsyncStopTable` logic will be executed multiple times, and multiple goroutines will be derived.

Some goroutines may have been stopped by the scheduler before executing [[line:761](https://github.com/pingcap/tiflow/blob/master/cdc/processor/sinkmanager/manager.go#L761)](https://github.com/pingcap/tiflow/blob/master/cdc/processor/sinkmanager/manager.go#L761), and we call these goroutines `G-left`. However, some goroutines can successfully execute and exit, and the successfully executed goroutines will set the state of the table to `tablepb.TableStateStopped`.

In a later round of tick, when the processor receives the remove table task again, the state of the table may have been changed to `tablepb.TableStateStopped`. Then it will enter the function `t.executor.IsRemoveTableSpanFinished(t.span)`, which will remove the table from the `sinkManager`.

After that, if `G-left` is rescheduled by the scheduler to execute, it may reach the line of code that causes the Panic.

## Solution

I think there is no need to panic here. If the corresponding table is not found when removing the table, just ignore it.

This will not cause correctness issues.

/cc @hi-rustin @overvenus

**Comment by overvenus** [comment]
Pre tablepipeline implementation, it ignores remove table requests if the table is removing or already removed.
