### ISSUE TITLE
ticdc lag reached 11min when run ha_ticdc(owner)_to_tikv(random)_network_partition last for 10m

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8677]
### What did you do?

http://perf.pingcap.net:3000/d/C1q8KDMVz/ha-test-summary?orgId=1&var-tag=All&var-case_name=All&var-testbed=endless-ha-test-tps-1658429-1-754
http://perf.pingcap.net:3000/d/WOw1JWmVk/ha-test-case-detail?orgId=1&refresh=10s&var-case_id=2820535
run ha_ticdc(owner)_to_tikv(random)_network_partition

### What did you see instead?

ticdc lag reached 11min when ha_ticdc(owner)_to_tikv(random)_network_partition last for 10m
![image](https://user-images.githubusercontent.com/84712107/227457928-b5af5741-59a0-43e2-a030-6ac81de163ed.png)

### Versions of the cluster

git hash
92cc5155c8224ae787898379016e1a7dfc4649b7

**Comment by nongfushanquan** [comment]
the behavior is expected  by the design.
/close

**Comment by asddongmen** [comment]
There is no mitigation of this issue.
