### ISSUE TITLE
ticdc lag reached 42min when run ha_tikv(random)_data_io_hang last for 40m

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8678]
### What did you do?

1、run tpcc with threads 10 and warehouse 1000
2、After 10 minutes, simulates the io of one tikv is hang but the pod is still active
fault start time：2023-03-18 12:48:57
3、After 40 minutes, recovery the fault
fault recover time：2023-03-18 13:28:58

### What did you expect to see?
changefeed lag is less than 30s

### What did you see instead?
changefeed lag reached 42min after inject fault

![image](https://user-images.githubusercontent.com/84712107/227459095-d436975b-c1fd-4130-af1f-b47c96a818c4.png)

### Versions of the cluster

git hash
92cc5155c8224ae787898379016e1a7dfc4649b7

**Comment by zhangjinpeng1987** [comment]
@Lily2025 Please describe the detailed test steps, not just the test case name.

**Comment by zhangjinpeng1987** [comment]
How long the IO hang lasted? Hang for ever or just slow the IO(like increase the fsync latency to 1s) of this TiKV?

**Comment by Lily2025** [comment]
> How long the IO hang lasted? Hang for ever or just slow the IO(like increase the fsync latency to 1s) of this TiKV?
IO hang lasted for 40m，simulate io can not write to disk

**Comment by nongfushanquan** [comment]
Since the I/O is hanging in the TiKV node, the Raft log cannot be applied successfully, and as a result, the resolved timestamp will not advance. However, the heartbeat among TiKV nodes is in another thread and continues to operate normally. Therefore, TiKV cannot detect this abnormal situation.So the lag keeps increasing until the injection is finished.

**Comment by nongfushanquan** [comment]
By design
/close

**Comment by Lily2025** [comment]
lag reached 270s when inject one of tikv io delay 500ms last for 10mins
![image](https://github.com/pingcap/tiflow/assets/84712107/afd784a5-064a-49a6-a21a-296517ef835a)
