### ISSUE TITLE
ticdc lag reached 5min when run ha_pdleader_time_offset last for 10m

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8679]
### What did you do?
1、run tpcc with threads 10 and warehouse 1000
2、After 10 minutes, simulates the time of pd leader is 5 minutes earlier
fault start time：2023-03-18 06:53:11
3、After 10 minutes, recovery the fault
fault recover time：2023-03-18 07:03:11

### What did you expect to see?
changefeed lag is less than 30s

### What did you see instead?
changefeed lag reached 5min

![image](https://user-images.githubusercontent.com/84712107/227460407-0645709d-f518-43b9-9aeb-6a622fa4e626.png)

### Versions of the cluster
git hash
92cc5155c8224ae787898379016e1a7dfc4649b7

**Comment by asddongmen** [comment]
The time drift of the PD affects TiCDC's checkpoint lag calculation. However, this only results in a metric calculation error and does not impact the actual replication progress. @Lily2025

**Comment by fubinzh** [comment]
I think we can close this issue per the comment above.

**Comment by Lily2025** [comment]
lgtm
