### ISSUE TITLE
ticdc lag reached 10min when run ha_tikv(random)_to_pdleader_network_partition last for 10m

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8681]
### What did you do?
1、run tpcc with threads 10 and warehouse 1000
2、After 10 minutes, simulates one of tikv is network isolated from the leader of pd
fault start time：2023-03-18 09:04:36
3、After 10 minutes, recovery the fault
fault recover time：2023-03-18 09:14:37

### What did you expect to see?
changefeed lag is less than 30s

### What did you see instead?
changefeed lag is reached 10min after inject fault

![image](https://user-images.githubusercontent.com/84712107/227461148-a3e35525-9ea3-4fb7-8263-5ca219bbfe3c.png)

### Versions of the cluster

git hash
92cc5155c8224ae787898379016e1a7dfc4649b7

**Comment by nongfushanquan** [comment]
make sure this behavior can be  monitored

**Comment by zhangjinpeng1987** [comment]
Can we recognize this partial network partition issue and transfer leaders from this isolated TiKV to other TiKV nodes? cc @nongfushanquan

**Comment by zhangjinpeng1987** [comment]
@Lily2025 Please describe the detailed test steps, not just the test case name.

**Comment by YuJuncen** [comment]
In fact we have implemented connecting to followers and let them forward the messages to leader at https://github.com/tikv/tikv/pull/9753. But this is default off because we may suffer a latency penalty when there are temporary network unavailable.

**Comment by YuJuncen** [comment]
I have tried to retrigger the case with `pd.enable-forwarding = true`: https://tcms.pingcap.net/dashboard/executions/plan/1808219

**Comment by zhangjinpeng1987** [comment]
@YuJuncen Please don't include internal link in github issue/pr

**Comment by YuJuncen** [comment]
Due to this can be fixed by changing the TiKV config term [`pd.enable-forwarding`]( https://docs.pingcap.com/tidb/stable/tikv-configuration-file#pdenable-forwarding-new-in-v500), close it for now. Feel free to reopen it when further discussion needed.
