### ISSUE TITLE
Time zone names that are valid in MySQL e.g. "+08:00" are rejected from the changefeed parameter

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiflow#8781]
### What did you do?

Create a changefeed to `mysql://root@password:127.0.0.1:3306/?time-zone=%2B08:00`

### What did you expect to see?

Changefeed successfully created

### What did you see instead?

```
[CDC:ErrMySQLInvalidConfig]MySQL config invalid: unknown time zone ' 08:00'
```

### Versions of the cluster

TiCDC 6.5.1

MySQL 5.7.37

(the downstream MySQL user has no permission to populate `mysql_tzinfo_to_sql`)

**Comment by hi-rustin** [comment]
You can find more details in[ this doc.](https://pingcap.feishu.cn/docx/DcGMd41xsoo2NWxZRrzcCQKknfb)

We found another bug if you do not set the timezone in the sink-URI, it will always use UTC when you create the changfeed.

**Comment by hi-rustin** [comment]
> 2\. it only verifies against the local tzdatabase via `time.LoadLocation`, but MySQL also permits `"SYSTEM"` and `"±HH:MM"`.
> 
> The second point is already handled by DM's `utils.ParseTimeZone` function. DM and TiCDC should share the same time zone name parsing function.

After discussed with the TiCDC team, we decided to do not to support it. You can see more at [this doc](https://pingcap.feishu.cn/docx/DcGMd41xsoo2NWxZRrzcCQKknfb#Q2cid8YCgoKkeWxsfyMc4DjLnZb).
The reasons are:
1. The timezone setting of TiCDC is already complicated enough. We don't want to introduce more complexity now.
2. The digital time zone does not handle the time zone correctly. This introduces an additional processing burden for users with winter and summer time zones (need to update time zones of TiCDC according to time zone changes. For Chicago users, they need to switch to -5:00 or -6:00).
3. TiCDC currently does not have the ability to automatically guarantee that the server and sink use the same time zone. Therefore, there is a possibility of the above problem. (We will phase out the configuration on the server, but we should not expand its complexity until then)
4. If we fix the second issue below, most users will automatically use the system's time zone. This should cover most users for now.

If you have any ideas about it, please feel free to comment.

**Comment by hi-rustin** [comment]
I am going to close this issue and open a new issue to track other bugs from [this doc](https://pingcap.feishu.cn/docx/DcGMd41xsoo2NWxZRrzcCQKknfb#Q2cid8YCgoKkeWxsfyMc4DjLnZb).

**Comment by kennytm** [comment]
I'd like to note that in order to support tzdb timezones like `America/New_York` in MySQL the user has to manually populate the [time zone *system* tables](https://dev.mysql.com/doc/refman/8.0/en/system-schema.html#system-schema-time-zone-tables) using `mysql_tzinfo_to_sql` which typically requires `root` **and** [restarting the MySQL server](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html#time-zone-installation), which is very hard to do on production. Even worse these tables aren't populated by default so typically you can't rely on `America/New_York` or even the string `UTC` working. 

The DST thing is a non-issue. No one in those area will use `time-zone=-06:00` because they *know* the offset is going to change every half-year. But this would potentially be used a lot in places with a fixed time zone offset (mostly Asia, Africa and South America) given that setting to `+05:30` doesn't require any special setup.

> If we fix the second issue below, most users will automatically use the server's time zone. This should cover most users for now.

@hi-rustin what is "the second issue below"

**Comment by hi-rustin** [comment]
> @hi-rustin what is "the second issue below"

In [this doc](https://pingcap.feishu.cn/docx/DcGMd41xsoo2NWxZRrzcCQKknfb#Q2cid8YCgoKkeWxsfyMc4DjLnZb).
