### ISSUE TITLE
ticdc lag is more than 10m after inject pdleader network partition to all

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8808]
### What did you do?

inject pdleader network partition
http://perf.pingcap.net:3000/d/WOw1JWmVk/ha-test-case-detail?orgId=1&refresh=10s&var-case_id=2731539

### What did you expect to see?
ticdc lag is less than 30s
![34cb2477-6bc3-4f10-8e1a-8992ea76046e](https://user-images.githubusercontent.com/84712107/232943320-e6d56d52-b207-4a5d-a135-5d646e5bf493.jpeg)

### What did you see instead?

ticdc lag is more than 10m after inject pdleader network partition

### Versions of the cluster

git hash：5252420517ce5497ed053aa6322fdb2a33f898e1

**Comment by fubinzh** [comment]
This issue is seen when testing with 6.5 nightly build.
![image](https://github.com/pingcap/tiflow/assets/7403864/92725bd8-b923-42d4-a940-654f491d8548)

bash-5.1# /cdc version
Release Version: v6.5.0-nightly
Git Commit Hash: 2ab025eb9de3ae76d13db953f00bb170d50ef9a8
Git Branch: heads/refs/tags/v6.5.0-nightly

**Comment by asddongmen** [comment]
This issue is mitigated by https://github.com/pingcap/tiflow/pull/9661, so I change its severity to moderate.

**Comment by asddongmen** [comment]
![img_v2_fd85ed6b-0f1c-473e-aa08-130401676f8g](https://github.com/pingcap/tiflow/assets/20351731/627fa4b7-72d1-4e04-8d5e-43ddaf80a69b)
![img_v2_d6217e6b-78d1-452e-8d32-d7d06f844a5g](https://github.com/pingcap/tiflow/assets/20351731/75dc15be-6f80-4f0b-a51a-08979dc2a5f2)

**Comment by asddongmen** [comment]
The daily HA test results from the past year indicate that the lag consistently remains within 1 minute. This meets our RPO goal, leading me to close this issue.
