### ISSUE TITLE
ticdc lag is more than 4m after inject one tikv network partition to all

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8809]
### What did you do?
1、run tpcc with threads 10 and warehouse 1000
2、After 10 minutes, simulates one of tikv is network isolated from other all pods
fault start time：2023-04-18 10:44:27
3、After 10 minutes, recovery the fault
fault recover time：2023-04-18 10:54:27

### What did you expect to see?
changefeed lag is less than 30s

### What did you see instead?
ticdc lag is more than 4m after inject fault
![image](https://user-images.githubusercontent.com/84712107/232949165-59f36ee1-a62e-43da-bc40-58dfcaa5508b.png)

### Versions of the cluster

git hash：5252420517ce5497ed053aa6322fdb2a33f898e1

**Comment by nongfushanquan** [comment]
By the design
/close

**Comment by zhangjinpeng1987** [comment]
Does this issue can be fixed by https://github.com/pingcap/tiflow/issues/8858 ?

**Comment by nongfushanquan** [comment]
fixed by the  https://github.com/pingcap/tiflow/pull/9771
