### ISSUE TITLE
The etcd client  does not use auto-sync and fails when the PD cluster address changed

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#8812]
# reproduce step

Start a TiDB cluster with 3 PDs ① ② ③ and a ticdc connected
Scale-out 3 more PDs ④ ⑤ ⑥
Wait 31 seconds
Scale-in the original PDs ① ② ③

ticdc is restarted.

**Comment by asddongmen** [comment]
TiCDC may shutdown or get stuck when in this scenario.

**Comment by asddongmen** [comment]
ref: https://github.com/pingcap/tiflow/issues/8802
