### ISSUE TITLE
Workload not splitted to CDC nodes though enable_table_across_nodes = true

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8821]
### What did you do?

1. Deploy a Cluster with 36 TiKVs, 2 CDC, prepare a big table over 50TB, 580K regions
2. Create Kafka changefeed enabling scaling out 
```
"scheduler": {
      "enable_table_across_nodes": true,
      "region_threshold": 100000,
      "write_key_threshold": 20000
    },
```
3. Run workload

### What did you expect to see?

Workload sync should be splitted to 2 CDC nodes

### What did you see instead?

Only one CDC node is syncing data to downstream Kafka

The big table is split to 2 spans:
![image](https://user-images.githubusercontent.com/7403864/233305353-a899a482-5f2d-4779-afaa-1cfa88e26ab6.png)

Only one CDC is pulling data
![image](https://user-images.githubusercontent.com/7403864/233305624-e0bb146f-42d5-4921-8609-fc5773871d0e.png)

There seems to be a hot spot issue for the workload, only few TiKV with high CPU usage
![image](https://user-images.githubusercontent.com/7403864/233305067-e352ed77-5934-4233-9779-c4ccf20aa7ff.png)

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
Release Version: v7.1.0-alpha
Git Commit Hash: c135676a1eb1f4455946e724dba9d5796a2aca73
Git Branch: heads/refs/tags/v7.1.0-alpha
UTC Build Time: 2023-04-18 11:32:51
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false

```

**Comment by asddongmen** [comment]
Fixed after we use a properly wokrload.
