### ISSUE TITLE
Kafka Sink: add support for OAUTHBEARER mechanism

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#8865]
### Is your feature request related to a problem?

When I using TiCDC Kafka sink, I can not connect to the Kafka server if I use OAUTHBEARER mechanism for authentication.

### Describe the feature you'd like

add support for OAUTHBEARER mechanism.

**Comment by hi-rustin** [comment]
You can see more at https://pingcap.feishu.cn/docx/ShDydVqtyo4dL6xAbPGctTdFn8c

**Comment by nongfushanquan** [comment]
fixed in the version 6.1 by the pr https://github.com/pingcap/tiflow/pull/9146
