### ISSUE TITLE
CDC lag >10s when upgrade TiKV

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8870]
### What did you do?

1. ti-operator cluster with 36 tikv, 3 cdc, 3 pd, create changefeed to sync to kafka
2. running workload, throughtput ~50MB/s
3. Upgrade cluester

### What did you expect to see?

lag should be less then 10s

### What did you see instead?

lag > 10s when uprade TiKV
![image](https://user-images.githubusercontent.com/7403864/234781305-d06a071c-a1db-41bf-8cfe-5f9ec5e97a3f.png)
![image](https://user-images.githubusercontent.com/7403864/234781966-abbf9338-6f2f-4ab6-8188-b9b6aec0d645.png)

### Versions of the cluster

[root@upstream-ticdc-0 /]# /cdc version
Release Version: v7.1.0-rc.0
Git Commit Hash: https://github.com/pingcap/tiflow/commit/4d633bfd28c0305109c52a01cd1304b436c0dfba
Git Branch: heads/refs/tags/v7.1.0-rc.0
UTC Build Time: 2023-04-21 10:14:01
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false

**Comment by asddongmen** [comment]
This issue can be alleviated by https://github.com/pingcap/tiflow/commit/5e06aa72e76291a641a65c1cb1688302ecd4c969

**Comment by asddongmen** [comment]
This issue can be alleviated by https://github.com/pingcap/tiflow/commit/5e06aa72e76291a641a65c1cb1688302ecd4c969

**Comment by nongfushanquan** [comment]
the lag  is closely related to the number of regions.If lots of regions on one node ,the lag will larger than 10s occasionally. In this case , there are more than 20k regions on one node
