### ISSUE TITLE
CDC changefeed stucks after CDC upgrade

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8880]
### What did you do?

1. ti-operator cluster with 36 tikv, 3 cdc, 3 pd, create changefeed to sync to kafka
2. running workload, throughtput ~40MB/s
3. upgrade cluster

### What did you expect to see?

 CDC lag <10s during CDC upgrade

### What did you see instead?

CDC lag stucks
![image](https://user-images.githubusercontent.com/7403864/236174330-efe2a993-4d7e-4e57-8a0b-d46aaabbbf38.png)

![image](https://user-images.githubusercontent.com/7403864/236174122-cd6bcf6a-e8a8-4cd2-916d-61ca7f4f4c4b.png)

### Versions of the cluster

[root@upstream-ticdc-0 /]# /cdc version
Release Version: v7.2.0-alpha
Git Commit Hash: cd77136707139ceb9867e38fc1eb46371908b83c
Git Branch: heads/refs/tags/v7.2.0-alpha
UTC Build Time: 2023-04-27 11:32:11
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false

**Comment by fubinzh** [comment]
similar issue seen when upgrade 4 ticdc nodes, ticdc worloads not balanced after upgrade.
![image](https://user-images.githubusercontent.com/7403864/236618102-e36a389d-593c-4f03-b1b6-56003aca3ec1.png)

**Comment by asddongmen** [comment]
This error is caused by the wrong version tag in the TiCDC image. It no longer occurs when we use the correct version tag.
