### ISSUE TITLE
It takes 30 minutes before changefeed lag is normal when resuming changefeed with --overwrite-checkpoint-ts=now

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8883]
### What did you do?

1. ti-operator cluster with 36 tikv, 3 cdc, 3 pd, create changefeed to sync to kafka
2. running workload, throughtput ~40MB/s
3. there was a changefeed whose lag was >5h
4. resume changefeed with --overwrite-checkpoint-ts=now

### What did you expect to see?

changefeed should be normal soon

### What did you see instead?

it takes over 30minutes before changefeed lag is normal.
![image](https://user-images.githubusercontent.com/7403864/236369123-a39e8bd9-eb8b-4f2d-837f-d2c782215e2c.png)

### Versions of the cluster

[root@upstream-ticdc-0 /]# /cdc version
Release Version: v7.2.0-alpha
Git Commit Hash: https://github.com/pingcap/tiflow/commit/cd77136707139ceb9867e38fc1eb46371908b83c
Git Branch: heads/refs/tags/v7.2.0-alpha
UTC Build Time: 2023-04-27 11:32:11
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false

**Comment by asddongmen** [comment]
It is not a bug but a enhancement to request.

**Comment by asddongmen** [comment]
Close it since it's stale.
