### ISSUE TITLE
SortEngine uses too much memory on aarch64 with pagesize=64K

### ISSUE THREAD

**Issue by hicqu** [pingcap/tiflow#8974]
### What did you do?

1. Create a changefeed and then pause it
2. Run 20min sysbench insert, to prepare some events
3. Resume the changefeed

### What did you see instead?

![图片](https://github.com/pingcap/tiflow/assets/8407317/6cf49ec5-e1ec-4dee-9674-d68a2af80a96)

* The root block is about 12GB, but TiCDC uses about 50GB exactly. I guess GC doesn't work fine.

=======================================

![图片](https://github.com/pingcap/tiflow/assets/8407317/6dc3a144-f115-4054-a784-46fcdd13fdbc)

* The red circles indicate default TiCDC configuration;
* The green circles indicate patched TiCDC configuration without pebble block-cache.

Seems disable pebble block-cache can resolve the problem, although I don't know why.

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
v6.5.2
```

**Comment by wk989898** [comment]
It is hard to validate with unit tests because there are many conditions and no clear conclusions.
