### ISSUE TITLE
one  changefeed lag keeps increasing while the other is normal

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9007]
### What did you do?

1. There are 2 kafka changefeed:
  one for big table
  one for 4k small tables
2. run workload for the big table and 4k small tables
3. check cdc lag

### What did you expect to see?

cdc lag should be similar for both changefeed

### What did you see instead?

the changefeed lag for big table keeps increasing, while that of 4k tables seem normal.

![image](https://github.com/pingcap/tiflow/assets/7403864/033f4b9d-1499-4db4-9f0c-131bbf797b07)

![image](https://github.com/pingcap/tiflow/assets/7403864/d41a4b80-fb14-4e3d-bdfb-1f9e9ff66f5c)

### Versions of the cluster

[root@tc-ticdc-0 /]# /cdc version
Release Version: v7.1.0
Git Commit Hash: 265dddef14dfd72209a7cb55201164a0de088381
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-18 02:31:38
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false

**Comment by fubinzh** [comment]
When change big table qps from 40000 to 10000, lag seem OK.

**Comment by nongfushanquan** [comment]
duplicated with https://github.com/pingcap/tiflow/issues/8959  and fixed by https://github.com/pingcap/tiflow/pull/9060
