### ISSUE TITLE
ticdc lag reached more than 10min and ticdc crash when inject pdleader data io hang

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#9054]
### What did you do?
1、run tpcc with threads 10 and warehouse 1000
2、After 10 minutes, simulates the io of pd leader is hang but the pod is still active
fault start time：2023-05-15 12:05:38
3、After 10 minutes, recovery the fault
fault recover time：2023-05-15 12:15:38

### What did you expect to see?
changefeed lag is less than 30s

### What did you see instead?
1 、changefeed lag reached more than 10min after inject fault
2、 ticdc crash

![image](https://github.com/pingcap/tiflow/assets/84712107/72c8db9a-e53a-4b5c-9eda-2ebc3133be34)

![image](https://github.com/pingcap/tiflow/assets/84712107/deaaeeed-c1b1-4478-88cc-2647c4bbc795)

![image](https://github.com/pingcap/tiflow/assets/84712107/cdce22dd-b6e1-40dc-9ba5-cdd53c2ea253)

### Versions of the cluster

git hash：1335f98cdbaf77239bbcbc6b61561e4254449ffe

**Comment by asddongmen** [comment]
#9106 alleviate this problem, in testing, it was found that after merging this PR, there is only a 50% chance of encountering the cdc stuck issue.

**Comment by zhangjinpeng1987** [comment]
What is the root cause of the lag since TiCDC doesn't depends on PD leader's IO, TiCDC just asynchronously push the checkpoint to PD. cc @nongfushanquan

**Comment by fubinzh** [comment]
This issue still seen with v7.2.0
chaos injection time: 2023-06-21 19:14 - 19:19
![7ecce631-bb00-4f54-99b9-eef0496bbdce](https://github.com/pingcap/tiflow/assets/7403864/01c24c3a-6730-40e5-b52f-50da6eec60ef)
![4457effb-e6c1-40c3-b5c8-757dc94a2a26](https://github.com/pingcap/tiflow/assets/7403864/a3c81b61-dab5-4a76-9c40-7cb2f3686803)

**Comment by nongfushanquan** [comment]
PD  can't read the leader's information from etcd , which may be caused by the following issue
https://github.com/etcd-io/etcd/issues/12528.

**Comment by asddongmen** [comment]
It's a etcd issue, we can fix now.

**Comment by Lily2025** [comment]
ticdc crash when inject pd leader io delay 1s
[2023/10/18 17:36:14.719 +08:00] [INFO] [chaos.go:64] ["Run chaos"] [name=iochaos_io_delay] [selectors="[endless-ha-test-ticdc-tps-3240159-1-638/tc-pd-2]"] [selectorsRetainPolicy(selectors)="[endless-ha-test-ticdc-tps-3240159-1-638/tc-pd-2]"] [targetSelectors="[nil]"] [targetSelectorsRetainPolicy(targetSelectors)="[nil]"] [experimentSpec="IODelaySpec{Duration: \"\", Scheduler: <nil>, Delay: \"1s\", Path: \"/var/lib/pd/data/**/*\", Percent: 100}"]
![image](https://github.com/pingcap/tiflow/assets/84712107/093bbf45-3fe5-478f-9188-92eaa5ac8c04)
![image](https://github.com/pingcap/tiflow/assets/84712107/c722ef12-577b-4f5a-aa95-037574c695c7)

**Comment by asddongmen** [comment]
If PD is able to upgrade  it etcd version to 3.4.31, it's likely that the issue will be resolved.
Ref: https://github.com/etcd-io/etcd/pull/17465#event-11888619658
cc @flowbehappy

**Comment by asddongmen** [comment]
After the merge of https://github.com/pingcap/tiflow/pull/10881, the checkpointTs lag during pd-leader-io-hang cases was reduced to less than 120s, meeting the requirement.
![image](https://github.com/pingcap/tiflow/assets/20351731/19783275-4480-4c42-86b7-5942ed32b2f0)
