### ISSUE TITLE
arm env, ticdc crashed when upgrade from v6.1.6 to v6.5.3

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiflow#9193]
### What did you do?

install a tidb cluster with v6.1.6 version 
upgrade to v6.5.3

### What did you expect to see?

upgrade successfully

### What did you see instead?

lt@ltdebijndiannao test-plan % kubectl logs tc-ticdc-0                                 
[WARN] TiCDC server data-dir is not set. Please use `cdc server --data-dir` to start the cdc server if possible.
Error: run server: [CDC:ErrVersionIncompatible]version is incompatible: PD 6.5.3 is not supported, the maximum compatible version is 6.2.0-alpha
lt@ltdebijndiannao test-plan % 

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by seiya-annie** [comment]
after pd upgraded to v6.5.3, ticdc crashed

**Comment by seiya-annie** [comment]
only failed in arm-64 env.

**Comment by fubinzh** [comment]
severity moderate

**Comment by asddongmen** [comment]
stale issue.
