### ISSUE TITLE
redo apply failed due to "error: context canceled"

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9249]
### What did you do?

1. run case redo_apply_basic_real_time_sync, create changefeed with redo log enabled, run workload, stop changefeed, and run redo apply

### What did you expect to see?

redo apply should succeed

### What did you see instead?

redo apply failed due to "Error: context canceled"

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
["Welcome to Change Data Capture (CDC)"] [release-version=v7.2.0-alpha] [git-hash=48d89accc55c07f085ffc035b644bf698b02cd5d] [git-branch=heads/refs/tags/v7.2.0-alpha] [utc-build-time="2023-06-15 11:32:12"] [go-version="go version go1.20.5 linux/amd64"] [failpoint-build=false]
```

**Comment by CharlesCheung96** [comment]
Close this issue temporarily because it has not reproduced for a long time.
