### ISSUE TITLE
cdc checkpoint not advance during upgrade from pre v6.5.2 version to v6.5.2 and later

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9256]
### What did you do?

1. Create pre 6.5.2 TiDB cluster (say v6.5.1) with 3 cdc
2. Run workload, and create changefeed to sync changes
3. Upgrade one of the ticdc nodes to v6.5.2

### What did you expect to see?

CDC checkpoint should adance during ugrade, the whole lag should be < 10s.

### What did you see instead?

CDC checkpoint not advance if some of the cdc nodes version < v6.5.2 and some others >=v6.5.2
This could result in cdc overall checkpoint lag > 10s for the cdc upgrade, considering that 
1), checkpoint not adance before all cdc nodes upgraded, e.g. this might takes more time if there are lots of tables to be re-balanced.
2), after all cdc nodes upgraded, changefeed may need additional time to catch up.

### Versions of the cluster

this happens when ugrade cdc from pre v6.5.3 to v6.5.3 and later.

**Comment by asddongmen** [comment]
It is by design.

**Comment by nongfushanquan** [comment]
In version less than 6.5.2, the ticdc node sync the progress( checkpoint ts & resolved ts ) by etcd , After 6.5.2 , they exchange this information by p2p directly . So in this upgrade scenario , the lag increase. After the upgrade , the lag will resume normal.
