### ISSUE TITLE
TiCDC can be blocked when kafka sink meets errors

### ISSUE THREAD

**Issue by hicqu** [pingcap/tiflow#9309]
### What did you do?

For kafka sink, if some sink errors happen:
* table sink can be blocked forever;
* etcd tick can be blocked forever;

It's in investigating now.

### What did you see instead?

TiCDC is blocked when some kafka sink errors happen.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by hicqu** [comment]
Close as can't reproduce.

**Comment by nongfushanquan** [comment]
Please add information to describe this issue
