### ISSUE TITLE
`update` ops can't be synced to tidb from mysql 8

### ISSUE THREAD

**Issue by aseaday** [pingcap/tiflow#9338]
### What did you do?

We try to sync Mysql 8.0.33 to Tidb v6.5.0 using tidb dmctl 7.2.0

### What did you expect to see?

The  original table's new row can be synced to tidb, but update operations can't be synced to tidb.

### What did you see instead?

`update` operations be applied

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
Starting component `dmctl`: /home/ubuntu/.tiup/components/dmctl/v7.2.0/dmctl/dmctl -V
Release Version: v7.2.0
Git Commit Hash: 33e21a7e12ec792ad6ffb53144c86b2872a6a216
Git Branch: heads/refs/tags/v7.2.0
UTC Build Time: 2023-06-21 14:48:02
Go Version: go version go1.20.5 linux/amd64
Failpoint Build: false```

Upstream MySQL/MariaDB server version:
```console
8.0.33
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
6.5.0
```
How did you deploy DM: tiup or manually?
```console
tiup
```
Other interesting information (system version, hardware config, etc):
```console
>ubuntu
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
 {
            "taskName": "lemon-read-record-task",
            "taskStatus": "Running",
            "sources": [
                "mysql-replica-24"
            ]
```

**Comment by fubinzh** [comment]
@aseaday I couldn't reproduce the issue with below configuration, dm sync is OK when running sysbench oltp_update_index workload. could you please provide detailed steps and logs so that we can further investigate?

mysql: 8.0.33
dm: 7.2.0
downstream tidb: 6.5.0
workload:  oltp_update_index 

```
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.33    |
+-----------+
1 row in set (0.00 sec)

/ # /tidb-server -V
Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

[root@dm-dm-master-0 /]# /dmctl -V
Release Version: v7.2.0
Git Commit Hash: 33e21a7e12ec792ad6ffb53144c86b2872a6a216
Git Branch: heads/refs/tags/v7.2.0
UTC Build Time: 2023-06-21 14:48:02
Go Version: go version go1.20.5 linux/amd64
Failpoint Build: false

[root@dm-dm-master-0 /]# cat /tmp/testcases/dm_migrate_mysql_basic/config/source.yaml
source-id: source-0
enable-gtid: true
from:
    host: upstream1
    user: root
    password:
    port: 3306

[root@dm-dm-master-0 /]# cat /tmp/testcases/dm_migrate_mysql_basic/config/task.yaml
---
name: test-infra
task-mode: all
is-sharding: false
meta-schema: "dm_meta"

target-database:
    host: "downstream-tidb"
    port: 4000
    user: "root"
    password: ""

mysql-instances:
    - source-id: "source-0"
      block-allow-list: "instance"

block-allow-list:
    instance:
        do-dbs: ["dm_migrate_mysql_basic"]


```

![image](https://github.com/pingcap/tiflow/assets/7403864/97ba9fa3-0442-4751-889d-61920dc39d0b)

**Comment by aseaday** [comment]
We use oracle cloud's mysql. 
```
+-----------------+
| version()       |
+-----------------+
| 8.0.33-u3-cloud |
+-----------------+
1 row in set (0.23 sec)
```
In order to exclude some errors caused by cloud version, I will deploy a 8.0.33 community edition and try a task.

**Comment by aseaday** [comment]
We also ignore some checks 
```
ignore-checking-items: ["dump_privilege","replication_privilege","version","conn_number"]
```
Because there is some privilege problem.

**Comment by aseaday** [comment]
I could find any useful log but
```
[2023/07/05 06:17:49.340 +00:00] [INFO] [ddl.go:276] ["ddl that dm doesn't handle, skip it"] [task=debug-2] [unit="binlog replication"] [component=ddl] [event=query] [queryEventContext="{schema: user_pool, originSQL: SAVEPOINT `__EFSavePoint`, startLocation: position: (binary-log.004280, 8269253), gtid-set: 2792ad0e-6b21-453f-a32b-fdf523f91e4a:1-2073485,29d159c9-15fc-11ee-9355-02001701db25:1-2384374,ad0c350c-14c3-11ee-be53-02001701db18:1-17956,f1453a3c-1485-11ee-8194-020017016833:1-6540, endLocation: position: (binary-log.004280, 8269356), gtid-set: 2792ad0e-6b21-453f-a32b-fdf523f91e4a:1-2073485,29d159c9-15fc-11ee-9355-02001701db25:1-2384374,ad0c350c-14c3-11ee-be53-02001701db18:1-17956,f1453a3c-1485-11ee-8194-020017016833:1-6540, lastLocation: position: (binary-log.004280, 8268583), gtid-set: 2792ad0e-6b21-453f-a32b-fdf523f91e4a:1-2073485,29d159c9-15fc-11ee-9355-02001701db25:1-2384373,ad0c350c-14c3-11ee-be53-02001701db18:1-17956,f1453a3c-1485-11ee-8194-020017016833:1-6540, re-sync: , needHandleDDLs: , trackInfos: }"]
```
Is there any ways to gimme a verbose logs?

**Comment by fubinzh** [comment]
> I could find any useful log but
> 
> ```
> [2023/07/05 06:17:49.340 +00:00] [INFO] [ddl.go:276] ["ddl that dm doesn't handle, skip it"] [task=debug-2] [unit="binlog replication"] [component=ddl] [event=query] [queryEventContext="{schema: user_pool, originSQL: SAVEPOINT `__EFSavePoint`, startLocation: position: (binary-log.004280, 8269253), gtid-set: 2792ad0e-6b21-453f-a32b-fdf523f91e4a:1-2073485,29d159c9-15fc-11ee-9355-02001701db25:1-2384374,ad0c350c-14c3-11ee-be53-02001701db18:1-17956,f1453a3c-1485-11ee-8194-020017016833:1-6540, endLocation: position: (binary-log.004280, 8269356), gtid-set: 2792ad0e-6b21-453f-a32b-fdf523f91e4a:1-2073485,29d159c9-15fc-11ee-9355-02001701db25:1-2384374,ad0c350c-14c3-11ee-be53-02001701db18:1-17956,f1453a3c-1485-11ee-8194-020017016833:1-6540, lastLocation: position: (binary-log.004280, 8268583), gtid-set: 2792ad0e-6b21-453f-a32b-fdf523f91e4a:1-2073485,29d159c9-15fc-11ee-9355-02001701db25:1-2384373,ad0c350c-14c3-11ee-be53-02001701db18:1-17956,f1453a3c-1485-11ee-8194-020017016833:1-6540, re-sync: , needHandleDDLs: , trackInfos: }"]
> ```
> 
> Is there any ways to gimme a verbose logs?

you can change the log-level config, https://github.com/pingcap/tiup/blob/c2ae2f613069ffd98127fba4776d3fef8db0393c/embed/examples/dm/topology.example.yaml#L49

**Comment by aseaday** [comment]
The problems exist not in tiflow but also in other's sync tools such as tapdata. 
I think It is caused by the | 8.0.33-u3-cloud , the cloud version may break something wrong.
I will follow this issue to fix it out.

**Comment by fubinzh** [comment]
@aseaday could you please close the issue if it is not a DM issue?

**Comment by aseaday** [comment]
Yes, the problem is that it is the mysql default mode binlog_row_value_options=PARTIAL_JSON
Please remove it
