### ISSUE TITLE
cdc lag >40s when executing lossy ddl

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9349]
### What did you do?

1. create mysql changefeed 
2. run workload "/go-tpc tpcc --db workload --warehouses 20 -T 20 --host upstream-tidb.cdc-testbed-tps-1815638-1-796 --port 4000 --parts 1 --time 30m0s run --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062'
3. execute lossy ddl:
 ```
alter table workload.stock modify `s_order_cnt` varchar(20) DEFAULT "123456";
 alter table workload.stock modify `s_remote_cnt` varchar(20) DEFAULT "123456";
```

### What did you expect to see?

cdc lag should not increase a lot 

### What did you see instead?

sometimes cdc lag increases > 10s, and even >40s sometimes.

case 1:
![image](https://github.com/pingcap/tiflow/assets/7403864/fabc707b-939c-4aad-a11d-02d819b3b653)

case 2:
![image](https://github.com/pingcap/tiflow/assets/7403864/30f5d83b-a029-4420-9a1f-4f24b22ce584)

case 3:
![image](https://github.com/pingcap/tiflow/assets/7403864/c2759208-a629-4a5c-9367-b68e9dbff6aa)

### Versions of the cluster

[release-version=v7.3.0-alpha] [git-hash=ebb2a0ff911b16f456d45d469f57004eacf95097] [git-branch=heads/refs/tags/v7.3.0-alpha] [utc-build-time=\"2023-07-03 11:03:12\"] [go-version=\"go version go1.20.5 linux/amd64\"]

**Comment by nongfushanquan** [comment]
The behavior is expected , when executing the lossy ddl , the ddl will block the dml ,so the resolved ts lag will increase
