### ISSUE TITLE
Exceeding gclifetime and gc-ttl, the changefeed status is normal, and the checkpoint lag exceeds 4 days

### ISSUE THREAD

**Issue by xiaobingMo** [pingcap/tiflow#9535]
### What did you do?

1、the upstream TiDB tidb_gc_life_time = 4 hours
2、the gc-ttl of the cdc = 24 hours
3、checkpoint lag > 4d

### What did you expect to see?

changefeed failed, upstream TiDB gc is not blocked

### What did you see instead?

changefeed is nromal , upstream TiDB gc is blocked

### Versions of the cluster

TiDB v6.5.3
TiCDC v6.5.3

**Comment by CharlesCheung96** [comment]
Fixed by [PR9330](https://github.com/pingcap/tiflow/pull/9330/files#diff-c2281a24d357ea97eba9ce2dbfcaed3469a1b35b7ad8657d63ef71af9f87d198R115-R128)
