### ISSUE TITLE
DM loading NONCLUSTERED auto_increment and AUTO_ID_CACHE=1 table with lightning physical backend results in "duplicate entry" 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9620]
### What did you do?

Refer to: https://github.com/pingcap/tidb/issues/46100
DM need update lightning version

### What did you expect to see?

It should be OK for DM to load NONCLUSTERED auto_increment and AUTO_ID_CACHE=1 table with lightning physical backend.

### What did you see instead?

After DM load data, later insert might report error "duplicate entry" 

### Versions of the cluster

DM version: v7.3.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lichunzhu** [comment]
TiDB dependencies are already updated on master https://github.com/pingcap/tiflow/commit/e4ac90bc2fa108e856ea056e2949420d7a7694fe.
I use the original PR's integration test data to do a manual test and it works. Close this now.

**Comment by D3Hunter** [comment]
this pr https://github.com/pingcap/tiflow/pull/9642 already updated tidb dependency, and include the fix, 7.5 contains it
