### ISSUE TITLE
changefeed task status failed after inject one of tikv io hang even if fault recovery

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#9650]
### What did you do?

1、run tpcc with 1000 warehouse and 10 thread
2、inject one of  tikv io hang last for 40min

### What did you expect to see?

changefeed task stauts should be normal

### What did you see instead?

changefeed task status failed after inject one of tikv io hang
the target status of TiCDC changfeed ticdc-task is normal, but the current status is failed

![image](https://github.com/pingcap/tiflow/assets/84712107/8b351ef8-b175-4cd3-859e-b7e86024d6e7)

### Versions of the cluster

git hash：c903b8723c245b0e3640c3fb09a8845f62c6e713

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by asddongmen** [comment]
fix by #9893
