### ISSUE TITLE
resolved ts and checkpoint ts not advance when kv-client.enable-multiplexing = true

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9673]
### What did you do?

1. create mysql changefeed
2. pause changefeed
3. run tpcc workload
4. resume changefeed 

### What did you expect to see?

1. resolved ts and changefeed checkpoint should advance normally.

### What did you see instead?

1. resolved ts and changefeed checkpoint stucks.  (this issue is not stably reproduciable)
![image](https://github.com/pingcap/tiflow/assets/7403864/7ca3d8ee-f3fb-450f-bd9c-d133956940c3)
![image](https://github.com/pingcap/tiflow/assets/7403864/7c2dabe8-ef23-4506-b936-4e4d74e94524)

### Versions of the cluster

CDC version:
["Welcome to Change Data Capture (CDC)"] [release-version=v7.4.0-alpha] [git-hash=74673c3cad726d87e2f7901a3b80f77f4f26e991] [git-branch=heads/refs/tags/v7.4.0-alpha]

**Comment by fubinzh** [comment]
[ticdc-0_2220647.log](https://github.com/pingcap/tiflow/files/12520136/ticdc-0_2220647.log)
[ticdc-1_2220647.log](https://github.com/pingcap/tiflow/files/12520138/ticdc-1_2220647.log)
[ticdc-2_2220647.log](https://github.com/pingcap/tiflow/files/12520139/ticdc-2_2220647.log)

**Comment by fubinzh** [comment]
This issue still seen in latest master.

**Comment by fubinzh** [comment]
This issue seen in latest master in several scenarios. 

/remove-severity major
/severity critical

**Comment by flowbehappy** [comment]
@fubinzh Hi, I wonder is there any workaround for this issue?

**Comment by fubinzh** [comment]
@flowbehappy This issue only happens on master, and you should be able to workaround this issue with cdc server configuration kv-client.enable-multiplexing = false.
