### ISSUE TITLE
dm: CompareGTID uses an extremely slow algorithm to check emptiness and slowed down replication speed

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiflow#9676]
### What did you do?

1. Set upstream to a MySQL cluster with 23 servers.
2. Set the source with GTID enabled (the GTID set should be around 1 KiB long).

### What did you expect to see?

Replication works normally and quickly.

### What did you see instead?

`CompareGTID` shows up significantly in the worker CPU profile and blocking the main thread, significantly slowing down replication speed

![1-fs8](https://github.com/pingcap/tiflow/assets/103023/00664462-89ee-4694-9663-b347e2e61946)

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
6.5.1
```
Upstream MySQL/MariaDB server version:
```console
5.7.29-32-log
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
6.5.3
```
How did you deploy DM: tiup or manually?
```console
k8s (operator)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by knull-cn** [comment]
the `MysqlGTIDSet.String()` just to check the empty.
maybe we can check it at `parseBinlogLocation`: if data of gtid was not empty and parse was not error, it was not empty. otherwise , it was empty.

**Comment by kennytm** [comment]
Since all devs seems to be busy with other stuff I've asked @feran-morgan-pingcap to try to deliver a PR by Oct 7th.

cc @GMHDBJD
