### ISSUE TITLE
cdc.incremental-scan-speed-limit doesn't work 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9712]
### What did you do?

1. deploy 6.5.3 TiDB cluster, TiKV configuration for incremental scan as below:
![image](https://github.com/pingcap/tiflow/assets/7403864/484b6b04-b7c1-4eea-8be4-2f88b6c53e0e)
2. Do incremental scan

### What did you expect to see?

cdc.incremental-scan-speed-limit should take effects

### What did you see instead?

cdc.incremental-scan-speed-limit doesn't work.

![image](https://github.com/pingcap/tiflow/assets/7403864/9e5256f1-226c-455d-9c42-e09d3145e453)

### Versions of the cluster

TiKV version:  6.5.3 with https://github.com/tikv/tikv/pull/15343/, which drop cdc events.
/ # /tikv-server -V
TiKV
Release Version:   6.5.3
Edition:           Community
Git Commit Hash:   42ca9aef5971f9b71e512168bc08698fed4fb0fc
Git Commit Branch: heads/refs/tags/v6.5.3
UTC Build Time:    2023-09-05 07:29:28

CDC version:
bash-5.1# /cdc version
Release Version: v6.5.3
Git Commit Hash: 1e2f277f2e3d9b57b15db9a2a9b2c62832c071ca
Git Branch: heads/refs/tags/v6.5.3
UTC Build Time: 2023-06-05 10:19:02
Go Version: go version go1.19.9 linux/amd64
Failpoint Build: false

**Comment by nongfushanquan** [comment]
The configure works well , however ,The computation expression for monitoring is incorrect, which include lots of datas read from the memory .
