### ISSUE TITLE
[TiCDC] support column filter

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tiflow#9734]
### Is your feature request related to a problem?

When this is a wide table in TiDB, it includes many columns and some of columns may be large (store blob json or img), the user using TiCDC to replicate mutations of this table to Kafka, and then consume these mutations to feed search system. The downstream search system don't care about the content in large columns like blob, binary and long text, it just indexing columns which contain address, age, source, destination, catalog, and other meta content of a row. Currently, TiCDC will replicate all the columns of each downstream, and if each row of content is large, it will waste TiCDC a lot of resource to handle these useless large columns.

### Describe the feature you'd like

Changefeed filter can choose table's meaningful columns to replicate downstream (aka, ignore some useless large column to reduce bandwidth and other resources usage).

### Describe alternatives you've considered

1) Do nothing, let downstream consumer application to filter these useless large columns. The drawback of this solution is it will eat some extra resources(bandwidth, IO, CPU, memory) of TiCDC and the whole pipeline and reduce the stability and performance of whole replication pipeline.

**Comment by zhangjinpeng1987** [comment]
All mutations will go through TiCDC's puller -> sorter -> mounter -> sinker. There is no schema information in puller and sorter, so these useless large columns  only can be dropped in mounter and sinker. 

Question: Is it possible to make the elimination earlier?

**Comment by zzkkll99** [comment]
While this feature is based on the resource consumption considerations above, there are indeed users who want to subscribe to only a subset of columns.

We had configured "sink. column_selectors" when we created the task and thought it was a column filter, but in our tests we found it wasn't.  I immediately thought it was a bug and reported it until I read the discussion you started and realized that I was wrong, but the documentation didn't give any more information.

info：https:github.com/pingcap/tiflow/issues/9751
https://docs.pingcap.com/zh/tidb/stable/ticdc-open-api-v2#%E5%88%9B%E5%BB%BA%E5%90%8C%E6%AD%A5%E4%BB%BB%E5%8A%A1

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tiflow/pull/9920 has fixed this issue, so close it.
