### ISSUE TITLE
cdc panic when eventFeedSession recive the event has empty entries

### ISSUE THREAD

**Issue by knull-cn** [pingcap/tiflow#9739]
### What did you do?

deploy cdc (v6.5.3)and create changefeed

### What did you expect to see?

normal and no panic

### What did you see instead?

panic
![image](https://github.com/pingcap/tiflow/assets/5057528/4d4ad8b1-dfb4-400c-bfce-915e1ab0f628)

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by kennytm** [comment]
Location of panic (`entries.Entries.Entries` is empty):

https://github.com/pingcap/tiflow/blob/v6.5.3/cdc/kv/client.go#L1085

Potential source of empty `Entries`:

1. https://github.com/tikv/tikv/blob/v6.5.3/components/cdc/src/delegate.rs#L689 — Lossy DDL reorg (https://github.com/pingcap/tidb/issues/43227)
2. https://github.com/tikv/tikv/blob/v6.5.3/components/cdc/src/delegate.rs#L564 — incremental scan results in nothing
