### ISSUE TITLE
CDC lag up to 80s during tikv rolling restart

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9756]
### What did you do?

1. TiDB cluster with 15 TiKV
2. Create Kafka changefeed
3. Run workload
4. Rolling restart TiKV

### What did you expect to see?

CDC lag should not increase too much.

### What did you see instead?

CDC lag increases to 80s
![image](https://github.com/pingcap/tiflow/assets/7403864/9e798b87-986e-4177-ab4f-5ad10e7b9c91)
![image](https://github.com/pingcap/tiflow/assets/7403864/508422cb-b403-4219-99a7-fed95fecbbd1)

### Versions of the cluster

bash-5.1# /cdc version
Release Version: v6.5.0-nightly
Git Commit Hash: 2ab025eb9de3ae76d13db953f00bb170d50ef9a8
Git Branch: heads/refs/tags/v6.5.0-nightly
UTC Build Time: 2023-09-07 10:21:33

**Comment by nongfushanquan** [comment]
https://github.com/pingcap/tiflow/pull/9740
