### ISSUE TITLE
CDC lag up to 30s+ when injecting one TiKV to one TiDB network partition

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9757]
### What did you do?

1. TiDB cluster with 15 TiKV, 2 TiDB, 
2. Create Kafka changefeed
3. Run workload
4. Inject one TiKV to one TiDB network partition.

### What did you expect to see?

CDC lag should impact too much.

### What did you see instead?

CDC lag up to 37s

![image](https://github.com/pingcap/tiflow/assets/7403864/4f04f360-5f25-40d6-a21d-d9790e249bcc)

### Versions of the cluster

bash-5.1# /cdc version
Release Version: v6.5.0-nightly
Git Commit Hash: 2ab025eb9de3ae76d13db953f00bb170d50ef9a8
Git Branch: heads/refs/tags/v6.5.0-nightly
UTC Build Time: 2023-09-07 10:21:33

**Comment by fubinzh** [comment]
This issue still exists in latest master.

**Comment by asddongmen** [comment]
I close it since it's stale, and there is no environment to investigate it.
if it happens again, please feel free to reopen it and contact me.
