### ISSUE TITLE
TiCDC: BR failed to restore due to the existence of the CDC task.

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiflow#9807]
### What did you do?

Run a BR restore job on the TiDB cluster with all TiCDC changefeeds stopped beforehand.

### What did you expect to see?

The BR job can run successfully.

### What did you see instead?

The BR restore job is failing with the following error messages:
`[2023/09/22 22:56:13.506 +00:00] [ERROR] [restore.go:64] ["failed to restore"] [error="failed to check task exists: found CDC changefeed(s): cluster/namespace: __backup__/0/tidb/cdc changefeed(s): [test-task], please stop changefeed(s) before restore"] [errorVerbose="found CDC changefeed(s): cluster/namespace: __backup__/0/tidb/cdc changefeed(s): [test-task], please stop changefeed(s) before restore\ngithub.com/pingcap/tidb/br/pkg/task.checkTaskExists\n\t/mnt/tidb/sql/br/pkg/task/stream.go:1082\ngithub.com/pingcap/tidb/br/pkg/task.RunRestore\n\t/mnt/tidb/sql/br/pkg/task/restore.go:576\nmain.runRestoreCommand\n\t/mnt/tidb/sql/br/cmd/br/restore.go:63\nmain.newDBRestoreCommand.func1\n\t/mnt/tidb/sql/br/cmd/br/restore.go:183\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/mnt/tidb/sql/br/cmd/br/main.go:58\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nfailed to check task exists"] [stack="main.runRestoreCommand\n\t/mnt/tidb/sql/br/cmd/br/restore.go:64\nmain.newDBRestoreCommand.func1\n\t/mnt/tidb/sql/br/cmd/br/restore.go:183\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/mnt/tidb/sql/br/cmd/br/main.go:58\nruntime.main\n\t/usr/l[ocal/go/src/runtime/proc.go:250"]](http://ngithub.com/spf13/cobra.(*Command)`

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
v7.1.0
```

**Comment by sdojjy** [comment]
From the Ticdc view, it's by design,  BR should not check the backup data.
