### ISSUE TITLE
Ineligible create table DDL is sent after it become ligible by next DDL

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#9819]
```
create table t (a int);
insert int t values (1);

alter table t add primary key (a);

insert int t values (2);
insert int t values (3);
```

The first one create table DDL should not be sent to the downstream, but it was observed unexpectedly.

**Comment by asddongmen** [comment]
In TiCDC, when it encounters a DDL, it grabs a schemaSnapshot based on the DDL's TableID. Then, it uses the IsIneligibleTableID function from schemaSnapshot to decide if the changes for that table should be synced.
The snag is with how the schemaWrap4Owner structure currently gets the schemaSnapshot. It's calling the GetLastSnapshot function directly. So, when it's handling a "create table" DDL, it might end up with a schemaSnapshot from after an "add index" DDL, causing things to go wrong.
