### ISSUE TITLE
integrtion test found concurrent map access 

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#9890]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_kafka_test/detail/pull_cdc_integration_kafka_test/2042/pipeline

**Comment by asddongmen** [comment]
The link provided in the comment is outdated; hence, there is no information about this issue. If it recurs, please provide more details and get in touch with me.
