### ISSUE TITLE
Tracking issue for kafka sink usability improvement

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#9891]
## Event routing
* [x] #9760
* [x] #9763 
* [x] #9862
* [x] #9821

## Column selector
* [x] #9967
## Docs
* [x] add docs about the index-value dispatcher and columns dispatcher
* [ ] refactor the docs about the event route to make it easier to understand

**Comment by asddongmen** [comment]
@3AceShowHand Shall we close this issue now?
