### ISSUE TITLE
resolved ts stucks when running redo log changefeed with pd/cdc/tikv failure

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9926]
### What did you do?

1. Create TiDB sync changefeed with redo log enabled
2. Run workload
3. Inject PD/CDC/tikv failure

### What did you expect to see?

CDC checkpoint should not stucks

### What did you see instead?

Resolved TS and Checkpoint TS stucks.

![image](https://github.com/pingcap/tiflow/assets/7403864/a6a27082-d6e4-4544-bde9-76b8ed040c41)

### Versions of the cluster

[release-version=v7.1.2] 
[git-hash=64790caa64ec27714b6a6cbb7ed7e3d18f2c8d2c]

**Comment by nongfushanquan** [comment]
This issue is caused by a pr which has been reverted ,so close it
/close
