### ISSUE TITLE
[feature-request] sink to cloud storage: customized delimiter with 2 characters

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tiflow#9969]
### Is your feature request related to a problem?

TiCDC has a one character limitation for CSV delimiter, this will limit users using special characters like hex(FF, FE) as delimiter.

### Describe the feature you'd like

When user specify the delimiter, supports at most 2 characters delimiter.

### Describe alternatives you've considered

There is a hard limitation that the delimiter is 1 character, so there is no alternative to workaround this problem.

### Teachability, Documentation, Adoption, Migration Strategy

This is an extension for existing sink to CSV capability, this will give users better capability to customize their CSV format.

**Comment by lidezhu** [comment]
Some customers use separators like `|@|` in their env. So we need to relief the restriction more to support 3 characters.
