### ISSUE TITLE
TiCDC can do GC in the cloud object storage automatic by configuration

### ISSUE THREAD

**Issue by nongfushanquan** [pingcap/tiflow#9976]
### What did you do?

create a changefeed ,and set the destination of the sink to S3.

### What did you expect to see?

The files on s3 can be removed when the data have been consumed after some days.

### What did you see instead?

The files have to be removed by the consumer

### Versions of the cluster

6.5.5 & 7.1.2

**Comment by CharlesCheung96** [comment]
Closed by #10097
